- test/src/specs/hardfork/v2021/since.rs
- util/types/src/core/extras.rs
- verification/src/transaction_verifier.rs
- When the length of since absolute (or relative) epoch is zero:
- The `epoch_index` will be considered as `0`.
- The `epoch_length` will be considered as `1`.
https://github.com/nervosnetwork/ckb/blob/85bf46065cc91e75980c9ee82925af77c524964d/verification/src/transaction_verifier.rs#L544-L547
https://github.com/nervosnetwork/ckb/blob/85bf46065cc91e75980c9ee82925af77c524964d/util/types/src/core/extras.rs#L452-L459
- Since relative epoch uses rational number operations but since absolute epoch doesn't.
https://github.com/nervosnetwork/ckb/blob/85bf46065cc91e75980c9ee82925af77c524964d/verification/src/transaction_verifier.rs#L657-L662
https://github.com/nervosnetwork/ckb/blob/85bf46065cc91e75980c9ee82925af77c524964d/verification/src/transaction_verifier.rs#L610-L612
- A transaction with …
> refactor(hardfork): verify the epoch in since more strictly

- ckb-bin/src/subcommand/list_hashes.rs
Error messages is better than error structs names or error enumeration types names.
For example:
https://github.com/nervosnetwork/ckb/blob/b085099a7875ffccaa791406ac30311c1a37c7fd/ckb-bin/src/subcommand/list_hashes.rs#L120-L121
https://github.com/nervosnetwork/ckb/blob/b085099a7875ffccaa791406ac30311c1a37c7fd/spec/src/lib.rs#L422-L433
https://github.com/nervosnetwork/ckb/blob/b085099a7875ffccaa791406ac30311c1a37c7fd/spec/src/lib.rs#L404-L408
> chore: better error messages for subcommand `list-hashes`

- test/src/specs/hardfork/v2021/vm_version.rs
- tx-pool/src/util.rs
- util/types/src/core/blockchain.rs
- util/types/src/core/error.rs
- verification/contextual/src/contextual_block_verifier.rs
- verification/src/transaction_verifier.rs
- refactor: merge time relative verifiers in ContextualTransactionVerifier
Before this commit:
- `TimeRelativeTransactionVerifier = MaturityVerifier + SinceVerifier`
- `ContextualTransactionVerifier = MaturityVerifier + SinceVerifier + OtherVerifiers`
After this commit:
- `TimeRelativeTransactionVerifier = MaturityVerifier + SinceVerifier`
- `ContextualTransactionVerifier = TimeRelativeTransactionVerifier + OtherVerifiers`
- feat(hardfork): reject vm1 lock script before hardfork started to keep compatible with old clients
Add `CompatibleVerifier` to `ContextualTransactionVerifier` to check compatible between different versions CKB clients.
When a new client with hardfork features released, before the hardfork started, the old CKB clients will still be able to work.
So, the new CKB client …
> feat(hardfork): reject vm1 lock script before hardfork started to keep compatible with old clients

- Cargo.lock
Fix [RUSTSEC-2021-0072: Task dropped in wrong thread when aborting LocalSet task](https://rustsec.org/advisories/RUSTSEC-2021-0072).
See tokio-rs/tokio#3929 for more details.
> chore(deps): bump tokio from 1.8.0 to 1.8.1

- network/src/peer_store/peer_store_impl.rs
- network/src/tests/peer_store.rs
- util/app-config/src/configs/memory_tracker.rs
Originally, only the data in the largest group was considered, but now it is changed to traverse at least half of the groups
> fix: fix peer store evict

- devtools/doc/rpc.py
- rpc/README.md
The parser only accepts the first paragraph of the enum variant, because
`handle_starttag` is not forwarded to the underlying markdown parser.
> doc(rpc): fix enum variant parsing

- util/launcher/src/migrations/add_extra_data_hash.rs
The redudant `as_ref` also causes crates publish failure that the
compiler cannot resolve the type `T` in `AsRef<T>`.
> refactor: remove redudant `as_ref`

- db/src/db.rs
- db/src/lib.rs
- sync/src/utils.rs
If the database is corrupted, panic is better than handle it silently.
Let the user know his database is corrupted asap.
> chore: panic if the database is corrupted

- sync/src/synchronizer/headers_process.rs
- sync/src/synchronizer/mod.rs
- sync/src/types/mod.rs
- test/src/main.rs
- test/src/specs/sync/block_sync.rs
There has always been a problem with the header sync protocol. When only the sync protocol is enabled, there may be a relatively large delay in obtaining the latest block. This is caused by incorrect state marking. This PR introduces a new state. Try to fix this problem.
The action of header sync is not completed at one time. It needs to be updated in real-time during the entire connection process. It cannot be considered that this node is always at the highest just because it is synchronized to the highest one time. That is to say, the completed state of sync should be dynamically converted to need sync again. 
The `TipSynced` status indicates that this node has synchronized the headers and will try to synchronize again after 28s. At the same time, such a node can be used as the request …
> fix: fix the status marking problem of header sync

- Cargo.lock
- benches/Cargo.toml
- network/Cargo.toml
- resource/Cargo.toml
- script/Cargo.toml
- util/jsonrpc-types/Cargo.toml
- util/rational/Cargo.toml
- util/types/Cargo.toml
At present, there are 3 versions of `rand` in [the CKB's `Cargo.lock`]:
- The version 0.8 is the latest but there is only 1 crates are dependent on it.
- There are 3 crates are dependent on 0.6, which was released 2.5 years ago, and it is unmaintained now.
- There are 21 crates are dependent on 0.7.
If we can remove rand v0.6 from CKB, we can remove about `514 - 497 = 17` **duplicate** dependencies from [the CKB's `Cargo.lock`].
[the CKB's `Cargo.lock`]: https://github.com/nervosnetwork/ckb/blob/b103f7c/Cargo.lock#L3944-L3987
- Bump bloom-filters from 0.1.1 to 0.1.2
- [Bump rand from 0.6 to 0.8](https://github.com/nervosnetwork/bloom-filters/compare/285b7b0...e48908e)
- Bump proptest from 0.9 to 1.0
- Skipped 0.10.x.
- [Too many changes](https://github.com/AltSysrq/proptest/blob/1.0.0/prop …
> chore(deps): upgrade several dependencies to remove the oldest version of rand

- script/src/error.rs
Original issue was posted by @mohanson: he wanted to `assert` script errors but he didn't find any API.
> chore: let a constructor for script error to be public so as to write tests

- Cargo.lock
- freezer/src/freezer_files.rs
- util/metrics-config/Cargo.toml
- util/metrics-config/src/lib.rs
- util/metrics-service/Cargo.toml
- util/metrics-service/src/lib.rs
- util/metrics/Cargo.toml
- util/metrics/src/lib.rs
- Remove all `tokio<1.0` dependencies.
Reduce `502 - 483 = 19` dependencies.
- Fix the metrics feature, it was broken since v0.43.0. 
- **(BREAK CHANGES)** Due to the refactor of [`metrics-rs`] `>0.12.1`, we couldn't keep the same configurations as before.
Since the metrics feature  is an experimental and development-only feature, I just made some break changes.
- According to the suggestion from @doitian, replaces [`metrics-rs`] with [`opentelemetry-rust`].
As [`opentelemetry-rust`] said, [it is not stable, too](https://docs.rs/opentelemetry/0.15.0/opentelemetry/#metrics), so I didn't change the APIs. I just wrote a series of compatible macros.
Due to the difference of those two crates, the presentation of data couldn't be totally the same as before.
We could tweak them later according …
> refactor: replace metrics-rs with opentelemetry-rust

- .github/workflows/preflight-checks.yaml
See passed example: https://github.com/doitian/ckb/runs/3082421857?check_suite_focus=true
> ci: skip preflight checks when the secret REPO_ACCESS_TOKEN is not set

- miner/src/miner.rs
- util/types/src/core/advanced_builders.rs
The built-in miner will ignore the extension field in block templates.
When call `as_builder()` to convert a `Block` to a `BlockBuilder`, all extra fields will be ignored, because the generated code of `BlockBuilder` couldn't know any about extra fields.
And the extension field is an extra field on the molecule-serialized `struct Block`, it will be ignored, too.
We already have the advanced `Block` builder, which is not generated.
The `as_advanced_builder` will handle the extension field.
- Set the `extension` in the [`TxPoolService::build_block_template(..)`](https://github.com/nervosnetwork/ckb/blob/fb27f98b699768f6723b11b904abeacf8fae093a/tx-pool/src/process.rs#L305) to the follow value:
```rust
let extension = if candidate_number % 2 == 0 {
let bytes: Bytes = format!("block number = …
```
> fix(hardfork): built-in miner shouldn't ignore the extension field in block templates

- script/src/ill_transaction_checker.rs
- test/src/specs/hardfork/v2021/vm_version.rs
- util/jsonrpc-types/src/blockchain.rs
* `IllTransactionChecker`: added comments
* `TODO ckb2021 how to test malformed hash type?`: recorded in backlog
* `// TODO ckb2021 Update the rfc number and fix the link, after the proposal is merged.`: already updated.
There are two todos remaining for testnet and mainnet activation.
> doc: resolve todos for ckb2021

- network/src/network.rs
- network/src/peer_registry.rs
- network/src/peer_store/peer_store_impl.rs
- network/src/protocols/feeler.rs
- network/src/protocols/identify/mod.rs
- network/src/tests/peer_store.rs
1. Remove the behavior of joining the peer store when the session is established, and now only operate the peer store after the identify or feeler is successfully established 
2. After the fork switch, the non-latest version of the node information will be slowly cleaned up, and no longer added to the peer store 
3. Remove unnecessary runtime judgment `RefCell`
> feat: remove old version peer from peer store on fork

- network/src/network.rs
- util/app-config/src/configs/mod.rs
- util/app-config/src/configs/network.rs
- util/launcher/src/lib.rs
This feature is designed for testing and use of ckb-network crate by third party code, allows user to customize network protocols, for example, only open sync protocol in full node:
```
support_protocols = ["Sync"]
```
> feat: add network protocol config

- ckb-bin/src/subcommand/migrate.rs
- db-migration/src/lib.rs
- util/launcher/src/migrate.rs
- util/launcher/src/shared_builder.rs
- fix: don't panic when the database is created by a higher version executable binary
- fix: the sub-command `run` shouldn't skip the fast migrations
This bug doesn't affect any old versions because there is no fast migrations in old versions.
Ref: [What are fast migrations?](https://github.com/nervosnetwork/ckb/pull/2571#issuecomment-781775665).
> fix: don't panic when the database is created by a higher version executable binary

- sync/src/synchronizer/mod.rs
- sync/src/types/mod.rs
relation：#2857
The last PR left a problem. There may be a race condition between the two actions. Before reducing `n_sync_started`, we need to determine whether it is in the `Started` state. 
This PR will backport to 0.43
> fix: there may be competition between header sync and eviction

- util/launcher/src/migrate.rs
- util/launcher/src/migrations/add_block_extension_cf.rs
- util/launcher/src/migrations/mod.rs
This PR is useless, unless the PR #2877 was backported to branch "rc/v0.43".
> chore(hardfork): bump db migrate version for the new column family of block extension data

- .github/workflows/ci.yaml
If we trigger on a branch and later skip the ci workflow, GitHub consider it as passed.
Side effect: forks cannot trigger this workflow other than the specific branches.
> ci: trigger ci on push specific branches

- test/src/main.rs
- test/src/specs/hardfork/v2021/cell_deps.rs
- test/src/specs/hardfork/v2021/mod.rs
- test/src/util/check.rs
The old test specs have `18+18+34+34 = 104` testcases in total.
Current test spec has `4*19*(2*2*2+1) = 684` testcases:
- 4 Chain Status:
- CKB v2019, far away from the start of v2021.
- CKB v2019, the last block in v2019 (boundary test).
- CKB v2021, the first block in v2021(boundary test).
- CKB v2021, far away from the start of v2021.
- 19 Cell Deps Cases.
The details can be found in comments.
- 3 Cell Status: where is the cell whose scripts requires the cell deps?
- The script is in an input cell.
- The script is in an output cell.
- No cell requires those cell deps.
- 2 Script Type
- Lock script.
- Type script.
- 2 Script Hash Type
- Data hash-type.
- Type hash-type.
> test(hardfork): refactor and add more testcases for cell deps

- sync/src/orphan_block_pool.rs
- sync/src/relayer/mod.rs
- sync/src/types/mod.rs
- test/src/main.rs
- test/src/specs/sync/mod.rs
- test/src/specs/sync/sync_and_mine.rs
Try traverse all unknown parent hash
> fix: try traverse all unknown parent hash

- tx-pool/src/process.rs
https://github.com/nervosnetwork/ckb/blob/develop/tx-pool/src/process.rs#L471
https://github.com/nervosnetwork/ckb/blob/develop/tx-pool/src/process.rs#L707-L709 
duplicate checked before submitting, but the lock released later,  there is still potentially inclusion.
> fix: callback potentially incorrect trigger on concurrent context

- Cargo.lock
- sync/src/tests/mod.rs
- sync/src/tests/synchronizer.rs
- util/channel/Cargo.toml
- util/channel/src/lib.rs
tests::synchronizer::basic_sync do not graceful shutdown, may cause 
```
pure virtual method called                                                                                                                                                                   
terminate called without an active exception 
```
bump crossbeam-channel from 0.3.9 to 0.5.1 incidentally.
Closes #2927
> fix(test): make sure testnode graceful shutdown basic sync

- bors.toml
Say there are two PRs, PR 1 asks for merging branch pr/1 into develop, and PR 2 requests merging pr/2 into pr/1.
Because we have enabled `delete_merged_branches`, bors will delete branch pr/1 after PR 1 is merged, which deprecates PR 2.
Enable `update_base_for_deletes` in bors.
> If turned on, and if delete_merged_branches is also turned on, then when
> a pull request is merged and its base branch is about to be deleted, any
> other pull requests made against the base branch will be fixed up.
>
> -- https://bors.tech/documentation/#:~:text=update_base_for_deletes
Tests 
- No code
> chore: enable `update_base_for_deletes` in bors

- miner/src/client.rs
HTTP body is a stream, it can't be read all by once.
We need to use streaming to read it completely, otherwise, the miner will not be able to obtain the block template correctly when the transaction volume is large.
> fix: fix stream body read

- store/src/store.rs
- sync/src/relayer/mod.rs
- util/types/src/extension/shortcuts.rs
Forget the extension fields when reconstruct blocks.
Only the relay protocol is broken, the sync protocol works well, so the chain works well.
The only things could be observed is that there are uncles in logs, but no real uncles in blocks.
I checked all `Block::new_builder(..)`, and found 2 locations.
This bug is not in  `version < 0.100`, so no release note is needed for the next release (`v0.100.0`).
```release-note
None
```
> fix(hardfork): should always check the extension field when reconstruct blocks

- tx-pool/src/block_assembler/mod.rs
- tx-pool/src/process.rs
- util/types/src/extension/serialized_size.rs
- Add some code to count the size of the block extension field when package a block template.
This code is meaningless currently, since there are no extension in block templates.
The biggest significance of this code is to ensure that the logic is correct.
- Add tests for the feature: the size of the block extension field should be included in block size limit.
See the discussion in https://github.com/nervosnetwork/rfcs/pull/224#issuecomment-896763326.
```release-note
None
```
> chore(hardfork): size of the block extension field should be included in block size limit

- rpc/README.md
- rpc/src/module/pool.rs
Problem Summary: The RPC document does not mention that when the transaction is already in the pool, `send_transaction` will rebroadcast the transaction to peers.
Tests 
```release-note
```
> docs(rpc): document that `send_transaction` will rebroadcast

- .gitignore
- Makefile
This PR changed the coverage report tool from tarpaulin to [grcov](https://github.com/mozilla/grcov), grcov is more simple to set up and it provides reporting for branches and calls count. Just run `make cov`, a `lcov-unit-test.info` file will be genearted in the root path. You can use some IDE [extension](https://github.com/ryanluker/vscode-coverage-gutters) to view the generated report, for example:
> test: use grcov to generate coverage report

- miner/src/client.rs
- miner/src/miner.rs
- miner/src/worker/dummy.rs
- miner/src/worker/eaglesong_simple.rs
- miner/src/worker/mod.rs
- resource/ckb-miner.toml
1. In the case that the poll interval is small enough, the miner may work on unknown work, which is equivalent to doing useless work(work cache is 32, the channel is unbound, worker get new work just one loop one get)
2. Assuming that miner must be submitted successfully 
3. Miner will submit uncle block 
4. If `block_on_submit` is false, the miner will not submit the block
- setup a dev node(test for Dummy)，use miner subcommand for it
- setup a staging node(test for Eaglesong)，use miner subcommand for it
- change `block_on_submit` to false，and `poll_interval` = 200, old miner can't work, the new one works well
- old miner may have uncle block submit, the new one doesn't
Rewritten part of the miner logic 
```release-note
None
```
> fix: Fix miner

- ckb-bin/src/subcommand/reset_data.rs
- The argument `--network-peer-store` for the sub-command `reset-data` couldn't work.
Because the path of `network/peer-store` is a directory but using a method which removes files to delete it.
- Return code is `0` when has errors.
- Prompt to remove a empty path.
Tests
- `ckb init --chain dev -C dev`
- Check 1:
- `ckb reset-data -C dev`: returns `0` immediately without prompt.
- `ckb run -C dev` and `Ctrl-C` after 10 seconds.
- Check 2:
- `ls dev/data/network/peer_store`: the directory should exists.
-  `ckb reset-data -C dev --force --network-peer-store`: returns `0` immediately without prompt.
- `ls dev/data/network/peer_store`: the directory should be removed.
- `rm dev/data/network/secret_key`
- `mkdir dev/data/network/secret_key` …
> fix(reset-data): the argument `--network-peer-store` couldn't work

- sync/src/orphan_block_pool.rs
- sync/src/types/mod.rs
Replace dashmap with rwlock on the orphan pool, ensure overall consistency 
Replace dashmap with rwlock on the orphan pool
Tests
- Unit test
```release-note
None
```
> chore: replace dashmap with rwlock on orphan pool

- .github/semantic.yml
Problem Summary: We introduced [semantic](https://github.com/zeke/semantic-pull-requests) in CI recently. It requires the PR title or at least one commit follows the naming convention. Since we rely on PR to generate the change log, we really want to check the PR title only and require the title must follow the naming convention.
What's Changed: Add a config file to ask semantic to always validate the PR title, and ignore the commits.
FYI: [configuration doc](https://github.com/zeke/semantic-pull-requests#configuration)
Tests 
Side effects
```release-note
```
> chore: only check PR title for semantic

- rpc/README.md
- rpc/src/module/miner.rs
- spec/src/consensus.rs
- tx-pool/src/process.rs
- util/jsonrpc-types/src/block_template.rs
- util/jsonrpc-types/src/blockchain.rs
- The RPC method `get_block_template` should always return the extension field and the value should always be `null`.
- Reject blocks which are submitted from JSON-RPC and have the extension field, for both mainnet and testnet.
- Allow extension fields for development and tests, since we have a lot of tests base on this feature.
Tests
- Manual test
- Update the code of CKB to set the CKB v2021 hardfork epoch to be `0` for both mainnet and testnet.
https://github.com/nervosnetwork/ckb/blob/cc792ca745014fe0976d442227984cc689cdf7c0/util/constant/src/hardfork/mainnet.rs#L5-L6
https://github.com/nervosnetwork/ckb/blob/cc792ca745014fe0976d442227984cc689cdf7c0/util/constant/src/hardfork/testnet.rs#L5-L6
- Replace the `extension` in block template as follow:
```rust
let extension = {
let bytes: …
```
> chore(hardfork): reject block extension from JSON-RPC temporarily

- Cargo.lock
Fix [RUSTSEC-2021-0093](https://rustsec.org/advisories/RUSTSEC-2021-0093).
> In the affected version of this crate, the result of the race condition is that one or more tasks in the worker queue can be popped twice instead of other tasks that are forgotten and never popped. If tasks are allocated on the heap, this can cause double free and a memory leak. If not, this still can cause a logical bug.
>
> Crates using `Stealer::steal`, `Stealer::steal_batch`, or `Stealer::steal_batch_and_pop` are affected by this issue.
```release-note
```
> chore(deps): bump crossbeam-deque from 0.8.0 to 0.8.1

- Cargo.lock
- script/Cargo.toml
ckb-vm 0.20.0-rc3 -> 0.20.0-rc4
```release-note
ckb-vm 0.20.0-rc4 release note: https://github.com/nervosnetwork/ckb-vm/releases/tag/0.20.0-rc4
```
> feat: update ckb-vm to 0.20.0-rc4

- .github/workflows/coverage_report.yaml
- .gitmodules
Problem Summary: Coverage CI failed because that grcov could not find the executable `llvm-profdata` in the toolchain 1.51.0.
https://github.com/nervosnetwork/ckb/runs/3377259782?check_suite_focus=true#step:4:1946
It's surprised that grcov exit with status code 0 event it fails to find the llvm-profdata executable.
What's Changed: Override toolchain to nightly in CI.
Tests 
```release-note
```
> chore: override toolchain in coverage workflow

- util/metrics-service/Cargo.toml
Problem Summary: In a Rust workspace, features of dependencies are merged. But when publishing crates, cargo only uses the features list in the current crate Cargo.toml
- Enable feature `server`, `tcp`, and `http1` for `hyper` in `ckb-metrics-service` (introduced by [jsonrpc-http-server](https://github.com/paritytech/jsonrpc/blob/dc6b8ede1e86feb32a2bbe4770628ee3788b3f4d/http/Cargo.toml#L15)).
Tests 
Run `cargo publish --dry-run` in directory `util/metrics-service`.
```release-note
```
> deps: fix crates publish

- devtools/release/publish-crates.sh
Problem Summary: There's no tool to yank a specific version of all the crates.
```
CKB_YANK=0.100.0-rc3 devtools/release/publish-crates.sh
```
Tests 
```release-note
```
> chore: update publish-crates.sh to support yanking

- script/src/types.rs
- script/src/verify/tests/ckb_latest/features_since_v2019.rs
- script/src/verify/tests/ckb_latest/features_since_v2021.rs
- script/src/verify/tests/utils.rs
When capturing the VM snapshot, missing add the current VM cycles to the snapshot current cycles.
Supplement the missing calculation.
- Unit test
* https://github.com/nervosnetwork/ckb/pull/2971/files#diff-d63dc7bd6c3b35d59cc62883deb3210e3a929ffbbec75672fe4abbbe6ca48284R481
* https://github.com/nervosnetwork/ckb/pull/2971/files#diff-d63dc7bd6c3b35d59cc62883deb3210e3a929ffbbec75672fe4abbbe6ca48284R442
* https://github.com/nervosnetwork/ckb/pull/2971/files#diff-d63dc7bd6c3b35d59cc62883deb3210e3a929ffbbec75672fe4abbbe6ca48284R403
```release-note
```
> fix: snapshot cycles calculation

- network/src/network.rs
- network/src/peer_store/addr_manager.rs
- network/src/peer_store/mod.rs
- network/src/peer_store/peer_store_impl.rs
- network/src/peer_store/types.rs
- network/src/protocols/identify/mod.rs
- network/src/protocols/tests/mod.rs
- network/src/services/dump_peer_store.rs
- network/src/services/outbound_peer.rs
- network/src/services/protocol_type_checker.rs
- network/src/tests/peer_store.rs
1. Peer store‘s detection and eviction efficiency is too low 
2. There is a certain conflict between the peer store obtaining available nodes and the nodes that need to be probed 
3. There is a problem with interval's choice of MissedTickBehavior
4.  When a node is disconnected, based on the peer store strategy, the node information may be lost 
1. Made some adjustments to the peer store's strategy of randomly obtaining node information
```
| -- choose to identify --| --- choose to feeler --- | --      delete     -- |
| 1      | 2     | 3      | 4    | 5    | 6   | 7    | More than seven days  |
```
2. Made some adjustments to the use of interval:
- Removed the immediate execution behavior of dump peer store startup 
- Adjust interval default MissedTickBehavior to delay or skip 
3. The …
> refactor: refactor peer store

- README.md
Problem Summary: Discord is the preferred chat tool for Nervos but the repo still links to Telegram.
Update the README badge. Remove the Telegram badge and add the Discord badge.
PREVIEW: [![Discord](https://img.shields.io/badge/chat-on%20Discord-7289DA.svg)](https://discord.gg/dBPuQ3qnXS)
Tests
```release-note
```
> doc: replace telegram badge with discord

- build.rs
The binary of `ckb` will be re-linked when any of follow conditions was satisfied:
- Any test-related code was changed.
- No `.git/HEAD` file but under `git` vcs. For example, in a [`Git Worktree`].
About 4.5 seconds will be spent for waiting linking `ckb-bin`, with an intel i9 laptop CPU and mounted-RAM as the disk.
It wastes me a lot of time every day, even I'm just writing tests.
Tests
- Manual test
- Run `make prod`, then run `echo "who cares this file" > freezer/tests/failpoints.rs`, at last run `make prod` again.
- Without the commits in this PR, the `ckb-bin` will be linked twice.
- With the commits in this PR, the `ckb-bin` will be linked only once.
- Run `make prod` twice in a [`Git Worktree`].
- Without the commits in this PR, the `ckb-bin` will be linked twice.
- With the …
> build: skip re-link ckb-bin when no code was changed, to make a better dev experience

- .github/workflows/coverage_report.yaml
Problem Summary: `rustup override` will affect following jobs in self runners.
What's Changed: Use `rust-toolchain` file to override the toolchain instead.
Tests 
```release-note
```
> chore: use rust-toolchain to override toolchain

- Cargo.lock
- test/src/main.rs
- util/app-config/src/app_config.rs
- util/logger-config/Cargo.toml
- util/logger-config/src/lib.rs
- util/logger-config/src/tests.rs
- util/logger-service/Cargo.toml
- util/logger-service/src/lib.rs
- util/logger-service/src/tests.rs
- util/logger-service/tests/basic_features.rs
- util/logger-service/tests/empty_filter.rs
- util/logger-service/tests/env_filter.rs
- util/logger-service/tests/extra_loggers.rs
- util/logger-service/tests/has_panic_info.rs
- util/logger-service/tests/log_to_file_disabled.rs
- util/logger-service/tests/log_to_file_enabled.rs
- util/logger-service/tests/silent_logger.rs
- util/logger-service/tests/update_main_logger.rs
- util/logger-service/tests/utils/mod.rs
- util/logger-service/tests/without_color.rs
- Fix few negligible logger-related issues:
- fix: the default logger configuration doesn't have the default values
`toml::from_str::<LoggerConfig>("").unwrap() != LoggerConfig::default()`
- fix: cause ambiguity since log file could be irrelevant to the `log_dir`
For example, if a user of crate `ckb-logger-service` set `logger.log_dir="/tmp/log_dir"` and `logger.file="run.log"` but run the binary under `/tmp/workdir`, he/she could NOT find the log file in `/tmp/log_dir`, because the log file is in `/tmp/workdir`.
Changes:
- Let the `logger.file` to be the main log file name.
- Written the main log into `logger.log_dir.join(logger.file)`.
_Only internal values are changed, doesn't affect the users of `ckb`._
- Minor changes:
- remove useless `#[derive(Debug)]`
- Two structs are private.
- …
> test: add tests for logger-related crates after fix few negligible issues

- Cargo.lock
- script/Cargo.toml
Contains a bug fix, see release notes below:
https://github.com/nervosnetwork/ckb-vm/releases/tag/0.20.0-rc5
> feat: update ckb-vm to 0.20.0-rc5

- miner/src/miner.rs
- miner/src/worker/dummy.rs
It is a mix of several problems here:
1. Timed poll is turned on from off on dummy miner
2. There is a consistency problem with the deletion judgment because of the background poll, that is, when self start = false, it will also update current, resulting in the previous judgment becoming false when start becomes true
3. Poll new block template will not be updated in this case because of the same work id, i.e., it is not possible to remove the judgment error caused by 2 through poll template
The actual effect is that there is a thread in the miner that keeps on looping but does not work
Tests
init with dev chain, mining it, it will not be stuck
```release-note
```
> fix: fix dummy miner solve

- util/app-config/src/app_config.rs
Since #2990, the log service will write logs into `log.dir + log.file`.
But the `log.file` is overridden to `log.dir + log.file` after `touch`.
Then the log service will write logs into `log.dir + log.dir + log.file`.
- Need to cherry-pick to the `rc/v0.100` release branch
Tests
- Manual test
- Test Case 1
- `ckb init -C /tmp/ckb-dir`
- `ckb run -C /tmp/ckb-dir`
- `cat /tmp/ckb-dir/data/logs/run.log`
- `ckb miner -C /tmp/ckb-dir`
- `cat /tmp/ckb-dir/data/logs/miner.log`
- Test Case 2
- `cd /tmp`
- `ckb init -C ckb-dir`
- `ckb run -C ckb-dir`
- `cat ckb-dir/data/logs/run.log`
- `ckb miner -C ckb-dir`
- `cat ckb-dir/data/logs/miner.log`
- Test Case 3
- `cd /tmp`
- `ckb init -C ckb-dir`
- `cd ckb-dir`
- `ckb run -C .`
- `cat data/logs/run.log`
- `ckb miner -C .`
- `cat data/logs/miner.log` …
> fix: shouldn't override the `log.file` after touch it

- miner/Cargo.toml
Problem Summary: `cargo publish` fails because hyper Client is available when enabling feature http1.
What's Changed: Enable feature http1 for hyper in miner/Cargo.toml
- Already cherry-picked to rc/v0.100
Tests 
Run `cargo publish --dry-run` in sub-directory `miner`.
```release-note
```
> chore(deps): enable hyper http1 for miner

- Cargo.lock
- Cargo.toml
- src/main.rs
- util/memory-tracker/Cargo.toml
https://github.com/gnzlbg/jemallocator/issues/168
https://github.com/jemalloc/jemalloc/issues/1497
see also: https://github.com/rust-lang/rust/pull/83152
Proposal:  switch global alloc to tikv-jemallocator which is more up-to-date
Side effects
```release-note
```
> perf: switch global alloc to tikv-jemallocator

- Cargo.lock
- benches/benches/benchmarks/overall.rs
- chain/Cargo.toml
- chain/src/tests/block_assembler.rs
- chain/src/tests/dep_cell.rs
- rpc/src/module/miner.rs
- rpc/src/module/test.rs
- shared/Cargo.toml
- shared/src/shared.rs
- tx-pool/Cargo.toml
- tx-pool/src/chunk_process.rs
- tx-pool/src/lib.rs
- tx-pool/src/process.rs
- tx-pool/src/service.rs
- tx-pool/src/util.rs
- util/launcher/src/shared_builder.rs
- util/snapshot/Cargo.toml
Previously, tx-pool has a potential issue, some code gets snapshots directly from the `ArcSwap` container, which means those snapshots represent the newest chain, it may be inconsistent with tx-pool owned snapshot.
Remove interface that can get snapshot from swap container.
https://github.com/nervosnetwork/ckb/pull/2984/files#diff-fb91da4f07a6ef121b8913771dd0cf067853b6a3b41eaa96fd242881b71b5f32L659-L664
Tests 
- Unit test
https://github.com/nervosnetwork/ckb/pull/2984/files#diff-6dd28380157411935dbe8b390f7a324dc57b8a8654f9276cb83e2cfca8df36f4R618-R641
```release-note
```
> fix: tx-pool snapshot consistency

- benches/benches/benchmarks/resolve.rs
- chain/src/chain.rs
- chain/src/tests/basic.rs
- chain/src/tests/cell.rs
- ckb-bin/src/subcommand/run.rs
- rpc/src/module/chain.rs
- store/src/store.rs
- store/src/transaction.rs
- util/snapshot/src/lib.rs
In principle，we should only impl cell_provider on snapshot, not the store directly.
Remove impl cell_provider on store
```release-note
```
> refactor: remove impl cell_provider on store

- Cargo.lock
- util/memory-tracker/Cargo.toml
- util/memory-tracker/src/process.rs
Remove heim dependence, because we only use a simple function to get the memory usage of the process, we don't need to rely on such a huge library 
Tests
- Manual test
Side effects
- Delete a series of related dependencies 
```release-note
```
> chore: remove heim dep

- util/app-config/src/app_config.rs
- util/app-config/src/configs/tx_pool.rs
Currently, the tx_pool default persistent path is  `data/tx_pool_persisted_data`, we will have more other data that need persistent.
Proposal: tweak default data/tx_pool_persisted_data -> data/tx_pool/persisted_data.
Tests 
`PoolPersisted` covered
```release-note
```
> [rc/v0.100] chore: tweak tx_pool default persisted path

- util/app-config/src/app_config.rs
- util/app-config/src/configs/tx_pool.rs
Currently, the tx_pool default persistent path is  `data/tx_pool_persisted_data`, we will have more other data that need persistent.
Proposal: tweak default data/tx_pool_persisted_data -> data/tx_pool/persisted_data.
Tests 
`PoolPersisted` covered
```release-note
```
> chore: tweak tx_pool default persisted path

- sync/src/orphan_block_pool.rs
- sync/src/relayer/mod.rs
- sync/src/tests/orphan_block_pool.rs
- sync/src/types/mod.rs
cleanup expired blocks in orphan pool periodically, avoid memory leak when long run
periodically  cleanup in sync module, and in cleanup procedure,  check if blocks with epoch less than  
chain tip epcho 6 epochs, remove these blocks and also remove items in header view.
Tests 
- Unit test
```release-note
```
> feat(sync orphan_block_pool): cleanup expired blocks in orphan block

- rpc/README.md
- rpc/src/module/net.rs
- util/jsonrpc-types/src/net.rs
make duration unit consistent in `get_peers` RPC 
Proposal: in 'get_peer' RPC, connected_duration uses secs but last_ping_duration uses millis,  we need to change connected_duration uses millis.
What's Changed: 
Tests 
- Unit test
Side effects
- rpc client should change 'connected_duration' duration unit from 'second' to 'millisecond' when `get_peers` RPC is used.
```release-note
**BREAKING RPC**. Change field `connected_duration` time unit from seconds to **milliseconds** in `get_peers` RPC to make time unit  used  consistently in `get_peers` , RPC clients are suggested to modify time quantity correspond with this change.
```
> refactor(rpc): change 'connected_duration' duration unit to milliseconds

- Cargo.lock
- network/src/lib.rs
- network/src/network.rs
- network/src/peer_store/ban_list.rs
- network/src/peer_store/peer_store_impl.rs
- network/src/protocols/discovery/mod.rs
- network/src/protocols/identify/mod.rs
- network/src/protocols/mod.rs
- network/src/protocols/tests/mod.rs
- network/src/services/protocol_type_checker.rs
- network/src/tests/compress.rs
- network/src/tests/mod.rs
- network/src/tests/peer_store.rs
- sync/Cargo.toml
- sync/src/tests/net_time_checker.rs
- util/launcher/src/lib.rs
add more tests on the network
Tests
- Unit test
Side effects
- Improved network unit test coverage to 70%+
```release-note
```
> test: add test for net

- Makefile
- devtools/release/make-with-debug-symbols
If we want to debug with **detached** debug information, there are two methods (with `gdb`):
- The `.gnu_debuglink` section.
The executable contains a debug link that specifies the name of the separate debug info file. 
The separate debug file's name is usually `executable.debug`.
- The `.note.gnu.build-id` section.
The executable contains a build ID, a unique bit string that is also present in the corresponding debug info file.
So, if the ckb binary has the `.note.gnu.build-id` section, even we have lots ckb binaries with different versions,
the tools, such as `gdb`, still can find the matched symbols file.
More technical details can be found in this manual [Debugging Information in Separate Files].
Postscript:
- Why we have to detach debug information?
Currently, the file of ckb debug …
> build: enable build-id when build ckb with debug symbols

- tx-pool/src/component/pending.rs
- tx-pool/src/component/proposed.rs
- tx-pool/src/component/tests/mod.rs
- tx-pool/src/component/tests/pending.rs
- tx-pool/src/component/tests/proposed.rs
- tx-pool/src/component/tests/util.rs
- tx-pool/src/pool.rs
- tx-pool/src/process.rs
- util/types/src/core/cell.rs
Previously, some conflict pending transactions may not be clean immediately, this does not affect the correctness，but will make developers who rely on `get_transaction` get confused.
Now, conflict pending transactions will be clean immediately after the new best block is committed.
Tests 
- Unit test
tx-pool/src/component/tests/pending.rs
```release-note
```
> feat: remove conflict pending for reorg

- util/src/lib.rs
This function was added in #735 to test if the program was likely to reach a deadlock.
Now, after about 2.5 years, it could be removed, since it wasn't used anymore.
Tests
```release-note
```
> chore: remove useless code

- network/src/protocols/identify/mod.rs
- network/src/protocols/tests/mod.rs
fix https://github.com/nervosnetwork/ckb/runs/3673717980#step:4:1915 this ci fail
1. assert fail because the assert is wrong here, the `registered` behavior is before `received`, and the `discovery` in the test is broadcast every second. It is impossible to determine whether the node3 is just in the process of trying to connect when asserting. It can also be changed to `wait_connect_state(&node3, 1)`, but I don’t think it’s necessary, it’s no problem to delete it directly 
2. When identify is closed, we should first check whether the current node information is banned and then insert the peer store, otherwise, the banned address may be spread 
Tests
- Unit test
```release-note
```
> fix: fix identify disconnect

- network/src/protocols/tests/mod.rs
fix https://github.com/nervosnetwork/ckb/runs/3698507039#step:4:2081
The ban cannot be judged as before, because the main body of ban may be node1 or node2, and there will be random problems. 
Tests
- Unit test
```release-note
```
> ci: fix ci

- Cargo.lock
- deny.toml
fix  https://rustsec.org/advisories/RUSTSEC-2021-0115 
Tests
```release-note
```
> chore: upgrade zeroize

- script/src/ill_transaction_checker.rs
- script/src/verify.rs
- script/src/verify_env.rs
Transaction submission in the current epoch can only use the VM version based on the current epoch 
Tests
- Integration test in other repo
```release-note
```
> fix: ignore proposal window on vm version selection

- rpc/src/module/test.rs
- sync/src/relayer/transactions_process.rs
- sync/src/types/mod.rs
- test/src/rpc.rs
- test/src/specs/relay/transaction_relay_low_fee_rate.rs
- test/src/specs/tx_pool/send_large_cycles_tx.rs
By design we should check that the corresponding tx hash has been requested before processing the relay transaction message, but the current code misses this check, this PR resolved this issue.
Check the `unknown_tx_hashes` structure before processing the message to see if the corresponding tx hash has already been requested.
Tests 
- Unit test
Side effects
This PR removed `broadcast_transaction` rpc from the `IntegrationTest` module, other integration tests that rely on this rpc need to be adapted accordingly, please refer to the related change of test code in this PR.
```release-note
```
> chore: check if the corresponding tx hash has already been requested before processing the tx relay message

- chain/src/tests/block_assembler.rs
Problem Summary: 
Since https://github.com/nervosnetwork/ckb/pull/2984, if tx-pool does not sync with chain yet, a blank template will return by request.  this may lead to some block-template tests failed randomly.
What's Changed:  Make block-template tests block on status sync.
Tests 
- Unit test
```release-note
```
> fix: block-template test

- devtools/ci/ci_main.sh
The minimum supported rust version for `cargo-deny` (`=1.53.0`, [since it upgrade spdx](https://github.com/EmbarkStudios/cargo-deny/commit/b0fc7c440bea0fb39dc6aea921094e4ea15b6887)) is greater the rust version we locked in `rust-toolchain` (`=1.51.0`).
We could just use the latest stable version of rust (`=1.56.0`, at present) to install `cargo-deny`.
Tests
- No code ci-runs-only: [ cargo_deny ]
```release-note
```
> ci: fix cargo deny installation

- network/src/network.rs
`ProtocolHandleErrorKind::Block(None)` just mention user there may be something blocking the event process, but nothing is wrong, always it just needs to wait for the process, except deadlock.
`ProtocolHandleErrorKind::AbnormallyClosed` is a terrible error for any protocol, it means there has one protocol handle abnormally closed, usually something wrong for panic
Tests
```release-note
```
> chore: move sentry scope

- Cargo.lock
- script/Cargo.toml
Upgrade to ckb-vm 0.20.0.
Note that there is no difference between ckb-vm 0.20.0 and ckb-vm 0.20.0-rc6 except version number.
> Update ckb-vm to 0.20.0

- sync/src/relayer/transaction_hashes_process.rs
- sync/src/status.rs
- sync/src/types/mod.rs
- test/src/main.rs
- test/src/specs/relay/mod.rs
- test/src/specs/relay/too_many_unknown_transactions.rs
- util/constant/src/sync.rs
A peer is allowed to send too many transactions hash but doesn't respond with the transaction entities.
Ban peer which sends too many unknown transactions hash.
Tests 
- Unit test
```release-note
```
> chore: limit number of unknown transactions per peer

- script/src/syscalls/load_cell_data.rs
Solve the problem that 'load_data_cell_as_code' cannot work with 'ckb-vm chunk run'
ref: https://github.com/nervosnetwork/ckb-vm/pull/218
> Fix: add dirty flag when load cell data as code

- Cargo.lock
- script/Cargo.toml
- script/src/syscalls/load_cell_data.rs
- script/src/syscalls/tests/vm_latest/syscalls_1.rs
- script/src/types.rs
- script/src/verify.rs
- script/src/verify/tests/ckb_latest/features_since_v2021.rs
- test/src/specs/hardfork/v2021/vm_b_extension.rs
chunk run with the snapshot unable to support the binary replacement behavior of exec, which will cause abnormal behavior after resume.
The upgraded VM supports backing up the current code(executable pages)  to the snapshot to fix the above problems. https://github.com/nervosnetwork/ckb-vm/pull/218
and https://github.com/nervosnetwork/ckb/pull/3176 should keep its behavior until hardfork activated
Tests
- Unit test
```release-note
```
> fix: upgrade ckb-vm to fix snapshot behavior

- script/src/types.rs
- script/src/verify.rs
The script group resume from the snapshot will lose the cycles consumed by the current execution, causing the value obtained by the current cycle syscall call to reset, causing potential inconsistencies.
This pr will fix the problem and only affects testnet  
Tests
- Unit test
```release-note
```
> fix: fix current cycles syscall on chunk run with snapshot

- network/src/network.rs
Increase the window size of yamux to improve bandwidth utilization.
By default, the window size of yamux is 256kb, but the maximum size of a block of ckb is 500k+, which means that the message needs to be sent and received twice + 2 window update messages to complete 
Side effects
- Memory usage may increase 
```release-note
```
> feat: increase yamux window size

- ckb-bin/src/subcommand/stats.rs
outputs miner status in cli cmd
Tests 
```
uncle_rate: 153507/5920421(0.025928392592351118)
by_miner_script:
percentage | total | args                                     | code_hash                                                        | hash_type 
35.9%      | 359   | dde7801c073dfb3464c7b1f05b806bb2bbb84e99 | 9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8 | Type
18.6%      | 186   | 7164f48d7a5bf2298166f8d81b81ea4e908e16ad | 9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8 | Type
14.0%      | 140   | ba6caca0c7e893e412d67264c2eb2a1fc13c46fd | 9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8 | Type
11.3%      | 113   | 4a336470564d07ca7059b7980481c2d59809d637 | …
```
> chore: output miner status

- network/src/protocols/discovery/mod.rs
- network/src/protocols/mod.rs
After more than two years of operation, I am sure that the stability of Tentacle’s notify can be guaranteed. This PR removes this unnecessary timer 
Tests
- Unit test
```release-note
```
> chore: remove unnecessary timer

- chain/src/tests/block_assembler.rs
- tx-pool/src/block_assembler/candidate_uncles.rs
- tx-pool/src/block_assembler/mod.rs
- tx-pool/src/block_assembler/tests.rs
- tx-pool/src/lib.rs
Problem Summary:  Now, candidate uncles will be clear immediately once we checked it's invalid, but this is variable and temporary, we should keep candidate until next epoch.
Proposal: retain candidate uncle until next epoch.
Tests 
- Unit test
```release-note
```
> feat: retain candidate uncle until next epoch

- .github/workflows/sync-mainnet.yml
What's Changed: This PR adds a new GitHub Actions workflow sync-mainnet.yml. sync-mainnet.yml runs [CKB Sync Mainnet Test](https://github.com/nervosnetwork/ckb-integration-test/tree/main/ckb-sync-mainnet) on a self-hosted runner.
The reason for running this workflow on a self-hosted runner could be found from the below references:
- https://github.community/t/one-job-stuck-for-6-hrs-and-failed/165249
- https://github.community/t/is-that-possible-to-run-job-which-takes-more-than-6-hours-on-self-hosted-runner/17121/4
- https://github.com/nervosnetwork/ckb-integration-test/pull/50
- https://github.com/nervosnetwork/ckb-integration-test/pull/32
Tests 
```release-note
```
> feat: run sync-mainnet.yml on self-hosted runner

- Cargo.lock
In the default configuration, it has no effect, but we can enable the adjustment of window size after hardfork
```
yamux 0.3.2: edition 2018 
yamux 0.3.3 and 0.3.1: edition 2021
- Fix yamux window update(#340)
```
Tests
- Unit test
```release-note
```
> chore: upgrade yamux

- .cargo/config
- .github/workflows/ci_aarch64_build_ubuntu.yaml
- devtools/ci/ci_main.sh
Now that aarch64 build has been tested for a while, I propose we include
aarch64 build workflow as part of the CI process
Add aarch64 build as part of the CI workflow
Tests 
- Unit test
- No code ci-runs-only: [ aarch64_build_ubuntu, quick_checks,linters ]
Side effects
```release-note
```
> chore: add aarch64 build workflow to CI

- .github/actions/ci_prologue/ci_prologue.sh
CI not run last job in the runs_only list , since the  in the last job contains a space, fix it
Tests
```release-note
```
> ci: ci not run last job in the run_job list

- .github/workflows/smoking_test.yaml
self-hosted runner has  different user name caused ckb service start failed, the smoking test failed. Change the `User` before start ckb service.
Tests 
```release-note
```
> ci: ckb service start failed on self runner,fix it

- sync/src/relayer/block_transactions_process.rs
- sync/src/relayer/compact_block_process.rs
- sync/src/relayer/tests/block_transactions_process.rs
- sync/src/relayer/tests/compact_block_process.rs
- sync/src/synchronizer/block_fetcher.rs
- sync/src/tests/inflight_blocks.rs
- sync/src/types/mod.rs
Currently, there is a record of `pending_compact_block` in `SyncState`, and a record of `pending_compact` in `InflightBlock`. The record in `InflightBlock` limits the `BlockTransaction` request to only two remote nodes at the same time. 
This is repetitive recording work, and because of the limitation, the construction work with n-2 data is completely wasted.
This change removes the internal records of `InflightBlock` and turns on the request limit of `BlockTransaction` .
The remaining question is, do we need to keep the limit on the number of requests? 
Tests
- Unit test
```release-note
```
> chore: remove inflight block struct's compact's record

- sync/src/relayer/compact_block_process.rs
- sync/src/relayer/tests/compact_block_process.rs
if block status is RECEIVED, it means block received and remain on orphan pool, the same block received afterwards does not need to be repeatedly inserted into the orphan pool 
Tests
- Unit test
```release-note
```
> chore: ignore received compact block

- script/src/types.rs
- script/src/verify.rs
- script/src/verify/tests/ckb_latest/features_since_v2021.rs
- tx-pool/src/chunk_process.rs
Normally, transaction script group execution is not order sensitivity, but consistent execution order may help prevent potential unexpected inconsistent bug
Proposal:  make script group with consistent order
Tests 
- Unit test
```release-note
```
> feat: script group consistent execution order

- sync/src/relayer/block_transactions_process.rs
- sync/src/relayer/tests/block_transactions_process.rs
- test/src/main.rs
- test/src/specs/relay/compact_block.rs
fix block transaction process dead loop
Although the sync protocol will force such a dead loop to be broken, as a single protocol, this is a must-fix
Tests
- Unit test
```release-note
```
> fix: fix block transaction process dead loop

- Cargo.lock
ref https://github.com/rust-lang/futures-rs/issues/2529, 0.3.18 has been yank
Tests
```release-note
```
> chore: downgrade futures version

- network/src/lib.rs
- network/src/network.rs
- util/launcher/src/lib.rs
Since the port reuse function of ckb is enabled by default on Linux, starting two ckb nodes will not report an error explicitly, after this PR will automatically exit the second ckb node 
Tests
Manual test:
1. start 2 ckb nodes with the same net port
2. the second one will stop with an error
```
2021-12-13 17:21:31.585 +08:00 main INFO ckb_bin::helper  raise_fd_limit newly-increased limit: 524288                                 
2021-12-13 17:21:34.235 +08:00 main INFO ckb_bin::subcommand::run  ckb version: 0.102.0-pre (1595009-dirty 2021-12-13)                 
2021-12-13 17:21:34.236 +08:00 main INFO ckb_launcher  Miner is disabled, edit ckb.toml to enable it                                   
IO Error: Os { code: 98, kind: AddrInUse, message: "Address already in use" } …
```
> feat: observe listen port occupancy

- Cargo.lock
- freezer/Cargo.toml
- miner/Cargo.toml
- store/Cargo.toml
- sync/Cargo.toml
- tx-pool/Cargo.toml
- util/network-alert/Cargo.toml
- verification/Cargo.toml
Fix #3249: [RUSTSEC-2021-0130] Use after free in lru crate.
- bump lru from 0.6.6 to 0.7.1.
Tests
- Unit test
```release-note
```
[RUSTSEC-2021-0130]: https://rustsec.org/advisories/RUSTSEC-2021-0130.html
> chore(deps): bump lru from 0.6.6 to 0.7.1 to fix RUSTSEC-2021-0130

- Makefile
- network/src/network.rs
dial command will reject by dialing feeler or session keep online
https://github.com/nervosnetwork/ckb/blob/5b44843b0053ca8eee23249c38eaca3308bceb64/network/src/network.rs#L332-L334
dialing feeler flag will remove on feeler disconnected
https://github.com/nervosnetwork/ckb/blob/5b44843b0053ca8eee23249c38eaca3308bceb64/network/src/protocols/feeler.rs#L47-L51
But if the remote side turns off the protocol before local has opened it, the local's dialing feeler flag will not be cleared, also, this node can no longer be dial
why has such a delay on open protocol?
outbound: request open -> wait remote response -> open protocol
inbound: wait request -> send back response and open the protocol
There is a slight difference in the opening time of the two sides
Tests 
- Unit test …
> fix: session close also should remove feeler dialing flag

- .github/workflows/sync-mainnet.yml
Sync-mainnet test failed since secrets cannot be used to condition job runs
Tests 
```release-note
```
> ci: Secrets cannot be used to condition job runs

- sync/src/relayer/compact_block_process.rs
- sync/src/types/mod.rs
* refactor compact block execute code, split compact block pre-check code into
non_contextual_check() and contextual_check() function
* move post process code into missing_or_collided_post_process() 
after failed to rebuild whole block, found missing or collided transactions. 
* use header reference instead of into_view() and import PendingCompactBlockMap
* add function comment in markdown format
i still not sure about function comments, please help.
the execute() function is about 250 lines, and contains some of pre-checks, and post-process after re-build block failed. 
i tried to make it more readable and hope you guys provide suggestions about how to make refactor better.
only split bunch of codes into 3 functions, not mean to change logic and behavior …
> refactor(relay): split compact block execute code, more readable

- sync/src/types/mod.rs
The locator algorithm is designed to send a sample of local chains to the remote end, so that both sides can determine the same header of the maximum height of both sides as efficiently as possible, thus completing the header synchronization work faster
As time goes on, the current locator algorithm becomes more and more inapplicable as the chain height increases, and we need a locator algorithm that constantly adjusts itself to the height of the chain. It allows the entire chain to be sampled as much as possible during the sampling process, instead of the lowest sampling point being pulled up step by step as the height increases
This PR relaxes the length of the locator to 52
Tests
- Unit test
```release-note …
```
> feat: tuning the locator algorithm

- chain/src/chain.rs
- tx-pool/src/process.rs
Chain verification should reset cache before hardfork, and  make sure cache no dirty write.
Make sure tx-pool don't access verification cache during hardfork.
Tests 
- Unit test
```release-note
```
> fix: verification cache reset during hardfork

- .github/workflows/package.yaml
- devtools/ci/package.sh
- docs/platform-support.md
- script/build.rs
Port CKB to aarch64, and provide official binary when release.
Note: No `ckb-cli` for AArch64 port.
Tests
- Unit test
```release-note
```
> feat: port to aarch64, and provide official binary when release

- .github/workflows/benchmark.yml
Benchmark test failed since secrets cannot be used to condition job runs
Tests 
```release-note
```
> ci: Benchmark failed since Secrets cannot be used to condition job runs

- sync/src/relayer/mod.rs
- sync/src/relayer/tests/helper.rs
- util/launcher/src/lib.rs
remove obsolete min_fee_rate, max_tx_verify_cycles from relayer
these 2 parts' function are already implemented in tx pool,  and these 2 fields in relay not working for now
None
```release-note
```
> refactor(relay): remove obsolete min_fee_rate, max_tx_verify_cycles from relayer

- devtools/doc/rpc.py
- rpc/README.md
- rpc/src/error.rs
- test/src/main.rs
- test/src/specs/tx_pool/collision.rs
- tx-pool/src/component/pending.rs
- tx-pool/src/component/proposed.rs
- tx-pool/src/component/tests/pending.rs
- tx-pool/src/component/tests/proposed.rs
- tx-pool/src/pool.rs
- tx-pool/src/process.rs
- util/app-config/src/configs/tx_pool.rs
- util/app-config/src/legacy/tx_pool.rs
- util/jsonrpc-types/src/pool.rs
- util/types/src/core/tx_pool.rs
Previously, pending transaction removed but descendants remain.
1. remove conflict and descendants.
2. transaction expiration.
3. non-mine mode.
Tests 
- Unit test
```release-note
```
> fix: resolve conflict descendants

- util/jsonrpc-types/src/uints.rs
Previously, uppercase hex format have been unintentionally forbiden. 
Many language such [java](https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-3.10.1) 
> each letter used as a hexadecimal digit may be uppercase or lowercase.
specify hexadecimal is not case-sensitive.
Tests 
- Unit test
```release-note
```
> feat: case-insensitive hex

- README.md
Replace the revoked link with the permanent customization link.
Problem Summary: The Discord server admin has revoked the invitation link.
What's Changed: Update the Discord server invitation link in README.
Tests 
```release-note
```
> chore: update discord invitation link

- sync/src/synchronizer/mod.rs
- util/types/schemas/extensions.mol
- util/types/src/generated/extensions.rs
Remove transactions filter related messages from sync protocol since [rfc 0011](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0011-transaction-filter-protocol/0011-transaction-filter-protocol.md) has been withdrawn.  And we didn't implement the logic in ckb node, so the message definition can been safely removed from the sync protocol.
Tests 
- Unit test
```release-note
```
> chore: remove transactions filter related messages from sync protocol

- Cargo.lock
- ckb-bin/src/subcommand/replay.rs
- miner/src/worker/eaglesong_simple.rs
- network/Cargo.toml
- network/src/network.rs
- network/src/peer_registry.rs
- network/src/protocols/discovery/state.rs
- network/src/protocols/ping.rs
- network/src/protocols/tests/mod.rs
- network/src/services/protocol_type_checker.rs
- rpc/src/module/net.rs
- sync/src/relayer/mod.rs
- sync/src/synchronizer/mod.rs
- sync/src/tests/net_time_checker.rs
- util/Cargo.toml
- util/stop-handler/Cargo.toml
ref: https://github.com/rust-lang/rust/pull/89926
upgrade tokio/tentacle/parking_lot
tokio:
```
- time: prevent panicking in `sleep` with large durations ([#4495])
- time: eliminate potential panics in `Instant` arithmetic on platforms where
`Instant::now` is not monotonic ([#4461])
- io: fix `DuplexStream` not participating in cooperative yielding ([#4478])
- rt: fix potential double panic when dropping a `JoinHandle` ([#4430])
- update minimum supported Rust version to 1.49 ([#4457])
- update `parking_lot` dependency to v0.12.0 ([#4459])
- update `mio` dependency to v0.8 ([#4449])
- rt: remove an unnecessary lock in the blocking pool ([#4436])
- rt: remove an unnecessary enum in the basic scheduler ([#4462])
- time: use bit manipulation instead of modulo to improve performance ([#4480]) …
```
> chore: fix instant panic on some case

- rpc/src/service_builder.rs
fix #3307, check PoW Dummy after integration test is enabled
fix #3307, move PoW Dummy check after integration_test_enable()
otherwise, normal node(without Integration test) also run pow dummy check.
Tests 
```release-note
```
> fix: fix 3307

- Cargo.lock
- miner/Cargo.toml
Problem Summary: The build fails because of inconsistent console versions.
1. Use the same version requirements on console in `miner/Cargo.toml` as in `db-migration/Cargo.toml`.
2. Use `cargo update -p console:0.13.0` to remove the inconsistent version from the dependency tree.
Tests
```release-note
```
> chore(deps): remove console 0.13.0

- .github/workflows/benchmark.yml
- .github/workflows/package.yaml
- .github/workflows/scheduled_audit.yaml
Problem Summary: Using `*-latest` environment is vulnerable to unexpected update.
For example, after GitHub upgrade windows-latest from windows-2019 to
windows-2022, yasm installed via scoop stops working, which leads to
failed CKB packaging.
https://github.com/nervosnetwork/ckb/runs/5343852953?check_suite_focus=true
What's Changed: Stop using `*-latest` in all GitHub Actions workflows.
Tests 
```release-note
```
> ci: lock actions virtual environment

- .github/workflows/package.yaml
Problem Summary: LLVM has upgraded to 13.0.1, which breaks the package workflows because the build script cannot find libclang via the environment variable LIBCLANG_PATH
What's Changed: Use `$env:USERPROFILE\scoop\apps\llvm\current\bin` instead.
Tests
```release-note
```
> ci: use llvm/current in LIBCLANG_PATH

- Cargo.lock
- util/types/Cargo.toml
Problem Summary: ckb-types depends on outdated version of bit-vec.
What's Changed: Upgrade the version requirement of bit-vec in util/types/Cargo.toml
Tests
```release-note
```
> chore(deps): upgrade bit-vec to 0.6.3

- sync/src/synchronizer/in_ibd_process.rs
- test/src/specs/alert/alert_propagation.rs
- test/src/specs/p2p/discovery.rs
- test/src/specs/p2p/whitelist.rs
- test/src/specs/sync/ibd_process.rs
- test/src/specs/tx_pool/txs_relay_order.rs
1. `suspend_sync` has determined if it is in sync start state
2. Errors sent behavior in outbound should be disconnected unless they are whitelisted
3. The protect node is randomly generated and should be disconnected if it is in ibd state, otherwise the sync data source is inherently missing
Tests
- Unit test
```release-note
```
> chore: protect node in ibd should also disconnnected

- chain/src/chain.rs
- tx-pool/src/process.rs
Problem Summary: log transaction verified result for monitor node to inspect transaction including cycles, vm...
What's Changed: 
- add checkpoint to log transaction verified result in chain and tx-pool 
- add `ckb_tx_monitor` log target to log tx verification result to logfile
- combined with config in ckb.toml to store JSON format tx verification log messages in separate output file.
Tests 
add  
> [logger.extra.ckb_tx_monitor]
> filter = "off,ckb_tx_monitor=trace"
after logger section in ckb.toml
Side effects
- None (transaction log message output only when logger.extra configured)
```release-note
```
> feat(verification): log tx verification result for monitor

- Cargo.lock
ID: RUSTSEC-2022-0013
Advisory: https://rustsec.org/advisories/RUSTSEC-2022-0013
Solution: Upgrade regex to >=1.5.5
Tests 
- Unit test
```release-note
```
> fix RUSTSEC-2022-0013

- spec/src/lib.rs
When running ckb dev chain locally, user may put some custom scripts into the genesis block for development convenience, however, currently only `system_cells` supports relative paths, while `dep_groups` does not.
works:
```
[[genesis.system_cells]]
file = { file = "../compiled_binary/always_failure" }
create_type_id = true
capacity = 100_000_0000_0000
```
not working:
```
[[genesis.dep_groups]]
name = "always"
files = [
{ file = "../compiled_binary/always_success" },
{ file = "../compiled_binary/always_failure" },
]
```
this PR resolved this issue.
Tests 
```
./ckb init -c dev
edit dev.toml # add two script to dep_groups
mkdir compiled_binary
cp ckb/test/template/specs/cells/always_success compiled_binary
cp …
```
> fix: genesis dep groups should supports relative file path

- util/app-config/src/cli.rs
- util/app-config/src/tests/cli.rs
fix(ckb cli) add h256 validator for --assume-valid-target and ba-code-hash
- add H256 validator for `ckb init --ba-code-hash` and `ckb run --assume-valid-target` replace naive is_hex check.
- add related 1 testcase
now cli report error at parsing phase, prompt invalid h256 message, instead of running error.
Tests 
- Unit test
```release-note
```
> fix(ckb cli) add h256 validator for --assume-valid-target and ba-code-hash

- util/jsonrpc-types/src/proposal_short_id.rs
- util/types/src/conversion/blockchain.rs
Please refer to https://github.com/nervosnetwork/godwoken/pull/629, I think unpack a reader to array is quite rare, we should always unpack to new type, for example: `H256([u8; 32]) or ProposalId([u8;10])`. 
And in ckb current code, there are only one place to unpack the `ProposalIdReader` to [u8;10], which can be simply replaced by `try_into`, so I proposal this PR to remove these two unsafe fn.
Tests 
- Unit test
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nervosnetwork/ckb/3353)
> chore: remove unsafe reader to array unpack fn

- .github/workflows/package.yaml
- docker/hub/Dockerfile
Problem Summary: The docker build images used in CKB are outdated.
What's Changed: Upgrade to the latest builder images with Rust 1.56.1
Tests
```release-note
```
> chore: upgrade rust to 1.56.1 in docker builder

- tx-pool/src/chunk_process.rs
- tx-pool/src/error.rs
- tx-pool/src/service.rs
- verification/src/lib.rs
Signalling program state changes is good use cases for the watch channel, consumers only see the most recent value,  avoiding useless buffer overhead.
Tests 
- Unit test
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nervosnetwork/ckb/3346)
> refactor: use watch channel to notify resume state changes

- .github/workflows/ci_benchmarks_windows.yaml
- .github/workflows/ci_integration_tests_windows.yaml
- .github/workflows/ci_unit_tests_windows.yaml
- .github/workflows/package.yaml
Problem Summary: Scoop no longer supports installation as admin by default.
What's Changed: Use two-steps installation as suggested by the Scoop README.
https://github.com/ScoopInstaller/Install#for-admin
Tests
```release-note
```
> chore(ci): install scoop as admin

- devtools/ci/check-cargotoml.sh
- devtools/ci/ci_main.sh
- devtools/release/publish-crates.sh
- devtools/smoking_test/check-migrate.sh
- devtools/smoking_test/tip_block_growth_check.sh
- test/run.sh
Problem Summary: The shell files are not consistent in format.
Format all the shell files using `shfmt` with following options:
- `-ci`: Indent case
- `-i 2`: 2-spaces indentation
Example to format the file `test/run.sh`
```
shfmt -ci -i 2 -w test/run.sh
```
See more details about `shfmt` in https://github.com/mvdan/sh
Tests
- Unit test
```release-note
```
> chore: format shell files using shfmt

- chain/src/chain.rs
fix #3309, cycles mismatched when monitor tx verified result.
mismatched between resolved(txs) and cache_entries(verified_result), because resolve(txs) includes cellbase_tx and cache_entries already exclude cellbase tx.
Tests 
I will contact with Devops team member, help to verify it.
```release-note
```
> fix(tx_monitor): fix #3309, mismatch resolved_tx and completed_tx

- util/constant/src/hardfork/mainnet.rs
Problem Summary: Activate ckb2021 in mainnet since epoch 5414
Tests
- Unit test
Side effects
- Breaking backward compatibility: Nodes must upgrade to this version or above before 2020 May 10th.
```release-note
```
> config: activate ckb2021 in mainnet since epoch 5414

- Cargo.lock
- network/Cargo.toml
- network/src/network.rs
Add metrics for network ban peer or  been banned, help to measure network partition.
ban peer operation ocurred at sync and tx_pool module, but callee function is at network module, network.rs
we add ban_peer and reason info. in metrics.
Tests 
- test manually
```release-note
```
> feat(metrics): add metrics for ban and been_baned

- network/src/network.rs
- test/src/main.rs
- test/src/specs/rpc/mod.rs
- test/src/specs/rpc/set_ban.rs
previous RPC `set_ban`(peer_ip, ... ) only adds peer into ckb inner ban_list, but doesn't disconnect the peer instantly.
the PR adds disconnect session operation when invoke RPC set_ban().
we add `disconnect session` into the process, to disconnect peers instantly.
RPC `set_ban` support user input single IP address, and IP/Subnet form. PR's code traverse connecting peers to check if match IP or within Subnet.  
Tests 
- Unit test
Side effects
- IP address traversal match may be a concern of performance when node has lots of peer connection.
```release-note
```
> fix(rpc): disconnect session of peers when invoke rpc set_ban

- .github/workflows/scheduled_audit.yaml
Problem Summary: The security audit job keeps failing in forks because GitHub Issues module is disabled.
What's Changed: Disable the job in forks.
Tests
```release-note
```
> fix: do not run job "Security Audit" in forks

- test/src/specs/rpc/set_ban.rs
fix CI test failure of testcase RpcSetBan of PR3387
CI test running enviroment differs from local host,  timming and lag will be a problem when write testcase and assert result.
here we should use `a more robust way to wait.`
we already check the result is positive in running test of PR3392.
Tests 
- Unit test
```release-note
```
> fix(test): fix PR3387's testcase CI running failure

- test/src/main.rs
- test/src/specs/rpc/mod.rs
- test/src/specs/rpc/set_ban.rs
Problem Summary: fix RpcSetBan run failed on MacOS
conditional flag set for this testcase, only running on Linux/Ubuntu for now.
the testcase design will utility localhost different ip binding, but due to OS difference, 
MacOS doesn't support 127.0.x.x binding on localhost interface, the test result is negative.
Tests 
- Unit test
```release-note
```
> fix(integration_test): fix RpcSetBan testcase failure on MacOS

- test/src/specs/dao/satoshi_dao_occupied.rs
- test/src/specs/dao/utils.rs
- test/src/specs/hardfork/v2021/cell_deps.rs
- test/src/specs/mining/basic.rs
- test/src/specs/mining/fee.rs
- test/src/specs/relay/get_block_proposal_process.rs
- test/src/specs/rpc/transaction_proof.rs
- test/src/specs/rpc/truncate.rs
- test/src/specs/tx_pool/collision.rs
- test/src/specs/tx_pool/pool_reconcile.rs
- test/src/specs/tx_pool/send_large_cycles_tx.rs
- test/src/util/mining.rs
Fix integration tests that fail due to inaccurate assertions
Add mine_until_transaction_confirm method to avoid interference when multiple transactions occur.
Tests 
- Unit test
```release-note
```
> fix: mining blocking until specified tx confirm

- sync/src/relayer/compact_block_process.rs
- sync/src/relayer/mod.rs
Problem Summary: Add metrics for fresh tx in compact block process, indicating effect of transactions broadcasted over network.
- metrics of compact block reconstruction success/failure count
- metrics of fresh txs count when reconstruct fail and total txs count when reconstruct pass.
- add a metrics of txs collide(two different txs have the same short_id value)
Tests 
```release-note
```
> feat(metrics): add metrics for fresh tx in compact block

- rpc/README.md
- util/jsonrpc-types/src/blockchain.rs
- util/types/src/core/blockchain.rs
Fix a typo for `rpc/README.md`
> fix typo for hash_type note

- Cargo.lock
- util/launcher/Cargo.toml
- util/launcher/src/shared_builder.rs
- util/runtime/Cargo.toml
- util/runtime/src/lib.rs
On windows the runtime in thread_local will get stuck when dropping
Only the join handle is stored in thread_local instead of the runtime.
Tests 
- Unit test
```release-note
```
> fix: thread locals runtime drop

- test/src/utils.rs
satoshi_dao_occupied test random failed
Wait tx_pool sync when generate unspent cell
Tests 
- Unit test
```release-note
```
> fix: satoshi_dao_occupied test

- util/types/schemas/extensions.mol
- util/types/src/generated/extensions.rs
- util/types/src/utilities/merkle_mountain_range.rs
Currently implementation of creating `VerifiableHeader` from `HeaderWithChainRoot` always fill a extension field that calculated from the chain root, this is wrong when `header.number()` less than `mmr_activated_number`.
* When `header.number() < mmr_activated_number` let extension be `None`
* change `HeaderWithChainRoot` data type from table to struct
> fix(light-client): Fix create variable header

- util/light-client-protocol-server/src/components/get_block_samples.rs
- util/light-client-protocol-server/src/components/get_last_state.rs
- util/light-client-protocol-server/src/components/mod.rs
- util/light-client-protocol-server/src/lib.rs
- util/types/schemas/extensions.mol
- util/types/src/conversion/mmr.rs
- util/types/src/generated/extensions.rs
* Remove `mmr_activated_number` field from SendLastState
* Add `last_hash` to field to GetLastState message
* Add `proof` and `chain_root` fields to SendLastState message
* Rename GetBlockProof to GetBlockSamples
* Rename SendBlockProof to SendBlockSamples
> refactor(light-client): update light client message schema

- util/light-client-protocol-server/src/components/get_block_samples.rs
Check last_block_hash not in main chain is allowed, since we will return `reorg_last_n_headers` to let light-client side fix fork problem.
> fix: the last block hash of GetBlockSamples no need in main chain

- Cargo.lock
- db/Cargo.toml
Bumps [rocksdb](https://github.com/nervosnetwork/rust-rocksdb) from 0.16.1 to 0.18.1.
follow rocksdb/INSTALL.md
> By default the binary we produce is optimized for the platform you're compiling on
(`-march=native` or the equivalent). SSE4.2 will thus be enabled automatically if your
CPU supports it. To print a warning if your CPU does not support SSE4.2, build with
`USE_SSE=1 make static_lib` or, if using CMake, `cmake -DFORCE_SSE42=ON`. If you want
to build a portable binary, add `PORTABLE=1` before your make commands, like this:
`PORTABLE=1 make static_lib`.
introduce portable feature
Tests 
- Unit test
```release-note
Title …
```
> chore(deps): bump rocksdb from 0.16.1 to 0.18.1

- sync/src/types/mod.rs
test `get_ancestor_use_skip_list` was broken since https://github.com/nervosnetwork/ckb/pull/3391
Make sure genesis skip_hash is none.
Tests 
- Unit test
```release-note
```
> fix(tests): get_ancestor_use_skip_list

- util/light-client-protocol-server/src/components/get_block_proof.rs
- util/light-client-protocol-server/src/components/get_block_samples.rs
- util/light-client-protocol-server/src/components/mod.rs
- util/light-client-protocol-server/src/lib.rs
- util/types/schemas/extensions.mol
- util/types/src/conversion/mmr.rs
- util/types/src/generated/extensions.rs
Add `GetBlockProof` light-client message handler to send proof of a batch of blocks.
> feat(light-client): add GetBlockProof message handler

- .github/workflows/package.yaml
- Makefile
- docker/hub/Dockerfile
Failed to package v0.104.0 because `make prod` now places ckb binary under `target/prod`.
- chore: use target/prod/ckb after make prod
- chore: fix aarch64 package
- chore: fix feature name in make prod_portable
Tests 
```release-note
```
> fix v0.104.0 package

- tx-pool/src/component/entry.rs
- tx-pool/src/component/pending.rs
https://github.com/contain-rs/linked-hash-map/releases/tag/v0.5.5
linked-hash-map was recently updated and supports drain 
https://docs.rs/linked-hash-map/latest/linked_hash_map/struct.LinkedHashMap.html#method.drain
> Current performance implications (why to use this over into_iter()):
>* Clears the inner HashMap instead of dropping it
>* Puts all drained nodes in the free-list instead of deallocating them
>* Avoids deallocating the sentinel node
Tests 
- Unit test
```release-note
```
> chore: leverage link-hash-map drain

- sync/src/synchronizer/mod.rs
- sync/src/tests/synchronizer/functions.rs
- sync/src/types/mod.rs
We need to ensure the order of `Acquire + Release`, because the operation here is multi-threaded and parallel
`fetch_x`
> Note that using [Acquire](https://doc.rust-lang.org/nightly/std/sync/atomic/enum.Ordering.html#variant.Acquire) makes the store part of this operation [Relaxed](https://doc.rust-lang.org/nightly/std/sync/atomic/enum.Ordering.html#variant.Relaxed), and using [Release](https://doc.rust-lang.org/nightly/std/sync/atomic/enum.Ordering.html#variant.Release) makes the load part [Relaxed](https://doc.rust-lang.org/nightly/std/sync/atomic/enum.Ordering.html#variant.Relaxed).
so we need at least use [`AcqRel`](https://doc.rust-lang.org/nightly/std/sync/atomic/enum.Ordering.html#variant.AcqRel) to make sure the order is right
Tests
- Unit test
```release-note …
```
> fix: fix atomic fetch update ordering

- Cargo.lock
- block-filter/Cargo.toml
- block-filter/src/filter.rs
- block-filter/src/lib.rs
- chain/src/tests/delay_verify.rs
- docs/hashes.toml
- network/src/network.rs
- spec/src/hardfork.rs
- spec/src/tests/consensus.rs
- sync/src/filter/mod.rs
- sync/src/types/mod.rs
- util/launcher/src/migrate.rs
- util/launcher/src/migrations/mod.rs
- util/launcher/src/migrations/rebuild_block_filter.rs
- util/light-client-protocol-server/src/lib.rs
- util/light-client-protocol-server/src/status.rs
- util/types/src/core/hardfork.rs
- util/types/src/utilities/merkle_mountain_range.rs
upgrade gcs lib to 0.2.0 and rebuild the block filter data since the gcs params M has been changed from `784930` to `784931`
Tests 
- Unit test
> chore: upgrade gcs filter lib and rebuild data

- sync/src/filter/get_block_filters_process.rs
increase `GetBlockFilters` message batch size to 1000, same as bip157:
```
The height of the block with hash StopHash MUST be greater than or equal to StartHeight, and the difference MUST be strictly less than 1000.
```
> chore: tweak block filter message batch size to 1000

- Cargo.lock
- script/Cargo.toml
Release Note:
https://github.com/nervosnetwork/ckb-vm/releases/tag/v0.21.4
Greatly improve the performance of ckb-vm. When run `./ckb replay --tmp-target tmp --profile 7000000 7100000` in mainnet,
- ckb v0.103.0 took 47 hours 30 minutes
- ckb v0.103.0 with new ckb-vm only took 25 hours and 15 minutes
> chore(deps): bump ckb-vm to v0.21.4

- Cargo.lock
- util/light-client-protocol-server/Cargo.toml
- util/light-client-protocol-server/src/components/get_transactions.rs
- util/light-client-protocol-server/src/components/mod.rs
- util/light-client-protocol-server/src/lib.rs
- util/types/schemas/extensions.mol
- util/types/src/generated/extensions.rs
This PR added GetTransactions/SendTransactions message to light client protocol, which is mainly used by clients to fetch unknown `cell_deps` to verify transactions on local ckb-vm
> feat: add GetTransactions message to light client protocol

- util/light-client-protocol-server/src/components/get_block_samples.rs
- util/light-client-protocol-server/src/constant.rs
- util/types/schemas/extensions.mol
- util/types/src/generated/extensions.rs
The number, how many last blocks should be sampled, is a security parameter for light client.
- It should depend on the client side.
Clients choose their best security parameters for their own cases.
- If it's a constant, we have to do hard-fork or soft-fork when we want to update it.
> feat(light-client): how many last blocks should be sampled depends on the client

- util/light-client-protocol-server/src/components/get_block_samples.rs
- util/types/schemas/extensions.mol
- util/types/src/conversion/network.rs
- util/types/src/generated/extensions.rs
- util/types/src/utilities/merkle_mountain_range.rs
The client couldn't recovery the block extension with `HeaderWithChainRoot`.
Because the data after the 32nd byte of a block extension is unknown.
- `VerifiableHeaderWithChainRoot` is not fixed-size.
- `VerifiableHeaderWithChainRoot` is bigger than `HeaderWithChainRoot` 20~120 bytes.
> fix(light-client): recovery block extensions to incorrect data

- Cargo.lock
- network/src/network.rs
fix https://github.com/nervosnetwork/ckb/discussions/2654#discussioncomment-3561768
Fix the panic caused by the configuration file
Reuse-bind cannot be performed between ipv4 and ipv6, and branch judgment is required
Tests
- Unit test
```release-note
```
> fix: fix tcp reuse bind

- util/light-client-protocol-server/src/components/get_block_samples.rs
When try to find the first block whose total difficulty is not less than a provided total difficulty between two block numbers, the end number shouldn't be included.
> fix(light-client): duplicate blocks in proof items

- .github/workflows/package.yaml
- devtools/ci/package.sh
- #3567 Add better cross-platform builds in releases.
- #3560 error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
- Fix #3567 by creating portable binaries for Linux, CentOS and macOS.
- Fix #3560 by statically linking OpenSSL.
Tests
```release-note
```
> portable release

- Cargo.lock
Upgrade some packages to remove duplicate dependencies
```bash
Updating flate2 v1.0.22 -> v1.0.24
Removing miniz_oxide v0.4.4
Removing hashbrown v0.11.2
Updating indexmap v1.8.0 -> v1.9.1
Updating getrandom v0.2.4 -> v0.2.7
Removing wasi v0.10.2+wasi-snapshot-preview1
Removing cast v0.2.7
Updating criterion-plot v0.4.4 -> v0.4.5
Updating enum-as-inner v0.3.3 -> v0.3.4
Updating heck v0.3.3 -> v0.4.0
Removing unicode-segmentation v1.9.0
```
Tests 
- Unit test
```release-note
```
> chore: organizing dependencies

- Cargo.lock
- Cargo.toml
- util/memory-tracker/Cargo.toml
> ## 0.5.0 - 2022-05-19
> Update jemalloc to 5.3.0 (https://github.com/tikv/jemallocator/pull/23)
Tests 
- Unit test
```release-note
```
> chore: update jemalloc to 5.3.0

- network/src/network.rs
This PR make synchronize progress faster. @driftluo. Revert #3200 
The default yamux.max_stream_window_size is 256K, but the maximum size of a block of ckb is 500K, which may increase the times of messages are transmitted across the network.  
On my machine, it reduce synchronize time cost about 1 hour.
> CKB sync progress:(timestamp(s), height)
>
> red line: not set `YamuxConfig.max_stream_window_size`, default (256K)
> blue line: set `YamuxConfig.max_stream_window_size` to `1M`
> 
> CPU: i7-9750H, 12 core, 4.5GHz; Memory: 64GB
change `NetworkService`'s `YamuxConfig.max_stream_window_size` from `256K(default)` to `1M`.
- #3141
- #3200 
Side effects
- Memory usage may increase
```release-note
```
> chore: increase yamux.max_stream_window_size from 256K to 1M

- util/light-client-protocol-server/src/components/get_blocks_proof.rs
- util/light-client-protocol-server/src/components/get_transactions_proof.rs
- util/light-client-protocol-server/src/lib.rs
Handle the follow cases:
- Receive a request for asking a proof without nothing required to be proved.
- Receive a request for asking a proof and all items required to be proved are missing.
> fix: handle the case when no item to prove

- Cargo.lock
- chain/src/tests/load_code_with_snapshot.rs
- devtools/doc/rpc.py
- rpc/README.md
- rpc/src/module/chain.rs
- test/src/lib.rs
- test/src/rpc.rs
- test/src/specs/hardfork/v2021/cell_deps.rs
- test/src/specs/hardfork/v2021/vm_version.rs
- test/src/specs/sync/chain_forks.rs
- test/src/specs/tx_pool/collision.rs
- test/src/specs/tx_pool/different_txs_with_same_input.rs
- test/src/specs/tx_pool/send_low_fee_rate_tx.rs
- test/src/util/check.rs
- tx-pool/src/service.rs
- util/jsonrpc-types/src/blockchain.rs
- util/jsonrpc-types/src/lib.rs
- util/types/src/core/mod.rs
- util/types/src/core/tx_pool.rs
Signed-off-by: Eval EXEC <execvy@gmail.com>
Issue Number: close #3424 
Problem Summary: support return raw molecule hex bytes for `get_transaction` rpc method.
- rewrite `verbosity=0` branch for `get_transaction` rpc method.
- delete `get_transaction_verbosity0()` 
- make `verbosity=0` 's behaviour as same as `verbosity=2`, except for when `verbosity=0`, it will return a 0x-prefixed hex encoded raw molecule `packed::Transaction` on `transaction` field;
- change `ChainRpc::get_transaction()`'s return type from `Result<Option<TransactionWithStatus>>` to `Result<Option<TransactionWithStatusResponse>>`
- move `json_types::TransactionWithStatus` to `tx_pool::TransactionWithStatus`
- change some specs tests assertion in `test/src/specs`
Tests 
- Unit test
Side …
> feat:ChainRpcImpl: support return raw molecule hex bytes for `get_transaction` rpc method

- Cargo.lock
- chain/Cargo.toml
- store/Cargo.toml
- util/light-client-protocol-server/Cargo.toml
- util/snapshot/Cargo.toml
- util/types/Cargo.toml
- util/types/schemas/extensions.mol
- util/types/src/generated/extensions.rs
- util/types/src/utilities/merkle_mountain_range.rs
- verification/contextual/Cargo.toml
- chore(light-client): update according to the RFC changes
- chore(light-client): rename the "hash" filed in HeaderDigest to "children_hash"
Ref: https://github.com/nervosnetwork/rfcs/pull/370#discussion_r1000116358
- docs(light-client): remove outdated documentation and link to the related RFC
- chore(deps): bump ckb-merkle-mountain-range from 0.5.1 to 0.5.2
Tests
- Unit test
Side effects： None
```release-note
```
> chore(light-client): update according to the RFC changes

- Cargo.lock
- benches/Cargo.toml
- ckb-bin/Cargo.toml
- network/Cargo.toml
- test/Cargo.toml
- util/app-config/Cargo.toml
Clap 3.2.22 lock yanked deps 
│ textwrap 0.15.1 registry+https://github.com/rust-lang/crates.io-index
│ --------------------------------------------------------------------- yanked version
Downgrade clap for now, as there is no available upgrade for now.
Tests 
- Unit test
```release-note
```
> fix: clap 3.2.22 lock yanked deps

- Cargo.lock
- script/Cargo.toml
- script/src/verify.rs
ChangeLogs:
https://github.com/nervosnetwork/ckb-vm/releases/tag/v0.22.0
> ckb-script: bump ckb-vm to v0.22.0

- util/launcher/src/migrations/add_chain_root_mmr.rs
Decrease max memory and increase speed, during chain root MMR migration.
Create a new DB transaction for every 10000 records inserted.
On an AWS 4C 8G instance, with latest testnet which tip number is `7139044`:
- Reduce the time for chain root MMR migration from `15` minutes to `12` minutes.
- Reduce the max memory during chain root MMR migration from `6.5 GiB` to `900 MiB`.
_p.s. These data has been tested 3 times._
Tests
- Unit test
```release-note
```
> perf: decrease max memory and increase speed, during chain root mmr migration

- block-filter/src/filter.rs
- resource/ckb.toml
- test/src/specs/sync/block_filter.rs
- util/app-config/src/configs/store.rs
- util/app-config/src/legacy/store.rs
- util/launcher/src/lib.rs
Two configuration options (block_filter_enable and support_protocols) are conflicting, one is off by default and one is on by default
Remove the `block_filter_enable` option.
Tests 
- Unit test
```release-note
```
> chore: remove block_filter_enable option

- rpc/README.md
- rpc/src/module/chain.rs
- rpc/src/module/experiment.rs
- rpc/src/module/mod.rs
- test/src/rpc.rs
- util/jsonrpc-types/src/experiment.rs
- util/jsonrpc-types/src/lib.rs
An new RPC to run the transaction and return cycles.
`estimate_cycles` is essentially a renaming of the previous `dry_run_transaction`, which was then moved from Experiment to Chain module, with the original `dry_run_transaction` retained and marked as deprecated.
Tests 
- Unit test
```release-note
```
> feat: add rpc estimate_cycles

- util/light-client-protocol-server/src/lib.rs
- util/types/src/utilities/merkle_mountain_range.rs
The genesis block could NOT have a chain root, since chain root is a state for previous blocks of a chain.
Even for dev chains.
Hence, we have to skip fetching a chain root for the genesis block.
Tests
- Unit test
```release-note
```
> fix(light-client): subtract overflow when try to get chain root for genesis block

- db/src/db_with_ttl.rs
In this [PR](https://github.com/nervosnetwork/ckb/pull/3029), we introduce the recent reject DB to record recently rejected transactions, which is implemented as rocksdb with TTL, using the default DB parameter configuration.
Since then, this db has been very heavily used on my machine until now:
```bash
dust -n 50 -d 1                                                                                                                      
4.0K   ┌── logs
8.0K   ├── ancient
212K   ├── tmp
2.8M   ├── network
164M   ├── indexer
1.5G   ├── tx_pool
24G   ├── db
26G ┌─┴ .        
```
However, the data inside is actually all `LOG.old.xxx` logs.
As a TTL database, its data storage is inherently time-limited, and it is obviously not reasonable to keep so many DB logs by default. 
By default, rocksdb …
> fix: set recent reject db log file limit to 10

- util/light-client-protocol-server/src/components/get_last_state_proof.rs
- util/light-client-protocol-server/src/tests/components/get_last_state_proof.rs
- util/light-client-protocol-server/src/tests/components/mod.rs
- util/types/src/utilities/merkle_mountain_range.rs
Should not skip the genesis block for last state proofs.
For example, when current tip header at 1, then the last state proof have to contain the genesis block.
Since #3675, the genesis block will use a default struct as its parent chain root, so we don't have to skip it anymore.
https://github.com/nervosnetwork/ckb/blob/5aa8b426d0aef48c5a854a74176b5eb9b85896fb/util/light-client-protocol-server/src/lib.rs#L125-L127
And, for more security, we should check if the parent chain root of a genesis block is a default struct.
Tests
- Unit test
```release-note
```
> fix(light-client): do not skip the genesis block for last state proofs

- tx-pool/src/component/container.rs
- tx-pool/src/component/tests/proposed.rs
Fix a potential issue where the transaction pool was not properly cleared of state when the MaximumAncestors limit was triggered
Tests 
- Unit test
```release-note
```
> fix(tx-pool): potential leaks when MaximumAncestors occurs

- util/indexer/src/indexer.rs
- util/indexer/src/service.rs
resolve https://github.com/nervosnetwork/ckb-indexer/issues/60
remove all long fork checking code and resolve the panic error since built-in indexer always connect to the ckb node in the same chain
Tests 
- Unit test
- Manual test (ref: https://github.com/nervosnetwork/ckb-indexer/issues/60)
```release-note
```
> fix: resolve a long reorg error

- rpc/README.md
- rpc/src/module/chain.rs
- util/jsonrpc-types/src/blockchain.rs
- util/jsonrpc-types/src/lib.rs
Fix https://github.com/nervosnetwork/ckb/pull/3684 introduced incompatibility issues
Because serde does not support flatten_if(https://github.com/serde-rs/serde/issues/1614), and for compatibility with verbosity mode, when with_cycles specified,  the hierarchical of response object will be different.
Tests 
- Unit test
```release-note
```
> fix: get block rpc compatibility

- Cargo.lock
- script/Cargo.toml
bump ckb-vm to v0.22.1
https://github.com/nervosnetwork/ckb-vm/releases/tag/v0.22.1
Fix issues that ckb-vm runs under macos ventura AArch64
Tests 
- Unit test
```release-note
```
> chore: bump ckb-vm to v0.22.1

- devtools/doc/rpc.py
- rpc/README.md
The current implementation of deployment info RPC returns an enum that is PascalCase, and the document is converted to a snake_case
Tests 
- Unit test
```release-note
```
> fix: rpc deployment info doc

- sync/src/synchronizer/block_fetcher.rs
- sync/src/synchronizer/mod.rs
- sync/src/types/mod.rs
Thanks to @eval-exec for pointing out these problems
ref: #3668
`unknown_list` is the key to enabling multi-node parallel download in ibd phase. Its implementation is the get locator algorithm:
https://github.com/nervosnetwork/ckb/blob/1ce2b34cbad6c9573cb2dbb50af8de1dce4b027c/sync/src/types/mod.rs#L2032-L2035
Note this line in the algorithm, all results are added to the genesis hash again at the end
If `insert_peer_unknown_header_list` can find the corresponding value at the beginning of a new connection, this node can be used as one of the download sources:
https://github.com/nervosnetwork/ckb/blob/1ce2b34cbad6c9573cb2dbb50af8de1dce4b027c/sync/src/types/mod.rs#L1875-L1889
Otherwise, `try_update_best_known_with_unknown_header_list` will get stuck in a dead loop on the genesis hash and the …
> fix: unknown list should get header from headermap and db

- test/src/main.rs
- test/src/specs/tx_pool/pool_reconcile.rs
- tx-pool/src/block_assembler/mod.rs
- tx-pool/src/component/container.rs
- tx-pool/src/component/proposed.rs
- tx-pool/src/component/tests/proposed.rs
- tx-pool/src/pool.rs
- tx-pool/src/process.rs
Usually when a new transaction is added to the pool, it has no in-pool children (because any such children would be an orphan).  In the event of a reorg, the assumption that a newly added tx has no in-pool children is false.  In particular, the pool is in an inconsistent state while new transactions are being added.
When a reorg occurs and the tx-pool adds transactions from the disconnect block, it also updates the state of the corresponding descendants to ensure that the state is consistent.
Tests 
- Unit test
```release-note
```
> Fix tx-pool potential inconsistent after reorg occurs

- tx-pool/src/component/proposed.rs
- tx-pool/src/component/tests/proposed.rs
- tx-pool/src/pool.rs
- tx-pool/src/process.rs
Check the in-pool chidren of all newly added transactions and no longer distinguish the entry source of newly added transactions.
Removed the separate `add_entry_from_detached ` interface, all new add transactions will be checked in-pool chidren
Tests 
- Unit test
```release-note
```
> fix: check in-pool chidren for all newly added tx

- rpc/src/util/fee_rate.rs
- tx-pool/src/component/container.rs
- tx-pool/src/component/entry.rs
- tx-pool/src/component/tests/container.rs
- tx-pool/src/component/tests/proposed.rs
- util/types/src/core/fee_rate.rs
- util/types/src/core/tx_pool.rs
vbytes changed to weight to prevent ambiguity
Tests 
- Unit test
```release-note
```
> refactor: vbytes changed to weight to prevent ambiguity

- tx-pool/src/block_assembler/mod.rs
- util/dao/src/lib.rs
In generating the blocktemplate is probably due to asynchronous reasons, resulting in the calculation of DAO is to filter out some conflicting transactions, but in filling in the blocktemplate transaction field did not use the filtered transactions, so led to potential inconsistency problems.
Ensure that the transaction used in filling the blocktemplate field is the same as the used in calculating the DAO
Tests 
- Unit test
```release-note
```
> fix: blocktemplate dao potential inconsistent with transactions

- Cargo.lock
- db/Cargo.toml
- db/src/transaction.rs
- store/src/data_loader_wrapper.rs
- store/src/db.rs
- store/src/snapshot.rs
- store/src/store.rs
- store/src/transaction.rs
- util/chain-iter/src/lib.rs
- util/indexer/Cargo.toml
- util/indexer/src/store/secondary_db.rs
- util/reward-calculator/src/lib.rs
- util/snapshot/src/lib.rs
- verification/contextual/src/contextual_block_verifier.rs
The new version of rocksdb supports transaction get_pinned, which can be used to eliminate the lifecycle on `ChainStore`, and also brings some fixes and performance improvements
https://github.com/nervosnetwork/rust-rocksdb/pull/43
Tests 
- Unit test
```release-note
```
> refactor: eliminate chainstore lifecycle

- Cargo.lock
- devtools/doc/rpc.py
- rpc/README.md
- rpc/src/module/chain.rs
- rpc/src/tests/fee_rate.rs
- rpc/src/util/fee_rate.rs
- tx-pool/src/util.rs
- util/jsonrpc-types/src/blockchain.rs
- util/types/src/core/fee_rate.rs
Due to the inertia of the previous fee_rate usage, change the unit returned by get_fee_rate_statics to shannons per kilo-weight
Tests 
- Unit test
```release-note
```
> fix: get_fee_rate_statics compatibility

- block-filter/src/filter.rs
- notify/src/lib.rs
- rpc/src/tests/examples.rs
- util/app-config/src/configs/notify.rs
- util/indexer/src/service.rs
- util/launcher/src/shared_builder.rs
- util/network-alert/src/tests/test_notifier.rs
Notify service is essentially a message bus, which should push messages to subscribers in non-blocking form, and push to subscribers should be treated as a remote call, so the timeout setting should be added.
Tests 
- Unit test
```release-note
```
> fix: notify message blocking

- block-filter/src/filter.rs
- rpc/src/module/chain.rs
- sync/src/filter/get_block_filter_check_points_process.rs
- sync/src/filter/get_block_filter_hashes_process.rs
- sync/src/filter/get_block_filters_process.rs
- sync/src/types/mod.rs
`block-filter::build_filter_data` call `refresh_snapshot` on every `new_block_watcher.changed()` here:
https://github.com/nervosnetwork/ckb/blob/d3fc58fa24a8c26783c604122c643602dfb527fb/block-filter/src/filter.rs#L94
and `ChainService` may update `snaphsot` simultaneously in here:
https://github.com/nervosnetwork/ckb/blob/d3fc58fa24a8c26783c604122c643602dfb527fb/chain/src/chain.rs#L480-L486
For example: 
1. In `fn build_filter_data`, `refresh_snapshot` load a `Snapshot` with tip_header(100)  
2. `ChainService` received a new_tip_header(101), and store it into snapshot
3. In `fn build_filter_data`, `refresh_snapshot` store the `Snapshot` with tip_header(100), this cause `tip_header` goes backwards. 
remove `refresh_snapshot()` in …
> Fix: block_filter: refresh_snapshot() in build_filter_data may race with ChainService

- rpc/src/tests/fee_rate.rs
- rpc/src/util/fee_rate.rs
The previous implementation had a bug that limited the maximum value of the target only when the input target was an even number
Tests 
- Unit test
```release-note
```
> fix: fee_rate statistics target limit

- rpc/README.md
- rpc/src/module/chain.rs
- test/src/rpc.rs
- test/src/specs/dao/dao_user.rs
- test/src/specs/hardfork/v2021/cell_deps.rs
- test/src/specs/hardfork/v2021/vm_version.rs
- test/src/specs/relay/transaction_relay.rs
- test/src/specs/tx_pool/different_txs_with_same_input.rs
- test/src/specs/tx_pool/orphan_tx.rs
- test/src/specs/tx_pool/pool_reconcile.rs
- test/src/specs/tx_pool/send_large_cycles_tx.rs
- test/src/specs/tx_pool/send_low_fee_rate_tx.rs
- test/src/util/check.rs
When I was doing the ckb-light-client rpc `get_transaction` alignment of the ckb rpc, I found that the `Option` was removable, because we now always return `Some(TransactionWithStatusResponse)`. This PR refactor this rpc result and simplify test related code.
Tests 
- Unit test
```release-note
```
> chore: remove Option from rpc `get_transaction` result

- rpc/src/module/chain.rs
When call the RPC method `get_transaction`:
- If a block has no non-cellbase transactions, the cycles of its cellbase are null.
e.g.:
- [Cellbase](https://pudge.explorer.nervos.org/transaction/0x3e8795baab13a6590077fed50bd10153302189492348c6e73948fa741ba8cd3e)
- If a block has at least one non-cellbase transactions, the cycles of its cellbase are the same as the first non-cellbase transaction.
Since `0.saturating_sub(1) == 1.saturating_sub(1) == 0` in the follow code:
https://github.com/nervosnetwork/ckb/blob/adcfac420560f3ca8b9d733ee23f930e53f5f6f3/rpc/src/module/chain.rs#L2034-L2036
e.g.:
- [Cellbase](https://pudge.explorer.nervos.org/transaction/0x160beca4ac14b44a7f055d2da77ad8422a1a128575e26273e66e07cf9e1e4f94)
- [First Non-Cellbase …
> fix(rpc): return the cycles of the first non-cellbase transaction as cellbase's cycles

- miner/src/client.rs
- resource/ckb-miner.toml
Previously, ckb-miner notify mode was turned on by default, and there were some compatibility problems, such as the default block_assembler was not configured accordingly, so it is better to turn off ckb-miner notify mode by default, and add a prompt when ckb-miner starts in notify mode
Tests 
- Unit test
```release-note
```
> fix: disable ckb-miner notify mode by default

- rpc/src/module/chain.rs
Backport #3763.
Tests
- Unit test
```release-note
```
> [backport] fix(rpc): return the cycles of the first non-cellbase transaction as cellbase's cycles

- network/src/peer_store/addr_manager.rs
- network/src/peer_store/peer_store_impl.rs
- network/src/protocols/discovery/addr.rs
- network/src/protocols/discovery/mod.rs
- network/src/protocols/identify/mod.rs
- network/src/protocols/tests/mod.rs
we introduced peer flags network-wide propagation in https://github.com/nervosnetwork/ckb/pull/3595
But there is a problem here, only the outbound connection time needs to be refreshed when disconnecting because the global state of connected peers may be deleted first and the flags obtained may be empty, which will reset the correct flags to the default state
Tests
- Unit test
Side effects
```release-note
```
> fix: fix identify unregister

- util/launcher/src/lib.rs
- util/network-alert/src/notifier.rs
The alerts returned in RPC `get_blockchain_info` will return all the alerts.
The expected behavior is that is should filter based on the alert version range requirements.
Related: https://github.com/nervosnetwork/ckb/issues/3800#issuecomment-1383685702
The root cause is that when launcher passes client version to alert notifier, it uses the full format such as `0.107.0-rc1 (1b3e6b1 2023-01-12)`. However, the notifier internal uses semver to parse the version directly. If it fails, it will consider all alerts as effective.
The solution: The launcher pass the short version format to alert notifier.
Tests 
- Build the ckb
- Run a testnet node, and call rpc `get_blockchain_info`
- The alerts MUST be empty, …
> fix: p2p alerts are not filterred in block chain info

- Cargo.lock
- network/src/peer_store/addr_manager.rs
- network/src/peer_store/peer_store_impl.rs
- network/src/protocols/discovery/addr.rs
- network/src/protocols/discovery/mod.rs
- network/src/protocols/identify/mod.rs
- network/src/protocols/tests/mod.rs
we introduced peer flags network-wide propagation in https://github.com/nervosnetwork/ckb/pull/3595
But there is a problem here, only the outbound connection time needs to be refreshed when disconnecting because the global state of connected peers may be deleted first and the flags obtained may be empty, which will reset the correct flags to the default state
Tests
- Unit test
Side effects
```release-note
```
> [hotfix 0.107.x] fix: fix identify unregister 

- util/launcher/src/lib.rs
- util/network-alert/src/notifier.rs
Rebase #3802 to v0.107.*
Merge #3804 first, which has upgraded tokio for https://rustsec.org/advisories/RUSTSEC-2023-0001
> [hotfix 0.107.x] fix: p2p alerts are not filterred in block chain info

- Cargo.lock
- util/network-alert/Cargo.toml
- util/network-alert/src/tests/generate_alert_signature.rs
- util/network-alert/src/tests/mod.rs
Problem Summary: Ease signing the alert and verifying the signature.
Add a new testcase. To create the signature, just change the raw alert and the private key in the testcase.
Tests 
- Unit test
```release-note
```
> chore: create a testcase to ease signing network alert

- chain/src/tests/load_code_with_snapshot.rs
- util/launcher/src/shared_builder.rs
`thread_local` is not necessary and has caused some unexpected problems since the switch to nextest runner
Tests 
- Unit test
```release-note
```
> fix: Tests db paths without thread_local

- .github/workflows/ci_benchmarks_macos.yaml
- .github/workflows/ci_benchmarks_ubuntu.yaml
- .github/workflows/ci_benchmarks_windows.yaml
- .github/workflows/ci_cargo_deny_ubuntu.yaml
- .github/workflows/ci_integration_tests_macos.yaml
- .github/workflows/ci_integration_tests_ubuntu.yaml
- .github/workflows/ci_integration_tests_windows.yaml
- .github/workflows/ci_linters_macos.yaml
- .github/workflows/ci_linters_ubuntu.yaml
- .github/workflows/ci_quick_checks_macos.yaml
- .github/workflows/ci_quick_checks_ubuntu.yaml
- .github/workflows/ci_unit_tests_macos.yaml
- .github/workflows/ci_unit_tests_ubuntu.yaml
- .github/workflows/ci_unit_tests_windows.yaml
- .github/workflows/ci_wasm_build_ubuntu.yaml
Problem Summary: CI runs twice on the same commit, once for merge queue, another after the merge commit has been pushed to the develop branch.
Update CI conditions to skip the jobs on pushing merge commit to the develop branch.
Tests 
```release-note
```
> chore(ci): avoid duplicated ci jobs for push and merge-group

- rpc/README.md
- util/indexer/src/service.rs
- util/jsonrpc-types/src/indexer.rs
- util/jsonrpc-types/src/lib.rs
backport https://github.com/nervosnetwork/ckb-indexer/pull/64
Problem Summary: Developer may need to match the exact script for the query in some cases, currently the rpc only has prefix matching, the developer can only get the cells and then filter them on the client side.
this PR adds the exact match mode.
Tests 
- Unit test
```release-note
```
> feat: add exact search mode

- sync/src/relayer/transaction_hashes_process.rs
- sync/src/relayer/transactions_process.rs
- sync/src/tests/types.rs
- sync/src/types/mod.rs
- test/src/main.rs
- test/src/specs/relay/transaction_relay.rs
- tx-pool/src/process.rs
- tx-pool/src/service.rs
- util/launcher/src/shared_builder.rs
- util/types/src/core/tx_pool.rs
When a transaction fails a double-spend check, it is still marked as known, making it impossible to rebroadcast by resubmitting
Ensure that if a transaction can be rebroadcast in case of verification failure, it should be removed from the known filter。
Tests 
- Unit test
```release-note
```
> [backport] fix transaction rebroadcast by resubmitting

- sync/src/relayer/transaction_hashes_process.rs
- sync/src/relayer/transactions_process.rs
- sync/src/tests/types.rs
- sync/src/types/mod.rs
- test/src/main.rs
- test/src/specs/relay/transaction_relay.rs
- tx-pool/src/process.rs
- tx-pool/src/service.rs
- util/launcher/src/shared_builder.rs
- util/types/src/core/tx_pool.rs
When a transaction fails a double-spend check, it is still marked as known, making it impossible to rebroadcast by resubmitting
Ensure that if a transaction can be rebroadcast in case of verification failure, it should be removed from the known filter。
Tests 
- Unit test
```release-note
```
> fix transaction rebroadcast by resubmitting

- script/Cargo.toml
- script/src/types.rs
This change adds a new `flatmemory` feature to ckb-script, which will use `FlatMemory` as the memory type for
`CoreMachine`/`CoreMachineType`. While this is not gonna be used in CKB, a FlatMemory will be quite useful in the development of surrounding tools, including ckb-debugger. Note that one option is that a debugger could maintain its own ckb-script package, but considering the fact that the change here is rather small, I would suggest we include this here feature in CKB.
> feat: Add flatmemory feature for FlatMemory based machine types

- script/src/error.rs
- script/src/verify.rs
- script/src/verify/tests/ckb_latest/features_since_v2019.rs
`InvalidCodeHash` is not friendly enough for the caller. Ref: #3854 
This PR change `ScriptError::InvalidCodeHash` to `ScriptError::ScriptNotFound(Byte32)`, This makes the error message more friendly.
- change `ScriptError::InvalidCodeHash` to `ScriptError::ScriptNotFound(Byte32)`
Tests 
- Unit test
Side effects
```release-note
```
> enhance: Improve ScriptError::InvalidCodeHash when code_hash can't be resolved

- Cargo.lock
- Cargo.toml
- benches/Cargo.toml
- chain/Cargo.toml
- ckb-bin/Cargo.toml
- db-migration/Cargo.toml
- db/Cargo.toml
- devtools/ci/check-cargotoml.sh
- freezer/Cargo.toml
- network/Cargo.toml
- resource/Cargo.toml
- rpc/Cargo.toml
- script/Cargo.toml
- store/Cargo.toml
- sync/Cargo.toml
- test/Cargo.toml
- tx-pool/Cargo.toml
- util/app-config/Cargo.toml
- util/dao/Cargo.toml
- util/indexer/Cargo.toml
- util/launcher/Cargo.toml
- util/light-client-protocol-server/Cargo.toml
- util/logger-service/Cargo.toml
- util/reward-calculator/Cargo.toml
- util/test-chain-utils/Cargo.toml
The remove_dir_all crate is a Rust library that offers additional features over the Rust standard library fs::remove_dir_all function. It suffers the same class of failure as the code it was layering over: TOCTOU race conditions, with the ability to cause arbitrary paths to be deleted by substituting a symlink for a path after the type of the path was checked.
Upgrade tempfile to remove remove_dir_all dependency, introduce https://doc.rust-lang.org/nightly/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace
Tests 
- Unit test
Side effects
- …
> chore: upgrade tempfile to remove remove_dir_all dependency

- verification/src/error.rs
Fix a typo, I think it should be `canonical`.
Ref: [Canonical Chain](https://ethereum.stackexchange.com/questions/47016/what-does-block-reached-canonical-chain-mean)
- None
Tests 
- Unit test
Side effects
- None
```release-note
```
> Fix typo: cannonical to canonical

- .dockerignore
Problem Summary: Test folder can occupy a lot of space and is not used in Docker.
What's Changed: Ignore the folder in .dockerignore to shrink the Docker build context.
Tests 
```release-note
```
> chore: add test/ to dockerignore

- tx-pool/src/component/commit_txs_scanner.rs
Fix an issue introduced from https://github.com/nervosnetwork/ckb/pull/3706/files#diff-4e835ff799b925b06ae537862d89faea15095eafdcb95f6e3ee6d74ea4045617R292-R305
that could potentially cause tx-pool panic
Replace the handling of quick errors with fault tolerance
Tests 
- Unit test
```release-note
```
> [backport] fix: potentially tx-pool panic after detached

- tx-pool/src/component/commit_txs_scanner.rs
Fix an issue introduced from https://github.com/nervosnetwork/ckb/pull/3706/files#diff-4e835ff799b925b06ae537862d89faea15095eafdcb95f6e3ee6d74ea4045617R292-R305
that could potentially cause tx-pool panic
Replace the handling of quick errors with fault tolerance
Tests 
- Unit test
```release-note
```
> fix: potentially tx-pool panic after detached

- Cargo.lock
ref: https://github.com/webdesus/fs_extra/pull/38
will warning during cargo build with 1.68
Tests
- Unit test
```release-note
```
> chore: fix outdate warning

- Cargo.lock
- block-filter/Cargo.toml
- block-filter/src/filter.rs
- store/Cargo.toml
- store/src/transaction.rs
- util/types/Cargo.toml
- util/types/src/utilities/block_filter.rs
- util/types/src/utilities/mod.rs
The code that builds filter data could not be reuse.
Move those code to be a standalone function.
Tests
- Unit test
```release-note
```
> refactor(light-client): let the function that builds filter data to be standalone

- resource/ckb.toml
- rpc/README.md
- rpc/src/error.rs
- rpc/src/module/pool.rs
- rpc/src/service_builder.rs
- rpc/src/tests/error.rs
- rpc/src/tests/examples.rs
- rpc/src/tests/mod.rs
- test/src/main.rs
- test/src/specs/relay/transaction_relay_low_fee_rate.rs
- test/src/specs/tx_pool/limit.rs
- test/template/ckb.toml
- tx-pool/src/chunk_process.rs
- tx-pool/src/component/entry.rs
- tx-pool/src/component/pending.rs
- tx-pool/src/pool.rs
- tx-pool/src/process.rs
- tx-pool/src/service.rs
- tx-pool/src/util.rs
- util/app-config/src/configs/tx_pool.rs
- util/app-config/src/legacy/tx_pool.rs
- util/jsonrpc-types/src/pool.rs
- util/launcher/src/lib.rs
- util/types/src/core/fee_rate.rs
- util/types/src/core/tests/tx_pool.rs
- util/types/src/core/tx_pool.rs
The tx-pool does not expire for all transactions
* Fix the expiration of tx-pool
* Tweak the default size limit of the tx-pool, the previous value was too small
* Remove the max cycles limit of the tx-pool, the significance of the size limit is to control the memory usage, while for the cycles limit is not very meaningful, so it is removed.
Tests 
- Unit test
Side effects
```release-note
```
> fix tx-pool remove expired

- Cargo.lock
```
┌─ /home/runner/work/ckb/ckb/Cargo.lock:282:1
│
282 │ openssl 0.10.38 registry+https://github.com/rust-lang/crates.io-index
│ --------------------------------------------------------------------- security vulnerability detected
│
= ID: RUSTSEC-2023-0023
= Advisory: https://rustsec.org/advisories/RUSTSEC-2023-0023
= `SubjectAlternativeName` and `ExtendedKeyUsage` arguments were parsed using the OpenSSL
function `X509V3_EXT_nconf`. This function parses all input using an OpenSSL mini-language
which can perform arbitrary file reads.
```
Upgrade openssl to 0.10.48
Tests 
- Unit test
```release-note
```
> chore: upgrade openssl to 0.10.48

- .github/workflows/ci_unit_tests_windows.yaml
Problem Summary: upgrade CI runner's dependency.
nextest-rs/nextest was introduces in PR: #3777
I didn't install latest nextest-rs/nextest on windows CI runner in #3777 because it's rust-toolchain is `1.61.0`, since we have specific rust-toolchain `1.67.1` in develop, we can upgrade nextest-rs/nextest to latest version on windows CI runner. 
https://github.com/nervosnetwork/ckb/pull/3777#issuecomment-1367167069
- Upgrade windows CI runner's nextest-rs/nextest to latest.
Tests 
- Unit test
Side effects
- None
```release-note
```
> CI: upgrade nextest-rs/nextest on windows CI job runner

- Cargo.lock
- ckb-bin/Cargo.toml
- ckb-bin/src/subcommand/migrate.rs
- deny.toml
```
13 │ atty 0.2.14 registry+https://github.com/rust-lang/crates.io-index
│ ----------------------------------------------------------------- unsound advisory detected
│
= ID: RUSTSEC-2021-0145
= Advisory: https://rustsec.org/advisories/RUSTSEC-2021-0145
= On windows, `atty` dereferences a potentially unaligned pointer.
```
```
134 │ crossbeam-channel 0.5.7 registry+https://github.com/rust-lang/crates.io-index
│ ----------------------------------------------------------------------------- yanked version
```
* replace `atty` with `is-terminal`
* upgrade crossbeam-channel from 0.5.7 to 0.5.8
Tests 
- Unit test
Side effects
```release-note …
```
> fix deny error

- deny.toml
Remove outdated ignored advisory criterias.
Tests
```release-note
```
> ci: remove outdated ignored advisory criterias

- util/launcher/src/shared_builder.rs
- util/runtime/src/lib.rs
- There are code duplicates in `new_global_runtime` and `new_background_runtime`.
- `thread_name` is unnecessary since we call `thread_name_fn`
- Add a new local function to remove duplicated parts
- Add comments for `new_background_runtime` and `with_temp_db`
Tests 
- Unit test
Side effects
```release-note
```
> chore: cleanup tokio new runtime wrapper

- chain/src/chain.rs
- rpc/README.md
- rpc/src/module/test.rs
Fixes #3941
- The RPC call has a timeout limitation, so we can not rollback too many blocks, with some testing I found 50000 is a proper limit.
- The iteration on `attached_blocks` is a typo, we can remove it.
We add a limit on the number of blocks, if we have a requirement for rollbacking many blocks in one time, we will implement it `cli` mode.
Tests 
- Unit test
```release-note
```
> Fix bug in truncate RPC all and add limit for better error message

- sync/src/relayer/compact_block_process.rs
- sync/src/relayer/tests/compact_block_process.rs
- sync/src/synchronizer/headers_process.rs
- sync/src/synchronizer/mod.rs
- sync/src/tests/synchronizer/functions.rs
- sync/src/types/mod.rs
To reduce [memory usage](https://github.com/nervosnetwork/ckb/issues/3940) during synchronization (especially for IBD), I plan to refactor the synchronization-related code in several PRs, this PR replaced the `HeaderView` struct in the `get_locator` related code with a smaller memory struct `BlockNumberAndHash`.
To make it easier for code reviewers, I split multiple PRs into smaller ones, with the goal of replacing the `HeaderView` under the sync mod with a smaller memory struct.
Tests 
- Unit test
```release-note
```
> refactor: use BlockNumberAndHash in get_locator

- sync/src/tests/types.rs
- sync/src/types/mod.rs
Same purpose as https://github.com/nervosnetwork/ckb/pull/3952, this PR replaced`HeaderView` with `BlockNumberAndHash` in fn `gen_ancestor`, also removed the mutable requirement since it's only used in unit test.
Tests 
- Unit test
```release-note
```
> refactor: use BlockNumberAndHash in get_ancestor

- Makefile
- db-schema/src/lib.rs
- db/src/db.rs
- devtools/doc/rpc.py
- devtools/windows/make.ps1
- rpc/README.md
- sync/src/lib.rs
- tx-pool/src/pool.rs
- util/app-config/src/app_config.rs
- util/network-alert/src/lib.rs
Issue Number: close #3951 
To avoid potential race conditions, it is recommended to generate documentation for all members in the workspace using the command `cargo doc --workspace`.
- use `cargo doc --workspace` to generate all crates' documents.
Tests 
- Unit test
Side effects
- None
```release-note
```
> Fix cargo doc not generate dependencies type document

- rustfmt.toml
Problem Summary: Some tools use rustfmt dirctly. Setting edition to 2021 in rustfmt.toml
tells these tools to recognize new features added in edition 2021 such
as async/await.
What's Changed: Set edition to 2021 in rustfmt.toml
Tests 
- Run `rustfmt notify/src/lib.rs`
- Expected result: no error
- Remove edition config from rustfmt.toml: show errors on `async`
```release-note
```
> chore: set edition to 2021 in rustfmt.toml

- sync/src/synchronizer/block_fetcher.rs
- sync/src/tests/synchronizer/functions.rs
- sync/src/types/mod.rs
Same purpose as https://github.com/nervosnetwork/ckb/pull/3952, this PR changed `last_common_header` field to  `BlockNumberAndHash`
Tests 
- Unit test
```release-note
```
> refactor: use BlockNumberAndHash as last_common_header

- Cargo.lock
- store/src/store.rs
- util/launcher/src/lib.rs
- util/light-client-protocol-server/Cargo.toml
- util/light-client-protocol-server/src/components/get_blocks_proof.rs
- util/light-client-protocol-server/src/components/get_last_state_proof.rs
- util/light-client-protocol-server/src/components/get_transactions_proof.rs
- util/light-client-protocol-server/src/lib.rs
- util/light-client-protocol-server/src/tests/utils/chain.rs
light-client protocol should not use the `ActiveChain` to find ancestor headers, because of `ActiveChain` finding headers from the sync `HeaderMap` which contains unverified block body.
Use snapshot to find ancestor headers.
Tests 
- Unit test
```release-note
```
> fix: use snapshot in light-client protocol

- rpc/README.md
- rpc/src/module/chain.rs
- rpc/src/tests/examples.rs
- tx-pool/src/service.rs
- util/jsonrpc-types/src/blockchain.rs
- util/types/src/core/tx_pool.rs
Issue Number: close #3938 
- Add `time_added_to_pool` field to `TransactionWithStatus`
Tests 
- Unit test
Side effects
- None
```release-note
```
> rpc(ChainRpc): Add `time_added_to_pool` field for `ChainRpcImpl::get_transaction`

- tx-pool/src/service.rs
Code refactor to remove duplicate code logic.
Tests 
- Unit test
```release-note
```
> Refactor tx_pool controller

- rpc/README.md
- rpc/src/module/chain.rs
- test/src/rpc.rs
Issue Number: close #3962 
- Add `only_committed` param for `get_transaction` RPC.
Tests 
- Unit test
Side effects
- None
```release-note
```
> rpc(ChainRpc): Add `only_committed` param for `get_transaction`

- devtools/release/publish-crates.sh
The line starts at 1 in sed. While 0 also works for GNU sed, the BSD
variant sed does not recognize the line number 0.
Test cases:
```
macos$ date | sed -e '0, /./d'
Sun May  7 11:45:37 CST 2023
// brew install gnu-sed
// gnu variant outputs nothing
macos$ date | gsed -e '0, /./d'
```
What's Changed: use 1 instead of 0 for the first line.
Tests 
```release-note
```
> chore: fix publish-crates.sh for macOS

- script/src/types.rs
- script/testdata/README.md
- sync/src/utils.rs
- Fix `ScriptVersion`'s comment
- Remove `ckb-c-stdlib`'s specific commit hash in `script/testdata/README.md`
- support `fn protocol_name` to check `RelayV3` for `ckb_metrics`
Tests 
- Unit test
Side effects
- None
```release-note
```
> Trivial fix for `ckb2023`

- resource/ckb.toml
- rpc/src/module/chain.rs
- rpc/src/module/stats.rs
- store/src/data_loader_wrapper.rs
- sync/src/relayer/compact_block_process.rs
- sync/src/relayer/tests/compact_block_process.rs
- sync/src/synchronizer/block_fetcher.rs
- sync/src/synchronizer/headers_process.rs
- sync/src/synchronizer/mod.rs
- sync/src/tests/synchronizer/functions.rs
- sync/src/tests/types.rs
- sync/src/types/header_map/backend.rs
- sync/src/types/header_map/backend_sled.rs
- sync/src/types/header_map/kernel_lru.rs
- sync/src/types/header_map/memory.rs
- sync/src/types/header_map/mod.rs
- sync/src/types/mod.rs
- traits/src/header_provider.rs
- traits/src/lib.rs
- util/app-config/src/configs/network.rs
- util/snapshot/src/lib.rs
- util/test-chain-utils/src/median_time.rs
- verification/src/header_verifier.rs
- verification/src/tests/header_verifier.rs
- verification/src/transaction_verifier.rs
resolve https://github.com/nervosnetwork/ckb/issues/3940
replace the struct `HeaderView` of sync mod with a more memory compact struct `HeaderIndexView`, and avoid holding headers messages in memory (remove bytes slice clone).
Compare with v0.109.0, this PR reduced the peak memory usage from 3.8G to 2.8G during IBD sync on my local PC. @jiangxianliang007 also did test on an aws c5.xlarge instance (4C8G), it reduced from 3.2G to 2.3G, sync performance has also improved, from 0 to 9 million, dropping from 19 hours and 25 minutes to 17 hours and 30 minutes. 
please not that this PR didn't replace the HeaderMap storage sled with other solution, there is another PR in testing
Tests 
- Unit test
```release-note
```
> refactor(perf): replace sync struct HeaderView with HeaderIndexView

- rpc/README.md
- rpc/src/module/chain.rs
- rpc/src/module/stats.rs
- spec/src/versionbits/convert.rs
- util/jsonrpc-types/src/blockchain.rs
- util/jsonrpc-types/src/info.rs
- util/jsonrpc-types/src/lib.rs
Issue Number: close #3978 
- Add `Ratio` struct in `ckb-jsonrpc` crate
- Set `jsonrpc::Ratio` as the type of `threshold` field for `DeploymentsInfo` and `Deployment`
Tests 
- Unit test
Side effects
- It's a break change
```release-note
```
> RPC: Set `jsonrpc::Ratio` as the type of  `threshold` field for  `DeploymentsInfo` and `Deployment` 

- rpc/README.md
- rpc/src/module/subscription.rs
- Fix `trait SubscriptionRpc`'s comment
Tests 
Side effects
- None
```release-note
```
> docs: Fix `trait SubscriptionRpc`'s comment

- script/src/syscalls/mod.rs
- script/src/syscalls/spawn.rs
A spawn's cycles consumption does not match its actual resource consumption.
After build the machine, deduct an extra cycls.
```text
extra_cycles = 100_000 + memory_size_in_bytes / 64
```
Tests 
- Unit test
Side effects
- None
```release-note
```
> scripts(spawn): deduct cycls used to build the machine

- Cargo.lock
- db/Cargo.toml
- network/src/protocols/tests/mod.rs
- util/indexer/Cargo.toml
1. tmpdir must hold until the test is finished, otherwise, it may delete before the test start
2. upgrade rocksdb to [0.20](https://github.com/nervosnetwork/rust-rocksdb/pull/45)
Tests
- Unit test
```release-note
```
> fix: fix tmp dir early drop on test

- Makefile
`make prod-test` should specify `with_sentry,with_dns_seeding` features, and use `nextest-rs/nextest` instead of `cargo test`.
- specify `with_sentry,with_dns_seeding` features for `make prod-test`
- use `nextest` to run `prod-test`
Tests 
- Unit test
Side effects
- None
```release-note
```
> `make prod-test` should specify prod features and use `nextest` instead of `cargo test`

- network/src/network.rs
- network/src/peer_store/peer_store_db.rs
In `AddrManager::load`, using `BufReader` reduces the time cost of `serde_json::from_reader(r)` from `8.77s` to `2.25s`, resulting in a `75%` improvement.
- Use `BufReader` in `PeerStore::load_from_dir_or_default`
- Add info-level log message during startup process to inform about peer store loading.
Tests 
- Unit test
Side effects
- None
```release-note
```
> Reduce `PeerStore::load_from_dir_or_default`'s timecost

- script/src/syscalls/mod.rs
- script/src/syscalls/spawn.rs
- script/src/types.rs
- script/src/verify.rs
- script/src/verify/tests/ckb_latest/features_since_v2021.rs
- script/src/verify/tests/ckb_latest/features_since_v2023.rs
This PR fixes a bug that when suspend happens when a child machine created by the spawn syscall is running, CKB cannot correctly suspend & resume the VM.
What's Changed: the bug relating spawn syscall and suspend / resume feature is fixed.
Tests 
- Unit test
Side effects
```release-note
```
> feat: Suspend support in spawn syscalls

- util/jsonrpc-types/src/cell.rs
- derive implements Clone for cell
Side effects
```release-note
```
> refactor: derive implements Clone for cell

- util/app-config/src/cli.rs
In the current ckb implementation: `ckb init --chain unsupported_spec` will create config files:
I think config files should NOT be created if `ckb init --chain` got an unsupported spec name.
So I make some change:
- Add possible values to `ckb init --chain`'s 
Tests 
- Unit test
Side effects
- None
```release-note
```
> Fix: `ckb init` creates config files even when an unsupported spec is specified.

- script/src/verify.rs
Calling `set_debug_printer` will have no effect.
The bug was introduced by this PR: https://github.com/nervosnetwork/ckb/commit/80b3d2177b9ffc45bf1219f7e2e1ac297d3c4660#diff-7e2ff24bf0a62c374be4d4f63d0cbf77a8ca525883575b9ce4609cff1c7e81b8R441-R459
1. Remove TransactionScriptsVerifier's debug_printer member
2. `set_debug_printer` now updates TransactionScriptsSyscallsGenerator's debug_printer
Tests 
- Unit test
Side effects
- None
```release-note
```
> fix(scripts): set_debug_printer should updates generator's debug_printer

- script/src/verify.rs
- spec/src/consensus.rs
- util/app-config/src/cli.rs
backport 
* https://github.com/nervosnetwork/ckb/pull/4011
* https://github.com/nervosnetwork/ckb/pull/4012
* https://github.com/nervosnetwork/ckb/pull/4015
Tests 
- Unit test
Side effects
```release-note
```
> backport 4011 4012 4015

- rpc/README.md
- rpc/src/module/chain.rs
- util/jsonrpc-types/src/blockchain.rs
The features of 2023 are not displayed correctly by rpc get_consensus
Tests 
- Unit test
Side effects
```release-note
```
> fix: get_consensus 2023 info

- chain/src/chain.rs
- rpc/README.md
- rpc/src/module/chain.rs
- script/fuzz/fuzz_targets/transaction_scripts_verifier_data2.rs
- script/src/verify/tests/utils.rs
- spec/src/consensus.rs
- spec/src/hardfork.rs
- tx-pool/src/util.rs
- util/jsonrpc-types/src/blockchain.rs
- util/types/src/core/hardfork/ckb2023.rs
- verification/src/tests/header_verifier.rs
update 2023 rfc number
Tests 
- Unit test
Side effects
```release-note
```
> chore: update 2023 rfc number

- script/src/verify/tests/utils.rs
This [CI action](https://github.com/nervosnetwork/ckb/actions/runs/5320745322/jobs/9634931777) failed, because the `2_in_2_out_rtx` may completed after first run.
And we didn't handle the else case:
https://github.com/nervosnetwork/ckb/blob/dbbca4e252f183b53237d286fee5ba31e342f171/script/src/verify/tests/ckb_latest/features_since_v2021.rs#L851-L853
Then `init_state` will be `None`, and panic will happen.
Since the `random_2_in_2_out_rtx` will consume `3276322` cycles, increase `CYCLE_BOUND` from `200_000` to `250_000` will make sure suspend/resume will happen in verification.
- Increase `CYCLE_BOUND` to `250_000`
Tests 
- Unit test
Side effects
- None …
> Ensure `random_2_in_2_out_rtx()` suspends on first execution

- Cargo.lock
Issue Number: close #4028 
- Update `openssl` from `0.10.48` to `0.10.55`, update `openssl-sys` from `0.9.83` to `0.9.90`
Tests 
- Unit test
Side effects
- None
```release-note
```
> Fix RUSTSEC-2023-0044 warning

- rpc/README.md
- rpc/src/module/chain.rs
- util/jsonrpc-types/src/blockchain.rs
Revert the formatting changes to get_consensus to make it compatible with the previous version
Tests 
- Unit test
Side effects
```release-note
```
> fix: get_consensus compatibility

- Makefile
The command `make docker-publish` will overwrite the `latest` tag in Docker Hub, even for rc versions.
Push the latest version as the image tag only. Skip the `latest` image
tag.
This will be used to push the rc version, which should not become the
latest image in Docker.
Tests 
```release-note
```
> chore: add `make docker-publish-rc`

- util/app-config/src/tests/cli.bats
This PR want to fix: https://github.com/nervosnetwork/ckb/actions/runs/5398930496/jobs/9805391563?pr=4048
Current regex can match `ckb 0.112.0-pre`, but it can't match `ckb 0.111.0-rc6`, so this CI action failed.
https://github.com/nervosnetwork/ckb/blob/1271cdf75ab1f1577b835259815619b0aa58bc19/util/app-config/src/tests/cli.bats#L30-L35
- fix bats test's `short_version` match rc version like `ckb 0.111.0-rc6`
Tests 
- Unit test
Side effects
- None
```release-note
```
> Fix bats tests failed for rc version like `ckb 0.111.0-rc6`

- script/src/lib.rs
- script/src/types.rs
backport 
* https://github.com/nervosnetwork/ckb/pull/4046
Tests 
- Unit test
Side effects
```release-note
```
> backport 4046

- sync/src/synchronizer/block_fetcher.rs
- sync/src/synchronizer/headers_process.rs
add comment to header sync with empty
Tests
- Unit test
```release-note
```
> chore: add comment to header sync with empty

- util/app-config/src/tests/ckb_run_replay.bats
In the current implementation: 
https://github.com/nervosnetwork/ckb/blob/860d56c94c386a5d82be6d7f9f50e38420892f88/util/app-config/src/tests/ckb_run_replay.bats#L5-L11
We should wait ckb process exit before get the tail of the log.
- wait ckb process exit before get the tail of the log.
Tests 
- Unit test
Side effects
- None
```release-note
```
> Fix bats test, `ckb_run` should wait ckb process exit

- tx-pool/src/service.rs
Issue Number: close #4032
- set `tx_pool_service.started` to `true` before `tx_pool_controller.load_persisted_data`
Tests 
- Unit test
Side effects
- None
```release-note
```
> Fix(`TxPoolService`): set `started` to `true` before `load_persisted_data`

- Cargo.lock
- util/stop-handler/Cargo.toml
- util/stop-handler/src/tests.rs
This PR want to fix the CI job failed on `Windows` platform: https://github.com/nervosnetwork/ckb/actions/runs/5585546337/jobs/10208427302
The `signal-handler::basic` unit test should handle the condition when it's in the `Windows` platform:
https://github.com/nervosnetwork/ckb/blob/c666193eadc8a52ffc0bfe242318981e32a1e556/util/stop-handler/src/tests.rs#L13-L22
The above function will failed to execute on Windows platform.
- add `winapi` to `dev-dependencies`
- Handle the `Windows` platform condition
Tests 
- Unit test
Side effects
- None
```release-note
```
> Fix stop-handler's unit test on `Windows` platform

- Cargo.lock
- util/stop-handler/Cargo.toml
- util/stop-handler/src/lib.rs
- util/stop-handler/src/tests.rs
On `Windows` platform, `stop-handler`'s unit test will pass by `cargo test`, but failed by `cargo nextest run`.
It seems that `nextest-rs/nextest` catches the Ctrl-C signal for the `stop-handler`'s unit test. So I'd like to make the unit test only run on `unix` platform.
Ref:
1. https://github.com/nervosnetwork/ckb/pull/4070#issuecomment-1640363313
2. https://github.com/nextest-rs/nextest/issues/907
- Make `stop-handler`'s unit test only run on `unix` platform.
Tests 
- Unit test
Side effects
- None
```release-note
```
> Remove `stop-handler`'s unit test for `Windows` platform

- Cargo.lock
- script/Cargo.toml
When using ckb-vm in interpreter mode, the fllowing test case will fail due to stack overflow.
```
$ cargo test -- --nocapture verify::tests::ckb_2023::features_since_v2023::check_peak_memory_512k_to_32m
```
The reason for the problem is that a huge function is used in ckb-vm, which consumes too much stack space.
For detaild ChangLogs, see:
https://github.com/nervosnetwork/ckb-vm/releases/tag/v0.24.4
Tests 
- Unit test
```release-note
```
> deps(script): update ckb-vm to v0.24.4

- devtools/ci/ci_main.sh
- test/Cargo.toml
- test/src/main.rs
- test/src/node.rs
There is a scenario `make integration` will hang for a long time when there is a bug in a `spec`, which may happen since we have a lot functions such as `mine_with_blocking`.
Proper `ctrl` handler will print out the running spec name, so that we may narrow the scope of root cause.
There is a odd scenario `make integration` will hang forever, it's safe to add `timeout` in `CI`, there is a trivial bug for that.
Tests 
- Unit test
Side effects
```release-note
```
> chore(test): add ctrl handler and fix integration test timeout issue

- devtools/ci/ci_main.sh
- test/src/node.rs
Set `make integration`'s timneout to `1 hour` [is not enough](https://github.com/nervosnetwork/ckb/actions/runs/5736150087/job/15545163278), it may cost more than 1 hour on MacOS runner.
- Increase `make integrations`'s timeout to `2 hour`
- Print ckb process' Spec name when kill the node, this may help to debug integration test.
Tests 
- Unit test
Side effects
- None
```release-note
```
> Increase integration CI timeout to `2 hours`

- rpc/README.md
- util/jsonrpc-types/src/blockchain.rs
- util/types/src/core/blockchain.rs
- util/types/src/core/tests/blockchain.rs
- util/types/src/extension/tests/check_data.rs
The hash type is split into the high 7 bits and the low 1 bit, when the low 1 bit is 1, it indicates the type, when the low 1 bit is 0, it indicates the data, and then it relies on the high 7 bits to indicate that the data actually corresponds to the version.
So data2 should be 4.
Tests 
- Unit test
Side effects
```release-note
```
> fix: data2 value

- test/src/specs/mining/fee.rs
This [CI job failed](https://github.com/nervosnetwork/ckb/actions/runs/5596018174/jobs/10232539158), and we can't reproduce it.
- Try to fix `FeeOfMultipleMaxBlockProposalsLimit` 
Tests 
- Unit test
Side effects
- None
```release-note
```
> Fix `FeeOfMultipleMaxBlockProposalsLimit` failed on MacOS CI action

- .github/workflows/ci_integration_tests_ubuntu.yaml
- Makefile
- spec/src/consensus.rs
- test/src/specs/dao/dao_tx.rs
- test/src/specs/dao/satoshi_dao_occupied.rs
- test/src/specs/hardfork/v2021/since.rs
- test/src/specs/hardfork/v2023/vm_version2.rs
- util/app-config/src/tests/cli_test.sh
- util/app-config/src/tests/later_bats_job/change_epoch.bats
Related issue: #4092 
- let `epoch_duration_target` affect epoch length when `permanent_difficulty_in_dummy` is enabled in `Dummy` mode.
Tests 
- Unit test
Side effects
```release-note
Note: This PR introduce a break change. When the CKB is in `Dummy` mode and the `permanent_difficulty_in_dummy` option is set to `true`, the epoch length will be influenced by the `epoch_duration_target` parameter. Specifically, the epoch length will be calculated as `epoch_duration_target / 8`.
```
> BREAK CHANGE! Consensus: Allow `epoch_duration_target` to impact epoch length in `Dummy` mode.

- .github/workflows/ci_integration_tests_ubuntu.yaml
- Makefile
- spec/src/consensus.rs
- test/src/specs/dao/dao_tx.rs
- test/src/specs/dao/satoshi_dao_occupied.rs
- test/src/specs/hardfork/v2021/since.rs
- test/src/specs/hardfork/v2023/vm_version2.rs
- util/app-config/src/tests/cli_test.sh
- util/app-config/src/tests/later_bats_job/change_epoch.bats
Related issue: #4092 
Backport #4097 
- let `epoch_duration_target` affect epoch length when `permanent_difficulty_in_dummy` is enabled in `Dummy` mode.
Tests 
- Unit test
Side effects
```release-note
Note: This PR introduce a breaking change for `Dummy` mode. 
When the CKB is in `Dummy` mode and the `permanent_difficulty_in_dummy` option is set to `true`,
the epoch length will be influenced by the `epoch_duration_target` parameter.
Specifically, the epoch length will be calculated as `epoch_duration_target / 8`. 
For example, if `epoch_duration_target` is configured as `14400`, …
```
> Backport #4097 to `rc/v0.111.x`

- .github/workflows/package.yaml
- Makefile
https://github.com/nervosnetwork/ckb/blob/5701fe106fe35f7b0e4204709f1c4fcecdb112f8/.github/workflows/package.yaml#L115
`aarch64-unknown-linux-gnu` package didn't use `prod` profile, and didn't use `deadlock_detection,with_sentry` features.
- Add `CKB_BUILD_TARGET` env to `Makefile`
- Use `make prod_portable` to package `aarch64-unknown-linux-gnu` target
Tests 
- Unit test
Side effects
- None
```release-note
```
> Fix `aarch64-unknown-linux-gnu` target build instructions

- rpc/src/error.rs
- rpc/src/tests/error.rs
- test/src/main.rs
- test/src/specs/mining/fee.rs
- tx-pool/src/component/tests/recent_reject.rs
- tx-pool/src/util.rs
- util/jsonrpc-types/src/pool.rs
- util/types/src/core/tests/tx_pool.rs
- util/types/src/core/tx_pool.rs
Backport #4107 to rc/v0.111.x
When send a transaction with `(outputs capacity) > (inputs capacity)`, `Reject::Malformed(Overflow)` error seems confused for user.
Tests 
- Unit test
Side effects
```release-note
```
> Backport #4107 to rc/v0.111.x

- network/src/protocols/mod.rs
- network/src/protocols/support_protocols.rs
fix disconnect miss `await`, it may lead to illegal node connection, but cannot be found in the node registration information
Tests 
- Unit test
```release-note
```
> fix: fix disconnect miss await

- Cargo.lock
- script/Cargo.toml
There is a bug in the ckb-vm aarch64 mode that memory would not be correctly zero-initialized.
Update ckb-vm to v0.24.6. For detaild ChangLogs, see:
https://github.com/nervosnetwork/ckb-vm/releases/tag/v0.24.6
Tests 
- Unit test
```release-note
```
> chore(scripts): update ckb-vm to v0.24.6

- script/src/syscalls/spawn.rs
- script/src/verify.rs
When current_cycles is called in spawn, only the sum of the cycles of the parent script and the current script is returned, and the grandpa script is not included.
Add a `cycles_base` parameter to spawn. Make child script's `cycles_base` equal to `parent script's cycles_base + parent script's machine.cycles()`
Tests 
- Unit test
```release-note
```
> fix(script/spawn): calucate the correct cycles_base

- rpc/README.md
- rpc/src/module/test.rs
There are deprecated parameters in the comments of RPC method `generate_block`.
- removed deprecated parameters
- added a note about concurrent calling
Tests 
```release-note
```
> fix: update the RPC `generate_block` method comments

- sync/src/relayer/compact_block_process.rs
- util/metrics/src/lib.rs
An efficient block verification process is important for reducing the network uncle rate, especially when the relay protocol receives the latest block,  which allows the miner to update the tip faster and thus work on the latest chain quickly. User may need this metric to monitor and optimize ckb node.
This PR add histogram metrics for relay protocol to record the compact block verification time.
Tests 
https://github.com/nervosnetwork/ckb/blob/19f5362a82da87441daa9ba002a3c4f404cff9de/util/metrics-config/src/lib.rs#L17-L16
```release-note
```
> chore: add histogram metrics for relay compact block verify time

- Cargo.lock
- util/gen-types/Cargo.toml
- util/hash/Cargo.toml
- util/hash/src/lib.rs
Due to a Rust [issue](https://github.com/rust-lang/cargo/issues/8170), `the features = "ckb-contract"` in `ckb-hash` crate Cargo.toml below did not actually work as expected：
```toml
[target.'cfg(not(any(target_arch = "wasm32", features = "ckb-contract")))'.dependencies]
blake2b = { package = "blake2b-rs", version = "0.2" }
[target.'cfg(any(target_arch = "wasm32", features = "ckb-contract"))'.dependencies]
blake2b = { package = "blake2b-ref", version = "0.2.0" }
```
This will result in the following two CI failures of the PR [refactor: Replace ckb-standalone-types with ckb-gen-types](https://github.com/nervosnetwork/ckb-std/pull/71) for the `ckb-std` CI:
```yml
cargo build --target=riscv64imac-unknown-none-elf --no-default-features --features=ckb-types,allocator
``` …
> fix: ckb-hash feature `ckb-contract` is invalid

- script/src/syscalls/spawn.rs
In Spawn syscall, if loading binary fails, only 500 cycles will be added. This is much lower than the actual resource consumption of the Spawn syscall.
Add extra_cycles even if loading fails.
Tests 
- Unit test
```release-note
```
> fix(scripts/spawn): always consume extra_cycles

- miner/src/worker/dummy.rs
We often use the dummy miner mode for local development, but currently the dummy miner only submits new blocks at configured intervals, when other nodes broadcast the new block, the dummy miner will not switch to the latest tip but continue to submit the old block, so it will become an uncle block.
This behavior is fine in single-node mode, but when we need to simulate the hash rate distribution of multiple nodes for testing, there is no way to simulate this behavior with the dummy miner.
Tweak the dummy miner inner loop, if there is new tip (`pow_hash` changed), start working on the new one.
Tests 
```
./ckb init -c dev --genesis-message dummy-miner-test  --ba-arg miner1-arg
./ckb init -c dev --genesis-message dummy-miner-test  --ba-arg …
```
> feat: notify dummy miner for new work

- sync/src/utils.rs
We should parse `Relayv3`'s message name to metrics service.
- Parse `RelayV3`'s message name
Tests 
- Unit test
Side effects
```release-note
```
> Fix parse `RelayV3`'s message name for metrics service

- network/src/peer_store/addr_manager.rs
- network/src/peer_store/peer_store_impl.rs
- network/src/tests/mod.rs
- network/src/tests/peer_store.rs
When the same address enters the peer store, we need to reset the random id and ensure that the address is unique
Tests
- Unit test
```release-note
```
> fix: keep peer store address unique

- rpc/README.md
- rpc/src/module/test.rs
- rpc/src/tests/examples.rs
- rpc/src/tests/mod.rs
- rpc/src/tests/module/miner.rs
- rpc/src/tests/module/mod.rs
- rpc/src/tests/module/pool.rs
- rpc/src/tests/module/test.rs
In the context of CKB applications, many contracts are closely tied to `epoch` processes, including ["DAO"](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0023-dao-deposit-withdraw/0023-dao-deposit-withdraw.md) script, ["cheque"](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0039-cheque/0039-cheque.md) script, and others. During the development process, facilitating the acceleration of epochs becomes essential.
Before this PR, there were two methods: 
1. relied on miners rapidly producing blocks
2. required multiple calls to the CKB RPC `generate_block`
Clearly, the latter is more suitable for integration testing (without requiring a miner). However, using `generate_block` poses two issues. Firstly, it requires the calling side to calculate and determine …
> feat(rpc): Introduce the new method `generate_epochs` in the `IntegrationTest` module

- util/gen-types/src/core.rs
`ScriptHashType` should derive `Hash`
Tests 
- Unit test
Side effects
- None
```release-note
```
> Add `derive(Hash)` to `ScriptHashType`

- Makefile
- chain/src/tests/block_assembler.rs
- devtools/windows/make.ps1
- network/src/tests/peer_store.rs
- sync/src/tests/inflight_blocks.rs
- sync/src/tests/mod.rs
- sync/src/tests/synchronizer/functions.rs
- verification/contextual/src/tests/mod.rs
- verification/src/tests/header_verifier.rs
We have removed the [`faketime`](https://crates.io/crates/faketime) crate from https://github.com/nervosnetwork/ckb/pull/3777. As a result, the `#[cfg(not(disable_faketime))]` is now meaningless and can be removed.
- Remove useless `--cfg disable_faketime` from `RUSTFLAGS`
Tests 
- Unit test
Side effects
- NOne
```release-note
```
> Remove useless `--cfg disable_faketime` from `RUSTFLAGS`

- chain/src/chain.rs
- ckb-bin/src/subcommand/run.rs
- network/src/network.rs
We have remove `stop_handler` from `ChainService` and `NetworkController` in #3999 : related [change](https://github.com/nervosnetwork/ckb/pull/3999/files#diff-821b94c6d358718330722e717ee1226b384b1b657262c0e42e357f621d60433aL53)
So the `non_owning_clone` become meaningless. Remove it to make code more neat. 
- Remove useless `non_owning_clone` method for `ChainController` and `NetworkController`
Tests 
- Unit test
Side effects
- None
```release-note
```
> Remove useless `non_owning_clone` method for `ChainController` and `NetworkController`

- sync/src/synchronizer/mod.rs
- util/gen-types/schemas/extensions.mol
- util/gen-types/src/generated/extensions.rs
Some union items in `SyncMessage` is deprecated, remove them.
- ~~[ ] TODO: Add a  integration test :thinking:~~
Tests 
- Unit test
Side effects
- None
```release-note
Title Only: Include this PR title in the release note.
```
> molecule: Remove deprecated `SyncMessage` union items.

- chain/src/tests/dep_cell.rs
There is a CI issue occuring on recent develop CI jobs on MacOS platform: https://github.com/nervosnetwork/ckb/actions/runs/6217344865/job/16872302061
```bash
SLOW [>19680.000s] ckb-chain tests::dep_cell::test_package_txs_with_deps
SLOW [>19740.000s] ckb-chain tests::dep_cell::test_package_txs_with_deps
SLOW [>19800.000s] ckb-chain tests::dep_cell::test_package_txs_with_deps
SLOW [>19860.000s] ckb-chain tests::dep_cell::test_package_txs_with_deps
SLOW [>19920.000s] ckb-chain tests::dep_cell::test_package_txs_with_deps
SLOW [>19980.000s] ckb-chain tests::dep_cell::test_package_txs_with_deps
SLOW [>20040.000s] ckb-chain tests::dep_cell::test_package_txs_with_deps
SLOW [>20100.000s] ckb-chain tests::dep_cell::test_package_txs_with_deps
Error: The operation was canceled.
```
Upon …
> Fix unit test `test_package_txs_with_deps` never complete

- sync/src/synchronizer/block_fetcher.rs
- sync/src/synchronizer/mod.rs
- sync/src/tests/synchronizer/functions.rs
I submit this PR for 2 reason:
1. I think there should be **only one** `Synchronizer` instance in CKB process. And `struct BlockFetchCMD` should depend on `SyncState` instead of `Synchronizer`
2. In #3958 , when `ChainService` verify a failed block, ChainService should transfer the `VerifyFailedBlockInfo`  to `Synchronizer`, then `Synchronizer` must ban the malicious peer. 
So I want to add a new field: `tokio::sync::mpsc::UnboundedReceiver<VerifyFailedBlockInfo>` field to the `Synchronizer` struct: 
https://github.com/nervosnetwork/ckb/pull/3958/files#diff-66d6800da6ed28c35f087178b6e0f1b31d6fea529dd97a86f6b5ce5dda26bbfcR884-R903
But `UnboundedReceiver` cannot be cloned, and `UnboundedReceiver`'s `fn recv(&mut self)` method need **mutable** self. Then I have to use `Arc<Mutex< ... >>` to …
> Remove `#[derive(Clone)]` from `Synchronizer`

- util/light-client-protocol-server/src/components/get_last_state_proof.rs
The MMR data are saved as key-value format and the keys are positions (`= block_number - MMR_enabled_block_number`).
https://github.com/nervosnetwork/ckb/blob/922516e967df45c08ce4a62f4c3f2fd8db88d745/store/src/transaction.rs#L371-L376
So, only the MMR data for main chain could be fetched from the storage.
https://github.com/nervosnetwork/ckb/blob/922516e967df45c08ce4a62f4c3f2fd8db88d745/util/light-client-protocol-server/src/components/get_last_state_proof.rs#L150
- CKB node sends the hash of block `H` to light client.
- Then CKB node changes to a fork chain which tip is block `G`.
- Light client asks CKB node for proof of the chain whose tip is block `H`.
- Difference:
- Before the bugfix:
- CKB node sends a proof base on block `H` with a incorrect MMR …
> fix(light-client): could not check MMR for fork chains

- util/light-client-protocol-server/src/components/get_blocks_proof.rs
- util/light-client-protocol-server/src/components/get_last_state_proof.rs
- util/light-client-protocol-server/src/components/get_transactions_proof.rs
same as #4171 , when ckb node received `GetBlocksProof` and `GetTransactionsProof` message, it should return main chain data only.
Tests 
- Unit test
```release-note
```
> fix: should only return main chain data

- rpc/README.md
- rpc/src/module/chain.rs
- rpc/src/module/pool.rs
- rpc/src/tests/module/pool.rs
- spec/src/consensus.rs
- test/src/specs/dao/dao_user.rs
- test/src/specs/dao/dao_verifier.rs
- util/dao/src/lib.rs
- util/jsonrpc-types/src/blockchain.rs
- verification/src/tests/transaction_verifier.rs
- verification/src/transaction_verifier.rs
The `Consensus.dao_type_hash` will not be `None` on `mainnet`, `testnet`, and `devnet`. Removing the `Option` wrapper will resolve the CI failure on the latest develop branch : https://github.com/nervosnetwork/ckb/commits/develop/.
- Remove the `Option` wrapper for `Consensus.dao_type_hash`
- In unit tests: `Consensus.dao_type_hash` will be `Byte32::default()`
Tests 
- Unit test
Side effects
- None
```release-note
```
> Remove `Consensus.dao_type_hash`'s `Option` wrapper

- test/src/specs/tx_pool/replace.rs
Issue Number: close #4180
Fix the spec test of RBF.
Tests 
- Unit test
```release-note
```
> Fix RBF spec test failed issue

- .github/workflows/package.yaml
We have published `nervos/ckb-docker-builder:centos-7-rust-1.71.1` and `nervos/ckb-docker-builder:bionic-rust-1.71.1`, then let CI workflow use `1.71.1`
- Upgrade CI workflow's docker image to `1.71.1`
Tests 
- Unit test
Side effects
- None
```release-note
```
> Upgrade CI workflow's docker image to `1.71.1`

- Cargo.lock
- benches/Cargo.toml
- deny.toml
- network/Cargo.toml
It's been too long since ckb upgraded its dependencies as a whole. https://github.com/nervosnetwork/ckb/pull/4146 After updating the toolchain, I thought it would be a good time to do a general upgrade of the dependencies to prevent some of them from being outdated.
* Explicitly allow Unicode License
the Unicode Data Files and Software License (Unicode-DFS-2016) was designed to be permissive and compatible with open-source licenses like the MIT License. 
Tests 
- Unit test
Side effects
```release-note
```
> chore: cargo update

- sync/src/synchronizer/mod.rs
The checks of sync message are incorrect and inadequate since CKB2021.
https://github.com/nervosnetwork/ckb/blob/5dadcbffbfcb7877fdf4f366fdec958d9838ff4e/sync/src/synchronizer/mod.rs#L718-L733
- `SendBlock` is the same before and after CKB2021, so the result of checks is always be `true`.
https://github.com/nervosnetwork/ckb/blob/5dadcbffbfcb7877fdf4f366fdec958d9838ff4e/util/gen-types/schemas/extensions.mol#L264-L266
- The `Block` could have 1 more field after CKB2021.
https://github.com/nervosnetwork/ckb/blob/5dadcbffbfcb7877fdf4f366fdec958d9838ff4e/util/gen-types/schemas/blockchain.mol#L94-L99
https://github.com/nervosnetwork/ckb/blob/5dadcbffbfcb7877fdf4f366fdec958d9838ff4e/util/gen-types/schemas/blockchain.mol#L101-L107
- As a comparison, the checks of relay message are correct. …
> fix: incorrect and inadequate checks of sync message

- rpc/README.md
- rpc/src/module/test.rs
The example response in `IntegrationTestImpl` are successful, then the `"error": null` won't appear in the response, remove them.
- Remove non-exist `error` field from `IntegrationTestImpl` rpc doc
Tests 
- Unit test
Side effects
- None
```release-note
```
> Remove non-exist `error` field from `IntegrationTestImpl` rpc doc

- Cargo.lock
- util/logger-service/Cargo.toml
CKB's `logger-service` depend on an unmaintained and old `atty` package, `atty` will dereference a potentially unaligned pointer on `Windows` platform: https://github.com/nervosnetwork/ckb/security/dependabot/15
This PR want to upgrade `env-logger` from `v0.6.2` to `v0.10.0`, then CKB won't need `atty` anymore.
- upgrade `env-logger` from `v0.6.0` to `0.10.0`, remove `atty` from `logger-service`'s dependencies
Tests 
- Unit test
Side effects
- None
```release-note
```
> Remove unmaintained `atty` dependency

- Cargo.lock
```
cargo deny check --hide-inclusion-graph --show-stats advisories sources
warning[unmaintained]: `net2` crate has been deprecated; use `socket2` instead
┌─ /home/runner/work/ckb/ckb/Cargo.lock:269:1
│
269 │ net2 0.2.39 registry+https://github.com/rust-lang/crates.io-index
│ ----------------------------------------------------------------- unmaintained advisory detected
advisories FAILED: 2 errors, 2 warnings, 0 notes
sources ok: 0 errors, 0 warnings, 0 notes
│
= ID: RUSTSEC-2020-0016
= Advisory: https://rustsec.org/advisories/RUSTSEC-2020-0016
= The [`net2`](https://crates.io/crates/net2) crate has been deprecated
and users are encouraged to considered [`socket2`](https://crates.io/crates/socket2) instead.
= Announcement: https://github.com/deprecrated/net2-rs/commit/3350e3819adf15170904 …
```
> Fix security-audit, upgrade ahash to 0.8.6 and 0.7.7

- Cargo.lock
Fix dependency alert: https://github.com/nervosnetwork/ckb/security/dependabot/16
- Upgrade rustix from `0.38.18` to `0.38.20`
Tests 
- Unit test
Side effects
- NOne
```release-note
```
> Upgade `rustix` to `0.38.20`, fix https://github.com/nervosnetwork/ckb/security/dependabot/16

- sync/src/synchronizer/mod.rs
We don't realy need `enum FetchCMD` to record block fetch task, since it have only **one** enum item, the suggestion is to use a `struct FetchCMD` with `peers` and `ibd_state` fields. This modification can result in cleaner code.
- Replace `enum FetchCMD` by a struct
Tests 
- Unit test
Side effects
- None
```release-note
```
> Replace `enum FetchCMD` by `struct FetchCMD`

- Cargo.lock
- util/app-config/Cargo.toml
- util/app-config/src/cli.rs
`ckb run --help` seems overwhelming since the help message for `--assume-valid-target` is so long.
Wrap help message with an option from `clap`.
Tests 
- Unit test
```release-note
```
> chore: Wrap help message with max width

- Cargo.lock
- rpc/Cargo.toml
- test/Cargo.toml
- tx-pool/Cargo.toml
`make test` and `make intergration` on MacOs will fail because of https://github.com/nervosnetwork/ckb/commit/28631e15ab235eb86743a5223e50ed844ec834f5,
in that commit we updated `reqwest` to the latest version, which contains a commit to [respect MacOS proxy settings](https://github.com/seanmonstar/reqwest/pull/1955).
It's inconvenient for devs who use `vpn` most of the time, and there is no feature option for it, so let's don't use the latest version right now.
Lock `reqwest` to version `0.11.20`
Tests 
- Unit test
```release-note
None: Exclude this PR from the …
```
> chore: Fix macos proxy issue in development env

- util/gen-types/schemas/blockchain.mol
- util/gen-types/schemas/extensions.mol
- util/gen-types/src/extension/shortcut.rs
- util/gen-types/src/generated/blockchain.rs
- util/gen-types/src/generated/extensions.rs
- util/light-client-protocol-server/src/components/get_blocks_proof.rs
- util/light-client-protocol-server/src/components/get_transactions_proof.rs
- util/types/src/utilities/merkle_mountain_range.rs
There is a new syscall `load_extension` in ckb2023 hardfork, but current light client protocol doesn't provide the `extension` field, it causes the client to be unable to support validation of transactions that use this syscall.
This pr adds two fields `blocks_uncles_hash` and `blocks_extension` to the `SendBlocksProof` and `SendTransactionsProof` message, they may be used to verify the header field `extra_hash`, client can store the extension data when verification passed.
Tests 
- Unit test
```release-note
```
> feat: tweak `SendBlocksProof` message to support ckb2023

- db/src/db.rs
- resource/ckb.toml
- resource/default.db-options
We previously used a global lru cache as rocksdb cache (default 128M) and setting the `cache_index_and_filter_blocks` parameter to true, the rocksdb's `IndexBlock` is placed in the cache also (note, we did not use `FilterBlock` in current code). With the increasing of stored data, `DataBlock` and `IndexBlock` will compete for cache expiration, there will be more cache misses, resulting in read performance degradation. 
rocksdb statistics log
```
Block cache LRUCache@0x7f41c443d3d0#3747917 capacity: 128.00 MB seed: 886014176 usage: 117.24 MB table_size: 32768 occupancy: 5795 collections: 155 last_copies: 19 last_secs: 0.001642 secs_since: 0
Block cache entry stats(count,size,portion): DataBlock(5543,23.49 MB,18.3507%) IndexBlock(251,93.22 MB,72.8312%) Misc(1,0.00 KB,0%)
```
This PR tries …
> performance: tuning rocksdb bloom filter

- test/src/specs/tx_pool/orphan_tx.rs
- tx-pool/src/component/pool_map.rs
- tx-pool/src/pool.rs
- tx-pool/src/process.rs
Fix the spec failure of TxPoolOrphanDoubleSpend.
https://github.com/nervosnetwork/ckb/pull/4208 was merged before https://github.com/nervosnetwork/ckb/pull/4199, maybe we should add `make intergration` when backporting.
Fix the spec from https://github.com/nervosnetwork/ckb/pull/4208
Tests 
- Unit test
```release-note
```
> fix spec of TxPoolOrphanDoubleSpend

- rpc/README.md
- rpc/src/module/indexer.rs
Add rpc doc for `get_transactions` and `get_cells` to clarify their pagination style.
When the number of returned objects is less than the requested `limit`, it indicates that it's the last page.
Tests 
- Unit test
Side effects
- None
```release-note
```
> Add doc for `get_transactions` and `get_cells` RPC

- sync/src/types/header_map/kernel_lru.rs
`Header Map Statistics` not align well, should add `one` space behind `memory` to make the table align well.
before:
```bash
$ cat tmp/data_dir/data/logs/run.log | grep -A4  "Header Map Statistics$"
2023-10-31 09:12:40.492 +00:00 GlobalRt-1 INFO ckb_shared::types::header_map::kernel_lru  Header Map Statistics
>       | storage | length  |  limit  | contain |   select   | insert  | delete  |
>       |---------+---------+---------+---------+------------+---------+---------|
>       | memory |  1488390|  1684210|  7684430|   416695468|  1744195|   255805|
>       | backend |        0|        -|        0|           -|        -|        0|
```
This PR:
```bash
$ cat tmp/data_dir/data/logs/run.log | grep -A4  "Header Map Statistics$"
2023-10-31 09:12:40.492 +00:00 GlobalRt-1 INFO …
```
> Make `Header Map Statistics` table align well

- test/src/main.rs
- test/src/specs/tx_pool/replace.rs
- tx-pool/src/component/pool_map.rs
- tx-pool/src/pool.rs
- tx-pool/src/process.rs
- We need more logs when debugging txpool issues
- For RBF, if the new `tx`'s cell comes from the conflicted `tx`, we reject RBF.
- Add more logs for debugging
- Add a rule for RBF
Tests 
- Unit test
Side effects
```release-note
```
> Add a check for RBF to avoid invalid cell deps

- test/src/main.rs
- test/src/specs/tx_pool/send_tx_chain.rs
- tx-pool/src/block_assembler/mod.rs
- tx-pool/src/process.rs
`Tx` may stay for a long time in txpool, when resolve error happened in block assembler.
`txpool` remove checking failed `txs`.
Tests 
- Unit test
Side effects
```release-note
```
> Txpool will evict tx when resolve error in block assembler

- rpc/README.md
- util/jsonrpc-types/src/block_template.rs
- util/jsonrpc-types/src/blockchain.rs
Problem Summary: the extension in `submit_block` is hidden and the doc is outdated.
What's Changed: show `extension` in Block structure and update the documentation.
Tests 
- Unit test: RPC test
```release-note
```
> doc: update RPC doc related to block extension

- spec/src/consensus.rs
In dummy mode, block reward is incorrectly calculated using the length of the previous epoch.
Tests 
- Unit test
Side effects
```release-note
```
> fix: dummy block reward

- test/src/main.rs
- test/src/specs/tx_pool/replace.rs
- tx-pool/src/pool.rs
To keep it consistent, now `RBF` will also can replace `tx` not in `Pending`.
Drop Rule #6 and fix tests.
Tests 
- Unit test
Side effects
```release-note
```
> Backport: RBF will also replace tx not in Pending 

- test/src/specs/hardfork/v2021/cell_deps.rs
This PR want to fix https://github.com/nervosnetwork/ckb/actions/runs/6847588555/job/18616144298 :
```
2023-11-16 04:18:03.847 +00:00 main INFO ckb_test  [CheckCellDeps] Start executing
2023-11-16 04:18:03.847 +00:00 *unnamed* INFO ckb_test::node  working_dir "/var/folders/_m/f2pp9dy135ng8gb3z154mgkh0000gn/T/ckb-it-CheckCellDeps-node0-Ie8GHW"
2023-11-16 04:18:05.384 +00:00 *unnamed* ERROR panic  thread 'unnamed' panicked at 'rpc call send_transaction: {"code":-1108,"message":"PoolRejectedMalformedTransaction: Malformed Overflow transaction","data":"Malformed(\"Overflow\", \"expect (outputs capacity) <= (inputs capacity)\")"}': src/rpc.rs:197   0: backtrace::capture::Backtrace::create
1: backtrace::capture::Backtrace::new
```
In `Dummy` mode, `epoch_length_target` will …
> Fix `CheckCellDeps` transaction fee not enough

- test/src/main.rs
- test/src/specs/tx_pool/replace.rs
- tx-pool/src/pool.rs
To keep it consistent, now `RBF` will also can replace `tx` not in `Pending`.
Drop Rule #6 and fix tests.
Tests 
- Unit test
Side effects
```release-note
```
> RBF will also replace tx not in Pending

- test/src/specs/hardfork/v2021/vm_b_extension.rs
Same as #4234
Fix https://github.com/nervosnetwork/ckb/actions/runs/6926449286/job/18838627516 :
```
2023-11-20 07:05:35.977 +00:00 *unnamed* ERROR panic  thread 'unnamed' panicked at 'rpc call send_transaction: {"code":-1108,"message":"PoolRejectedMalformedTransaction: Malformed Overflow transaction","data":"Malformed(\"Overflow\", \"expect (outputs capacity) <= (inputs capacity)\")"}': src/rpc.rs:197   0: ckb_logger_service::setup_panic_logger::{{closure}}
at /runner/_work/ckb/ckb/util/logger-service/src/lib.rs:508:25
1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/alloc/src/boxed.rs:1999:9
std::panicking::rust_panic_with_hook
at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:709:1 …
```
> Fix `CheckVmBExtension` failed on CI

- devtools/init/linux-systemd/README.md
In the documentation for starting the ckb service via systemd on [here](https://github.com/nervosnetwork/ckb/blob/develop/devtools/init/linux-systemd/README.md), it's noted that the `ckb.service` is handled by the root's systemd. Therefore, to view its logs, you'd need to use `sudo journalctl`.
Tests 
- Unit test
Side effects
- None
```release-note
```
> Fix using `journalctl` to check the log of `ckb.service`

- Cargo.lock
- Makefile
- rpc/README.md
- rpc/src/module/pool.rs
- rpc/src/tests/examples.rs
- rpc/src/tests/mod.rs
- test/src/main.rs
- test/src/node.rs
- test/src/rpc.rs
- test/src/specs/rpc/get_pool.rs
- test/src/specs/rpc/mod.rs
- tx-pool/Cargo.toml
- tx-pool/src/component/pool_map.rs
- tx-pool/src/component/sort_key.rs
- tx-pool/src/pool.rs
- tx-pool/src/service.rs
- util/jsonrpc-types/src/lib.rs
- util/jsonrpc-types/src/pool.rs
- util/metrics/src/lib.rs
- util/types/src/core/tx_pool.rs
When we need to troubleshoot tx status issues in tx-pool,
we don't know the internal status and info from tx, this PR try to add more details of tx in `tx-pool`.
- Add troubleshoot API for ckb-cli
- Addd metric API
Tests 
- Unit test
Side effects
```release-note
```
> Add troubleshoot and metric API for tx-pool

- block-filter/src/filter.rs
- chain/src/chain.rs
- ckb-bin/src/helper.rs
- ckb-bin/src/lib.rs
- miner/src/client.rs
- miner/src/miner.rs
- network/src/network.rs
- notify/src/lib.rs
- sync/src/synchronizer/mod.rs
- sync/src/types/header_map/mod.rs
- tx-pool/src/chunk_process.rs
- tx-pool/src/service.rs
- util/app-config/src/tests/ckb_run_replay.bats
- util/app-config/src/tests/graceful_shutdown.bats
- util/indexer/src/service.rs
- util/metrics-service/src/lib.rs
- util/stop-handler/src/stop_register.rs
When ckb received exit signal multiple times, it will print:
```rust
error!("send exit signal to channel failed since the channel is full, this should not happen")
```
This shouldn't be an `ERROR` level log, should downgrade the log level from `ERROR` to `INFO`.
- Downgrade log level from `ERROR` to `INFO` when ckb received exit signal multiple time.
- Upgrade exit signal related log from `DEBUG` to `INFO`
Tests 
- Unit test
Side effects
- None
```release-note
```
> Improve exit signal related log message

- sync/src/relayer/mod.rs
When `RelaySwitch` is `RelaySwitch::Ckb2023RelayV2`, the log message should be `v2` instead of `v1`.
Tests 
Side effects
- None
```release-note
```
> Fix `Relayer::notify`'s `remove_notify`'s log when `RelaySwitch` is `Ckb2023RelayV2`

- util/types/src/utilities/merkle_mountain_range.rs
Since CKB enabled the MMR feature through version bits with following code:
https://github.com/nervosnetwork/ckb/blob/3d674d558e5574f0c77a52798775c903561a933a/verification/contextual/src/contextual_block_verifier.rs#L567-L569
https://github.com/nervosnetwork/ckb/blob/3d674d558e5574f0c77a52798775c903561a933a/spec/src/consensus.rs#L1031
the extension field of the first block in the MMR activated epoch, doesn't contain the chain root.
So, when check the extension fields, the first block in the MMR activated epoch should be skipped.
Ref: nervosnetwork/ckb-light-client#163
Tests
- Unit test
```release-note
```
> fix: no chain_root in 1st block of the mmr activated epoch

- sync/src/relayer/tests/reconstruct_block.rs
- test/src/main.rs
- test/src/node.rs
- test/src/rpc.rs
- test/src/specs/tx_pool/replace.rs
- tx-pool/src/chunk_process.rs
- tx-pool/src/component/edges.rs
- tx-pool/src/component/pool_map.rs
- tx-pool/src/pool.rs
- tx-pool/src/process.rs
When multiple conflicted `tx` are added into `txpool` at the same time, because multiple threads may access same old data, `resolve_tx` may not resolve the conflicted tx to `Dead`, then `check_rbf` will be skipped, spec test `RbfConcurrency` is added to reproduce this scenario.
In this PR, `check_rbf` is moved to `submit_entry`, which will be guarded with a `write` lock, this change will make sure there is no double-spending tx in `Pending`, and with an extra benefit that only `tx` passed `verify_rtx` may invoke `check_rbf`.
Tests 
- Unit test
Side effects
- …
> Fix concurrency issue for RBF 

- Cargo.lock
Fix dependabot's alert: https://github.com/nervosnetwork/ckb/security/dependabot/17
- Upgrade `openssl` from `0.10.57` to `0.10.61`
- Upgrade `openssl-sys` from `0.9.93` to `0.9.97`
Tests 
- Unit test
Side effects
- None
```release-note
```
> Upgrade `openssl` from `0.10.57` to `0.10.61`

- Makefile
- docker/hub/Dockerfile-aarch64
Issue Number: close #4206
For MacOS, if users follow the [guide](https://docs.nervos.org/docs/basics/guides/run-ckb-with-docker/) to run `ckb`, there will be an error:
```console
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Illegal instruction
```
This PR add arm arch docker image for ckb.
Pair PR: https://github.com/nervosnetwork/ckb-docker-builder/pull/18
Tests
- Unit test
Side effects
```release-note …
```
> Add aarch64 docker image  for ckb

- script/src/verify.rs
With a public `detailed_run` method, one can get the resulting machine from running a single script in a CKB transaction. With a full machine instance, further inspections upon errors can be simpler.
Tests 
- Unit test
Side effects
```release-note
```
> chore: Split machine running logic from run into detailed_run method

- sync/src/filter/get_block_filter_check_points_process.rs
- sync/src/filter/get_block_filter_hashes_process.rs
- sync/src/filter/get_block_filters_process.rs
- sync/src/types/mod.rs
ckb full node may generate an empty filter related message and send it to light client since the filter data are built asynchronously, this may cause the light client to ban the ckb node.
change to use `latest_built_filter_block_number` to replace the tip number when building filter message.
Tests 
- Unit test
```release-note
```
> fix: resolve empty filter related message bug

- .github/workflows/package.yaml
- devtools/ci/ci_main.sh
- docker/hub/Dockerfile
Issue Number: close #4159 
The OpenSSL 1.1.1 series has reached its [End of Life](https://www.openssl.org/blog/blog/2023/09/11/eol-111), so it's time for us to transition to OpenSSL 3 since CKB is statically built with OpenSSL 1.1.1.
Tests 
- Unit test
Side effects
- None
```release-note
```
> Upgrade OpenSSL from `1.1.1` to `3.1.3`

- rpc/README.md
- rpc/src/module/pool.rs
- Fix send_transaction's doc
Tests 
Side effects
- None
```release-note
```
> Fix `PoolRpc::send_transaction` param `outputs_validator` default value should be `passthrough`

- rpc/README.md
- rpc/src/module/pool.rs
- tx-pool/src/component/sort_key.rs
- tx-pool/src/pool.rs
- util/jsonrpc-types/src/lib.rs
- util/jsonrpc-types/src/pool.rs
- util/types/src/core/tx_pool.rs
This PR updated the type of `struct PoolTxDetailInfo::score_sortkey` from `String` to `struct AncestorsScoreSortKey`. This change makes it easier to parse and work with.
- Change `score_sortkey`'s type from `String` to `struct AncestorsScoreSortKey`
Tests 
- Unit test
Side effects
- None
```release-note
```
> Change `score_sortkey`'s type from `String` to `struct AncestorsScoreSortKey`

- Cargo.lock
- ckb-bin/Cargo.toml
- ckb-bin/src/helper.rs
- ckb-bin/src/lib.rs
- ckb-bin/src/subcommand/daemon.rs
- ckb-bin/src/subcommand/mod.rs
- ckb-bin/src/subcommand/run.rs
- devtools/init/README.md
- util/app-config/src/args.rs
- util/app-config/src/cli.rs
- util/app-config/src/lib.rs
Issue Number: close #4237
- use crate `daemonize` for supporting daemon 
- use crate `colored` for better terminal UX
- Note: `new_global_runtime` need to be invoked after daemonize success
Command line:
- `ckb run --daemon` - run ckb in daemon 
- `ckb daemon --check` - check the status of service
- `ckb daemon --stop` - stop the daemon process
Tests 
- Unit test
Side effects
```release-note
```
> Support easy run daemon mode for Linux/MacOS

- chain/src/tests/block_assembler.rs
- shared/src/shared_builder.rs
- tx-pool/src/callback.rs
- tx-pool/src/component/pool_map.rs
- tx-pool/src/pool.rs
- tx-pool/src/process.rs
- tx-pool/src/service.rs
The `total_tx_size` and `total_tx_cycle` are zero when we use `plug_entry` to add entries into `tx_pool`, which caused some confusing when debugging.
Updating statics was implemented in callbacks because we had 3 separate queue in `txpool`, now we have refactor it to the only one `PoolMap`, it's better and cleaner to move this part to `PoolMap`.
Cleanup `callbacks` to move `txpool` statics part to `PoolMap`.
Tests 
- Unit test
```release-note
```
> chore: Move  txpool statistics from callbacks to PoolMap

- chain/src/tests/block_assembler.rs
`shared.Snapshot.tip_number` before `tx_pool.plug_entry`
This PR want to fix https://github.com/nervosnetwork/ckb/issues/4252
Issue Number: close #4252 
In the `fn test_package_multi_best_scores` function, we generate three blocks in quick succession. This could potentially lead to the `snapshot.tip_number` of the `block_assembler` lagging behind `shared.snapshot.tip_number`.
Consequently, in the `BlockAssembler::calc_dao` function, the following scenario may occur:
The `snapshot.tip_number` is 3, but `calc_dao` is processing a transaction that is packed in block 4. As a result, the transactions in block 4 fail to be resolved.
So, I want to make sure the block_assembler's snapshot.tip_number is larger than shared.snapshot.tip_number before `tx_pool.plug_entry`.
What's …
> Ensure that `block_assembler`'s `Snapshot.tip_number` reaches  `shared.snapshot().tip_number` before `tx_pool.plug_entry`

- script/src/error.rs
- script/src/types.rs
- script/src/verify.rs
- script/src/verify/tests/ckb_latest/features_since_v2019.rs
- script/src/verify/tests/ckb_latest/features_since_v2021.rs
- tx-pool/src/chunk_process.rs
Previously we were converting ckb-vm Error type into a string, which makes it harder to inspect into ckb-vm Error for certain values. However, upon further checking, it seems that ckb's Error type can preserve enough information, so we don't always have to cast ckb-vm's Error type into a string.
This commit fixes the code so we are preserving the original Error type from ckb-vm when we need it. For exsiting tests cases leveraging ckb_error::assert_error_eq, the code still passes without any modifications needed.
A test case has also been added here, showcasing how we can destructing a ckb_error::Error type step by step, resulting in the inner-most ckb-vm's Error type.
- Need to …
> chore: Expose ckb-vm Error type directly in ScriptError

- util/indexer/src/service.rs
Fix the issue：the end in `script_len_range` parameter of `IndexerSearchKeyFilter` is not inclusive.
```
*   script_len_range: [u64; 2], filter cells by script len range, [inclusive, exclusive]
```
Tests 
```release-note
```
> fix(indexer): The end in `script_len_range` parameter of `IndexerSearchKeyFilter` is not inclusive

- util/app-config/src/args.rs
- util/app-config/src/lib.rs
The CI is failing because of an cfg error in #4237 , we may need to investigate why CI failure may still get the PR was merged successfully.
https://github.com/nervosnetwork/ckb/actions/runs/7354769222/job/20022410084
Windows don't have daemon option.
Tests 
- Unit test
```release-note
```
> chore: ix windows ci error failed for daemon option

- rpc/README.md
- rpc/src/module/pool.rs
- tx-pool/src/component/sort_key.rs
- tx-pool/src/pool.rs
- util/jsonrpc-types/src/lib.rs
- util/jsonrpc-types/src/pool.rs
- util/types/src/core/tx_pool.rs
Backport #4273
This PR updated the type of `struct PoolTxDetailInfo::score_sortkey` from `String` to `struct AncestorsScoreSortKey`. This change makes it easier to parse and work with.
- Change `score_sortkey`'s type from `String` to `struct AncestorsScoreSortKey`
Tests 
- Unit test
Side effects
- None
```release-note
```
> Backport #4273

- network/src/peer_store/addr_manager.rs
- network/src/peer_store/peer_store_impl.rs
- network/src/protocols/discovery/mod.rs
- network/src/protocols/tests/mod.rs
- network/src/tests/peer_store.rs
- util/dao/utils/src/lib.rs
Fix bug：
1. The propagation address obtained by discovery from the peer store should be one that has been connected locally within seven days, and the check of the address that keeps the connection should not be skipped.
2. To determine if the IP is duplicated, we need to confirm that the address has been selected.
Tests
- Unit test
```release-note
```
> fix: fix peer store random fetch

- benches/benches/benchmarks/resolve.rs
Issue Number: close #4274
This PR want to set `DATA_DIR` as a temporary dir for `make bench-test`.
Tests 
- Unit test
Side effects
- None
```release-note
```
> Init a temp `DATA_DIR` for `bench-test`

- util/gen-types/src/conversion/blockchain/mod.rs
Problem Summary: 
`ckb-gen-types` complements the two type conversions that used to exist in `ckb-standalone-types`. 
User feedback from:
https://github.com/nervosnetwork/ckb-std/pull/71#issuecomment-1875026833
```
impl<'r> Unpack<[u8; 32]> for Byte32;
impl<'r> Unpack<[u8; 10]> for ProposalShortId;
```
Tests 
```release-note
```
> chore: supplements `ckb-gen-types` with two type conversions that used to exist in `ckb-standalone-types`

- rpc/README.md
- rpc/src/module/chain.rs
- util/jsonrpc-types/src/blockchain.rs
- util/types/src/core/tx_pool.rs
- Add `block_number` to `TxStatus` for `get_transaction` RPC.
Tests 
- Unit test
Side effects
```release-note
```
> [RPC CHANGE] : Add `block_number` to `TxStatus` for `get_transaction` RPC

- rpc/README.md
- rpc/src/module/indexer.rs
Issue Number: None
Tests 
- Unit test
Side effects
- None
```release-note
```
> update scrip_type -> script_type

- util/app-config/src/tests/cli.bats
- Fix the regex expression to match ckb version string like `ckb 0.113.0 (82871a3 2024-01-09)` or `ckb 0.113.0-rc3 (3287c63 2024-01-02)`
Tests 
Side effects
- None
```release-note
```
> Fix the regex expression for ckb's version test

- sync/src/types/mod.rs
`ActiveChain#shared#state` and `ActiveChain#state` are duplicated. Should reuse `ActiveChain#shared#state` only.
- Remove `ActiveChain`'s `state` field
Tests 
- Unit test
Side effects
- None
```release-note
```
> Remove `ActiveChain`'s `state: SyncState` field, reuse `ActiveChain#shared#state` instead

- Cargo.lock
Issue Number: close #4304
- Upgrade h2 from 0.3.21 to 0.3.24
Tests 
- Unit test
Side effects
```release-note
```
> Upgrade h2 from 0.3.21 to 0.3.24, fix RUSTSEC-2024-0003

- rpc/Cargo.toml
- rpc/src/server.rs
Because `Axum` cors setting, if we send request from browser console, we met this issue:
```console
Access to fetch at 'http://127.0.0.1:8114/' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
Add `CorsLayer::permissive()` for a permissive setting for `cors`.
Tests 
- Unit test
Side effects
- …
> Fix RPC cors issue of preflight request

- rpc/Cargo.toml
- rpc/src/server.rs
Because current default cors setting, if we send request from browser console, we met this issue:
```console
Access to fetch at 'http://127.0.0.1:8114/' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
- Add `CorsLayer::permissive()` for a permissive setting for `cors`.
- Add `keep-alive` by the way, our current setting is set `keep-alive` when `websockets` is enabled, we should set it by default.
Tests 
- Unit test
- …
> backport: Fix RPC cors issue of preflight request

- README.md
- docs/dev-miner.md
The project lack documentation on how to test the same pow algorithm (Eaglesong) on the dev chain.
Tests 
```release-note
```
> chore: add how to test miner on dev chain doc

- README.md
1. https://github.com/nervosnetwork/ckb/wiki/Chains said `The wiki is deprecated by docs site.`
2. `wiki/Chains` is still using old network names: Lina and Aggron.
- https://github.com/sporeprotocol/spore-sdk/pull/79#discussion_r1462934127
> docs: remove an outdated wiki link in README

- rpc/src/server.rs
After RPC framework changed, if we sent an GET request to RPC endpoint, the error message has changed to:
```console
Missing request extension: Extension of type `jsonrpc_utils::stream::StreamServerConfig` was not found. Perhaps you forgot to add it? See `axum::Extension`.%
```
Let's keep the same message with the old version.
Issue Number: close #4309
Add a special handler for RPC endpoint, distinguished from the Websockets configuration.
Tests 
- Unit test
Side effects
```release-note
Title Only: Include …
```
> Fix error message when sent HTTP GET to RPC

- rpc/src/tests/module/pool.rs
- test/src/main.rs
- test/src/specs/tx_pool/limit.rs
- tx-pool/src/component/entry.rs
- tx-pool/src/component/links.rs
- tx-pool/src/component/pool_map.rs
- tx-pool/src/component/tests/links.rs
- tx-pool/src/component/tests/mod.rs
We met a scenario that a `cell dep` may have many transactions as descendants, and we can not  submit a new transaction to consume the dep cell.
`cell dep` should be handled specially when calculating the entry's `ancestors_count`.
In this PR, we add a `direct_ancestors_count` to store the directed parent-child relationship between transactions.
This is a short-term solution.
Tests 
- Unit test
Side effects
```release-note
```
> Don't account for cell dep for MAX_ANCESTORS_COUNT

- .github/workflows/package.yaml
- Cargo.lock
- network/Cargo.toml
The easiest way to make ckb binary statically link SSL is to enable the `openssl-vendored` feature of the `tentacle` package.
Previously, we needed to compile OpenSSL dependencies in `ckb-docker-builder` which was cumbersome. Enabling `openssl-vendored` in CKB's `tentacle` dependency simplifies this. It makes our maintenance much easier.
- Enable `openssl-vendored` feature for tentacle
- Delete "compile openssl from source code" part for CKB's release script
Tests 
- Unit test
Side effects
- make CKB binary staticlly linked with OpenSSL.
```release-note
```
> Enable the `openssl-vendored` feature for the `tentacle` package to allow CKB to statically link with OpenSSL.

- Cargo.lock
- rpc/README.md
- rpc/src/module/indexer.rs
- util/indexer/Cargo.toml
- util/indexer/src/service.rs
- util/jsonrpc-types/src/indexer.rs
- util/jsonrpc-types/src/lib.rs
We might want to filter cells based on output data, and the CKB Indexer can handle that easily.
This pull request extends `IndexerSearchMode` by adding `Partial`, which, when combined with the existing `Prefix` and `Exact` modes, can be used for flexible filtering of cell data.
Tests 
- Unit test
- Manual test
```bash
curl -X POST -H "Content-Type: application/json" -d '{
"id": 2,
"jsonrpc": "2.0",
"method": "get_cells",
"params": [
{
"script": {
"code_hash": "0xbbad126377d45f90a8ee120da988a2d7332c78ba8fd679aab478a19d6c133494",
"hash_type": "data1",
"args": "0x"
},
"script_type": "type",
"script_search_mode": "prefix",
"filter": {
"output_data": "0xa58618a553",
"output_data_filter_mode": "partial"
},
"with_data": false
},
"asc",
"0x64"
]
}' …
```
> feat(indexer): support cell data filter

- test/src/main.rs
- test/src/specs/tx_pool/replace.rs
- tx-pool/src/pool.rs
The current RBF fee check rules use the directly conflicted transactions' fee as compare target, but in the child-pay-for-parent scenario, the new transaction with fee large than root transactions but less than all descendant's sum may succeed in RBF rules.
The current celldep check also has a similar issue.
This PR will fix these 2 issue, by adding all the fee of descendants and root transactions and check the celldeps including descendants.
Tests 
- Unit test
Side effects
```release-note
Title Only: Include …
```
> Fix RBF fee and celldeps check rule issue with replaced txs and their descendants

- rpc/src/server.rs
After RPC framework changed, if we sent an GET request to RPC endpoint, the error message has changed to:
```console
Missing request extension: Extension of type `jsonrpc_utils::stream::StreamServerConfig` was not found. Perhaps you forgot to add it? See `axum::Extension`.%
```
Let's keep the same message with the old version.
Issue Number: close #4309
Add a special handler for RPC endpoint, distinguished from the Websockets configuration.
Tests 
- Unit test
Side effects
```release-note
Title Only: Include …
```
> backport: Fix error message when sent HTTP GET to RPC 

- test/src/main.rs
- test/src/specs/tx_pool/replace.rs
- tx-pool/src/pool.rs
The current RBF fee check rules use the directly conflicted transactions' fee as compare target, but in the child-pay-for-parent scenario, the new transaction with fee large than root transactions but less than all descendant's sum may succeed in RBF rules.
The current celldep check also has a similar issue.
This PR will fix these 2 issue, by adding all the fee of descendants and root transactions and check the celldeps including descendants.
Tests 
- Unit test
Side effects
```release-note
Title Only: Include …
```
> backport: Fix RBF fee and celldeps check rule issue with replaced txs and their descendants

- util/app-config/src/tests/cli.bats
- Fix the regex expression to match ckb version string like `ckb 0.113.0 (82871a3 2024-01-09)` or `ckb 0.113.0-rc3 (3287c63 2024-01-02)`
Tests 
Side effects
- None
```release-note
```
> backport: Fix the regex expression for ckb's version test 

- util/constant/src/hardfork/testnet.rs
This reverts commit f2890dfa7847eca36e11f8dc26e9e2214a4a0777.
2nd hardfork still needs some tweaking:
* We need to consider whether to keep A extension
* Spawn syscall needs more time to refine its design.
Tests 
- Unit test
Side effects
```release-note
```
> chore: delayed 2nd hardfork testnet activation

- chain/src/chain.rs
- util/metrics/src/lib.rs
We need to monitor the time duration for `process_block`, this is useful to benchmark the new verify with pause, we want to compare the different results from develop branch and the new feature branch.
Add `ckb_block_process_duration` in matrics.
Tests 
- Unit test
```release-note
```
> Add ckb_block_process_duration in metric for monitoring and testing

- rpc/src/tests/module/pool.rs
- test/src/main.rs
- test/src/specs/tx_pool/limit.rs
- tx-pool/src/component/entry.rs
- tx-pool/src/component/links.rs
- tx-pool/src/component/pool_map.rs
- tx-pool/src/component/tests/links.rs
- tx-pool/src/component/tests/mod.rs
We met a scenario that a `cell dep` may have many transactions as descendants, and we can not  submit a new transaction to consume the dep cell.
`cell dep` should be handled specially when calculating the entry's `ancestors_count`.
In this PR, we add a `direct_ancestors_count` to store the directed parent-child relationship between transactions.
This is a short-term solution.
Tests 
- Unit test
Side effects
```release-note
```
> backport: Don't account for cell dep for MAX_ANCESTORS_COUNT

- rpc/src/server.rs
There is a trivial issue introduced in #4314, the `shutdown` layer didn't applied to websocket after the PR, which makes it will hung up when server terminate websocket.
Fix the shutdown handler, make it's default for HTTP and Websocket, since we will always send exit signal in these two scenario, so we can make the code simpler.
Tests 
- Unit test
Side effects
```release-note
```
> Fix the websockets terminate issue

- rpc/src/server.rs
There is a trivial issue introduced in #4314, the `shutdown` layer didn't applied to websocket after the PR, which makes it will hung up when server terminate websocket.
Fix the shutdown handler, make it's default for HTTP and Websocket, since we will always send exit signal in these two scenario, so we can make the code simpler.
Tests 
- Unit test
Side effects
```release-note
```
> backport: Fix the websockets terminate issue

- .github/workflows/ci_benchmarks_windows.yaml
- .github/workflows/ci_integration_tests_windows.yaml
- .github/workflows/ci_unit_tests_windows.yaml
- .github/workflows/package.yaml
- Cargo.lock
- script/Cargo.toml
Solve a bug where a variable is not initialized. Check out below page for more information about this bug:
https://github.com/nervosnetwork/ckb-vm/pull/394
Update ckb-vm to v0.24.7. For detaild ChangLogs, see:
https://github.com/nervosnetwork/ckb-vm/releases/tag/v0.24.7
Tests 
- Unit test
```release-note
```
> chore(scripts): update ckb-vm to v0.24.7

- devtools/doc/rpc-gen/src/gen.rs
- devtools/doc/rpc-gen/src/main.rs
- devtools/doc/rpc-gen/src/utils.rs
- devtools/doc/rpc-gen/templates/markdown.tera
- rpc/README.md
- rpc/src/module/miner.rs
- Different module may have the same method names, for https://github.com/nervosnetwork/ckb/pull/4224
- openrpc submodule need to use branch name with ckb repo, to remove duplicates for different users.
- Use a more accurate method link, so that the duplicated methods can refer to the right position. 
Tests 
- Unit test
```release-note
```
> Support RPC duplicate method name  for different modules

- Cargo.lock
- util/app-config/src/tests/graceful_shutdown.bats
- util/indexer/Cargo.toml
- util/indexer/src/service.rs
Issue Number: close #4311
In the `apply_init_tip` function, there is a loop that should take into account the exit signal:
https://github.com/nervosnetwork/ckb/blob/1ee9c985d61285749128adbbb916ede7742404aa/util/indexer/src/service.rs#L156-L172
Additionally, once `initial_syncing` is finished and CKB receives an exit signal, there is no need to spawn the `new_block_watcher` polling job.
- handle exit signal in `apply_init_tip`
Tests 
- Unit test
Side effects
- None
```release-note
```
> `IndexerService::apply_init_tip` should stop after received exit signal.

- tx-pool/src/chunk_process.rs
- verification/src/transaction_verifier.rs
The `inner` in `ScriptVerifier` is useless.
Clean up the `inner`, add alias `ScriptVerifier` for `TransactionScriptsVerifier` to keep compatible.
Tests 
- Unit test
Side effects
```release-note
```
> alias ScriptVerifier for TransactionScriptsVerifier

- test/src/main.rs
- test/src/specs/relay/transaction_relay.rs
- tx-pool/src/process.rs
There is a paste-copy bug in `resumeble_process_tx`, when a peer send malformed_tx with large cycles it won't be banned for a while.
Fix the parameter error in invoking `non_contextual_verify`.
Tests 
- Unit test
Side effects
```release-note
```
> A peer send manlformed tx with large cycles will also be banned

- test/src/main.rs
- test/src/specs/relay/transaction_relay.rs
- tx-pool/src/process.rs
There is a paste-copy bug in `resumeble_process_tx`, when a peer send malformed_tx with large cycles it won't be banned for a while.
Fix the parameter error in invoking `non_contextual_verify`.
Tests 
- Unit test
Side effects
```release-note
```
> backport 114: A peer send manlformed tx with large cycles will also be banned

- util/app-config/src/tests/graceful_shutdown.bats
- util/indexer/src/service.rs
…trl-c signal
In #4345, the `tokio::select!` will stuck forever if ckb doesn't received ctrl-C signal. Should use `stop.is_canceled()`.
- use `stop.is_canceled()` to check if ckb has received exit signal.
Tests 
- Unit test
Side effects
- None
```release-note
```
> IndexerService should use `is_cancelled()` to check if ckb received Ctrl-C signal

- Cargo.lock
- util/app-config/src/tests/graceful_shutdown.bats
- util/indexer/Cargo.toml
- util/indexer/src/service.rs
Backport #4345 #4348
Issue Number: close #4311
In the `apply_init_tip` function, there is a loop that should take into account the exit signal:
https://github.com/nervosnetwork/ckb/blob/1ee9c985d61285749128adbbb916ede7742404aa/util/indexer/src/service.rs#L156-L172
Additionally, once `initial_syncing` is finished and CKB receives an exit signal, there is no need to spawn the `new_block_watcher` polling job.
- handle exit signal in `apply_init_tip`
Tests 
- Unit test
Side effects
- None
```release-note
```
> Backport to `v0.114.x` , `IndexerService::apply_init_tip` should stop after received exit signal.

- Cargo.lock
- util/indexer/Cargo.toml
- util/indexer/src/service.rs
- util/stop-handler/src/lib.rs
- util/stop-handler/src/stop_register.rs
- `try_loop_sync` should not run if ckb has received stop signal.
Tests 
- Unit test
Side effects
- None
```release-note
```
> `IndexerService::try_loop_sync` should not run if ckb has received stop signal

- Cargo.lock
- util/indexer/Cargo.toml
- util/indexer/src/service.rs
- util/stop-handler/src/lib.rs
- util/stop-handler/src/stop_register.rs
Backport https://github.com/nervosnetwork/ckb/pull/4351
- `try_loop_sync` should not run if ckb has received stop signal.
Tests 
- Unit test
Side effects
- None
```release-note
```
> Backport #4351 `IndexerService::try_loop_sync` should not run if ckb has received stop signal

- ckb-bin/src/subcommand/migrate.rs
- db-migration/src/lib.rs
- shared/src/shared_builder.rs
- util/app-config/src/args.rs
- util/app-config/src/cli.rs
- util/app-config/src/lib.rs
- util/migrate/src/migrate.rs
- util/migrate/src/tests.rs
If all the migrations can be run in background, user don't need to manually run `ckb migrate --force`.
We should make it's transparent when all migrations can run in background.
Add `--include-background` to check all migrations include background ones.
Tests 
- Unit test
```release-note
```
> Add --include-background to include background migrations in migrate subcommand

- Cargo.lock
- script/Cargo.toml
There is a small issue in the old version of ckb-vm that leads to a slight performance decrease.
Update ckb-vm to v0.24.8. For detaild ChangLogs, see:
https://github.com/nervosnetwork/ckb-vm/releases/tag/v0.24.8
Tests 
- Unit test
```release-note
```
> chore(scripts): update ckb-vm to v0.24.8

- ckb-bin/src/subcommand/migrate.rs
- db-migration/src/lib.rs
- shared/src/shared_builder.rs
- util/app-config/src/args.rs
- util/app-config/src/cli.rs
- util/app-config/src/lib.rs
- util/migrate/src/migrate.rs
- util/migrate/src/tests.rs
If all the migrations can be run in background, user don't need to manually run `ckb migrate --force`.
We should make it's transparent when all migrations can run in background.
Add `--include-background` to check all migrations include background ones.
Tests 
- Unit test
```release-note
```
> backport 114: Add --include-background to include background migrations in migrate subcommand 

- Cargo.lock
- script/Cargo.toml
Fix some bugs in VERSION2 MOP instructions.
Update ckb-vm to v0.24.9. For detaild ChangLogs, see:
https://github.com/nervosnetwork/ckb-vm/releases/tag/v0.24.9
Tests 
- Unit test
```release-note
```
> chore(scripts): update ckb-vm to v0.24.9

- Cargo.lock
- Makefile
- devtools/doc/rpc-gen/Cargo.toml
- devtools/doc/rpc-gen/src/gen.rs
- devtools/doc/rpc-gen/src/main.rs
- devtools/doc/rpc-gen/src/syn.rs
- rpc/README.md
- util/jsonrpc-types/src/blockchain.rs
- util/jsonrpc-types/src/debug.rs
- util/jsonrpc-types/src/info.rs
- util/jsonrpc-types/src/json_schema.rs
- util/jsonrpc-types/src/pool.rs
- util/types/src/core/service.rs
There are several issues:
- `Uint32` is wrong and replaced with `AlertId`
- Missing some fields, such as `IndexerSearchKeyFilter`, cc @EthanYuan 
- Fix issues in `gen.rs` 
- Add some predefined types in the doc generator, similar with `rpc.py` 
Tests 
- Unit test
Side effects
```release-note
```
> Fix rpc doc generator issues

- devtools/doc/rpc-gen/src/utils.rs
The result from command `cargo pkgid` may have differences between different arch.
Strip out the first `@` in command line output.
Tests 
- Unit test
```release-note
```
> chore: Fix get_version in doc gen

- rpc/README.md
Issue Number: close #3513
Add the link to a GitHub topic as mentioned in the issue <https://github.com/nervosnetwork/ckb/issues/3513>
Tests
- Integration test: CI that covers RPC doc generation
```release-note
```
> doc: add link to rpc proxy projects

- rpc/README.md
- rpc/src/error.rs
- shared/src/shared_builder.rs
- test/src/specs/tx_pool/limit.rs
- tx-pool/src/component/entry.rs
- tx-pool/src/component/links.rs
- tx-pool/src/component/pool_map.rs
- tx-pool/src/component/tests/links.rs
- tx-pool/src/component/tests/pending.rs
- tx-pool/src/pool.rs
- tx-pool/src/process.rs
- util/jsonrpc-types/src/pool.rs
- util/types/src/core/tx_pool.rs
The are conflicts rule between cell dep reference and cell consume relationships.
Assume there are 3 transactions, B cell dep A(and there may be many transactions also cell dep A), C consumes A. 
- If C is committed first, B and all other transactions will be invalidated.
- If there are too many transactions all cell dep A, transaction C can not be submitted to `txpool`.
This is an alternative solution with https://github.com/nervosnetwork/ckb/pull/4352
In this PR, we introduce these changes:
- Add a new `check_entry_ancestors_limit ` to find all candidates needed to evict due to cell ref conflicts, based on `evict_score`. 
- Remove `DirectParents` and  `direct_ancestors_count`, we make sure an entry's ancestors number is valid after evicting conflicted cell ref …
> Evict possible cell ref txs before submitting cell consuming transaction

- rpc/README.md
- rpc/src/module/net.rs
- sync/Cargo.toml
- sync/src/orphan_block_pool.rs
- sync/src/synchronizer/block_fetcher.rs
- sync/src/tests/orphan_block_pool.rs
- util/constant/src/sync.rs
- util/jsonrpc-types/src/net.rs
This PR adds a special download mode during ibd to limit the memory usage of the orphan pool.
Tests
- Unit test
```release-note
```
> feat: limit ibd orphan pool size

- Cargo.lock
- devtools/doc/rpc-gen/Cargo.toml
- devtools/doc/rpc-gen/src/gen.rs
- devtools/doc/rpc-gen/templates/markdown.tera
- rpc/Cargo.toml
- rpc/README.md
- util/fixed-hash/core/Cargo.toml
- util/jsonrpc-types/Cargo.toml
There is an issue from schemars: https://github.com/GREsau/schemars/issues/193, which may insert `_and_` and `_for_` in types, we don't want this.
Add a wrapper function `fix_type_name` to workaround it, it will cost much more time to wait schemars fix its issue, or we need to dig into schemars by ourself which will also cost time.
Tests 
- Unit test
Side effects
```release-note
```
> Fix type name issue caused from schemars

- test/src/specs/tx_pool/limit.rs
- tx-pool/src/pool.rs
- tx-pool/src/process.rs
Currently, the `limit_size` is only invoked by `_update_tx_pool_for_reorg`, so we only shrink tx_pool size when generating a new block. Ideally, we should also limit size when inserting a new Entry into pool.
Invoke `limit_size` in `submit_entry`.
Tests 
- Unit test
Side effects
```release-note
```
> Limit txpool size when inserting an Entry 

- test/src/main.rs
- test/src/node.rs
In the current integration test, `PoolPersisted` is only permitted to be executed on non-Windows platforms, as there is no `stop_gracefully` implementation for the Node used in the integration test.
- Implement graceful termination for the integration test on the Windows platform.
- Allow `PoolPersisted` to be executed on Windows.
Tests 
- Unit test
Side effects
- None
```release-note
```
> Allow the `PoolPersisted` integration test to run on Windows.

- Cargo.lock
- devtools/doc/rpc-gen/Cargo.toml
- devtools/doc/rpc-gen/src/gen.rs
- devtools/doc/rpc-gen/src/syn.rs
- rpc/README.md
- rpc/src/module/chain.rs
- rpc/src/module/experiment.rs
The new readme generator didn't add note for deprecated rpc methods.
- Add `syn` related code to support these notes.
Tests 
- Unit test
```release-note
```
> chore: add deprecated notes for rpc README

- devtools/ci/check-cargotoml.sh
- resource/Cargo.toml
- util/fixed-hash/macros/Cargo.toml
- util/types/Cargo.toml
Use bash script with pattern match to check unused crates seems slow and not easy to maintain, [cargo-shear](https://github.com/Boshen/cargo-shear) is a better tool for this task.
While it has false positive warnings caused by macros, we can add them to the ignored list.
- Add `cargo-shear` into `devtools/ci/check-cargotoml.sh`
- Trivial cleanup for performance
Tests 
- Unit test
```release-note
```
> (chore): Add cargo shear to check crates

- test/src/specs/relay/compact_block.rs
- util/indexer-sync/src/pool.rs
- util/memory-tracker/src/jemalloc.rs
fix some typos in conments
Tests 
- Unit test
Side effects
```release-note
```
> chore: fix some typos in conments

- chain/src/chain.rs
On the develop branch, the `ChainService`'s `process_block` channel has a capacity of `DEFAULT_CHANNEL_SIZE`(32), but it does not provide any benefit for `ckb-sync` or `ckb-chain`:
https://github.com/nervosnetwork/ckb/blob/149b5c53e2c6e089d3e4ff6013d1992b56f3b4c6/chain/src/chain.rs#L225
In a scenario where `ckb-sync` sends a block to `ChainService` through `ChainController::process_block`, and at the same time, `ChainService` receives a `Ctrl-C` exit signal.
Then `ChainService`'s `process_block_sender` have one `ProcessBlockRequest` in its buffer:
https://github.com/nervosnetwork/ckb/blob/149b5c53e2c6e089d3e4ff6013d1992b56f3b4c6/chain/src/chain.rs#L41
When `self.process_block_sender` and `self.stop_receiver` are ready at the same time, `ChainService`'s `select!` may choose to execute …
> Set ChainService process_block channel size to zero

- devtools/ci/ci_main.sh
I beleave we shouldn't set `CKB_TEST_SEC_COEFFICIENT=5` on windows's integration test script.
- Remove `CKB_TEST_SEC_COEFFICIENT=5` on windows's integration test script.
Tests 
- Unit test
Side effects
- None
```release-note
```
> Remove `CKB_TEST_SEC_COEFFICIENT` on windows ci integration

- test/Cargo.toml
- test/src/main.rs
- test/src/node.rs
On latest develop branch, Windows CI failed: https://github.com/nervosnetwork/ckb/actions/runs/8718279015/job/23915178721
- Use `windows_sys` to send `Ctrl-C` signal to process on Windows platform
Tests 
- Unit test
Side effects
- None
```release-note
```
> Fix send Ctrl-C signal on Windows integration test'

- Cargo.lock
- deny.toml
- util/rich-indexer/Cargo.toml
- **Fix `RUSTSEC-2024-0336`, Change sqlx feature `runtime-tokio-rustls` to `runtime-tokio-native-tls`**
- **Remove ignored `RUSTSEC-2021-0145`, it does not affect current ckb**
Fix https://github.com/nervosnetwork/ckb/actions/runs/8777396874/job/24082289815,
- Let sqlx use `runtime-tokio-native-tls` instead of `runtime-tokio-rustls` to drop `rustls` dependency.
Tests 
- Unit test
Side effects
- None
```release-note
```
> Fix RUSTSEC-2024-0336, let sqlx use `runtime-tokio-native-tls` instead of `runtime-tokio-rustls` to drop `rustls` dependency

- test/src/node.rs
In the latest develop branch's CI report: https://github.com/nervosnetwork/ckb/actions/runs/8749973042/job/24047547692
ckb-test compile error
- fix ckb-test compile error
Tests 
- Unit test
Side effects
- None
```release-note
```
> Fix windows integration test compile error

- test/src/main.rs
It's hard to let PoolPersisted execute on windows, disable it now, fix later...
- Disable `PoolPersisted` on windows integration test
Tests 
- Unit test
Side effects
- None
```release-note
```
> Disable PoolPersisted on windows CI

- rpc/README.md
- rpc/src/module/pool.rs
- tx-pool/src/process.rs
- tx-pool/src/service.rs
- util/jsonrpc-types/src/lib.rs
- util/jsonrpc-types/src/pool.rs
- util/types/src/core/mod.rs
- util/types/src/core/tx_pool.rs
- verification/src/cache.rs
Returns the result of transaction pool acceptance tests, indicating whether the raw transaction would be accepted by the transaction pool. The transaction will not be inserted into the transaction pool.
- Add `test_tx_pool_accept` for `PoolRpc`
Tests 
- Unit test
Side effects
- None
```release-note
```
> Add `PoolRpc::test_tx_pool_accept`, check if the transaction can be accepted by TxPool

- rpc/README.md
- rpc/src/module/pool.rs
Backport #4447 's second commit.
- Remove unreachable errors for test_tx_pool_accept
Tests 
- Unit test
Side effects
```release-note
```
> Backport #4447 's 2nd commit,Remove unreachable error for test_tx_pool_accept

- devtools/ci/check-cargotoml.sh
The latest version of `cargo-shear` requires rustc 1.76.0 or newer, while the currently active rustc version is 1.75.0.
Lock the version of `cargo-shear` to 0.024.
Tests 
- Unit test
```release-note
```
> chore: lock cargo shear version

- chain/src/chain.rs
When run `ckb run` without disabling `assume-valid-target`, all the cycles in blocks are zero, since we skipped verification in this scenario.
Don't store all zeros in db, set `ext.cycles` to None.
Tests 
- Unit test
```release-note
```
> Skip storing all zero cycles in db when disable script

- chain/src/chain.rs
Reverts nervosnetwork/ckb#4452
I think #4452 introduced a bug:
```bash
./ckb run -C /tmp/a --assume-valid-target 0xb72f4d9758a36a2f9d4b8aea5a11d232e3e48332b76ec350f0a375fac10317a4
...
...
...
2024-05-12 18:16:13.895 +00:00 GlobalRt-0 ERROR ckb_sync::types  accept block BlockView { data: Block(0x3602000014000000e4000000e800000032020000000000007ea9081ac4e403716e01000014000000000000000000001400cf0600218cf6b29f5ffb1582387c587d79d1cded15f8aa72c5171875442cd228572cb5c2139e3b25f6a1574202374f54c4ee699e3b6cefd88b815e7243e72dc1e888ee00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000288ff8cff820a12e5942acecf28623000c66038e9300000000f656c8ccfefe06000539030000000073000000b4fc2dea040000004a01000008000000420100000c000000d9000000 …
```
> Revert "Skip storing all zero cycles in db when disable script"

- rpc/README.md
- rpc/src/module/chain.rs
- tx-pool/src/service.rs
- Add `include_tx_pool: bool` param to `ChainRpcImpl::get_live_cell` RPC
Tests 
- Unit test
Side effects
- None
```release-note
```
> Add `include_tx_pool: Option<bool>` param to `ChainRpcImpl::get_live_cell`'

- rpc/README.md
- rpc/src/module/chain.rs
- tx-pool/src/service.rs
Backport #4454
- Add `include_tx_pool: bool` param to `ChainRpcImpl::get_live_cell` RPC
Tests 
- Unit test
Side effects
- None
```release-note
```
> Backport #4454 Add `include_tx_pool: Option<bool>` param to `ChainRpcImpl::get_live_cell`'

- Makefile
- chain/src/tests/find_fork.rs
- script/src/error.rs
- tx-pool/src/component/pool_map.rs
fix some comments
Tests 
- Unit test
Side effects
```release-note
```
> chore: fix some comments

- script/fuzz/fuzz_targets/transaction_scripts_verifier_data0.rs
- script/fuzz/fuzz_targets/transaction_scripts_verifier_data1.rs
- script/fuzz/fuzz_targets/transaction_scripts_verifier_data2.rs
Data1 verifier always returns `Err(Error { kind: Script, inner: TransactionScriptError { source: Inputs[0].Lock, cause: Invalid VM Version: 1 } })`. 
Use the correct hardfork writing to make ckb2021 and ckb2023 always effective in the three fuzz targets. There are no issues with Data0 and Data2 fuzz target at the moment, but I still made same changes to them.
Tests 
- Unit test
```release-note
```
> script(fuzz): fixed the issue where data1 verifier always returns invalid version error

- Makefile
- ckb-bin/src/subcommand/run.rs
- db-migration/src/lib.rs
- devtools/doc/rpc-gen/src/gen.rs
- rpc/src/service_builder.rs
- rpc/src/tests/setup.rs
- test/src/specs/tx_pool/limit.rs
- test/src/specs/tx_pool/orphan_tx.rs
- test/src/specs/tx_pool/replace.rs
- tx-pool/src/component/tests/links.rs
- tx-pool/src/component/tests/orphan.rs
- tx-pool/src/process.rs
- util/indexer/src/service.rs
Problem Summary: 
When I review a performance issue, I found there are some necessary clones.
`clippy::redundant_clone` may remove them from the code.
add `clippy::redundant_clone`.
Tests 
- Unit test
Side effects
```release-note
```
> chore: add clippy::redundant_clone

- sync/src/relayer/mod.rs
- sync/src/synchronizer/block_fetcher.rs
- sync/src/tests/inflight_blocks.rs
- sync/src/types/mod.rs
- util/types/src/block_number_and_hash.rs
- util/types/src/lib.rs
I think `BlockNumberAndHash` is more suitable to be placed in `ckb-types`. Moreover, I want to use `BlockNumberAndHash` in `ckb-db` and `ckb-db-schema`.
- Move `struct BlockNumberAndHash` to `ckb-types`
Tests 
- Unit test
Side effects
- None
```release-note
```
> Move `BlockNumberAndHash` from`ckb-sync` to `ckb-types`

- rpc/src/module/subscription.rs
Fixes #4489
The current channel size is too small, which may introduce `RecvError::Lagged` when the workload is high.
- enlarge the notify channel size, keep it same with `ckb_notify::NOTIFY_CHANNEL_SIZE`.
- ignore the `RecvError::Lagged` and continue to get the later notifications. 
Tests 
- Unit test
Side effects
```release-note
```
> Fix websocket subscription performance issue

- resource/ckb.toml
1. The command `ckb init <lock_arg>` execution failed; you should use `ckb init --ba-arg <lock_arg>` instead.
2. `{cmd} {blocktemplate}` may be misunderstood as needing to fill in `echo {blocktemplate}.`
> Update configuration comments

- ckb-bin/src/lib.rs
- ckb-bin/src/subcommand/run.rs
- rpc/src/server.rs
- test/src/net.rs
- test/template/ckb.toml
- util/launcher/src/lib.rs
- util/runtime/src/lib.rs
- util/stop-handler/src/tests.rs
Currently, we have some RPC API from indexer such as `get_cells`, `get_transactions`, `get_cells_capacity` which may cost a lot of computing resources, it may occupy all the tokio tasks, and `ckb` can not process blocks in extreme scenarios.
RPC will run in a standalone tokio runtime, so that we can process block even in extreme scenario.
Tests 
- Unit test
Side effects
```release-note
```
> Use standalone runtime for RPC service

- ckb-bin/src/subcommand/run.rs
- rpc/README.md
- rpc/src/module/net.rs
- sync/src/types/mod.rs
- util/jsonrpc-types/src/net.rs
- util/launcher/src/lib.rs
Issue Number: close #4485 
- Add `assume_valid_target_reached: bool` and `min_chain_work_reached: bool` to `sync_state` RPC
- let `check_assume_valid_target` don't reset `SyncConfig::assume_valid_target` to `None` if the assume target has found in `Snapshot`.
Tests 
- Unit test
Side effects
```release-note
```
> Add `assume_valid_target_reached: bool` to `NetRpc::sync_state` 

- Cargo.lock
```bash
error[yanked]: detected yanked crate (try `cargo update -p bytes`)
┌─ /home/runner/work/ckb/ckb/Cargo.lock:40:1
│
40 │ bytes 1.6.0 registry+https://github.com/rust-lang/crates.io-index
│ ----------------------------------------------------------------- yanked version
```
Upgrade bytes to >=4.1.3
Tests 
- Unit test
```release-note
```
> chore: fix yanked bytes

- shared/src/shared_builder.rs
- sync/src/relayer/mod.rs
- test/src/main.rs
- test/src/specs/tx_pool/orphan_tx.rs
- test/src/util/transaction.rs
- tx-pool/src/component/orphan.rs
- tx-pool/src/process.rs
- tx-pool/src/service.rs
- util/types/src/core/tx_pool.rs
- util/types/src/core/views.rs
* Modify the record scope of tx-pool reject record, Now that all rejects are record except Duplicate (which gets rebroadcast)
* Fixed the case where some inputs of a transaction are unknown will not add to the orphan pool.
* Now actively fetches unknown transactions from node broadcasting orphan tx
Tests 
```release-note
```
> Modify the record scope of tx-pool reject record and fix rule for orphan tx.

- sync/src/synchronizer/mod.rs
- Early return `BlockFetchCMD::process_fetch_cmd` if ckb has received exit signal
Tests 
- Unit test
Side effects
- None
```release-note
```
> Early return process_fetch_cmd if ckb received exit signal

- util/constant/src/default_assume_valid_target.rs
We haven't update the hardcoded DEFAULT_ASSUME_VALID_TARGET since Apr 22, update it now.
- Update the DEFAULT_ASSUME_VALID_TARGET
Tests 
Side effects
- None
```release-note
```
> Update the hardcoded DEFAULT_ASSUME_VALID_TARGET

- sync/src/synchronizer/mod.rs
Backport https://github.com/nervosnetwork/ckb/pull/4527 
Tests 
Side effects
- None
```release-note
```
> Backport #4527 Early return process_fetch_cmd if ckb received exit signal

- store/src/store.rs
- Remove duplicated commented `fn calc_data_hash`
Tests 
Side effects
- None
```release-note
```
> Remove duplicate commented `fn calc_data_hash`

- .github/workflows/stall.yml
Problem Summary: Too many inactive issues and prs
What's Changed: Stall issues after 30 days and close after 5 days. Stall prs after 45 days and close after 10 days.
Ref https://github.com/marketplace/actions/close-stale-issues
Tests 
```release-note
```
> chore: auto close stalled issues and prs

- sync/src/relayer/mod.rs
- sync/src/relayer/tests/mod.rs
- sync/src/tests/sync_shared.rs
- sync/src/types/mod.rs
`HeaderProcess` uses the current snapshot to process the one-time message, During the entire processing process, the changes in the db itself are imperceptible. Normally, there is no problem here. But during this process, if a compact block message is received and processed successfully, the chain inserts a new block, and the block's header is in the previous header process message, there will be a concurrency problem.
I use a simple diagram to describe the time series problem here：
```bash
sync thread   |          process headers         |
relay thread    |  compact block process  |
```
The time series here is that the header process holds the old snapshot longer than the compact block process completion time.
This will cause the block status in the old snapshot to differ from the actual …
> fix: fix sync relayer collaboration

- deny.toml
- sync/src/relayer/tests/helper.rs
- test/src/node.rs
- test/src/rpc.rs
- test/src/specs/fault_injection/randomly_kill.rs
- test/src/specs/sync/sync_churn.rs
- test/src/specs/sync/sync_invalid.rs
Fix unit test and integration test on latest develop branch CI.
- Wait init_load_unverified thread exit before processing block in unit test
- Don't use unwrap on SyncChurn's Sender'
- Wait rpc_client are ready before send rpc request
Tests 
- Unit test
Side effects
- None
```release-note
```
> Fix unit test and integration test for test_accept_block and SyncChurn

- sync/src/tests/synchronizer/basic_sync.rs
- test/src/node.rs
- test/src/specs/sync/invalid_block.rs
Want to fix: 
https://github.com/nervosnetwork/ckb/actions/runs/10256636258/job/28376143614
https://github.com/nervosnetwork/ckb/actions/runs/10256636255/job/28376145250
In Integration Test, when node crash, print last 500 lines of log.
In Unit test `fn basic_sync`, wait init_load_unverified thread exit before process bad block
- Unit test: wait init_load_unverified thread finish before insert block
- Integration Test: print last 500 lines log when node crash
- Integration Test: wait init_load_unverified thread exit before process block on MacOS platform
Tests 
- Unit test
Side effects
- None
```release-note
```
> Fix Unit Test and Integration Test on MacOS and Windows platform

- test/src/node.rs
- test/src/specs/sync/last_common_header.rs
- test/src/specs/sync/sync_invalid.rs
This PR want to increase wait timeout for LastCommonHeaderForPeerWithWorseChain, fix https://github.com/nervosnetwork/ckb/actions/runs/10259218824/job/28436471337 on MacOS
- **Integration Test: Extract wait_find_unverified_blocks_finished as independent method**
- **Integration Test: Increase wait timeout for LastCommonHeaderForPeerWithWorseChain**
Tests 
- Unit test
Side effects
- None
```release-note
```
> Integration Test: Increase wait timeout for LastCommonHeaderForPeerWithWorseChain

- test/src/main.rs
- test/src/specs/sync/sync_churn.rs
- Decrease mined blocks count and restart count on macos and windows
Tests 
- Unit test
Side effects
- None
```release-note
```
> Integration Test: decrease restart times and mined blocks count on windows and macos

- tx-pool/src/component/tests/chunk.rs
- tx-pool/src/component/verify_queue.rs
- tx-pool/src/verify_mgr.rs
Fix error from spec `CheckVmVersion2`.
It's safe to skip none and don't call `after_process` for None returned from `process_tx`.
Tests 
- Unit test
```release-note
```
> Test: remove expect in verify_mgr because process_tx may return None

- resource/ckb.toml
- util/app-config/src/configs/indexer.rs
- util/gen-types/src/lib.rs
- util/indexer/src/service.rs
- util/jsonrpc-types/src/blockchain.rs
- util/jsonrpc-types/src/bytes.rs
- util/rich-indexer/src/indexer/mod.rs
- util/rich-indexer/src/indexer_handle/async_indexer_handle/get_cells.rs
- util/rich-indexer/src/indexer_handle/async_indexer_handle/get_transactions.rs
- util/rich-indexer/src/indexer_handle/async_indexer_handle/mod.rs
- util/rich-indexer/src/indexer_handle/mod.rs
- util/rich-indexer/src/service.rs
- util/rich-indexer/src/tests/insert.rs
- util/rich-indexer/src/tests/query.rs
close #4520 related https://github.com/serde-rs/json/issues/635
A large number of data requests will consume more than 10x the memory when serialized in JSON, resulting in huge memory overhead and affecting the operation of the server
We recommend setting the memory usage limit at 2 GB, meaning only 200 MB of data can be requested at a time. The maximum cell data size is 500 KB, and 400 cells can be requested at one time.
In addition, we strongly recommend using this configuration #4529 to limit the upper limit of batch requests.
Tests
- Unit test
```release-note
```
> fix: add limit to get cells

- rpc/README.md
- rpc/src/module/chain.rs
- util/jsonrpc-types/src/blockchain.rs
- util/types/src/core/tx_pool.rs
- Add tx_index for TxStatus for get_transaction RPC
Tests 
- Unit test
Side effects
- None
```release-note
```
> Add `tx_index` to `TxStatus` for `get_transaction` RPC

- test/src/main.rs
- test/src/worker.rs
- Integration Test: let RandomlyKill and SyncChurn run in sequnece
Tests 
- Unit test
Side effects
- None
```release-note
```
> IntegrationTest: Let RandomKill and SyncChurn run in sequence

- tx-pool/src/component/verify_queue.rs
- tx-pool/src/verify_mgr.rs
we found `SendLargeCyclesTxToRelay` is not stable, seems some large cycle tx is not properly processed when replay.
The root cause is when `verify_queue` wake up a `OnlySmallCycleTx` to large cycle tx, the worker will directly return, then other worker also miss the chance to pick it up.
- Let `Worker::process_inner` re_notify other workers if current worker is a `OnlySmallCycleTx` Worker, but there is large cycle tx in `VerifyQueue`
Tests 
- Unit test
Side effects
- None
```release-note
```
> `VerifyQueue`: re_notify other Worker when `OnlySmallCycleTx` received a large cycle tx

- test/src/specs/sync/block_sync.rs
- In BlockSyncNonAncestorBestBlocks, wait nodes find unverified blocks finish before inserting invalid blocks.
Tests 
Side effects
- None
```release-note
```
> Integration Test: wait find unverified blocks finish before insert invalid block

- test/src/specs/sync/block_sync.rs
- test/src/specs/sync/ibd_process.rs
- Integration Test: wait find unverified blocks finish before integration test
Tests 
- Unit test
Side effects
- None
```release-note
```
> Integration Test: wait find unverified blocks finish in BlockSyncFromOne and IBDProcess

- test/src/specs/tx_pool/send_large_cycles_tx.rs
Fix the failure on MacOs Github CI.
The root cause is on slow machine, like Github MacOS CI server, it will cost almost 8 seconds to finish IBD stage, in spec `SendLargeCyclesTxToRelay` when the relay message is sent from `node1` to `node0`, `node0` may still in IBD mode, so tx is not synced.
Tests 
- Unit test
```release-note
```
> Fix SendLargeCyclesTxToRelay spec on slow machine

- test/src/node.rs
`ForksContainSameUncle` has the chance of 1/10 to fail in my local machine with error `Uncles(DoubleInclusion)`, after debugging I found the [`uncle` block hash](https://github.com/chenyukang/ckb/blob/dc20e94885256617675edab4f71f828ff23c47ed/test/src/specs/sync/chain_forks.rs#L565) is same with new block hash in [node_b.mine(1)](https://github.com/chenyukang/ckb/blob/dc20e94885256617675edab4f71f828ff23c47ed/test/src/specs/sync/chain_forks.rs#L567).
This issue if fixed in https://github.com/nervosnetwork/ckb/commit/0dc63c2c0cc947b0f1916579a15a27f3d2054421
But it's reverted in the following changes, I believe it is unintentional.
Make sure the uncle block timestamp is different from the next block timestamp in main fork
- Need to cherry-pick to …
> chore(test): Fix the unstable spec ForksContainSameUncle caused by block hash collision 

- tx-pool/src/verify_mgr.rs
When there are a lot of transaction pending in verify queue, `ctrl-c` may need to wait worker finishing all of them, because of this [loop](https://github.com/chenyukang/ckb/blob/ce418075496faad44d111f2cbc25b1eb961f8d8b/tx-pool/src/verify_mgr.rs#L78-L124) in verify worker, there is no chance to update `self.status` since worker is executing `process_inner`.
Worker should return from iteration when exit signal is sent.
Tests 
- Unit test
```release-note
```
> Fix: verify worker exit when signal_exit is_cancelled

- rpc/README.md
- rpc/src/module/pool.rs
- tx-pool/src/service.rs
With the new verify queue in PR https://github.com/nervosnetwork/ckb/pull/4291, the verify-queue may contain a lot of transactions in the extreme scenario, similar as `clear_tx_pool` we need a RPC to clear it.
Add a RPC `clear_tx_verify_queue` in the txpool RPC module.
Tests 
- Unit test
Side effects
```release-note
```
> chore(RPC): add PRC to clear verify queue 

- sync/src/synchronizer/mod.rs
- Do not start `BlockDownload` thread if ckb has received exit signal
Tests 
- Unit test
Side effects
- None
```release-note
```
> Do not start `BlockDownload` thread if ckb has received exit signal

- chain/src/init_load_unverified.rs
- test/src/specs/sync/sync_churn.rs
- In init_load_unverified thread, if no unverified blocks found after tip, early return
Tests 
- Unit test
Side effects
- None
```release-note
```
> Early return init_load_unverified thread when no unverified blocks found after tip

- test/src/node.rs
- Integration Test: Do not kill gracefully on windows 
Tests 
- Unit test
Side effects
- None
```release-note
```
> Integration Test: do not kill gracefully on windows

- test/src/node.rs
- test/src/rpc.rs
- test/src/specs/fault_injection/randomly_kill.rs
- Integration Test: restart node if it failed to start in RandomlyKill
Tests 
- Unit test
Side effects
- None
```release-note
```
> Integration Test: restart node if it failed to start in `RandomlyKill`

- shared/src/shared.rs
- shared/src/types/header_map/kernel_lru.rs
- tx-pool/src/service.rs
In multi-threaded state, atomic should use Acquire/Release at least
Tests
- Unit test
```release-note
```
> fix: fix atomic ordering in multi-thread

- test/src/main.rs
- test/src/specs/tx_pool/replace.rs
- tx-pool/src/pool.rs
- tx-pool/src/process.rs
When we replace some transactions in RBF, some old transactions may be okay to be recovered, since there are no conflicts after removing transactions. 
If we don't recover these transactions, it may introduce a scenario of a possible cycling attack in lightning network.
Add `conflicts_outputs_cache` to track the relationship of `input -> tx` in RBF, then add possible transactions into the verify pool, so that they may be recovered.
This PR is based on the `new-verify` branch, one reason is we can not recursively call `submit_entry` in async. Another reason is `new-verify`'s worker-consumer model is more suitable for retrying submit transactions.
Tests 
- Unit test
- Manual test (add …
> Recover possible transaction in conflicted cache when RBF

- chain/src/init.rs
- chain/src/lib.rs
- chain/src/tests/find_fork.rs
- chain/src/verify.rs
In current develop:
The log looks like:
```
2024-08-30 02:31:18.961 +00:00 consume_unverified_blocks INFO ckb_chain::consume_unverified  [verify block] new best block found: 13721606 => 0x26ba9b2e2c562aecdb13042feab7c7c850bacd95748127a43167a104680b3044, difficulty diff = 0x34b5ec519ab53fc6, unverified_tip: 13721606
```
the `ckb_chain::consume_unverified` looks inappropriate. Changing it to `ckb_chain::verify` should be more appropriate.
Rename `ckb_chain::consume_unverified` to `ckb_chain::verify`
- Change `consume_unverified.rs` to `verify.rs` in `./chain/src/`
Tests 
- Unit test
Side effects
- None
```release-note
None: Exclude this PR from the release …
```
> Rename `ckb_chain::consume_unverified` to `ckb_chain::verify`

- util/app-config/src/tests/bats_tests/cli_test.sh
Sometimes `git clone` may fail for network issues.
Add a retry strategy for it.
Tests 
- Unit test
```release-note
```
> chore(test): add retry for git clone in cli_test

- script/src/verify/tests/ckb_latest/features_since_v2021.rs
- test/src/specs/tx_pool/send_large_cycles_tx.rs
`step_cycles` is randomly generated, which may introduce different VM execution results.
cc PR #4546
Tests
- Unit test
```release-note
```
> test: fix script test error caused by rand step cycles

- .github/workflows/ci_integration_tests_macos.yaml
- .github/workflows/ci_integration_tests_ubuntu.yaml
- .github/workflows/ci_integration_tests_windows.yaml
- deny.toml
Want to fix:
- Inogre  https://rustsec.org/advisories/RUSTSEC-2024-0370
- Upgrade actions/upload-artifact to v4: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
Tests 
Side effects
- None
```release-note
```
> Ignore RUSTSEC-2024-0370 : https://rustsec.org/advisories/RUSTSEC-2024-0370

- block-filter/src/filter.rs
Backrpot #4641
- **Let BlockFilter exit if ckb has received exit signal**
Tests 
- Unit test
Side effects
- None
```release-note
```
> Backport Let BlockFilter exit if ckb has received exit signal#4641

- block-filter/src/filter.rs
- BlockFilter should exit if ckb has received exit signal
Tests 
- Unit test
Side effects
- None
```release-note
```
> Let BlockFilter exit if ckb has received exit signal

- rpc/src/tests/fee_rate.rs
- rpc/src/util/fee_rate.rs
Want to fix #4646 and #4350
- get_fee_rate_statistics skip first cellbase in BlockExt
Tests 
- Unit test
Side effects
- None
```release-note
```
> `get_fee_rate_statistics` should skip first (cellbase) Transaction

- rpc/src/tests/fee_rate.rs
- rpc/src/util/fee_rate.rs
backport #4647 to `rc/v0.118.x`
- get_fee_rate_statistics skip first cellbase in BlockExt
Tests 
- Unit test
Side effects
- None
```release-note
```
> backport # 4647 `get_fee_rate_statistics` should skip first (cellbase) Transaction

- script/src/types.rs
ISA_A should not be contained in version 2.
Remove ISA_A flag.
Tests 
- Unit test
Side effects
```release-note
```
> fix(script): remove isa a in version 2

- Cargo.lock
- deny.toml
- util/rich-indexer/Cargo.toml
- util/rich-indexer/src/indexer/insert.rs
- util/rich-indexer/src/indexer/remove.rs
- util/rich-indexer/src/indexer_handle/async_indexer_handle/get_transactions.rs
- util/rich-indexer/src/store.rs
- util/rich-indexer/src/tests/mod.rs
remove deny with sqlx
By the way, I think that SQL creates tables and indexes that can use `IF NOT EXISTS` to avoid judging whether it has been initialized. Although it is a non-standard statement, but both SQLite and Postgresql support it.
https://github.com/nervosnetwork/ckb/blob/21f49f23a20dfb329638ffb13fa020e069b987c3/util/rich-indexer/resources/create_postgres_table.sql#L1
https://github.com/nervosnetwork/ckb/blob/21f49f23a20dfb329638ffb13fa020e069b987c3/util/rich-indexer/src/store.rs#L68
https://github.com/nervosnetwork/ckb/blob/21f49f23a20dfb329638ffb13fa020e069b987c3/util/rich-indexer/src/store.rs#L77-L79
https://github.com/nervosnetwork/ckb/blob/21f49f23a20dfb329638ffb13fa020e069b987c3/util/rich-indexer/src/store.rs#L251-L266 …
> chore: remove deny with sqlx

- util/rich-indexer/src/store.rs
fix #4669 
IF NOT EXIST is only supported by Postgresql version 9.6 and above, and it not support Create Database
Tests
- Unit test
```release-note
```
> fix: fix pg init

- tx-pool/src/component/orphan.rs
backport #4676
When an entry in `OrphanPool` is empty, it should be removed.
- Remove empty entry in `OrphanPool`
Tests 
- Unit test
Side effects
- None
```release-note
```
> Backport #4676, Remove empty entry for `OrphanPool`

- tx-pool/src/component/orphan.rs
When an entry in `OrphanPool` is empty, it should be removed.
- Remove empty entry in `OrphanPool`
Tests 
- Unit test
Side effects
- None
```release-note
```
> Remove empty entry for `OrphanPool`

- db/Cargo.toml
Issue Number: close #4682 
- let ckb-rocksdb support LZ4
Tests 
- Unit test
Side effects
- None
```release-note
```
> Support LZ4 rocksdb compression type

- network/Cargo.toml
Problem Summary: Tentacle 0.6.2 introduces changes that require Rust 1.80.0 where ckb 0.119.0 minimum supported rust version is 1.75.0. So lock the tentacle to 0.6.1 in the `Cargo.toml` file for future possible patch releases. This only affects crates publish which does not use the `Cargo.lock` file.
What's Changed: Lock tentacle to 0.6.1 using `= 0.6.1`.
Tests 
- Unit test
```release-note
```
> [rc/v0.119.x] chore: lock tentacle

- deny.toml
- util/rich-indexer/src/indexer/remove.rs
Fix inconsistent mapping of PG Sqlite types in rust
Tests
- Unit test
```release-note
```
> fix: fix pg sqlite inconsistent types

- ckb-bin/src/subcommand/run.rs
close #4671
- Generate default.db-options file if it not exist
Tests 
- Unit test
Side effects
- None
```release-note
```
> Generate `default.db-options` file if it not exist

- Cargo.lock
Problem Summary: Failed to build OpenSSL 3.3 in CentOS 7 because of this issue:
https://github.com/openssl/openssl/issues/25366
```
cargo update openssl-sys
```
- Publish new release of [nervosnetwork/ckb-docker-builder](https://github.com/nervosnetwork/ckb-docker-builder)
- Skip v0.120.0-rc1 and start to release v0.120.0-rc2
Tests 
```release-note
```
> chore: bump openssl to 3.4.0

- script/Cargo.toml
Problem Summary: Failed to publish ckb-script because of the missing features.
What's Changed: Add missing features of "tokio" in the Cargo.toml of ckb-script
Tests 
-   Integration test
-   Manual test
`cargo publish` in directory `script/`.
```release-note
```
> fix: add missing features for tokio

- error/src/internal.rs
- script/src/error.rs
- script/src/verify.rs
- script/src/verify/tests/ckb_latest/features_since_v2023.rs
Issue Number: close #4701 
- let `ckb_vm::Error::External("stopped")` return `ErrorKind::Internal` instead of `ErrorKind::Script`
return `ErrorKind::Internal` then ckb will not think the tx is malformled:
https://github.com/nervosnetwork/ckb/blob/8cb49e4d727f337a2c80e210507a9e277bab3391/util/types/src/core/tx_pool.rs#L68-L84
Tests 
- Unit test
Side effects
- None
```release-note
```
> Don't ban remote peer when ckb_vm received Ctrl-C signal when processing chunk_tx

- rpc/src/error.rs
Issue Number: close #4698
- use remove_backtrace to remove backtrace from error message
Tests 
- Unit test
Side effects
- None
```release-note
```
> Remove anyhow's backtrace from RPC response

- Cargo.lock
- resource/ckb.toml
- util/app-config/src/tests/app_config.rs
make ckb default listen on ws port
Tests
- Unit test
```release-note
```
> feat: default listen on ws port

- Cargo.lock
- notify/Cargo.toml
- spec/Cargo.toml
- util/metrics-service/Cargo.toml
**Blocking** release of v0.120.0
Problem Summary: Failed to `cargo publish` because of missing features listed in `Cargo.toml`
What's Changed: See commit messages
- Need to cherry-pick to the release branch rc/v0.120.x
Tests 
```
CKB_PUBLISH_FROM=util/metrics-service devtools/release/publish-crates.sh -n
CKB_PUBLISH_FROM=spec devtools/release/publish-crates.sh -n
```
```release-note
```
> bugfix: add missing crate features

- Cargo.lock
- deny.toml
- network/Cargo.toml
- network/src/services/dns_seeding/mod.rs
ID: RUSTSEC-2024-0421
Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0421
Tests 
- `cargo deny check --hide-inclusion-graph --show-stats advisories sources`
```release-note
```
> chore(deps): update idna

- .github/workflows/package.yaml
Issue Number: close #4745 
It was disabled before because ckb-cli aarch64 package was not available when ckb started to package aarch64 binary.
What's Changed: Enable packaging ckb-cli for aarch64 linux
Tests 
- Run package workflow 
```release-note
```
> chore: package ckb-cli for aarch64 linux

- script/src/verify.rs
- Extract `TransactionScriptsVerifier::map_vm_internal_error`
Tests 
- Unit test
Side effects
- None
```release-note
```
> Extract `TransactionScriptsVerifier::map_vm_internal_error`

- network/src/peer_store/browser.rs
In the original peer store implementation of wasm , there is only one database (in IndexedDB) to store all peers, different network configurations are distinguished by store names, this can cause one issue: There is no way to use multiple configurations after the database was created, since IndexedDB disallows creating stores unless there is an upgrade for a certain database. 
This PR updates peer store implementation on wasm, to use database names to distinguish different configurations, and database names comes from `path` section in network configuration, so makes it possible to switch network configurations in the same website
> peer-store, wasm: use `path` as database name in wasm peer-store implementation

- CONTRIBUTING.md
The project link is broken, this PR replaces it with a more general link to the issue tracker.
> fix: replace broken link in `CONTRIBUTING.md`

- network/fuzz/Cargo.toml
- network/fuzz/fuzz_targets/fuzz_addr_manager.rs
- network/fuzz/fuzz_targets/fuzz_peer_store.rs
- network/fuzz/src/lib.rs
make cargo clippy for ckb-network-fuzz happy
- Fix clippy warning in ckb-network-fuzz
Tests 
- Unit test
Side effects
- None
```release-note
```
> ckb-network-fuzz: make cargo clippy happy

- script/src/lib.rs
- script/src/types.rs
- script/src/verify.rs
- script/src/verify/tests/ckb_latest/features_since_v2021.rs
- script/src/verify/tests/ckb_latest/features_since_v2023.rs
- script/src/verify/tests/utils.rs
- tx-pool/src/chunk_process.rs
- verification/src/cache.rs
- verification/src/lib.rs
- verification/src/transaction_verifier.rs
As of now, TransactionSnapshot and TransactionState from ckb-script package are exactly the same. There is no need to keep them both.
Tests 
- Unit test
Side effects
```release-note
```
> refactor: Remove TransactionSnapshot structure

- benches/benches/benchmarks/overall.rs
- chain/src/tests/util.rs
- network/src/network.rs
- network/src/peer_registry.rs
- network/src/peer_store/addr_manager.rs
- network/src/peer_store/peer_store_impl.rs
- network/src/peer_store/types.rs
- network/src/protocols/discovery/mod.rs
- network/src/protocols/feeler.rs
- network/src/protocols/identify/mod.rs
- network/src/services/outbound_peer.rs
- network/src/tests/mod.rs
- network/src/tests/peer_store.rs
- rpc/src/tests/setup.rs
- sync/src/relayer/tests/helper.rs
- test/src/net.rs
- util/launcher/src/lib.rs
- util/light-client-protocol-server/src/tests/utils/chain.rs
1. peer store only retains TCP multiaddr
2. peer store support store DNS
3. `OutboundPeerService` specifying the transport type, In wasm, user can specify ws or wss for dial operation
4. identify/discovery allows no tcp/ip multiaddr spread
5. public_listens allow no tcp/ip multiaddr
6. Keep connected nodes up to date in the peer store
7. Fix feeler flags fetch fail
Tests
- Unit test
```release-note
```
> Peer store optimization

- rpc/src/module/net.rs
`get_peers` RPC returned `RemoteAddress.addresses` shouldn't contains duplicate `MultiAddr`.
- In `NetRpcImpl::get_peers`, use `HashSet` to remove duplicate `MultiAddr`.
Tests 
- Unit test
Side effects
- None
```release-note
```
> `NetRpcImpl::get_peers` return `Remoteaddress.addresses` dedup

- Cargo.lock
- Upgrade openssl from 0.10.68 to 0.10.70, fix  https://rustsec.org/advisories/RUSTSEC-2025-0004
Tests 
- Unit test
Side effects
- None
```release-note
```
> Upgrade openssl from 0.10.68 to 0.10.70, fix  https://rustsec.org/advisories/RUSTSEC-2025-0004

- Cargo.lock
- network/src/network.rs
- network/src/peer_store/peer_store_impl.rs
- network/src/protocols/tests/mod.rs
- network/src/services/outbound_peer.rs
- network/src/tests/peer_store.rs
outbound service impl filter with transport：
TCP -> All
WS -> IP and DNS
WSS -> Only DNS
Tests 
- Unit test
```release-note
```
> feat: impl filter with transport

- network/src/network.rs
- network/src/peer_store/peer_store_impl.rs
- network/src/protocols/identify/mod.rs
Mark DNS address connected time on peer store, allow it to spread across multiple nodes. 
The transmission path is as follows:
- DNS address public with identify protocol https://github.com/nervosnetwork/ckb/blob/b44d2d2729cee98ccab8db83fddcd235619db145/network/src/protocols/identify/mod.rs#L520-L530
- discovery protocol will random fetch it from peer store when it had connected during last week https://github.com/nervosnetwork/ckb/blob/b44d2d2729cee98ccab8db83fddcd235619db145/network/src/protocols/discovery/mod.rs#L140-L150
- peer store random fetch https://github.com/nervosnetwork/ckb/blob/b44d2d2729cee98ccab8db83fddcd235619db145/network/src/peer_store/peer_store_impl.rs#L206-L210
Tests
- Unit test
```release-note
Title Only: Include only the PR title in the release …
```
> feat: mark dns address connected time on peer store

- devtools/git/merge-master.sh
Problem Summary: util/constant/src/latest_assume_valid_target.rs should be merged from master into develop
What's Changed: include util/constant/src/latest_assume_valid_target.rs when merging master in the script devtools/git/merge-master.sh
Tests 
```release-note
```
> chore: include latest_assume_valid_target.rs when merging master

- rpc/README.md
- rpc/src/module/chain.rs
- util/constant/src/hardfork/mainnet.rs
Planned CKB Edition Meepo (2024) activation on the Mainnet. Binary version 0.200 scheduled for release around Mar. 1.
```release-note
```
> chore: 2nd hardfork mainnet activation params

- network/src/network.rs
fix
```bash
error[E0560]: struct `NetworkState` has no field named `pending_dns_addrs`
--> network/src/network.rs:186:13
|
186 |             pending_dns_addrs: RwLock::new(HashMap::default()),
|             ^^^^^^^^^^^^^^^^^ `NetworkState` does not have this field
|
= note: all struct fields are already assigned
```
introduced from https://github.com/nervosnetwork/ckb/pull/4812
Tests 
- Unit test
```release-note
```
> fix: wasm build

- script/src/lib.rs
- script/src/types.rs
The ckb-debugger needs to use this data structure.
Make it public.
Tests 
Side effects
```release-note
```
> chore(script): make DataLocation public

- script/src/lib.rs
- script/src/scheduler.rs
- script/src/types.rs
The current approach completely prohibits the possibility of receiving external arguments to initialize the VM stack, which has led to the breakdown of some important functions in the ckb-debugger.
Use an enumeration type to represent the type of the parameter. 
- `VmArgs::Reader(u64, u64, u64) == Some((u64, u64, u64))`
- `VmArgs::Vector(vec![]) == None`
- `VmArgs::Vector(vec!["a", "b", "c"]) : The new method for ckb-debugger`
Tests 
```release-note
```
> script: refactored vmargs to accept a vector array

- network/src/network.rs
- network/src/peer_store/peer_store_db.rs
This PR want to fix: `make wasn` error on latest develop branch:
```bash
error[E0521]: borrowed data escapes outside of closure
--> network/src/services/dump_peer_store.rs:43:24
|
42 |         self.network_state.with_peer_store_mut(|peer_store| {
|                                                 ----------
|                                                 |
|                                                 `peer_store` is a reference that is only valid in the closure body
|                                                 has type `&'1 mut PeerStore`
43 |             let task = peer_store.dump_to_idb(path);
|                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|                        |
|                        `peer_store` escapes the closure body here
|                        argument …
```
> wasm: fix `make wasm` build failed by `error[E0521]: borrowed data escapes outside of closure`

- util/constant/src/default_assume_valid_target.rs
- util/constant/src/latest_assume_valid_target.rs
After v0.200.0 released, `make clippy` failed on develop since we merged master into develop: https://github.com/nervosnetwork/ckb/commit/33446e83c28e1c6f09d94de5de7efefe26dfcff5
```bash
Checking petgraph v0.6.5
error: empty line after doc comment
--> util/constant/src/default_assume_valid_target.rs:1:1
|
1 | / /// Get default assume valid targets
2 | |
| |_^
3 |   /// mainnet
4 |   pub mod mainnet {
|   --------------- the comment documents this module
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#empty_line_after_doc_comments
= note: `-D clippy::empty-line-after-doc-comments` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::empty_line_after_doc_comments)]`
= help: if the empty line is unintentional remove …
```
> clippy: fix `make clippy` failed on develop

- Cargo.lock
- Execute `cargo update`
```bash
ckb on  exec/cargo-update is 📦 v0.201.0-pre via 🦀 v1.85.0 via ❄️  impure (nix-shell) on ☁️
❯ cargo update
Updating crates.io index
Locking 198 packages to latest Rust 1.85.0 compatible versions
Updating allocator-api2 v0.2.18 -> v0.2.21
Updating anstream v0.6.15 -> v0.6.18
Updating anstyle v1.0.8 -> v1.0.10
Updating anstyle-parse v0.2.5 -> v0.2.6
Updating anstyle-query v1.1.1 -> v1.1.2
Updating anstyle-wincon v3.0.4 -> v3.0.7
Updating anyhow v1.0.94 -> v1.0.97
Updating async-trait v0.1.83 -> v0.1.87
Updating axum v0.7.7 -> v0.7.9 (available: v0.8.1)
Updating bit-set v0.5.3 -> v0.8.0
Adding bit-vec v0.8.0
Updating bitcoin-io v0.1.2 -> v0.1.3
Updating bitflags v2.6.0 -> v2.9.0
Updating bstr v1.10.0 -> v1.11.3
Updating bumpalo v3.16.0 -> v3.17.0
Updating …
```
> chore: execute `cargo update`

- network/src/network.rs
- network/src/protocols/tests/mod.rs
when the user configuration is wrong, exit and output log(The wasm side code is not modified, because wasm currently has no listen, and this field configuration is meaningless)
Tests
- Unit test
```release-note
```
> chore: when the user configuration is wrong, exit and output log

- script/src/lib.rs
- script/src/scheduler.rs
- script/src/syscalls/debugger.rs
- script/src/syscalls/generator.rs
- script/src/types.rs
- script/src/verify.rs
- script/src/verify/tests/ckb_latest/features_since_v2021.rs
- script/src/verify/tests/utils.rs
- verification/src/transaction_verifier.rs
This enables ckb-script to be used in more environments. I do remember that there is discussion about moving ckb-script out of CKB for more usages. However, I implemented this change due to 2 factors:
* The change is not so big
* We had similar APIs for debug printer as well
In a later time, we can re-evaluate the necessity to move ckb-script out of CKB completely.
Tests 
- Unit test
Side effects
```release-note
Title …
```
> feat: Syscall generator shall be customizable

- Cargo.lock
- Cargo.toml
- script/src/lib.rs
- script/src/scheduler.rs
- script/src/syscalls/generator.rs
- script/src/syscalls/spawn.rs
- script/src/types.rs
- script/src/verify.rs
- script/src/verify/tests/utils.rs
- verification/src/transaction_verifier.rs
Tests 
- Unit test
Side effects
```release-note
```
> refactor: ckb-script shall only rely on DefaultMachineRunner trait

- devtools/release/bump.sh
- devtools/release/release-pkg.sh
Problem Summary: #4818 breaks some release scripts
-   fix `bump.sh`
-   fix `release-pkg.sh`
Tests 
-   No code ci-runs-only: [ quick_checks,linters ]
```release-note
```
> fix release scripts

- Cargo.lock
- Cargo.toml
- network/src/network.rs
close #4867 
changelog：
```
Features
Upgrade to Rust 2024 edition(#402)
Drop async-runtime,async-timer features(#406)
Support session init from user(#405)
Support proxy and onion(#392)
```
Tests
- Unit test
```release-note
```
> chore: upgrade p2p

- util/dao/src/lib.rs
Problem Summary: `DaoCalculator` requires a generic argument `DL` to implement `EpochProvider`, but some functions (such as `transaction_fee`) are not using `EpochProvider`. This makes it impossible to use DaoCalculator in light client, since there is no `EpochProvider` in light client
This PR splits functions in `DaoCalculator` that doesn't use `EpochProvider` into an individual `impl` block which doesn't require `DL` to implement `EpochProvider`
N/A
N/A
Title Only
> Update `DaoCalculator` so it can be used in light client

- chain/src/init.rs
- chain/src/lib.rs
- chain/src/tests/basic.rs
- chain/src/tests/block_assembler.rs
- chain/src/tests/delay_verify.rs
- chain/src/tests/dep_cell.rs
- chain/src/tests/find_fork.rs
- chain/src/tests/non_contextual_block_txs_verify.rs
- chain/src/tests/reward.rs
- chain/src/tests/truncate.rs
- chain/src/tests/uncle.rs
- chain/src/tests/util.rs
- rpc/src/tests/setup.rs
- sync/Cargo.toml
- sync/src/relayer/tests/block_proposal_process.rs
- sync/src/relayer/tests/block_transactions_process.rs
- sync/src/relayer/tests/compact_block_process.rs
- sync/src/relayer/tests/get_block_proposal_process.rs
- sync/src/relayer/tests/get_transactions_process.rs
- sync/src/relayer/tests/helper.rs
- sync/src/relayer/tests/reconstruct_block.rs
- sync/src/tests/mod.rs
- sync/src/tests/sync_shared.rs
- sync/src/tests/synchronizer/basic_sync.rs
- sync/src/tests/synchronizer/functions.rs
- sync/src/tests/util.rs
- util/light-client-protocol-server/src/tests/utils/chain.rs
- verification/contextual/src/tests/contextual_block_verifier.rs
- verification/contextual/src/tests/uncle_verifier.rs
Some of our sync tests have been slightly unstable: they pass in 95%+ of the time, however from time to time, they would break, if we try to rerun them in CI, in most cases those tests would then pass.
I managed to dig into those tests with a little help from rr, it seems that 2 timings would affect those unstable tests:
1. When a test finishes, C++'s destructors decide to destruct rocksdb's global Timer structure.
2. When all the threads spawned by ChainService terminates, Rust decides to drop ChainService. However, a RocksDB instance is buried deep in ChainService. When the RocksDB instance is destructed, C++ code would eventually run Timer::Cancel on the global Timer structure.
If timing 2 happens before timing 1, everything is fine, the test will pass. However from time to time, …
> test: Attempted fixes on unstable tests

- .github/dependabot.yml
This PR want to config dependabot group multiple PR into one PR. 
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates
- https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#groups--
- Config dependabot.yml group multiple PRs into one PR
Tests 
Side effects
- None
```release-note
```
> Config `Dependabot` group multiple PRs into one PR

- .github/workflows/dependabot-prs.yml
This PR want dependabot generated PR add crates update info
https://github.com/dependabot/fetch-metadata
Tests 
Side effects
- None
```release-note
```
> CI: let dependabot PR add fetch metadata

- Makefile
- devtools/ci/ci_main.sh
- devtools/windows/make.ps1
- add `--locked` for all `cargo build`
Tests 
- Unit test
Side effects
- None
```release-note
```
> CI: add `--locked` for cargo build
