Makefile
```
↪  make stats                                                                                                                                         Wed Nov 28 17:51:55 CST 2018
cargo-count v0.2.4
Gathering information...
Language    Files  Lines   Blanks  Comments  Code    Unsafe (%)
--------    -----  -----   ------  --------  ----    ----------
TOML        29     551     48      0         503
Rust        150    26,147  3,017   789       22,341
HTML        163    21,958  846     0         21,112
CSS         4      6,850   936     46        5,868
JavaScript  9      3,076   534     381       2,151
Shell       2      11      3       4         4
Ruby        1      109     6       1         102
--------    -----  -----   ------  --------  ----    ----------
Totals:              358 …
```
=> chore: add a make task `make stats` for counting lines of code

Cargo.lock, chain/Cargo.toml, miner/Cargo.toml, network/src/discovery_service.rs, network/src/lib.rs, network/src/network_config.rs, pool/Cargo.toml, pow/Cargo.toml, protocol/Cargo.toml, shared/Cargo.toml, sync/Cargo.toml, util/Cargo.toml, util/crypto/Cargo.toml, util/instrument/Cargo.toml, util/logger/Cargo.toml
=> chore: upgrade outdated deps

nodes_template/default.json
127.0.0.01 is accessible but seems to have a typo.
=> fix: fix rpc_url

chain/src/chain.rs, network/src/network.rs, sync/src/relayer/mod.rs, sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/get_headers_process.rs, sync/src/synchronizer/headers_process.rs, sync/src/synchronizer/mod.rs
* fix: unchecked subtract overflow
* turn off `kad` temporarily
* fix debug log format
=> fix: unchecked subtract overflow

rpc/doc.md, rpc/src/integration_test.rs, rpc/src/server.rs, spec/src/lib.rs, src/cli/run_impl.rs
side change:
1. move local_node_id from integration_test to network 
2. chain spec document fix
=> docs: rpc api document

Cargo.lock, script/src/lib.rs, script/src/syscalls/load_cell.rs, script/src/syscalls/load_cell_by_field.rs, script/src/syscalls/load_input_by_field.rs, script/src/syscalls/mod.rs, script/src/verify.rs, spec/Cargo.toml, spec/src/lib.rs
This PR includes the following changes:
* feat: add dep cell loading support in syscalls
* feat: add DATA_HASH field type in Load Cell By Field
* refactor: use serialized flatbuffer format in referenced cell, this enables us to add signed args in common cells, while previously we can only embed script binary part.
=> VM Changes

network/src/memory_peer_store.rs, network/src/network.rs, network/src/network_service.rs, network/src/outbound_peer_service.rs, network/src/peer_store.rs, network/src/peers_registry.rs, network/src/tests/peers_registry.rs, sync/src/synchronizer/mod.rs
Actually, we don‘t need so many boxes.
@jjyr
=> refactor: get rid of redundant box

README.md
=> docs: update README for using a simple shell command to modify the config file

spec/src/consensus.rs
https://github.com/nervosnetwork/ckb/issues/54
=> chore: add cellbase maturity

chain/src/chain.rs, core/src/cell.rs, core/src/error.rs, core/src/transaction.rs, pool/src/tests/pool.rs, pool/src/txs_pool/pool.rs, pool/src/txs_pool/types.rs, protocol/src/builder.rs, protocol/src/convert.rs, protocol/src/protocol.fbs, protocol/src/protocol_generated.rs, rpc/doc.md, rpc/src/module/chain.rs, rpc/src/types.rs, script/src/syscalls/fetch_script_hash.rs, script/src/syscalls/load_cell_by_field.rs, script/src/syscalls/mod.rs, script/src/verify.rs, shared/src/shared.rs, verification/src/block_verifier.rs, verification/src/error.rs, verification/src/tests/transaction_verifier.rs, verification/src/transaction_verifier.rs
https://github.com/nervosnetwork/mruby-contracts/pull/3
https://github.com/nervosnetwork/ckb-demo-ruby-sdk/pull/27
=> refactor: several rename

Cargo.lock, core/src/header.rs, core/src/script.rs, core/src/transaction.rs, core/src/uncle.rs, pow/src/clicker.rs, rpc/Cargo.toml, rpc/doc.md, rpc/src/module/chain.rs, rpc/src/module/pool.rs, rpc/src/server.rs, rpc/src/types.rs, rpc/src/types/blockchain.rs, rpc/src/types/bytes.rs, rpc/src/types/proposal_short_id.rs, rpc/src/types/response.rs, script/Cargo.toml, script/src/verify.rs, util/crypto/Cargo.toml
=> define jsonrpc types

Cargo.lock, rpc/src/config.rs
=> feat: enum config

protocol/src/builder.rs, protocol/src/protocol.fbs, protocol/src/protocol_generated.rs, src/cli/run_impl.rs, sync/src/lib.rs, sync/src/net_time_checker.rs
=> feat: collect clock time offset from network peers

network/Cargo.toml
https://github.com/nervosnetwork/ckb/issues/193
=> chore: bump ring from 0.12 to 0.13

Cargo.lock, util/crypto/Cargo.toml, util/crypto/src/secp/generator.rs, util/crypto/src/secp/mod.rs, util/crypto/src/secp/privkey.rs, util/crypto/src/secp/pubkey.rs, util/crypto/src/secp/signature.rs
=> Upgrade secp256k1

Cargo.lock, util/crypto/Cargo.toml, util/crypto/src/secp/generator.rs, util/crypto/src/secp/mod.rs, util/crypto/src/secp/privkey.rs, util/crypto/src/secp/pubkey.rs, util/crypto/src/secp/signature.rs
Reverts nervosnetwork/ckb#242 since it breaks Linux
=> Revert "Upgrade secp256k1"

chain/src/chain.rs, chain/src/lib.rs, chain/src/tests/basic.rs, chain/src/tests/find_fork.rs, chain/src/tests/mod.rs, chain/src/tests/util.rs, core/src/header.rs, core/src/script.rs, core/src/transaction.rs, pool/src/txs_pool/pool.rs, rpc/Cargo.toml, rpc/src/module/chain.rs, rpc/src/module/miner.rs
fix issue: `get_forks` may push genesis in old_blocks, cause tx_pool infinite loop
=> fix: fork logic

miner/src/client.rs, miner/src/config.rs, miner/src/miner.rs, nodes_template/miner.json, src/cli/miner.rs
Always try to update block_template after submit_block.
NEW CONFIG: block_on_submit control whether miner block on submit_block.
BREAKING CHANGE: miner config poll_interval unit: second -> millisecond
=> fix(miner): uncles in solo mining

Cargo.lock, Makefile, network/src/service/discovery_service.rs, protocol/Cargo.toml, protocol/src/builder.rs, protocol/src/convert.rs, protocol/src/error.rs, protocol/src/lib.rs, sync/src/relayer/block_proposal_process.rs, sync/src/relayer/block_transactions_process.rs, sync/src/relayer/compact_block.rs, sync/src/relayer/compact_block_process.rs, sync/src/relayer/get_block_proposal_process.rs, sync/src/relayer/get_block_transactions_process.rs, sync/src/relayer/mod.rs, sync/src/relayer/transaction_process.rs, sync/src/synchronizer/block_process.rs, sync/src/synchronizer/filter_process.rs, sync/src/synchronizer/get_blocks_process.rs, sync/src/synchronizer/get_headers_process.rs, sync/src/synchronizer/headers_process.rs, sync/src/synchronizer/mod.rs, util/src/lib.rs, util/src/unstable/mod.rs, util/src/unstable/try_convert.rs
Apply clippy lint fallible_impl_from :  https://rust-lang.github.io/rust-clippy/v0.0.212/index.html#fallible_impl_from
=> feat: use TryFrom convert protocol

.travis.yml, Cargo.lock, Cargo.toml, devtools/ci/script.sh, docker/hub/Dockerfile, rpc/src/module/trace.rs, shared/src/tx_pool/trace.rs, src/cli/run_impl.rs, test/Cargo.toml, test/fixtures/nodes_template/default.toml, test/src/main.rs, test/src/node.rs, test/src/rpc.rs, test/src/specs/block_relay.rs, test/src/specs/block_sync.rs, test/src/specs/mining.rs, test/src/specs/mod.rs, test/src/specs/pool.rs, test/src/specs/transaction_relay.rs
addition:
* remove integration tests from root workspace
* fix integration tests logger panic at flush
=> fix: trace rpc

network/src/network.rs, network/src/network_service.rs, rpc/README.md, rpc/src/module/net.rs, test/src/main.rs, test/src/node.rs, test/src/rpc.rs, test/src/specs/block_relay.rs, test/src/specs/block_sync.rs, test/src/specs/mining.rs, test/src/specs/mod.rs, test/src/specs/net.rs, test/src/specs/pool.rs, test/src/specs/transaction_relay.rs, util/jsonrpc-types/src/lib.rs, util/jsonrpc-types/src/net.rs
=> test: add more integration test for new p2p lib

Cargo.lock, Cargo.toml, README.md, nodes_template/default.toml, nodes_template/miner.toml, pow/src/cuckoo.rs, src/cli/miner.rs, src/cli/mod.rs, src/cli/sentry_config.rs, src/main.rs, src/setup.rs, test/fixtures/nodes_template/default.toml, test/src/main.rs, util/logger/src/lib.rs
Enable debug for release profile in `Cargo.toml`
```
[profile.release]
debug = true
```
or via `RUSTFLAGS`
```
RUSTFLAGS=-g cargo build --release
```
```
sentry::integrations::panic::register_panic_handler()
```
```
let sentry = sentry::init(sentry::ClientOptions {
release: Some("foo-bar-baz@1.0.0".into()),
dsn: "https://48c6a88d92e246478e2d53b5917a887c@sentry.io/1422795"
.parse()
.ok(),
..Default::default()
});
if sentry.is_enabled() {
sentry::integrations::panic::register_panic_handler();
}
```
- - - -
- [Getting Started with Rust Error Tracking](https://blog.sentry.io/2018/10/22/getting-started-with-rust-error-tracking)
=> Integrate Sentry

network/src/peer_store/sqlite/db.rs, network/src/peer_store/sqlite/peer_store.rs, network/src/tests/sqlite_peer_store.rs
1. reset peer status
2. remove banned addrs from peer_attemps result
=> fix: reset peer store connection status when setup

Cargo.lock, network/Cargo.toml
Related PR: https://github.com/nervosnetwork/p2p/pull/92
=> fix: Upgrade p2p fix repeat connection bug

protocol/src/protocol_generated_verifier.rs
Refs https://github.com/nervosnetwork/cfb/pull/16
=> fix: flatbuffers vtable `num_fields` overflow

util/jsonrpc-types/src/cell.rs
=> chore: add deserialize for CellWithStatus&CellOutputWithOutPoint

Cargo.lock, protocol/Cargo.toml, rpc/Cargo.toml, script/Cargo.toml, sync/Cargo.toml
=> chore(deps): use flatbuffers crate instead of git repo

.travis.yml, devtools/ci/script.sh, devtools/init/README.md, devtools/init/linux-systemd/README.md, devtools/init/linux-systemd/ckb-miner.service, devtools/init/linux-systemd/ckb.service
- Build binaries
- Include docs, license
Future Tasks:
- Include init scripts for popular operation systems.
=> chore: build release packages in travis

build.rs, util/build-info/src/lib.rs
- rerun build.rs to get latest version info when any file has changed.
- include pre version.
=> chore: ckb version tweaks

.travis.yml, devtools/ci/script.sh
bors is not stable. We'll run the integration test after PR merged to develop
and RC branches.
=> chore: drop bors

docs/run-ckb-with-docker.md
Use the full name `nervos/ckb`.
=> docs: fix docker image name

network/src/peer_store/sqlite/db.rs
=> fix: PeerStore unique constraint failed

util/jsonrpc-types/src/blockchain.rs
close https://github.com/nervosnetwork/ckb/issues/456
=> fix: valid_since use String instead u64 in RPC

Cargo.lock, script/Cargo.toml
This is a hotfix for VM bug fixed at here: nervosnetwork/ckb-vm#47
=> [v0.9.0] hotfix: fix VM hang bug for certain invalid programs

test/src/specs/transaction/depend_tx_in_same_block.rs
=> test: sync call rpc

src/subcommand/prof.rs
resolve #554 and #533 merge issue, which broken CI.
=> fix: resolve merge issue

rpc/README.md, test/src/rpc.rs, test/src/specs/pool.rs, test/src/specs/transaction_relay.rs, util/jsonrpc-types/src/blockchain.rs
1. Add rpc doc
2. Fix integration test
=> fix: integration test

Cargo.lock, db/Cargo.toml, db/src/rocksdb.rs
At startup:
- If database is not existed, create it and write a version into it, then **do as normal**.
- If database is existed, check if it has a version.
- If the database doesn't has a version, **panic with a message**.
- If the database has a version, check if it is matched with current program.
- If match, **do as normal**.
- If not match, check if the database can be migrated automatically.
- If it can be migrated, **do migration**.
- **Panic with a message**.
=> feat: check if the data in database is compatible with the program

miner/src/block_assembler.rs
Reduce memory usage by avoiding tx clone in BlockAssembler
=> chore: avoiding tx clone in BlockAssembler

rpc/src/module/chain.rs
* fix: Return early for non-existent block
* feat: Limit page size of `get_cells_by_lock_hash`
=> fix: Return early for non-existent block

Cargo.lock, network/Cargo.toml, network/src/config.rs, network/src/network.rs
=> chore: upgrade secio

Cargo.lock, network/Cargo.toml, network/src/benches/sqlite_peer_store.rs, network/src/config.rs, network/src/network.rs, network/src/peer_store/sqlite/db.rs, network/src/peer_store/sqlite/peer_store.rs, network/src/protocols/discovery.rs, network/src/services/dns_seeding/seed_record.rs, network/src/tests/peer_registry.rs, network/src/tests/sqlite_peer_store.rs, sync/src/synchronizer/mod.rs
ref: https://github.com/nervosnetwork/p2p/pull/124
=> fix: fix cpu problem

Cargo.lock, benches/Cargo.toml, benches/benches/process_block.rs
Resolve `CapacityOverflow` error in bench code
=> chore: fix bench code

chain/src/chain.rs, rpc/README.md, rpc/src/module/chain.rs, rpc/src/module/miner.rs
- feat: add a new rpc: get_block_by_number
- chore: adjust log to make it better to show chain status
=> feat: add a new rpc: get_block_by_number

test/integration.toml
Fix integration test that gets broken by #642
=> fix: Fix integration test

devtools/ci/script.sh
- Use `make prod` to build release
- Include RPC doc in the package
=> chore: tweak package script

Makefile
run `make` to show help message by default:
TODO: add notes for "Generates Files" recipes
=> chore: format Makefile to show friendly help messages

chain/src/chain.rs, rpc/README.md, rpc/src/module/chain.rs, shared/src/shared.rs, store/src/store.rs, sync/src/relayer/tests/compact_block_process.rs, sync/src/synchronizer/mod.rs, sync/src/tests/relayer.rs, sync/src/tests/synchronizer.rs, sync/src/types.rs, traits/src/chain_provider.rs, verification/src/block_verifier.rs, verification/src/tests/dummy.rs, verification/src/tests/uncle_verifier.rs
* add rpc `get_epoch_by_number`
=> feat: add rpc get_epoch_by_number

.travis.yml, devtools/ci/install.sh, devtools/ci/script.sh
Run fmt and clippy evenly between osx and linux.
=> chore: ci round robin

Cargo.lock, script/Cargo.toml
The new version contains fixes for 2 bugs revealed in comprehensive testing.
=> feat: upgrade CKB VM version

Cargo.lock, network/src/protocols/mod.rs, rpc/src/module/pool.rs, rpc/src/server.rs, shared/Cargo.toml, shared/src/chain_state.rs, shared/src/lib.rs, shared/src/tx_pool_executor.rs, sync/Cargo.toml, sync/src/net_time_checker.rs, sync/src/relayer/block_proposal_process.rs, sync/src/relayer/block_transactions_process.rs, sync/src/relayer/compact_block_process.rs, sync/src/relayer/get_block_proposal_process.rs, sync/src/relayer/get_block_transactions_process.rs, sync/src/relayer/get_transaction_process.rs, sync/src/relayer/mod.rs, sync/src/relayer/tests/compact_block_process.rs, sync/src/relayer/transaction_hash_process.rs, sync/src/relayer/transaction_process.rs, sync/src/synchronizer/mod.rs, sync/src/tests/mod.rs, sync/src/tests/relayer.rs, sync/src/tests/synchronizer.rs, test/src/net.rs
1. reduce chain_state lock time during tx verification
2. async relay verification
=> perf: asynchronized verify relayed txs

resource/ckb.toml, rpc/README.md, rpc/src/config.rs, rpc/src/module/experiment.rs, rpc/src/module/mod.rs, rpc/src/server.rs, shared/src/chain_state.rs, verification/src/lib.rs
* Add rpc `dry_run_transaction`
* Add rpc `_compute_transaction_id`
* Enable Experiment moduel by default
=> feat: add rpc experiment module

Cargo.lock, network/Cargo.toml, network/src/protocols/mod.rs, sync/src/relayer/mod.rs, sync/src/synchronizer/mod.rs, sync/src/tests/mod.rs
Network unlimited buffer size will cause OOM, already fixed in p2p library
=> fix: Update p2p library fix network OOM issue

miner/src/block_assembler.rs, miner/src/miner.rs, rpc/README.md, rpc/json/rpc.json, rpc/src/module/chain.rs, rpc/src/module/miner.rs, rpc/src/module/net.rs, rpc/src/module/pool.rs, rpc/src/module/stats.rs, test/src/node.rs, test/src/specs/tx_pool/pool_resurrect.rs, util/jsonrpc-types/src/block_template.rs, util/jsonrpc-types/src/blockchain.rs, util/jsonrpc-types/src/chain_info.rs, util/jsonrpc-types/src/lib.rs, util/jsonrpc-types/src/net.rs, util/jsonrpc-types/src/pool.rs, util/jsonrpc-types/src/string.rs, util/jsonrpc-types/src/sync.rs, util/occupied-capacity/core/src/units.rs
* Stringify all numbers into string automatically, based on serde
=> feat: stringify numbers

test/src/specs/p2p/disconnect.rs, test/src/specs/relay/transaction_relay.rs
increase the timeout to resolve poor CI server performance issue.
=> chore: fix integration test

Cargo.lock, network/Cargo.toml, network/src/network.rs
=> perf: Upgrade p2p version to alpha 12

devtools/ci/script.sh
Remove the nested integration fold.
=> chore: fix travis fold

core/src/difficulty.rs, pow/src/lib.rs
1. make pow verify logic consistent with resolve
2. rename difficulty convert function
=> refactory: make pow verify logic consistent with resolve

Cargo.lock, network/Cargo.toml, network/src/network.rs, network/src/peer_store.rs, network/src/peer_store/sqlite/peer_store.rs, sync/src/relayer/mod.rs, sync/src/synchronizer/get_blocks_process.rs, sync/src/synchronizer/mod.rs
* upgrade p2p to 0.2.0-alpha.14
* remove peer from peer store when peer id not match
* Rollback sync/relay notify interval
=> fix(deps): upgrade p2p to 0.2.0-alpha.14

chain/src/tests/basic.rs, core/src/cell.rs, core/src/transaction_meta.rs, db/src/rocksdb.rs, script/src/syscalls/mod.rs, script/src/verify.rs, shared/src/cell_set.rs, shared/src/chain_state.rs, shared/src/tx_pool/pending.rs, shared/src/tx_pool/proposed.rs, shared/tx-pool-executor/src/tx_pool_executor.rs, store/src/store.rs, verification/src/contextual_block_verifier.rs, verification/src/error.rs, verification/src/tests/transaction_verifier.rs, verification/src/transaction_verifier.rs
RFC update: https://github.com/nervosnetwork/rfcs/pull/116
=> feat: Transaction since field support epoch-based verification rule

rpc/README.md, rpc/json/rpc.json
fix typo from `than` to `then`
=> docs: update rpc doc

sync/src/synchronizer/mod.rs
rebased to rc/v0.12.0, original PR: https://github.com/nervosnetwork/ckb/pull/761
=> [ᚬrc/v0.12.0] perf: avoiding duplicate block downloading

Cargo.lock, benches/benches/process_block.rs, resource/ckb.toml, script/src/verify.rs, shared/src/shared.rs, src/subcommand/export.rs, src/subcommand/import.rs, src/subcommand/prof.rs, src/subcommand/run.rs, store/Cargo.toml, store/src/lib.rs, store/src/store.rs, util/app-config/Cargo.toml, util/app-config/src/app_config.rs
rebased to rc/v0.12.0, original PR: https://github.com/nervosnetwork/ckb/pull/694
=> [ᚬrc/v0.12.0] perf: change db cache to store cache

Makefile, devtools/ci/script.sh, devtools/doc/rpc.py, rpc/README.md, rpc/json/rpc.json, rpc/src/module/chain.rs
* Return `block_hash` for `get_cells_by_lock_hash`
* Add `make gen-doc` command
BREAKING CHANGE: RPC `get_cells_by_lock_hash` response changed.
=> feat: Live cell block hash

Cargo.lock, network/Cargo.toml
✨ Silky smooth `Ctrl + C` experience ✨
=> [ᚬrc/v0.12.0] fix(deps): Upgrade p2p fix gracefully shutdown network service

resource/specs/dev.toml, resource/specs/testnet.toml, spec/src/consensus.rs, test/integration.toml
BREAKING CHANGE: consensus hard fork
=> [ᚬrylai-testbed] feat: tweak max block cycles limit

Cargo.lock, Cargo.toml, src/main.rs
before: 
duration 13.837705427s txs 8084 tps 621
after:
duration 12.359878473s txs 8084 tps 673
=> [ᚬrylai-testbed] feat: using jemalloc as the global allocator on unix

Cargo.lock, script/Cargo.toml, script/src/verify.rs
NOTE: this is a breaking change since it changes VM behavior.
=> [ᚬrylai-testbed-3] feat: upgrade CKB VM to W^X version

network/src/config.rs, network/src/network.rs, network/src/protocols/discovery.rs, network/src/services/outbound_peer.rs, test/src/net.rs, test/src/specs/mod.rs
* Fix outbound service interval cause network thread CPU 100% bug
* Fix discovery service broadcast local address
=> [ᚬrc/v0.12.0] fix: Outbound peer service and discovery service

devtools/doc/rpc.py, rpc/README.md, rpc/json/rpc.json
=> [ᚬrc/v0.12.0] doc: Group rpc APIs [skip ci]

miner/src/block_assembler.rs, rpc/src/module/miner.rs, test/src/specs/mining/basic.rs
* Use block hash as one of the keys of block template cache
=> [ᚬrylai-testbed] fix: fix block template cache

devtools/doc/rpc.py, rpc/README.md, rpc/json/rpc.json
- Delete trailing spaces
- Indent list with 4 spaces
- Add module title
=> [ᚬrc/v0.12.0] docs: tweak RPC doc markdown style.

Cargo.lock, network/Cargo.toml
upgrade p2p
ref: https://github.com/nervosnetwork/p2p/pull/150
https://github.com/nervosnetwork/p2p/pull/147
=> [ᚬrc/v0.12.0] chore: upgrade p2p

rpc/src/module/chain.rs, rpc/src/module/experiment.rs, rpc/src/module/miner.rs, rpc/src/module/pool.rs, rpc/src/module/test.rs, store/src/store.rs, util/jsonrpc-types/src/block_template.rs, util/jsonrpc-types/src/blockchain.rs, util/jsonrpc-types/src/proposal_short_id.rs
- chore: remove an unnecessary `to_vec`
- chore: remove unnecessary `TryFrom`
=> [ᚬrc/v0.12.0] chore: remove unnecessary code

test/src/main.rs, test/src/specs/sync/mod.rs, test/src/specs/sync/sync_timeout.rs
add an integration test for https://github.com/nervosnetwork/ckb/commit/2a3efc5dd49a3e37ad72c6f4101bd82a59c56e8e
=> test: add integration for sync timeout

script/src/syscalls/load_witness.rs, script/src/syscalls/mod.rs, script/src/verify.rs
NOTE: this is a breaking change.
=> [ᚬrc/v0.12.0] feat: add load witness syscall

docker/hub/Dockerfile, docs/run-ckb-with-docker.md
https://github.com/nervosnetwork/ckb-docker-builder
=> [ᚬrc/v0.12.0] chore(docker): build docker image from nervos/ckb-docker-builder

network/src/services/dns_seeding/mod.rs
=> [ᚬrc/v0.12.0] chore: Remove DNS seeding public key

resource/ckb.toml, test/src/main.rs, test/src/net.rs, test/src/node.rs, test/src/rpc.rs, test/src/specs/mining/basic.rs, test/src/specs/mining/size_limit.rs, test/src/specs/p2p/disconnect.rs, test/src/specs/p2p/discovery.rs, test/src/specs/p2p/malformed_message.rs, test/src/specs/relay/block_relay.rs, test/src/specs/relay/compact_block.rs, test/src/specs/relay/transaction_relay.rs, test/src/specs/sync/block_sync.rs, test/src/specs/sync/chain_forks.rs, test/src/specs/sync/invalid_locator_size.rs, test/src/specs/tx_pool/cellbase_maturity.rs, test/src/specs/tx_pool/depend_tx_in_same_block.rs, test/src/specs/tx_pool/different_txs_with_same_input.rs, test/src/specs/tx_pool/pool_reconcile.rs, test/src/specs/tx_pool/pool_resurrect.rs, test/src/specs/tx_pool/valid_since.rs, test/src/utils.rs
* Refactor RPC client in integration tests
* Add sync block integration tests
=> test: add sync block integration tests

sync/src/synchronizer/mod.rs
* Discard invalid orphan blocks
When accepts a new block, its descendants should be accepted too if valid. So if an error occurs when we try to accept its descendants, the descendants are invalid.
=> fix: Discard invalid orphan blocks

Makefile, docker/hub/Dockerfile, resource/src/template.rs, src/main.rs
- avoid dirty flag in version info
- bind rpc on 0.0.0.0 in docker
- fix docker files permissions
=> [ᚬrylai] fix(docker): fix docker problems found in rylai

.travis.yml, devtools/ci/script.sh, docs/get-ckb.md
- Add tutorial how to build in CentOS
- Static link openssl in Linux packages.
Closes #626
=> [ᚬrylai] chore: better support for CentOS

db/Cargo.toml
It will speed up compilation a bit.
=> chore: close rocksdb features we do not use

Cargo.lock, network/Cargo.toml, network/src/network.rs, network/src/protocols/discovery.rs
* Decrease error log level from warning to debug
* Or send it to sentry
=> chore(network): decrease network error log level

docs/configure.md
=> docs: clarity how to run two connected nodes

chain/src/tests/basic.rs, core/src/extras.rs, util/dao/src/lib.rs
BREAKING CHANGE: it changes the block reward rule
=> feat: revise remainder reward rule

Cargo.lock, Cargo.toml, util/crypto/src/secp/pubkey.rs, util/multisig/Cargo.toml, util/multisig/src/error.rs, util/multisig/src/lib.rs, util/multisig/src/secp256k1.rs
Used in alert system https://github.com/nervosnetwork/ckb/pull/887
=> feat: secp256k1 multisig

Cargo.lock, chain/Cargo.toml, chain/src/chain.rs, core/src/uncle.rs, db/Cargo.toml, miner/Cargo.toml, miner/src/block_assembler.rs, shared/Cargo.toml, shared/src/chain_state.rs, spec/src/consensus.rs, store/Cargo.toml, store/src/lib.rs, store/src/store.rs, sync/Cargo.toml, traits/Cargo.toml, util/app-config/Cargo.toml, util/jsonrpc-types/Cargo.toml, verification/Cargo.toml, verification/src/contextual_block_verifier.rs, verification/src/error.rs, verification/src/lib.rs, verification/src/tests/uncle_verifier.rs, verification/src/transaction_verifier.rs, verification/src/uncles_verifier.rs
1. get rid uncle age limit
2. try include disconnected block as uncle
=> feat: revise uncle rule

.travis.yml, Makefile, devtools/jsonfmt/Cargo.toml, devtools/jsonfmt/src/main.rs, rpc/json/rpc.json
Make sure that users are able to generate the `rpc.json`, if they can build `ckb`。
=> chore(ci): remove dependencies with npm and prettier

sync/src/synchronizer/mod.rs
Rebased to `rc/v0.13.0`
@doitian
=> [ᚬrc/v0.13.0] fix: Sync blocked by protected peer

core/src/transaction.rs, verification/src/error.rs, verification/src/tests/transaction_verifier.rs, verification/src/transaction_verifier.rs
=> feat: add a transaction error `InsufficientCellCapacity`

Cargo.lock, ckb-bin/Cargo.toml, ckb-bin/src/subcommand/init.rs, db/src/rocksdb.rs, resource/ckb.toml, resource/src/lib.rs, resource/src/template.rs, script/Cargo.toml, script/src/lib.rs, script/src/verify.rs, util/app-config/src/app_config.rs, util/hash/Cargo.toml
This PR also updates CKB-VM with the following changes:
* [#64](https://github.com/nervosnetwork/ckb-vm/pull/64) windows support adjustments
=> feat: initial windows support

Cargo.lock
closed #951 
Fix bugs on  kqueue platforms
ref: https://github.com/tokio-rs/mio/blob/master/CHANGELOG.md
=> chore: upgrade mio dependence

.travis.yml, README.md
- 8e5778d3: docs: link version badge to releases page
- b9a09900: docs: add badges for both master/develop branches
- 68ffc8a9: chore(ci): run cov for develop branch
[Click HERE for the preview of `README.md`.](https://github.com/nervosnetwork/ckb/blob/8e5778d367e34bdc6aa937f5180b4b93012dc665/README.md)
=> docs: update badges in README

chain/src/tests/basic.rs, chain/src/tests/delay_verify.rs, chain/src/tests/find_fork.rs, chain/src/tests/util.rs, core/src/block.rs
Just refactor the test in the chain.
=> test: refactor chain test

Cargo.lock, sync/Cargo.toml, sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/mod.rs, sync/src/tests/synchronizer.rs, sync/src/types.rs
It's a backport of PR https://github.com/nervosnetwork/ckb/pull/970
=> [ᚬrc/v0.14.0] perf(sync): Fix get ancestor performance issue

sync/src/relayer/block_proposal_process.rs, sync/src/relayer/get_block_proposal_process.rs, sync/src/relayer/mod.rs, sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/headers_process.rs, sync/src/synchronizer/mod.rs, sync/src/types.rs
* feat: Avoid locking a long time
---
#979 has closed by bot automatically and I cannot find the way to re-open it :(
So here re-submit #979 here.
=> feat: Wrap lock methods

miner/src/miner.rs, miner/src/worker/cuckoo_simple.rs, miner/src/worker/mod.rs
update miner status output:
```
Found! #197 42c12fefe7fddad6a1adc5401b2be9bb416516e139011e37c39b23bd5920d684
Found! #198 bd2b4fa3055dd069773235f9c33d1a008a5df0ec4a5c7a8de81f384a370ed00a
Found! #199 f323842256389e04534a8928c1cc415320a94f843fb879c6955a46601c99b6ba
CuckooSimple-Worker-0 ⠖ [00:01:38] gps:    141.652 / cycles found:       1188
CuckooSimple-Worker-1 ⠐ [00:01:38] gps:    143.091 / cycles found:       1253
Total seals found:   3
```
=> [ᚬrc/v0.14.0] chore: print found seal information

core/src/cell.rs
The code coverage did not cover https://github.com/nervosnetwork/ckb/blob/develop/core/src/cell.rs#L390-L409 before.
And the `HeaderMemoryDb` was ​redundant and useless.
=> test: refactor cell test

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
[[Rendered view of the new template]](https://github.com/nervosnetwork/ckb/blob/b585413863351059c66fef827d10e1ff787d0917/.github/ISSUE_TEMPLATE/bug_report.md)
=> chore: simplify the issue template

network/src/peer_store/types.rs
=> fix: peer_store time calculation overflow

docs/get-ckb.md
[[Rendered View]](https://github.com/nervosnetwork/ckb/blob/3b3113dc3d4ad204501382b3ef0da85d5631b031/docs/get-ckb.md)
=> docs: system requirements

core/src/block.rs, miner/src/block_assembler.rs, miner/src/client.rs, protocol/src/convert.rs, test/src/node.rs, test/src/specs/mining/basic.rs, test/src/utils.rs, util/jsonrpc-types/src/blockchain.rs, verification/src/tests/uncle_verifier.rs
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3cc77c2bf9357b5328b9627d0f2ff6ef
=> chore: try_into to into

miner/src/block_assembler.rs, miner/src/client.rs, miner/src/lib.rs, test/src/node.rs, util/jsonrpc-types/src/block_template.rs
wait for https://github.com/nervosnetwork/ckb/pull/1049
=> Block template from

verification/src/block_verifier.rs, verification/src/tests/block_verifier.rs, verification/src/tests/mod.rs, verification/src/tests/uncle_verifier.rs, verification/src/uncles_verifier.rs
=> test: refactor some verification tests and add more tests

core/src/transaction.rs, verification/src/tests/transaction_verifier.rs, verification/src/transaction_verifier.rs
refactor tx verification and add more test cases.
=> test: add more transaction verification test case

network/src/network.rs, network/src/protocols/discovery.rs, network/src/protocols/mod.rs, network/src/protocols/test.rs
1. fix discovery miss impl on add_new_addr 
2. fix discovery quick exit on add_new_addrs 
3. add test for protocols
=> test: Add test for protocols

chain/src/chain.rs, chain/src/tests/basic.rs, chain/src/tests/delay_verify.rs, chain/src/tests/util.rs, core/src/block.rs, core/src/transaction.rs, shared/src/cell_set.rs, shared/src/chain_state.rs, shared/src/tx_pool/orphan.rs, shared/src/tx_pool/proposed.rs, shared/tx-pool-executor/src/tx_pool_executor.rs, test/src/utils.rs, util/jsonrpc-types/src/blockchain.rs, util/test-chain-utils/src/lib.rs, util/test-chain-utils/src/macros.rs
sync: https://github.com/nervosnetwork/ckb/pull/1076
=> fix: cellset consistency

test/src/specs/indexer/basic.rs
it's introduced in https://github.com/nervosnetwork/ckb/pull/1080/commits/8187bf343e77708bf0e4cdbfce2c8259528fa4d0#diff-19087ccf8fa525e3f2ead4951d3cf0b2R353
=> test: fix integration test for genesis block indexer

sync/src/types.rs
This PR is trying to resolve ibd peer timeout slow switching issue for some special case, e.x. node resume after hibernation, it's a performance optimization also.
bitcoin reference: https://github.com/bitcoin/bitcoin/blob/0b68fca700713e8e4c843c982b6047dc04410bc0/src/validation.cpp#L1027
=> fix: ibd should remain false once returned false

sync/src/synchronizer/headers_process.rs
=> fix: fix debug log state error

sync/src/synchronizer/mod.rs, sync/src/types.rs
1. fix protect node count 
2. fix header sync eviction condition
=> fix: fix sync logic

sync/src/relayer/compact_block_process.rs, sync/src/synchronizer/block_fetcher.rs, sync/src/types.rs
resolve similar bug as https://github.com/nervosnetwork/ckb/pull/1100 and refactor the previous fix to method.
=> fix: total difficulty comparison should include hash

Cargo.lock, util/occupied-capacity/core/src/lib.rs, util/occupied-capacity/src/lib.rs, util/reward-calculator/Cargo.toml, util/reward-calculator/src/lib.rs
Why I put the two commits in the same PR?
The reason is that without the refactoring, the last test case would be more complicated than now, it would need more data to craft.
There is no cache in store, we should avoid DB query. Later I will try to add some cache in the store or somewhere.
=> chore: reward refactor and test

network/src/protocols/test.rs, test/README.md, test/src/main.rs, test/src/node.rs, test/src/specs/alert/alert_propagation.rs, test/src/specs/indexer/basic.rs, test/src/specs/indexer/genesis_issued_cells.rs, test/src/specs/mining/basic.rs, test/src/specs/mining/bootstrap.rs, test/src/specs/mining/size_limit.rs, test/src/specs/p2p/discovery.rs, test/src/specs/p2p/malformed_message.rs, test/src/specs/relay/block_relay.rs, test/src/specs/relay/compact_block.rs, test/src/specs/relay/mod.rs, test/src/specs/relay/transaction_relay.rs, test/src/specs/sync/block_sync.rs, test/src/specs/sync/chain_forks.rs, test/src/specs/sync/invalid_locator_size.rs, test/src/specs/sync/mod.rs, test/src/specs/sync/sync_timeout.rs, test/src/specs/tx_pool/cellbase_maturity.rs, test/src/specs/tx_pool/depend_tx_in_same_block.rs, test/src/specs/tx_pool/different_txs_with_same_input.rs, test/src/specs/tx_pool/limit.rs, test/src/specs/tx_pool/pool_reconcile.rs, test/src/specs/tx_pool/pool_resurrect.rs, test/src/specs/tx_pool/valid_since.rs, test/src/utils.rs
integration test refactoring and fix integration test for #1137
=> test: integration test refactoring

benches/benches/process_block.rs, chain/src/chain.rs, chain/src/tests/basic.rs, store/src/store.rs, sync/src/relayer/compact_block_process.rs, sync/src/synchronizer/block_process.rs, sync/src/synchronizer/get_blocks_process.rs, sync/src/synchronizer/headers_process.rs, sync/src/synchronizer/mod.rs
https://github.com/nervosnetwork/ckb/pull/1195
* fix fetch invalid block
* fix response invalid block
* fix repeat process block overwrite block ext
* fix: compact block filter
=> bundle fix port

network/src/services/outbound_peer.rs
Reserved only do nothing except for connect all reserved peers
=> fix: reserved only do nothing except for connect all reserved peers

sync/src/synchronizer/mod.rs, sync/src/types.rs
Backports the following commits to rc/v0.15.z:
- fix: fix sync logic (#1103)
=> [ᚬrc/v0.15.z] fix: fix sync logic

sync/src/synchronizer/headers_process.rs
Backports the following commits to rc/v0.15.z:
- fix: fix debug log state error (#1101)
=> [ᚬrc/v0.15.z] fix: fix debug log state error

sync/src/relayer/mod.rs
Backports the following commits to rc/v0.15.z:
- fix: resolve fresh proposal txs checking bug (#1139)
=> [ᚬrc/v0.15.z] fix: resolve fresh proposal txs checking bug

test/src/specs/tx_pool/valid_since.rs
ref: https://github.com/nervosnetwork/ckb/pull/1150
=> test: Fix valid_since test

Cargo.lock, chain/src/tests/reward.rs, chain/src/tests/util.rs, rpc/src/test.rs, script/src/verify.rs, shared/src/cell_set.rs, shared/tx-pool-executor/src/tx_pool_executor.rs, sync/src/relayer/tests/reconstruct_block.rs, sync/src/tests/mod.rs, sync/src/tests/sync_shared_state.rs, sync/src/tests/synchronizer.rs, sync/src/tests/util.rs, sync/src/types.rs, test/src/main.rs, test/src/rpc.rs, test/src/specs/relay/compact_block.rs, test/src/utils.rs, util/test-chain-utils/Cargo.toml, util/test-chain-utils/src/chain.rs, util/test-chain-utils/src/lib.rs, verification/src/tests/commit_verifier.rs
* test: SyncSharedState insert_new_block
* integration-test: Relay cmpblock which difficulty lt shared best known
* fix: Correct return value of insert_new_block
=> test: insert_new_block

miner/src/worker/cuckoo_simple.rs, miner/src/worker/dummy.rs, miner/src/worker/mod.rs
Avoid same nonces for different threads.
=> feat: partition nonce for miners who use multi-threads

network/src/network.rs
we shouldn't call peer_registry `remove_peer ` before session was closed, it will be removed in disconnect event.
=> fix: resolve rpc `remove_node` and network `report_peer` bug

Cargo.lock, network/Cargo.toml, network/src/protocols/mod.rs, sync/src/relayer/block_proposal_process.rs, sync/src/relayer/transaction_process.rs, sync/src/synchronizer/mod.rs, sync/src/tests/mod.rs
According performance test use `tokio_threadpool::blocking` to handle heavy future task can improve TPS.
=> feat: Use tokio_threadpool::blocking to handle heavy future task

network/src/config.rs, network/src/network.rs, network/src/peer.rs, network/src/peer_registry.rs, network/src/protocols/test.rs, network/src/services/outbound_peer.rs, network/src/tests/peer_registry.rs, resource/ckb.toml, sync/src/synchronizer/headers_process.rs, sync/src/synchronizer/mod.rs, sync/src/types.rs, test/src/net.rs
1. Enable IBD with whitelist peers
2. Rename reserved to whitelist
Breaking changes:
In ckb.toml:
```diff
-reserved_peers = []
-reserved_only = false
+whitelist_peers = []
+whitelist_only = false
```
=> feat: IBD with whitelist

.travis.yml, Makefile, resource/ckb.toml, test/Cargo.toml, test/README.md, test/src/main.rs
Limit to only Linux platform and max running time to 30 minutes.
=> test: enalbe interation for PR

test/src/main.rs, test/src/node.rs, test/src/rpc.rs, test/src/specs/sync/chain_forks.rs, test/src/specs/sync/invalid_block.rs
waiting for https://github.com/nervosnetwork/ckb/pull/1217
=> test: re-enable chain fork integration test

network/src/protocols/test.rs, sync/src/tests/inflight_blocks.rs
1. Fix feeler protocol test random behavior, sleep can't eliminate randomness
2. Comparison with HashSet
=> test: Fix test

sync/src/block_status.rs, sync/src/synchronizer/get_blocks_process.rs, sync/src/tests/sync_shared_state.rs, sync/src/tests/util.rs, sync/src/types.rs
* feat: Add `BLOCK_VALID` status.
* test: Add test to check the block status after switching forks
=> feat: cache BLOCK_INVALID/BLOCK_VALID status

Cargo.lock, sync/Cargo.toml, sync/src/types.rs
https://blog.rust-lang.org/2019/07/04/Rust-1.36.0.html#a-new-hashmapk,-v%3E-implementation
=> chore: remove hashbrown

test/src/main.rs, test/src/node.rs
* Run with --ba-advanced option, enable the default miner
=> [HOLD] fix: Run integration with --ba-advanced

.travis.yml
Skip the integration test when the last commit is a merge created by bors.
=> chore(ci): do not repeat integration test in develop

sync/src/relayer/compact_block_process.rs, sync/src/relayer/error.rs, sync/src/relayer/tests/compact_block_process.rs
https://github.com/cryptape/ckb-internal/issues/1150
=> fix: shoud not reject not better compact block

Cargo.lock, sync/Cargo.toml, sync/src/relayer/tests/helper.rs
https://github.com/cryptape/ckb-internal/issues/1202
=> test: re-export p2p from network

rpc/src/module/test.rs
* Add a RPC interface `broadcast_transaction`, which does not verify the given transaction, and broadcast to other peers directly. Use for testing only.
=> feat: Add RPC broadcast_transaction

chain/src/tests/reward.rs, core/src/lib.rs, core/src/reward.rs, miner/src/block_assembler.rs, rpc/README.md, rpc/json/rpc.json, rpc/src/module/chain.rs, rpc/src/test.rs, shared/src/shared.rs, sync/src/synchronizer/mod.rs, sync/src/tests/synchronizer.rs, sync/src/tests/util.rs, traits/src/chain_provider.rs, util/jsonrpc-types/src/blockchain.rs, util/jsonrpc-types/src/lib.rs, util/reward-calculator/src/lib.rs, verification/src/contextual_block_verifier.rs
Backport https://github.com/nervosnetwork/ckb/pull/1297
=> [ᚬrc/v0.17] feature: add get_block_finalized_reward_info rpc

protocol/src/builder.rs, protocol/src/protocol.fbs, protocol/src/protocol_generated.rs, protocol/src/protocol_generated_verifier.rs, sync/src/synchronizer/get_headers_process.rs, sync/src/synchronizer/in_ibd_process.rs, sync/src/synchronizer/mod.rs, test/src/main.rs, test/src/node.rs, test/src/specs/sync/ibd_process.rs, test/src/specs/sync/mod.rs
Add `in ibd` message to improve the flexibility of ibd
=> feat: add in ibd message to improve the flexibility of ibd

protocol/src/builder.rs, protocol/src/protocol.fbs, protocol/src/protocol_generated.rs, protocol/src/protocol_generated_verifier.rs, sync/src/relayer/block_proposal_process.rs, sync/src/relayer/compact_block.rs, sync/src/relayer/get_block_proposal_process.rs, sync/src/relayer/mod.rs
refactor: use block_hash instead of block_number in get_block_proposal message
=> refactor: use block_hash 

rpc/README.md, rpc/json/rpc.json, rpc/src/test.rs
* Make it more easy to modified when APIs changed
* Generate document in JSON format when the test fails
* Print the all errors at the end
=> test: Refactor rpc test

ckb-bin/src/subcommand/run.rs, network/src/network.rs, network/src/peer.rs, network/src/protocols/identify.rs, network/src/protocols/test.rs, protocol/src/protocol.fbs, protocol/src/protocol_generated.rs, protocol/src/protocol_generated_verifier.rs, rpc/src/test.rs, test/src/net.rs
BREAKING CHANGE: identify message add one field
=> fix: fix get peers rpc version field

Cargo.lock, chain/src/chain.rs, miner/src/block_assembler.rs, miner/src/miner.rs, notify/src/lib.rs
release note：
-  Fix a bug in reference counting.
- Optimize recv_timeout().
- Add Select::remove().
- Various small improvements, code cleanup, more tests.
=> chore: upgrade crossbeam channel

sync/src/relayer/block_proposal_process.rs, sync/src/relayer/tests/block_proposal_process.rs, sync/src/relayer/tests/compact_block_process.rs, sync/src/relayer/tests/mod.rs, sync/src/types.rs
test: assert request proposal for compact block process
test: block proposal process test
=> test: block proposal process test

resource/ckb.toml, shared/src/chain_state.rs, shared/src/tx_pool/pool.rs, shared/src/tx_pool/types.rs, sync/src/relayer/get_block_proposal_process.rs, sync/src/relayer/mod.rs
=> perf: add committed txs cache for compact block reconstruction

test/src/lib.rs, test/src/main.rs, test/src/specs/alert/alert_propagation.rs, test/src/specs/indexer/basic.rs, test/src/specs/indexer/genesis_issued_cells.rs, test/src/specs/mining/basic.rs, test/src/specs/mining/bootstrap.rs, test/src/specs/mining/size_limit.rs, test/src/specs/mod.rs, test/src/specs/p2p/disconnect.rs, test/src/specs/p2p/discovery.rs, test/src/specs/p2p/malformed_message.rs, test/src/specs/relay/block_relay.rs, test/src/specs/relay/compact_block.rs, test/src/specs/relay/transaction_relay.rs, test/src/specs/sync/block_sync.rs, test/src/specs/sync/chain_forks.rs, test/src/specs/sync/ibd_process.rs, test/src/specs/sync/invalid_block.rs, test/src/specs/sync/invalid_locator_size.rs, test/src/specs/sync/sync_timeout.rs, test/src/specs/tx_pool/cellbase_maturity.rs, test/src/specs/tx_pool/depend_tx_in_same_block.rs, test/src/specs/tx_pool/different_txs_with_same_input.rs, test/src/specs/tx_pool/limit.rs, test/src/specs/tx_pool/pool_reconcile.rs, test/src/specs/tx_pool/pool_resurrect.rs, test/src/specs/tx_pool/valid_since.rs
Add two macro, `name!` and `environment!`, in integration-tests.
=> test: refactor integration

Cargo.lock, network/Cargo.toml, network/src/services/dns_seeding/seed_record.rs, util/crypto/Cargo.toml, util/crypto/src/secp/signature.rs
=> chore: upgrade cryptography library

.gitignore, Cargo.lock, Cargo.toml, chain/src/tests/basic.rs, core/src/extras.rs, protos/schemas/common.fbs, protos/src/convert/from_common.rs, protos/src/convert/to_common.rs, protos/src/generated/common.rs, rpc/README.md, rpc/json/rpc.json, spec/Cargo.toml, spec/src/consensus.rs, spec/src/lib.rs, util/dao/src/lib.rs, util/rational/Cargo.toml, util/rational/src/lib.rs, verification/src/tests/uncle_verifier.rs
backport https://github.com/nervosnetwork/ckb/pull/1307
=> [ᚬrc/v0.17] feat: difficulty adjustment rfc version

test/src/specs/tx_pool/dao.rs
Simplify the dao-transaction constructor in tests.
=> test: Simplify dao tests

sync/src/relayer/transaction_hashes_process.rs
1. return if no tx hashes missing in transaction_hashes_process
2. twist debug info
=> Twist transaction hashes log

rpc/src/server.rs
allow dns resolver on rpc server
=> feat: allow dns resolver on rpc server

Cargo.lock, ckb-bin/Cargo.toml, ckb-bin/src/helper.rs, ckb-bin/src/subcommand/init.rs, db/src/db.rs, util/app-config/src/args.rs, util/app-config/src/cli.rs, util/app-config/src/lib.rs
=> feat(ckb-bin): add interactive mode for init sub command

ckb-bin/src/helper.rs, ckb-bin/src/lib.rs, ckb-bin/src/subcommand/mod.rs, ckb-bin/src/subcommand/reset_data.rs, util/app-config/src/app_config.rs, util/app-config/src/args.rs, util/app-config/src/cli.rs, util/app-config/src/lib.rs
=> feat(ckb-bin): add reset data subcommand

.travis.yml
=> chore: skip Travis on bors merge in develop

util/reward-calculator/src/lib.rs
fix: The loading tx_fees is unordered HashSet [L150-L157](https://github.com/nervosnetwork/ckb/blob/develop/util/reward-calculator/src/lib.rs#L150-L157). But we use it as an ordered vector when calculates proposal_fees [L211]( https://github.com/nervosnetwork/ckb/blob/develop/util/reward-calculator/src/lib.rs#L211).
=> fix: Calculate transaction fees in order

core/src/cell.rs, core/src/transaction.rs, shared/src/chain_state.rs, shared/src/tx_pool/pool.rs, shared/src/tx_pool/proposed.rs, shared/src/tx_pool/types.rs
=> feat: Add dep group support

util/reward-calculator/src/lib.rs
=> [ᚬrc/v0.18] fix: Calculate transaction fees in order

core/src/cell.rs, verification/src/contextual_block_verifier.rs
This is a workaround to keep the current testnet main chain valid. It will not go into future versions.
=> [ᚬrc/v0.18] feat: Hardcode allow 34827

sync/src/lib.rs, sync/src/synchronizer/block_fetcher.rs, test/src/main.rs, test/src/specs/sync/chain_forks.rs
backport of https://github.com/nervosnetwork/ckb/pull/1420
=> [backport] fix: long forks

Cargo.lock, verification/Cargo.toml, verification/src/tests/uncle_verifier.rs
Add randomness for uncle block generation, make it would reconcile the main randomly.
=> test: add randomness for uncle test

notify/src/lib.rs, util/src/lib.rs
- Some code was commented almost half a year (since 2019-02-27).
- Some code was obsolete since we upgrade the rust toolchain.
=> chore: remove some useless code

indexer/src/store.rs, script/src/verify.rs, shared/src/tx_pool/types.rs, sync/src/synchronizer/in_ibd_process.rs, sync/src/synchronizer/mod.rs, sync/src/types.rs, test/src/specs/tx_pool/send_secp_tx.rs, util/crypto/src/secp/generator.rs, util/crypto/src/secp/mod.rs, util/jsonrpc-types/src/bytes.rs, util/network-alert/src/tests/test_verifier.rs
This PR includes some tiny improvements, I do not want to create PR one by one for every commits as they are very tiny.
The changes:
1. use derive Clone
2. use derive Default
3. refactor SECP generator
4. remove the useless param in `in_ibd_process.rs`
5. make the logs noiseless in unit test
If anyone disagrees of bundling them together, I could create single PRs for each of them.
=> chore: make the logs noiseless in unit test and some other tiny improvements

miner/src/candidate_uncles.rs, miner/src/lib.rs, network/src/peer_store/sqlite/db_trace.rs, network/src/peer_store/sqlite/peer_store.rs, network/src/protocols/identify.rs, network/src/services/dns_seeding/seed_record.rs, util/crypto/src/secp/mod.rs, util/crypto/src/secp/signature.rs
remove some `allow(dead_code)`
=> chore: clean code, not allow dead_code

devtools/doc/rpc.py, rpc/README.md
=> chroe(rpc): keep rpc doc endpoints order same as rpc.json

.travis.yml
Code Coverage test task is unstable.
=> chore(ci): allow code coverage failures

ckb-bin/src/subcommand/cli/secp256k1_lock.rs, ckb-bin/src/subcommand/init.rs, ckb-bin/src/subcommand/run.rs, docs/hashes.toml, resource/ckb.toml, resource/specs/dev.toml, resource/specs/staging.toml, resource/specs/testnet.toml, spec/src/consensus.rs, test/Cargo.toml, test/src/node.rs, util/app-config/src/cli.rs, util/jsonrpc-types/src/blockchain.rs
Co-authored-by: Quake <quake@nervos.org>
Co-authored-by: Qian Linfeng <thewawar@cryptape.com>
=> feat: Use secp256k1 referenced by hash type "type" as the default lock.

sync/src/relayer/block_transactions_process.rs, sync/src/relayer/tests/block_transactions_process.rs
If transaction collision happens during `BlockTransactionProcess`, the node should update the cached `missing_index`.
=> fix: should update cached missing_indexes when collision

test/src/node.rs, test/src/specs/sync/chain_forks.rs
resolve random failure of `chain_fork5` and fix typo in `connect_and_wait_ban`
=> test: fix integration test

test/src/main.rs, test/src/specs/sync/ibd_process.rs
1. Enhanced ibd process test
2. Enable disconnect test
=> test: Enhanced ibd process test

benches/benches/benchmarks/next_epoch_ext.rs, benches/benches/benchmarks/util.rs, chain/src/tests/basic.rs, chain/src/tests/reward.rs, chain/src/tests/util.rs, docs/hashes.toml, miner/src/block_assembler.rs, resource/specs/testnet.toml, rpc/src/test.rs, spec/src/consensus.rs, spec/src/lib.rs, sync/src/tests/synchronizer.rs, test/src/specs/tx_pool/send_secp_tx.rs, util/dao/utils/src/lib.rs, util/test-chain-utils/src/chain.rs
Fix dao statistics missing second transaction in genesis block.
Closes #1436
=> fix: Fix dao statistics in genesis block

indexer/src/store.rs
This PR resolved the performance issue of indexer module by using the `snapshot` API, before this PR, it took 10 seconds to index 100 blocks:
```
2019-09-02 21:58:57.513 +08:00 IndexerStore DEBUG ckb-indexer  Start sync index states with chain store
2019-09-02 21:59:07.194 +08:00 IndexerStore DEBUG ckb-indexer  End sync index states with chain store
```
after this PR, it took 0.06 second:
```
2019-09-02 22:10:39.420 +08:00 IndexerStore DEBUG ckb-indexer  Start sync index states with chain store
2019-09-02 22:10:39.480 +08:00 IndexerStore DEBUG ckb-indexer  End sync index states with chain store
```
=> perf: resolve indexer store performance issue

util/types/src/extension/check_data.rs
We can reject malformed messages from network asap.
=> chore: reject malformed message asap, don't verify them

Cargo.lock, network/Cargo.toml
BREAKING CHANGE: handshake serialization
=> feat: use molc to handshake

rpc/README.md, rpc/json/rpc.json, rpc/src/test.rs
docs: Add calculate_dao_maximum_withdraw example
I mark this example `skip: true` because it is difficult to construct its test.
=> docs: Add calculate_dao_maximum_withdraw example

docs/hashes.toml, resource/specs/dev.toml, resource/specs/staging.toml, resource/specs/testnet.toml
=> [ᚬrc/v0.20] fix: Update secp type script hash in genesis

script/src/lib.rs, script/src/verify.rs
This can be helpful in CKB script debugger's development
=> refactor: Expose method to invoke a single script on a transaction

sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/mod.rs
backport of https://github.com/nervosnetwork/ckb/pull/1554
=> fix: Data race between orphan_pool and storage

benches/benches/benchmarks/next_epoch_ext.rs, util/types/schemas/ckb.mol, util/types/src/conversion/blockchain.rs, util/types/src/core/advanced_builders.rs, util/types/src/extension/std_traits.rs, util/types/src/generated/types.rs, verification/src/error.rs
use uint256 to type difficulty
=> chore: use uint256 to type difficulty

docs/hashes.toml, resource/specs/dev.toml, resource/specs/staging.toml, resource/specs/testnet.toml
=> feat: use zero lock system cells

test/src/main.rs
* feat(test): Print panicked logs when node panicked
* chore: tweak based Clippy warning `the function has a cognitive complexity`
=> feat(test): Print panicked logs when node panicked

Cargo.lock, spec/src/consensus.rs, test/src/lib.rs, test/src/node.rs, test/src/specs/dao/dao_tx.rs, test/src/specs/dao/mod.rs, test/src/specs/dao/satoshi_dao_occupied.rs, test/src/specs/tx_pool/send_secp_tx.rs, util/dao/Cargo.toml, util/dao/src/lib.rs, verification/Cargo.toml, verification/src/tests/transaction_verifier.rs, verification/src/transaction_verifier.rs
Dependent on this PR https://github.com/nervosnetwork/ckb/pull/1600
=> fix: Use dao type script hash in dao transaction

rpc/README.md, rpc/json/rpc.json, rpc/src/test.rs
doc: Add RPC docs of get_block_template, submit_block
=> doc: Add RPC docs of get_block_template, submit_block

rpc/README.md, rpc/json/rpc.json
* The result of `get_block_template` in RPC document is wrong
=> doc: Correct result of get_block_template

docs/hashes.toml, resource/specs/dev.toml, resource/specs/staging.toml, resource/specs/testnet.toml, rpc/README.md, rpc/json/rpc.json, spec/src/consensus.rs, test/integration.toml, test/src/specs/tx_pool/send_secp_tx.rs, util/dao/src/lib.rs
BREAKING CHANGE: primary/secondary epoch reward has changed
=> feat: setup issuance schedule

devtools/doc/rpc.py, rpc/README.md
doc: Note generating via `make gen-rpc-doc`
=> doc: Note generating via `make gen-rpc-doc`

tx-pool/src/process/block_template.rs
* chore: Remove repeating `get_proposals`
=> chore: Remove repeating get_proposals

Makefile, network/src/network.rs, resource/ckb.toml, test/src/main.rs, test/src/net.rs, test/src/node.rs, test/src/specs/p2p/malformed_message.rs, test/src/specs/p2p/mod.rs, test/src/specs/p2p/whitelist.rs, test/src/specs/sync/ibd_process.rs, test/src/specs/sync/mod.rs
=> test: add whitelist test

rpc/README.md, rpc/json/rpc.json, tx-pool/src/process/block_template.rs, util/jsonrpc-types/src/block_template.rs, util/jsonrpc-types/src/blockchain.rs
json type number must use hex string
=> fix: json type number must use hex string

test/src/main.rs, test/src/specs/mining/mod.rs, test/src/specs/mining/uncle.rs, test/src/specs/sync/chain_forks.rs
* test: A uncle inherited from a fork-block in side fork is invalid
* test: A uncle inherited from a fork-uncle in side fork is invalid
* test: Miner should not add uncles into the epoch starting
* test: Different forks contain a same uncle
=> test: Pack uncles during switching epoch and reorg

test/src/specs/consensus/insufficient_reward.rs
https://dev.azure.com/nervosnetwork/ckb/_build/results?buildId=6455
=> test: fix insufficient_reward on Windows

ckb-bin/src/subcommand/init.rs
=> fix: fix init args

.travis.yml, Makefile
https://github.com/RustSec/cargo-audit/issues/143
https://internals.rust-lang.org/t/idea-cargo-install-update/11072
https://github.com/rust-lang/cargo/issues/6797
=> ci: Make sure cargo-audit up-to-date

rpc/README.md, rpc/json/rpc.json
replace difficulty with compact_target
=> chore: update get_block_template rpc doc

README.md
Now that this has been decided the doc should reflect that before the next round of mining test.
=> docs: Update PoW mining algorithm description

Cargo.lock, script/Cargo.toml, script/src/verify.rs, spec/src/consensus.rs, test/src/specs/tx_pool/send_secp_tx.rs, util/test-chain-utils/Cargo.toml, util/test-chain-utils/src/chain.rs, util/test-chain-utils/src/lib.rs
Move TWO_IN_TWO_OUT_CYCLES test in uint test
=> test: move typical_secp256k1_blake160_2_in_2_out cycle and size test

util/crypto/src/secp/mod.rs, util/crypto/src/secp/privkey.rs
* disable Debug/Display trait on  privkey
* zeroize when privkey dropped
=> feat: zeroize  when privkey dropped

Cargo.lock, util/logger/Cargo.toml, util/logger/src/lib.rs
=> feat: enable ansi support for windows

sync/src/types.rs
Update best headers(peers/global) after update header_map
=> fix: Fix get_header_view panic bug

Cargo.lock, benches/benches/benchmarks/overall.rs, chain/Cargo.toml, chain/src/tests/block_assembler.rs, rpc/src/module/miner.rs, script/Cargo.toml, script/src/verify.rs, spec/src/consensus.rs, spec/src/lib.rs, sync/src/relayer/compact_block_process.rs, sync/src/synchronizer/headers_process.rs, util/types/src/constants.rs, util/types/src/core/advanced_builders.rs, verification/src/header_verifier.rs, verification/src/tests/header_verifier.rs, verification/src/tests/transaction_verifier.rs, verification/src/transaction_verifier.rs
* TWO_IN_TWO_OUT_COUN   3875 ->  1600
* MAX_BLOCK_PROPOSALS_LIMIT ->  2400
* remove useless `HEADER_VERSION`
* `BLOCK_VERSION`, `TX_VERSION`, `TYPE_ID_CODE_HASH`  move to `consensus`
=> tweak consensus params

docs/hashes.toml, resource/build.rs, resource/specs/dev.toml, resource/specs/staging.toml, resource/specs/testnet.toml, spec/src/consensus.rs, spec/src/lib.rs, test/Cargo.toml, test/integration.toml, test/src/lib.rs, test/src/specs/dao/satoshi_dao_occupied.rs
* use all zeros lock to issuance satoshi cell
* remove bitcoin lock script from genesis
=> feat: security issuance satoshi cell by use all zeros lock

Cargo.lock, network/Cargo.toml, network/src/network.rs
BREAKING CHANGE: Encryption Algorithm
See: https://github.com/nervosnetwork/p2p/blob/master/CHANGELOG.md#026
=> chore: upgrade p2p dep

ckb-bin/src/helper.rs, ckb-bin/src/subcommand/run.rs, network/src/network.rs, network/src/protocols/test.rs, rpc/src/test.rs, test/src/net.rs
Shutdown when protocol handle panic
=> feat: shutdown when protocol handle panic

network/src/network.rs, network/src/protocols/mod.rs
BREAKING CHANGE: protocol handshake
=> style: Unified protocol handshake information format

ckb-bin/src/subcommand/cli/secp256k1_lock.rs, network/src/protocols/mod.rs, sync/src/net_time_checker.rs, sync/src/relayer/mod.rs, sync/src/relayer/tests/helper.rs, sync/src/relayer/transactions_process.rs, sync/src/synchronizer/block_process.rs, sync/src/synchronizer/get_headers_process.rs, sync/src/synchronizer/mod.rs, sync/src/tests/mod.rs, util/network-alert/src/alert_relayer.rs
1. fix #1746
2. add reason on `ban_peer` in cx trait
=> fix: fix cli output and ban reason

rpc/src/module/chain.rs, test/Cargo.toml, test/src/main.rs, test/src/rpc.rs, test/src/specs/dao/dao_verifier.rs, test/src/specs/dao/dao_verify.rs, test/src/specs/dao/mod.rs, test/src/specs/mining/fee.rs, util/dao/src/lib.rs, util/jsonrpc-types/src/blockchain.rs, util/types/src/core/reward.rs
* fix: Return non-zero rewards for the first 11 blocks
* test: Add DAOVerifier to verify the dao_fields
=> fix: Return non-zero rewards for the first 11 blocks

Cargo.lock, db/Cargo.toml, db/src/db.rs, db/src/iter.rs, db/src/lib.rs, indexer/src/store.rs, rpc/src/module/chain.rs, store/src/db.rs, store/src/snapshot.rs, store/src/store.rs, store/src/transaction.rs, sync/src/relayer/transactions_process.rs, util/snapshot/src/lib.rs
* get rid of useless lifetimes and unnecessary intermediate conversion code
* property api
=> refactor: db iterator interface

Cargo.lock, benches/Cargo.toml, docs/hashes.toml, resource/Cargo.toml, resource/specs/testnet.toml, test/src/specs/tx_pool/send_multisig_secp_tx.rs
See https://github.com/nervosnetwork/ckb-system-scripts/pull/61 for related changes.
=> feat: Upgrade system script for modified multi-sign lock script

Cargo.lock, benches/Cargo.toml, docs/hashes.toml, resource/Cargo.toml, resource/specs/testnet.toml, test/src/specs/tx_pool/send_multisig_secp_tx.rs
=> [ᚬrc/v0.24] feat: Upgrade system script for modified multi-sign lock script

.travis.yml, azure-pipelines.yml, test/src/specs/mod.rs, test/src/specs/p2p/whitelist.rs, test/src/specs/relay/transaction_relay.rs, test/src/specs/sync/block_sync.rs, test/src/specs/sync/get_blocks.rs, test/src/specs/sync/ibd_process.rs, test/src/utils.rs, test/src/worker.rs
* feat(test): Add a new setup, `retry_failed`, to specify the retry times when failed.
* feat(test): Add env var `CKB_TEST_SEC_COEFFICIENT`, then `utils::sleep(5s)` is equal to `thread::sleep(5 * CKB_TEST_SEC_COEFFICIENT)`
* chore(CI): Run CI with 4 concurrencies.
=> feat: Handle non determinism tests

rpc/README.md, rpc/json/rpc.json, rpc/src/module/chain.rs, util/jsonrpc-types/src/cell.rs
Add back to celloutput lost type script
=> fix: Add back to celloutput lost type script

test/src/main.rs, test/src/specs/mining/mod.rs, test/src/specs/mining/proposal.rs, test/src/specs/sync/get_blocks.rs, tx-pool/src/component/pending.rs, tx-pool/src/pool.rs, tx-pool/src/process/block_template.rs
* test: Add avoid_duplicated_proposals_with_uncles
* perf: Avoid re-proposed uncle transactions
=> perf: avoid reproposed uncle proposals

Cargo.toml, src/main.rs
jemalloc is crashed on MacOS catalina.
=> feat: disable jemalloc on MacOS

docs/hashes.toml, resource/specs/testnet.toml, spec/src/lib.rs
This make the system script cell capacity determined.
=> feat: allow overriding system script cell capacity

resource/ckb.toml
1. Remove sentry config
2. Add bootnodes config
=> chore: Update mainnet config

store/src/store.rs, sync/src/types.rs
When get header from main chain we can get it from snapshot
=> fix: Fix get locator performance bug

docs/hashes.toml, resource/specs/testnet.toml
- Lower the initial difficulty
- Update the timestamp
=> chore: tweak testnet spec

sync/src/types.rs
Move the main chain shortcut from `get_locator` to `get_ancestor`, there are bunch functions other than `get_locator` call `get_ancestor` directly, this change saves many DB queries when the base block on main chain.
=> refactor: move main chain shortcut to get_ancestor

rpc/README.md, rpc/json/rpc.json
resolve doc copy-paste error and add tx struct link to rfc
=> chore: send_transaction rpc doc tweak

network/src/protocols/identify.rs
If it cannot be parser, ban it, only two possibilities:
1. message format error（molecule）
2. not on same net
=> fix: ban peer that are not on the same network

network/src/network.rs, network/src/protocols/mod.rs, sync/src/relayer/mod.rs, sync/src/relayer/tests/helper.rs, sync/src/synchronizer/mod.rs, sync/src/tests/mod.rs
fix lost sync/relayer protocol registration
=> fix: fix lost sync/relayer protocol registration

test/src/main.rs, test/src/specs/mining/mod.rs, test/src/specs/mining/tx_select.rs
Add an integration test for `get_block_template` transactions selection
=> test: get_block_template transactions selection

chain/src/chain.rs, ckb-bin/src/subcommand/import.rs, ckb-bin/src/subcommand/run.rs, indexer/src/store.rs, network/src/network.rs, network/src/peer_store/peer_store_impl.rs, network/src/protocols/mod.rs, network/src/services/dump_peer_store.rs, resource/src/template.rs, rpc/src/module/chain.rs, rpc/src/module/pool.rs, rpc/src/module/stats.rs, rpc/src/service_builder.rs, shared/src/shared.rs, spec/src/lib.rs, sync/src/orphan_block_pool.rs, sync/src/relayer/block_transactions_process.rs, sync/src/relayer/block_uncles_verifier.rs, sync/src/relayer/compact_block_process.rs, sync/src/synchronizer/block_process.rs, sync/src/synchronizer/mod.rs, sync/src/types.rs, tx-pool/src/component/pending.rs, tx-pool/src/component/proposed.rs, util/test-chain-utils/src/mock_store.rs, util/types/src/conversion/storage.rs, util/types/src/core/cell.rs, verification/src/contextual_block_verifier.rs, verification/src/header_verifier.rs
Reduce useless clone / to_owned use
=> perf: Reduce useless clone / to_owned use

.travis.yml, docs/ckb-core-dev.md
add `--locked` option on `cargo install` command
=> test: add --locked option on cargo install command

util/dao/src/lib.rs
`withdrawing_header` is the header of block where dao prepare transaction in.
=> chore: Rename withdraw_header to withdrawing_header in DaoCalculator

Cargo.lock, util/jsonrpc-types/Cargo.toml
=> chore(deps): bump jsonrpc-core from 10.1.0 to 14.0.5

rpc/README.md, rpc/json/rpc.json, rpc/src/module/pool.rs, util/jsonrpc-types/src/pool.rs
BREAKING CHANGE: rpc interface
fix #1845
Need to expose more information about the pool here?
=> feat: add more info on rpc

test/src/main.rs
1. Add an option to run all tests regardless of failure.
2. Fix a bug: when the nodes are panicked, the exit code is 0.
For example: add `if block.number() > 0 { panic!(); }` to function `insert_block(..)` in `ckb-store`, all integration tests will be passed (`exit code == 0`).
Since the follow two pieces of code are not match (`panicked_error` is skipped when exit):
https://github.com/nervosnetwork/ckb/blob/e76cbe076586d362ce7f676635caf1e84f1cc9d4/test/src/main.rs#L150-L152
https://github.com/nervosnetwork/ckb/blob/e76cbe076586d362ce7f676635caf1e84f1cc9d4/test/src/main.rs#L165-L167
=> test: add options for integration tests and fix a bug

Cargo.lock, miner/Cargo.toml, miner/src/client.rs
=> feat: built-in miner should support https rpc url

sync/src/synchronizer/block_fetcher.rs
=> perf: Speed up fetch collect

Cargo.lock, error/Cargo.toml, sync/src/types.rs
Fix https://github.com/nervosnetwork/ckb/issues/1986
=> [ᚬrc/v0.30] perf: Fix build_skip performance bug

Cargo.lock, network/Cargo.toml, network/src/network.rs
release note:
https://github.com/nervosnetwork/p2p/blob/master/CHANGELOG.md#030-alpha2
Bug Fix
- Fix overflow on be attacked on Secio
- Fix throughput issues caused by code limit
Features
- Error type Changed
=> chore: upgrade tentacle

Cargo.lock
=> [ᚬrc/v0.31] chore: upgrade tokio

azure-pipelines.yml
CI Result Preview: [CKB GitHub Action](https://github.com/nervosnetwork/ckb/runs/683297253)
=> chore: upgrade dependencies on Windows in azure pipelines

chain/src/tests/block_assembler.rs
fix https://travis-ci.com/github/nervosnetwork/ckb/jobs/349597648#L1826
=> fix: prepare_uncles_test failed on block_template update delayed

util/app-config/src/configs/network.rs
Restrict the permissions of secret key files
=> chore: restrict secret file permissions

.github/CODEOWNERS
The code owners are assigned according to the number of added lines.
=> chore: setup module code owners

Cargo.lock, network/Cargo.toml, network/src/errors.rs, network/src/network.rs, network/src/protocols/discovery/substream.rs
tentacle:
- Performance optimization
- Split error type
tokio：
- Fix task budgeting with `block_in_place`
- Fix notify when resetting a Delay to a time in the past
=> chore: upgrade tentacle/tokio

Makefile, azure-pipelines.yml, devtools/windows/make.ps1, docs/ckb-on-windows.md
Add a PowerShell script for Windows so developers can perform the tasks without installing too many dependencies.
=> chore: add make script for Windows PowerShell

sync/src/types.rs
When a node is start from number 0, it will sync all headers at first, then the `block_status_map` will be full quickly.
Then, along with the block sync, all data in `block_status_map` will be removed.
When the IBD is done, there will be nothing left in `block_status_map`.
But when another new-started node try to sync data from this node, this node will fetch all block statuses from database and insert them into `block_status_map` without deletions. And full block status will store in memory until the node is shutdown.
https://github.com/nervosnetwork/ckb/blob/b2b2276478619b1ecd6d9eeefb3186013c430b9a/sync/src/synchronizer/get_blocks_process.rs#L46
https://github.com/nervosnetwork/ckb/blob/b2b2276478619b1ecd6d9eeefb3186013c430b9a/sync/src/types.rs#L1752-L1755
Up to now, there all 2,222,026 …
=> improvement: don't cache all block status in memory

sync/src/relayer/compact_block_process.rs
- `fn_get_pending_header` always try call `get_header_view`:
https://github.com/nervosnetwork/ckb/blob/6678f812fd3f3263010298388f73cafd2e92590a/sync/src/relayer/compact_block_process.rs#L153-L164
- `get_header_view` always try call `get_block_header`
https://github.com/nervosnetwork/ckb/blob/6678f812fd3f3263010298388f73cafd2e92590a/sync/src/types.rs#L1170-L1179
- Always try call `get_block_header` after `fn_get_pending_header`: 
https://github.com/nervosnetwork/ckb/blob/6678f812fd3f3263010298388f73cafd2e92590a/sync/src/relayer/compact_block_process.rs#L305-L307
=> improvement: don't query store twice in method chaining

util/logger/src/lib.rs
If using log targets with `-`, we **shouldn't** just replace `-` by `_`, we should keep the original value, too.
For example:
If the **real** log target is `ckb-relay`, log filter is `info,ckb-relay=trace`, the lenient log filter should be `info,ckb-relay=trace,ckb_relay=trace`, not `info,ckb_relay=trace`.
=> fix: fix the lenient logger filter parser

test/src/specs/alert/alert_propagation.rs
Add case description and some assertion for alert_propagation
=> refactor: integration test - alert

Cargo.lock, db/Cargo.toml, db/src/snapshot.rs
commits viewable in
https://github.com/nervosnetwork/rust-rocksdb/pull/18
https://github.com/nervosnetwork/rust-rocksdb/pull/16
=> chore: bump rocksdb 0.14.1

test/src/specs/consensus/insufficient_reward.rs
Add case description and update case assertions
=> refactor: integration test - consensus

test/src/specs/sync/block_sync.rs
While waiting for the `get_blocks` message in the integration test, we should determine whether the last block hash is equal or not, otherwise, in the case of sending `get_blocks` in batches (which is triggered by timer), subsequent messages will be processed when the first batch is received, which may cause the random integration test failure.
=> fix: integration test random failures

Cargo.lock, chain/Cargo.toml, chain/src/chain.rs, sync/Cargo.toml, sync/src/relayer/block_transactions_process.rs, sync/src/relayer/compact_block_process.rs, sync/src/relayer/get_block_proposal_process.rs, sync/src/relayer/get_block_transactions_process.rs, sync/src/relayer/get_transactions_process.rs, sync/src/relayer/mod.rs, sync/src/status.rs, sync/src/synchronizer/get_blocks_process.rs, sync/src/synchronizer/get_headers_process.rs, sync/src/synchronizer/mod.rs, sync/src/types/mod.rs, util/logger/Cargo.toml, util/logger/src/lib.rs
=> refactor: replace metric macros by metrics service

Cargo.lock, tx-pool/Cargo.toml, tx-pool/src/service.rs
replace crossbeam-channel with async oneshot
=> feat: tx-pool block_on async oneshot

rpc/src/server.rs
It helps to check whether the RPC server has started.
=> chore: print RPC server listen addresses in log

network/src/network.rs, network/src/peer.rs, network/src/protocols/ping.rs, network/src/protocols/test.rs
1. rewrite ping
2. remove `last_ping_time`
=> refactor: Rewrite ping

devtools/doc/rpc.py, rpc/README.md, rpc/json/rpc.json, rpc/src/module/chain.rs, store/src/store.rs, store/src/transaction.rs, util/jsonrpc-types/src/lib.rs
This PR adds an optional `verbosity ` param to chain related rpc, returns data in hex format without calculated hash values, it will improve performance in some scenarios, ~~for example, ckb-indexer can scan 2,000,000 blocks in 13 minutes with this change (before: 20 minutes)~~ **This benchmark is not correct, I will rerun it and update**
=== updated ckb-indexer benchmark result ===
scan 2,000,000 blocks, run 3 times, avg:
before: 17 minutes 40 seconds
after: 12 minutes 30 seconds
=== response example ===
hex format: 
```
echo '{                                                                                     
"id": 2,     
"jsonrpc": "2.0",
"method": "get_tip_header",
"params": ["0x1"]
}' \
| tr -d '\n' \
| curl -H 'content-type: application/json' -d @- \
http://localhost:8114 …
```
=>  feat: add verbosity param to chain related rpc

Cargo.lock, ckb-bin/src/subcommand/replay.rs, db-migration/Cargo.toml, db-migration/src/lib.rs, db/src/db.rs, indexer/src/migrations.rs, miner/Cargo.toml, shared/src/migrations/table_to_struct.rs, util/instrument/Cargo.toml, util/logger-service/src/lib.rs
Add migrarion processbar, improve migration display
=> feat: improve migration progress display

network/src/network.rs, network/src/protocols/disconnect_message.rs
Clean up the historical `Both` registration issues
=> chore: all leftover registrations of `both` are cleared

.travis.yml, devtools/ci/qput-7z
Build prod-with-debug and upload to qiniu directly in CI.
The job has been tested in https://travis-ci.com/github/nervosnetwork/ckb/builds/177427769
=> chore: upload release for deployment to qiniu

devtools/doc/rpc.py, rpc/README.md, rpc/src/module/experiment.rs
* Update the script to work with new added `<a>` tags in the generated HTML files.
* Fix missing spaces
* Fix links to types
* add missing doc of PoolTransactionEntry
=> docs(rpc): upgrade rpc.py

chain/src/chain.rs, chain/src/switch.rs, ckb-bin/src/subcommand/run.rs, network/src/protocols/test.rs, rpc/README.md, rpc/src/module/chain.rs, spec/src/consensus.rs, sync/src/synchronizer/mod.rs, sync/src/types/mod.rs, tx-pool/src/process.rs, util/app-config/src/args.rs, util/app-config/src/cli.rs, util/app-config/src/configs/network.rs, util/app-config/src/lib.rs, util/jsonrpc-types/src/blockchain.rs, verification/src/contextual_block_verifier.rs, verification/src/transaction_verifier.rs
Added option to skip verification for faster synchronization of trusted node data to a specified height
**Please know exactly what you are doing before you use it!**
=> feat: add assume valid target config

Cargo.toml, Makefile, ckb-bin/Cargo.toml, ckb-bin/src/lib.rs, ckb-bin/src/setup_guard.rs, network/Cargo.toml, network/src/network.rs, sync/Cargo.toml, sync/src/relayer/mod.rs, sync/src/relayer/transactions_process.rs, sync/src/synchronizer/mod.rs, util/app-config/Cargo.toml, util/app-config/src/app_config.rs, util/app-config/src/lib.rs, util/logger-service/Cargo.toml, util/logger-service/src/lib.rs
move sentry to optional dependency, reduce dependency libs on other target (wasm32, etc)
=> feat: add with_sentry feature

Cargo.lock, network/Cargo.toml, network/src/network.rs, network/src/services/dns_seeding/mod.rs
Replace `resolve` that has not been maintained for a long time
=> chore: replace dns resolver

ckb-bin/src/subcommand/migrate.rs, db-migration/src/lib.rs, shared/src/shared.rs, util/app-config/src/args.rs, util/app-config/src/cli.rs, util/app-config/src/lib.rs
`ckb migrate --check`
if migration is in need 0 will be return，otherwise ExitCode::Cli(64) returned.
=> feat: migrate check

sync/src/relayer/mod.rs, sync/src/synchronizer/mod.rs, sync/src/types/mod.rs
=> fix: relay and sync should be order independent

test/src/main.rs
According to https://github.com/nervosnetwork/ckb/pull/2435#issuecomment-751191097, add an argument to control this feature.
=> chore(integration): add an argument in command line to control integration report

devtools/doc/rpc.py, rpc/README.md, rpc/src/module/subscription.rs
=> docs: fix reject tx subscription RPC doc

sync/src/types/mod.rs
- This issue was introduced since #2455.
That issue fix the bug: if relay protocol connected but sync protocol not, then there will be no response for all received relay messages.
More details about that issue can be found in issue #2450.
Before the PR, only sync protocol can add peers, but after it, relay protocol can add peers, too.
- If there are any peers in `Peers`, the sync protocol could do `notify`, even if it wasn't connected.
So, it could do `send_getheaders_to_peer`.
https://github.com/nervosnetwork/ckb/blob/4a5e8a2a0790192f57dbad2d6f1abc1be5ab84bf/sync/src/synchronizer/mod.rs#L749-L751
https://github.com/nervosnetwork/ckb/blob/4a5e8a2a0790192f57dbad2d6f1abc1be5ab84bf/sync/src/synchronizer/mod.rs#L506-L507
- But, since sync protocol wasn't connected, the …
=> fix: don't do sync before sync connected

test/src/main.rs
- remove `--quiet` command line argument
- add `--verbose`, when use this argument will set `ckb_test` log level as `trace`(`info` as a default value). And there will add more verbose `debug/trace` logs into integration test util functions.
=> chore(integration): add --verbose argument for showing verbose log

Cargo.lock, Cargo.toml, shared/Cargo.toml, shared/migration-template/Cargo.toml, shared/migration-template/src/lib.rs, shared/src/lib.rs, shared/src/migrations/add_number_hash_mapping.rs, shared/src/migrations/cell.rs, util/types/src/lib.rs
multi-thread number_hash_mapping migration
extract multi-thread migration template:
https://github.com/nervosnetwork/ckb/blob/e841287b9484ae325acc64e4e74c5fb705a09bcd/shared/src/migrations/add_number_hash_mapping.rs#L20-L21
=> feat: multi thread number_hash_mapping migration

rpc/README.md, rpc/src/module/chain.rs, test/src/main.rs, test/src/rpc.rs, test/src/specs/rpc/get_block_median_time.rs, test/src/specs/rpc/mod.rs
resolve https://github.com/nervosnetwork/ckb/issues/2518
=> feat: add RPC get_block_median_time

sync/src/relayer/compact_block_verifier.rs
The code must not be empty here
=> chore: remove unnecessary judgment

chain/src/chain.rs
Remove some staled metrics and rename the metric name "ckb-chain.tip_number" to "ckb.chain_tip"
=> feat: metricize chain growth

test/src/main.rs, test/src/specs/rpc/get_block_template.rs, test/src/specs/rpc/mod.rs, test/src/specs/rpc/submit_block.rs
Add integration test cases for RPC Miner Module:
- get_block_template
- submit_block
=> chore(integration): add cases RPC - Miner module

Cargo.lock, chain/src/chain.rs, verification/Cargo.toml, verification/src/contextual_block_verifier.rs, verification/src/transaction_verifier.rs
Add some metrics about block and transaction processing costs.
=> feat: metricize processing cost

sync/src/lib.rs, sync/src/net_time_checker.rs, sync/src/relayer/block_transactions_process.rs, sync/src/relayer/compact_block_process.rs, sync/src/relayer/get_block_proposal_process.rs, sync/src/relayer/get_block_transactions_process.rs, sync/src/relayer/get_transactions_process.rs, sync/src/relayer/mod.rs, sync/src/relayer/tests/block_transactions_process.rs, sync/src/relayer/tests/compact_block_process.rs, sync/src/relayer/tests/helper.rs, sync/src/status.rs, sync/src/synchronizer/get_blocks_process.rs, sync/src/synchronizer/get_headers_process.rs, sync/src/synchronizer/mod.rs, sync/src/types/mod.rs, sync/src/utils.rs
* Metricize network message traffic and labeled with message name and processing result
* Remove some staled metrics
=> feat: metricize network traffic

Cargo.lock, miner/Cargo.toml, miner/src/client.rs
allow miner HTTP basic authorization
=> feat: allow miner http basic authorization

test/src/node.rs
Fix few panics in integration tests, when tx-pool doesn't reach the tip as chain in the timeout (10s).
Reset the timeout if the tx-pool still works. So the timeout is flexible but also bounded.
=> test: no timeout if the tx-pool still works

sync/src/types/mod.rs
Not conflict with #2609:
- This PR to make block status map to be smaller.
After this PR, the max size of block status map during IBD: `4*10^6 -> 5*10^4` (current mainnet has about `4*10^6` blocks, and **I only test once**).
- #2609 to cache block status map into disk if the size of block status map is bigger than a threshold (default: `10^6`, `1/4` of current mainchain).
If this PR merged, #2609 will not work in almost all scenarios at present.
But I don't close it because:
- The max size of block status map will be increased if network is poor or too many forked blocks.
- We can set it to a smaller value, #2609 provide an option.
- That PR refactor the `HeaderMap` to `CachedHashMap`, so we can reuse the temporary storage for other `HashMap`s later.
Both of these two PRs could be merged.
=> improvement: smaller block status map during IBD

network/src/network.rs
There is a modification conflict with #2565
=> chore: dail observed address use another way

Makefile, devtools/windows/make.ps1
Pre PR of migrate travis to github actions: Made some changes in Makefile.
The PR https://github.com/nervosnetwork/ckb/pull/2686
https://github.com/nervosnetwork/ckb/pull/2687
https://github.com/nervosnetwork/ckb/pull/2688
https://github.com/nervosnetwork/ckb/pull/2689
https://github.com/nervosnetwork/ckb/pull/2690 based on this PR
=> Pre PR of migrate travis to github actions

.github/workflows/remove-old-artifacts.yml
This workflow deletes old artifacts older than a month.
=> feat: add workflow to remove old artifacts

.github/workflows/merge_pr_by_bors.yaml, bors.toml
A workflow for PR verify before merge by bors. Need pre PR https://github.com/nervosnetwork/ckb/pull/2686 due to Makefile changes.
TODO:
=> workflow to merge PR by bors

.github/workflows/rc_branch.yaml
Add workflow to run some tests when commit on  'rc*' branch, Need pre PR https://github.com/nervosnetwork/ckb/pull/2686 due to some Makefile changes
=> Workflow for 'rc*' branch

.github/workflows/daily_cronjob.yaml
Add daily cron job on master&develop branch, need pre PR https://github.com/nervosnetwork/ckb/pull/2686 due to some Makefile changes
=> A daily cronjob on master&develop branch

.github/workflows/benchmark/terraform/.gitignore, .github/workflows/benchmark/terraform/.terraform.lock.hcl, .github/workflows/benchmark/terraform/README.md, .github/workflows/benchmark/terraform/ami.tf, .github/workflows/benchmark/terraform/main.tf, .github/workflows/benchmark/terraform/variables.tf, .github/workflows/benchmark/terraform/versions.tf
I divided https://github.com/nervosnetwork/ckb/pull/2680 into 3 smaller parts:
1. Terraform configuration files
2. Ansible playbook
3. Workflow file
This PR is the first part. Brief description is here: [PREVIEW](https://github.com/keroro520/ckb/blob/workflow-benchmark-terraform-configuration-files/.github/workflows/benchmark/terraform/README.md)
=> feat: prepare benchmark workflow - terraform configuration files

.github/workflows/benchmark.yml
I divided https://github.com/nervosnetwork/ckb/pull/2680 into 3 smaller parts:
1. Terraform configuration files
2. Ansible playbook
3. Workflow file
This PR is the 3rd part.
=> feat: add workflow "Benchmark"

.github/workflows/sync/ansible/.gitignore, .github/workflows/sync/ansible/README.md, .github/workflows/sync/ansible/ansible.cfg, .github/workflows/sync/ansible/files/produce-report.sh, .github/workflows/sync/ansible/playbook.yml, .github/workflows/sync/ansible/requirements.yml, .github/workflows/sync/ansible/vars/all.yml
This is a part of "Sync-Mainnet" workflow: Ansible playbook
=> feat: prepare sync-mainnet workflow - ansible playbook

test/src/main.rs, test/src/specs/rpc/get_blockchain_info.rs, test/src/specs/rpc/mod.rs
I rebase and re-submit https://github.com/nervosnetwork/ckb/pull/2491
=> chore(integration): add cases RPC - Module stats

.github/workflows/ci.yaml, Makefile, devtools/doc/rpc.py
Fix issues as below:
1. Remove the Latest_Linters steps from ci-success check since it allow failure
2. Fixed make check-dirty-rpc-doc failure
=> Fix quick check failure

.github/workflows/backport.yml, .github/workflows/benchmark.yml, .github/workflows/ci.yaml, .github/workflows/daily_cronjob.yaml, .github/workflows/remove-old-artifacts.yml, .github/workflows/sync.yml
- Disable GitHub Actions that **require self-hosted runners** for the forked repositories as default.
- Disable GitHub Actions that **run periodically** for the forked repositories as default.
- Allow disabling or enabling the self-hosted CI tests for any branches in any repositories.
- If the HEAD commit message contains `enable self-hosted ci`, the self-hosted CI tests will **be required**.
- If the HEAD commit message contains `disable self-hosted ci`, the self-hosted CI tests will **be skipped**.
| Type | Forked             | Allowed Branch     | Control Message    | Run CI             | Preview     |
|------|--------------------|--------------------|--------------------|--------------------|-------------|
| PR   | :heavy_check_mark: | :x:                | No control message | …
=> ci: disable self-hosted tests for forked repositories and support control them with commit messages

verification/src/transaction_verifier.rs
I found `median_timestamps_cache` of `SinceVerifier` to be almost useless when counting lru cache hits / miss ratio: it pre-allocates an inputs-sized cache for each transaction, but for most transactions without the `since` field, this cache is useless and is quickly deallocated. For the few transactions that have the `since` field, the header fetch is already cached in store layer, so I don't see the need to add another cache here.
=> chore: remove lru cache from SinceVerifier

util/runtime/src/lib.rs
- Improve the experience for reading our logs, to distinguish logs between different threads.
- Unify naming style of thread names.
Since a long thread name will cut to 15 characters.
No doubt about it, `CamelCase` is better than `snake_case`, since the name in `CamelCase` is more short.
This limit is created by kernel.
```c
/* Task command name length: */
#define TASK_COMM_LEN     16
```
Ref: [The definition of `TASK_COMM_LEN` in latest stable kernel.](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/linux/sched.h?h=v5.10.12#n213)
p.s. The default name of the tokio runtime is "tokio-runtime-worker", we could only see "tokio-runtime-w" in system tools, such as `top`, `htop` and so on.
=> feat: give an unique id to each global runtime thread

.github/workflows/package.yaml, util/build-info/src/lib.rs
* Update package command
* Use Bionic to build Ubuntu binary
* Fix commit date in the CKB version
=> chore: update package command

network/src/peer_store/peer_store_impl.rs, network/src/tests/peer_store.rs, util/app-config/src/configs/memory_tracker.rs
=> fix: fix peer store evict

.github/workflows/benchmark.yml, .github/workflows/sync.yml, .github/workflows/sync/ansible/playbook.yml, .github/workflows/sync/terraform/main.tf, .github/workflows/sync/terraform/scripts/main.tf.template, .github/workflows/sync/terraform/variables.tf
Report the results of each day's "Benchmark" and "Sync-Mainnet" to https://github.com/nervosnetwork/ckb/pull/2372
=> feat: schedule benchmark and sync-mainnet

rpc/src/module/test.rs
Calculating `header.dao` is the most challenging step when creating testing blocks because it requires history blocks.
Now there is `generate_block_with_template`, but `generate_block_with_template` will insert the generated block: 
https://github.com/nervosnetwork/ckb/blob/0683c7d00222f9c0ae84121d821e282fabf75c48/rpc/src/module/test.rs#L236-L237
Sometimes test cases want to inject invalid blocks into the chain via [`process_block_without_verify`](https://github.com/nervosnetwork/ckb/blob/0683c7d00222f9c0ae84121d821e282fabf75c48/rpc/src/module/test.rs#L34-L35). So I added the test-used RPC `calculate_dao_field`.
=> feat: add test-used rpc calculate_dao_field

network/src/network.rs
=> feat: dial bootnode randomly

tx-pool/src/process.rs
https://github.com/nervosnetwork/ckb/pull/2756#discussion_r662000531
=> chore: log failed transactions results

sync/src/synchronizer/headers_process.rs, sync/src/synchronizer/in_ibd_process.rs, sync/src/synchronizer/mod.rs, sync/src/types/mod.rs, test/src/main.rs, test/src/specs/sync/block_sync.rs
=> fix: backport fix of the status marking problem of header sync to 0.43

README.md
* Specify branch explicitly
* Add query filter to the links
=> chore: update README ci badges

README.md
* Put Nervos Talk before Telegram
* Add a landing page for Nervos Talk
=> chore: update README chat badges

Cargo.lock, script/Cargo.toml, script/src/ill_transaction_checker.rs
=> feat: upgrade hyper and ckb-vm

deny.toml, sync/src/orphan_block_pool.rs, sync/src/relayer/mod.rs, sync/src/types/mod.rs, test/src/main.rs, test/src/specs/sync/mod.rs, test/src/specs/sync/sync_and_mine.rs
=> backport fix: try traverse all unknown parent hash

rpc/README.md, rpc/src/module/pool.rs, test/src/node.rs, test/src/rpc.rs
before request tx_pool_info, make sure tx-pool is ready.
=> fix: persisted test wait tx-pool ready

.github/workflows/smoking_test.yaml
Problem Summary: Smoking test failed because of snapshot URL not specified.
https://github.com/nervosnetwork/ckb/actions/workflows/smoking_test.yaml
What's Changed: Fix the secret variable name in the workflow file `smoking_test.yaml`.
Tests 
=> chore: fix secret name in workflow

.github/pull_request_template.md
Problem Summary: It's not clear how to exclude a PR or just include the title in the release note.
What's Changed: Add more information in the template.
- Add `Title Only` in the block to include only the PR title in the release note.
- Add `None` in the block to exclude the PR from the release note.
Tests 
```release-note
None
```
=> chore: explain how to use the release note section in pr template

script/fuzz/.gitignore, script/fuzz/Cargo.toml, script/fuzz/README.md, script/fuzz/fuzz_targets/transaction_scripts_verifier_data0.rs, script/fuzz/fuzz_targets/transaction_scripts_verifier_data1.rs
This PR adds 2 fuzzers for ckb-script crate, one is for vm0 version, another is for vm1 version.
=> test: add `TransactionScriptsVerifier` fuzz test

resource/Cargo.toml, resource/src/lib.rs
write target file directly; append .tmp.$PID to the target file as the tmp file
=> refactor(ckb-resource): Remove dependency on tempfile in ckb-resource

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
Problem Summary: The issue templates are stalled.
- Remove two rarely used templates.
- Update bug report template.
Tests 
```release-note
```
=> chore: update bug templates

.github/workflows/coverage_report.yaml
A workflow  for overage report, run ckb unit/integration test code coverage weekly and upload coverage report to codecov.io
```release-note
```
=> ci: Workflow for code coverage

src/main.rs
Problem Summary: There is a typo in the main entry
What's Changed: exectuble->executable
Tests 
=> chore: fix typo in comment

test/src/main.rs, test/src/rpc.rs, test/src/specs/tx_pool/send_large_cycles_tx.rs
add Integration test for chunk process
```release-note
```
=> test: add relay wrong tx test for chunk process

.github/workflows/backport.yml
refactor backport based on new pr template
```release-note
```
=> refactor: refactor backport based on new pr template

.github/workflows/ci_cargo_deny_ubuntu.yaml, .github/workflows/ci_integration_tests_macos.yaml, .github/workflows/ci_integration_tests_ubuntu.yaml, .github/workflows/ci_integration_tests_windows.yaml, .github/workflows/ci_linters_macos.yaml, .github/workflows/ci_linters_ubuntu.yaml, .github/workflows/ci_linters_windows.yaml, .github/workflows/ci_quick_checks_macos.yaml, .github/workflows/ci_quick_checks_ubuntu.yaml, .github/workflows/ci_quick_checks_windows.yaml, .github/workflows/ci_unit_tests_macos.yaml, .github/workflows/ci_unit_tests_ubuntu.yaml, .github/workflows/ci_unit_tests_windows.yaml, devtools/ci/ci_main.sh
fix: update composite source to ckb repo
```release-note
```
=> fix: update composite source to ckb repo

Makefile, error/src/util.rs, rpc/src/tests/examples.rs, rpc/src/tests/mod.rs, rpc/src/tests/module/miner.rs, rpc/src/tests/module/mod.rs, rpc/src/tests/module/pool.rs
Problem Summary: add two unit test:
1. add unit test for get_block_template cache expiration
2. add unit test for exceeded maximum ancestors count
What's Changed: only new unit test
Tests 
- Unit test
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nervosnetwork/ckb/3015)
=> test: add unit test for `get_block_template_cache` and `exceeded_maximum_ancestors_count`

Makefile, error/src/util.rs
resolved the CI task error which is introduced by https://github.com/nervosnetwork/ckb/pull/3015
Tests 
- Unit test
```release-note
```
=> chore: fix ci test error

Cargo.lock, util/launcher/Cargo.toml, util/launcher/src/lib.rs, util/launcher/src/tests.rs
add a test for migration with the [0.34](https://github1s.com/nervosnetwork/ckb/blob/v0.34.0/chain/src/chain.rs#L381) DB scheme
Tests
- Unit test
```release-note
```
=> test: add test for migration

Cargo.lock, db/Cargo.toml, db/src/db_with_ttl.rs, db/src/lib.rs, db/src/tests/db_with_ttl.rs, db/src/tests/mod.rs, rpc/README.md, rpc/src/module/chain.rs, test/src/main.rs, test/src/rpc.rs, test/src/specs/hardfork/v2021/cell_deps.rs, test/src/specs/hardfork/v2021/vm_version.rs, test/src/specs/tx_pool/collision.rs, test/src/specs/tx_pool/different_txs_with_same_input.rs, test/src/specs/tx_pool/send_low_fee_rate_tx.rs, tx-pool/Cargo.toml, tx-pool/src/component/mod.rs, tx-pool/src/component/recent_reject.rs, tx-pool/src/component/tests/mod.rs, tx-pool/src/component/tests/recent_reject.rs, tx-pool/src/pool.rs, tx-pool/src/process.rs, tx-pool/src/service.rs, util/app-config/src/configs/tx_pool.rs, util/app-config/src/legacy/tx_pool.rs, util/jsonrpc-types/src/blockchain.rs, util/launcher/src/shared_builder.rs
Proposal: https://talk.nervos.org/t/rfc-ckb-better-support-to-query-transaction-status/6043
Tests 
- Unit test
db/src/tests/db_with_ttl.rs
tx-pool/src/component/recent_reject.rs
test/src/specs/tx_pool/different_txs_with_same_input.rs
Side effects
- Backward compatibility
* The new configuration has default value if not provided, it‘s compatible.
* No migration required.
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nervosnetwork/ckb/3029)
=> feat: record recent reject

util/types/src/core/blockchain.rs
Impl `Debug` to `ScripreHashType` and `DepType`.
```release-note
```
=> chore: derive Debug to core types

test/src/main.rs, test/src/rpc.rs, test/src/specs/tx_pool/get_raw_tx_pool.rs, test/src/specs/tx_pool/mod.rs
Add integration test for rpc `get_raw_tx_pool`
Tests 
```release-note
```
=> test: add integration test for rpc `get_raw_tx_pool`

.github/workflows/coverage_report.yaml
Upload coverage report artifact
Tests
- Unit test
```release-note
None
```
=> feat: upload coverage report artifact

chain/src/chain.rs, network/src/protocols/tests/mod.rs, notify/src/lib.rs, rpc/src/module/subscription.rs, test/src/specs/tx_pool/get_raw_tx_pool.rs
Resolve `make clippy` error and resolve https://github.com/nervosnetwork/ckb/issues/3062
Tests 
run `make clippy`
```release-note
```
=> chore: resolve make clippy error

.github/workflows/ci_integration_tests_macos.yaml, .github/workflows/ci_integration_tests_ubuntu.yaml, .github/workflows/ci_integration_tests_windows.yaml, .github/workflows/ci_linters_macos.yaml, devtools/ci/ci_main.sh
ci linters failed but still exit 0
Tests
- Unit test
```release-note
```
=> fix:  ci_linters dose not exit 1 when command run failed

.github/workflows/smoking_test.yaml, devtools/smoking_test/check-migrate.sh, devtools/smoking_test/ckb.service
refactor somking test
```release-note
```
=> refactor: refactor smoking test

rpc/src/error.rs, rpc/src/module/pool.rs, rpc/src/tests/error.rs, tx-pool/src/service.rs
remove unnecessary `downcast_submit_transaction_reject` fn
Tests 
- Unit test
```release-note
```
=> chore: remove unnecessary downcast error

network/src/protocols/identify/mod.rs, network/src/protocols/ping.rs
ckb always enable secio, these judgments are meaningless 
Tests
- Unit test
```release-note
```
=> chore: remove unnecessary code

chain/src/tests/txs_verify_cache.rs, spec/src/consensus.rs, test/src/main.rs, test/src/specs/hardfork/v2021/delay_txs.rs, test/src/specs/hardfork/v2021/mod.rs, tx-pool/src/chunk_process.rs, tx-pool/src/process.rs, tx-pool/src/service.rs, tx-pool/src/util.rs
Proposal:  delay txs during hardfork
Tests 
```release-note
```
=> feat: delay txs during hardfork

rpc/README.md, rpc/src/module/pool.rs, util/jsonrpc-types/src/pool.rs
chore: change default validator of `send_transaction` rpc to `pasthrough`
Tests 
- Unit test
```release-note
```
=> chore: change default validator of `send_transaction` rpc to `pasthrough`

sync/src/types/header_map/backend_rocksdb.rs
let panic bring its error message 
Tests
- Unit test
```release-note
```
=> chore: panic with error message

network/src/network.rs
stream size cannot currently be adjusted，revert #3141 
Tests
```release-note
```
=> fix: revert 3141

devtools/ci/benchmark.sh
What's Changed: 
benchmark run failed due to unbound variable CKB_BENCH_PATH
Tests 
```release-note
```
=> ci: unbound variable CKB_BENCH_PATH

.github/workflows/smoking_test.yaml, devtools/smoking_test/check-migrate.sh, devtools/smoking_test/tip_block_growth_check.sh
smoking test failed, fixed it
Tests 
```release-note
```
=> ci: smoking test failed, fixed it

network/src/lib.rs
What's Changed: Expose `compress` module from ckb-network. When implementing testing protocols to communicate with CKB full nodes, requires the `compress` module.
Tests 
```release-note
```
=> chore: expose compress module from ckb-network

network/src/lib.rs
fix document linter
Tests 
```release-note
```
=> fix: doc linter

.github/workflows/benchmark.yml
trigger benchmark on pr review specific branches
- PR to update : https://github.com/nervosnetwork/ckb-integration-test/pull/61/files
Tests 
```release-note
```
=> ci: trigger benchmark on pr review specific branches

network/src/services/outbound_peer.rs
use `dial_feeler` on this function
Tests
```release-note
```
=> chore: fix typo

network/src/protocols/discovery/addr.rs, network/src/protocols/discovery/mod.rs
What's Changed: Update some logs related to the "discovery" network protocol.
Tests 
```release-note
```
=> chore: improve debuggability of discovery protocol

network/src/protocols/identify/mod.rs
What's Changed: Update some logs related to the "identify" network protocol.
Tests 
```release-note
```
=> chore: improve debuggability of identify protocol

tx-pool/src/util.rs
Problem Summary: devchain has not delay-window
What's Changed: Correct the delay-window check for devchain
Tests 
- Unit test
```release-note
```
=> chore: devchain has not delay-window

test/run.sh
remove with_sentry feature
- all tests
```release-note
```
=> ci: remove usless feature with_sentry

.github/workflows/smoking_test.yaml
Add test result to Postgres in order to monitoring it
Tests 
```release-note
```
=> ci(test data): add smoking test report to postgres

Cargo.lock, chain/src/tests/load_code_with_snapshot.rs, script/Cargo.toml, script/src/syscalls/debugger.rs, script/src/syscalls/exec.rs, script/src/syscalls/load_cell.rs, script/src/syscalls/load_cell_data.rs, script/src/syscalls/load_header.rs, script/src/syscalls/mod.rs, script/src/syscalls/pause.rs, script/src/syscalls/tests/vm_latest/syscalls_1.rs, script/src/verify.rs, script/src/verify/tests/ckb_latest/features_since_v2019.rs, script/src/verify/tests/ckb_latest/features_since_v2021.rs
fix: Use valid assembly separator on Apple Silicon
https://github.com/nervosnetwork/ckb-vm/commit/5d417a17c68cefbd0ec3ec8948fb48cfe5699dc2
upgrate ckb-vm to 0.21.1
Tests 
- Unit test
```release-note
```
=> chore: upgrate ckb-vm to 0.21.1

.github/workflows/sync-mainnet.yml
sync mainnet failed due to the directory name contains  the  special characters '/', fix it
Tests 
```release-note
```
=> ci: fix sync mainnet failed

.github/workflows/ckb-integration-test.yml
What's Changed: Schedule to run ckb-integration-test
Tests 
```release-note
```
=> feat: schedule to run ckb-integration-test

Cargo.lock, network/Cargo.toml, util/app-config/Cargo.toml, util/crypto/Cargo.toml
lock tentacle on `0.4.0-alpha.2`
Tests
- Unit test
```release-note
```
=> chore: lock tentacle

.github/workflows/ci_benchmarks_macos.yaml, .github/workflows/ci_benchmarks_ubuntu.yaml, .github/workflows/ci_benchmarks_windows.yaml, .github/workflows/ci_cargo_deny_ubuntu.yaml, .github/workflows/ci_integration_tests_macos.yaml, .github/workflows/ci_integration_tests_ubuntu.yaml, .github/workflows/ci_integration_tests_windows.yaml, .github/workflows/ci_linters_macos.yaml, .github/workflows/ci_linters_ubuntu.yaml, .github/workflows/ci_quick_checks_macos.yaml, .github/workflows/ci_quick_checks_ubuntu.yaml, .github/workflows/ci_unit_tests_macos.yaml, .github/workflows/ci_unit_tests_ubuntu.yaml, .github/workflows/ci_unit_tests_windows.yaml, .github/workflows/ci_wasm_build_ubuntu.yaml
ci: trigger ci on push specific branches
Tests 
- tests
```release-note
```
=> ci: trigger ci on push specific branches

rpc/src/module/pool.rs, spec/src/consensus.rs
update rfc/0024 link
Tests 
```release-note
```
=> docs: update ckb genesis script list link

chain/src/tests/block_assembler.rs, rpc/src/tests/examples.rs, rpc/src/tests/mod.rs
* rpc test temp dir droped too early
* blank template test wait sync chain and pool 
Tests 
- Unit test
```release-note
```
=> fix: potential test failed

Cargo.lock, network/Cargo.toml, network/src/network.rs, util/app-config/src/configs/network.rs
bump tentacle to 0.4.0-alpha.3
```release-note
```
=> chore: bump tentacle to 0.4.0-alpha.3

Cargo.lock, deny.toml, rpc/Cargo.toml, rpc/README.md, rpc/src/module/test.rs, rpc/src/service_builder.rs, rpc/src/tests/examples.rs
Open IntegrationTestRpc in rpc/module/test, add rpc comment document.
- open 6 functions,  add check Dummy PoW chain in integration test (not add separate check in each function) 
- add encoding_rs license.clarify in deny.toml( reqwest crate refer to encoding_rs)
Tests 
```release-note
None: Exclude this PR from release note.
```
=> test: open IntegrationTestRpc and add comment

ckb-bin/src/subcommand/replay.rs
fix subcommand replay crash due to divide profile_time(zero) if the time is less than one second
- fix subcommand replay crash due to divide profile_time(will be zero if the time is less than one second)
- set minimum profiling time to 5 seconds, if profiling time is less than 5 seconds, show prompt message to suggest increase block range, make profiling time meets minimum time.  
- minor change to output style.
- fix crash
- add minimum profiling time limit
- minor output style refactor
Tests 
Side effects
- None
```release-note
```
=> fix(ckb-bin): fix replay command crash if profile time less than one second

Cargo.lock, ckb-bin/Cargo.toml, ckb-bin/src/lib.rs, ckb-bin/src/subcommand/list_hashes.rs, util/app-config/Cargo.toml, util/app-config/src/cli.rs, util/app-config/src/lib.rs, util/app-config/src/tests/cli.rs
upgrade current clap(2.33.2) to latest version 3.1
clap crate upgrade from 2.x to 3.x,  refactor lifetime usage,  replace  deprecated App with Command.
Note: Clap derived usage, reduce parsing code will be another PR.
Tests 
- Unit test
```release-note
```
=> feat(ckb cli) upgrade clap from v2.0 to v3.x

network/src/protocols/mod.rs, network/src/protocols/support_protocols.rs
1. Add logging to abnormal disconnects
2. Align the highest version number of all protocols with a constant
Tests
- Unit test
```release-note
```
=> chore: add some logs

.github/workflows/ci_integration_tests_ubuntu.yaml, util/app-config/src/tests/ckb_run_replay.bats, util/app-config/src/tests/cli.bats, util/app-config/src/tests/cli_test.sh, util/app-config/src/tests/export_import.bats, util/app-config/src/tests/init_reset.bats, util/app-config/src/tests/peer_id.bats
add skeleton code, add a few cases(ckb --version and ckb import,...) to verify design 
PR Summary: 
- Add ckb cli test cases, using bats platform.
- put bats test_cases into `cargo test`(cause these test cases need test-bed setup, so skip these cases when `cargo test` unless you use `-- --ignored` flag)
- add new CI workflow(`ci_ckb_cli`), process ckb cli bats test.
- test-bed setup including:
- ckb binary build
- bats and support lib installation
- `[ckb-assets](https://github.com/nervosnetwork/ckb-assets)` for test db.
Tests 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> test(cli): add cli test cases, using bats

.github/workflows/ckb-integration-test.yml
=> ci : fix integration workflow

Cargo.lock, script/Cargo.toml
Update ckb-vm to v0.21.2
Fixed an arm64 asm bug, detailed https://github.com/nervosnetwork/ckb-vm/releases/tag/v0.21.2
Tests 
- Unit test
None
=> chore(script): update ckb-vm to v0.21.2

rpc/README.md, rpc/src/module/chain.rs
Correct typo in RPC README.md
```release-note
```
=> doc: correct typo on anchor in RPC README.md

README.md, docs/configure.md, docs/platform-support.md, rpc/README.md, util/jsonrpc-types/src/chain_info.rs
Problem Summary: Update chain names according to [RFC37](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0037-ckb2021/0037-ckb2021.md)
- Rename Lina to Mirana
- Rename Aggron to Pudge
Tests
```release-note
```
=> doc: update chain codename

test/src/node.rs, test/src/util/mining.rs
Fix some integration random failed.
mine exclude uncles by default, because uncles' proposals can affect the assertions of some tests.
Tests 
- Unit test
```release-note
```
=> fix(integration): mine exclude uncles by default

test/src/specs/hardfork/v2021/cell_deps.rs
temp fix cell_deps tests
Tests 
- Unit test
```release-note
```
=> chore: temp fix cell_deps test

test/src/specs/rpc/truncate.rs
Wait tx_pool sync.
Tests 
- Unit test
```release-note
```
=> fix(tests): rpc truncate

Cargo.lock
fix yanked zeroize_derive deny
- update zeroize_derive to 1.3.2
- update parking_lot_core to 0.9.3, remove duplicate windows-sys deps
Tests 
- Unit test
```release-note
```
=> fix yanked zeroize_derive deny

Cargo.lock, ckb-bin/src/lib.rs, test/Cargo.toml, test/src/net.rs, util/launcher/Cargo.toml, util/launcher/src/shared_builder.rs, util/runtime/Cargo.toml, util/runtime/src/lib.rs
- Runtime shutdown timeout
- upgrade tokio-util contains fixes a memory leak
Tests 
- Unit test
```release-note
```
=> fix: runtime shutdown

chain/src/tests/load_code_with_snapshot.rs, script/src/syscalls/load_cell_data.rs, script/src/syscalls/tests/vm_latest/syscalls_1.rs, script/src/types.rs, script/src/verify.rs, script/src/verify/tests/ckb_latest/features_since_v2021.rs, script/src/verify/tests/utils.rs
Since hardfork has been completed and all existing nodes have been removed from the snapshot bug, this snapshot-compatible behavior of removing the page flag can be safely removed
Tests
- Unit test
```release-note
```
=> feat: remove snapshot compatible code

Cargo.lock, db/Cargo.toml
fix rocksdb libring link
Tests 
- Unit test
```release-note
```
=> chore(deps):bump rocksdb from 0.18.1 to 0.18.2

Cargo.lock, network/Cargo.toml, network/src/lib.rs, network/src/network.rs, network/src/protocols/disconnect_message.rs, network/src/protocols/discovery/mod.rs, network/src/protocols/discovery/state.rs, network/src/protocols/feeler.rs, network/src/protocols/identify/mod.rs, network/src/protocols/mod.rs, network/src/protocols/ping.rs, network/src/protocols/support_protocols.rs, network/src/protocols/tests/mod.rs, sync/src/net_time_checker.rs, sync/src/relayer/mod.rs, sync/src/relayer/tests/helper.rs, sync/src/synchronizer/mod.rs, sync/src/tests/mod.rs, sync/src/tests/net_time_checker.rs, sync/src/tests/synchronizer/functions.rs, test/src/net.rs, util/network-alert/src/alert_relayer.rs
introduce `async_trait` to ckb
this is a break change for ckb, it upgrade tentacle from 0.4.0-aphla to 0.4.0
ckb-network will also use `async_trait` to ckb protocol
[release note](https://github.com/nervosnetwork/tentacle/blob/master/CHANGELOG.md#040)
Tests 
- Unit test
```release-note
```
=> feat: upgrade tentacle

Cargo.lock, ckb-bin/Cargo.toml, network/Cargo.toml, sync/Cargo.toml, tx-pool/Cargo.toml, util/app-config/Cargo.toml, util/logger-service/Cargo.toml, util/logger-service/src/lib.rs
Issue Number: https://github.com/nervosnetwork/ckb/issues/3457
https://github.com/nervosnetwork/ckb/security/dependabot/2
* upgrate sentry (drop chrono
* use time 0.3 drop replace chrono 
* log time in utc instead of local time
The format of the time will remain the same
```
before:
2022-07-01 11:05:24.807 +08:00
now:
2022-07-01 03:22:11.673 +00:00
```
Tests 
- Unit test
```release-note
```
=> feat: log in utc time

sync/src/types/mod.rs
Optimize download block behavior for synchronous protocols
Since each environment is different, the policy here must also be dynamically adjusted according to the current environment, and a low-level limit is given here, since frequent restarting of a task consumes more than a low-level limit
The current timing of ckb synchronization is network + insert database, as the transaction volume increases + block size grows, the time lag of verification transaction will become larger, the fixed 1s configuration is not reasonable
Tests
- Unit test
```release-note
```
=> perf: perf sync

traits/src/cell_data_provider.rs, traits/src/epoch_provider.rs, traits/src/header_provider.rs
Add more detailed comment to ckb-traits crate
Tests 
- Unit test
```release-note
```
=> chore: update ckb-traits doc

docs/configure.md
line 21: Take following directory -> Take the following directory
line 59: carefully -> careful
line 63: adds the
Tests 
- Unit test
Side effects
```release-note
```
=> fixing syntax

docs/quick-start.md
line 3: Following steps -> The following steps 
line 5: creates -> create
line 12: this same directory -> the same directory
=> docs: fixing syntax

.github/workflows/ci_integration_tests_macos.yaml, .github/workflows/ci_integration_tests_ubuntu.yaml, .github/workflows/ci_integration_tests_windows.yaml
integration test timeout
tweak ci integration timeout limit
Tests 
- Unit test
```release-note
```
=> chore: tweak ci integration timeout

devtools/doc/rpc.py, rpc/README.md
fix rpc doc 
Tests 
```release-note
```
=> chore: fix rpc docs

chain/Cargo.toml, tx-pool/Cargo.toml, util/dao/Cargo.toml
fix dao crate publish
remove dao useless feature
Tests 
- Unit test
```release-note
```
=> chore: fix dao publish

.github/workflows/benchmark.yml, .github/workflows/ci_aarch64_build_ubuntu.yaml, .github/workflows/ci_benchmarks_macos.yaml, .github/workflows/ci_benchmarks_ubuntu.yaml, .github/workflows/ci_benchmarks_windows.yaml, .github/workflows/ci_cargo_deny_ubuntu.yaml, .github/workflows/ci_integration_tests_macos.yaml, .github/workflows/ci_integration_tests_ubuntu.yaml, .github/workflows/ci_integration_tests_windows.yaml, .github/workflows/ci_linters_macos.yaml, .github/workflows/ci_linters_ubuntu.yaml, .github/workflows/ci_quick_checks_macos.yaml, .github/workflows/ci_quick_checks_ubuntu.yaml, .github/workflows/ci_unit_tests_macos.yaml, .github/workflows/ci_unit_tests_ubuntu.yaml, .github/workflows/ci_unit_tests_windows.yaml, .github/workflows/ci_wasm_build_ubuntu.yaml, .github/workflows/ckb-integration-test.yml, .github/workflows/coverage_report.yaml, .github/workflows/package.yaml, .github/workflows/smoking_test.yaml, .github/workflows/sync-mainnet.yml
* lock ckb-assets checkout via tag
* upgrade action/checkout@3
Tests 
- Unit test
```release-note
```
=> chore(ci): lock ckb-assets checkout via tag

.github/workflows/coverage_report.yaml, Makefile
Fix cov toolchain 
Tests 
- Unit test
```release-note
```
=> chore(ci): fix cov toolchain

util/light-client-protocol-server/src/components/get_block_samples.rs
- Denote all difficulties to $D_{i}$.
- Denote total difficulty for block $i$ to $B_{i}$.
- Denote the boundary difficulty to $D_{boundary}$.
- Denote $k$ to satisfied that $D_{k} \lt D_{boundary} \le D_{k+1}$
- Denote the number of first block whose total difficulty is not less than $D_{boundary}$ is $n$.
Namely, $B_{n-1} \lt D_{boundary} \le B_{n}$.
The bug will be happened when $B_{n-1} \lt D_{k} \lt D_{boundary} \le D_{k+1} \le B_{n}$.
Because the first block whose total difficulty is not less than $D_{k}$ still is $n$.
The bug due to that the previous commit only removes the difficulties which are satisfied that $B_{n} \le D_{i}$.
In fact, all difficulties which are satisfied that $B_{n-1} \lt D_{i}$ should be removed.
=> fix(light-client): skip difficulties which lead to find the boundary block

Cargo.lock, rpc/Cargo.toml, util/logger-service/Cargo.toml, util/logger-service/src/lib.rs
Fix https://github.com/nervosnetwork/ckb/security/dependabot/5
replace ansi_term with yansi
Tests 
- Unit test
```release-note
```
=> chore: replace ansi_term with yansi

.github/workflows/smoking_test.yaml, devtools/smoking_test/tip_block_growth_check.sh
ci: migrate somking test to github runner
Tests 
- Unit test
```release-note
```
=> ci: migrate somking test to github runner

Cargo.lock, network/Cargo.toml, network/src/services/dns_seeding/mod.rs, network/src/services/dns_seeding/seed_record.rs, network/src/services/dns_seeding/tests.rs, util/app-config/Cargo.toml, util/crypto/Cargo.toml, util/crypto/src/secp/privkey.rs, util/crypto/src/secp/pubkey.rs, util/crypto/src/secp/signature.rs
upgrade secio and yamux, also upgrade secp256k1
yamux release note
```
Fix wrong behavior on half close
```
secp256k1 from 0.20 - 0.24 [release note](https://github.com/rust-bitcoin/rust-secp256k1/blob/master/CHANGELOG.md#0240---2022-07-20)
Tests
- Unit test
```release-note
```
=> chore: upgrade some deps

Cargo.lock, devtools/ci/check-cargotoml.sh, util/light-client-protocol-server/Cargo.toml, util/light-client-protocol-server/src/components/get_blocks_proof.rs, util/light-client-protocol-server/src/components/get_last_state_proof.rs, util/light-client-protocol-server/src/components/get_transactions_proof.rs, util/light-client-protocol-server/src/lib.rs, util/light-client-protocol-server/src/tests/components/get_blocks_proof.rs, util/light-client-protocol-server/src/tests/components/get_transactions_proof.rs, util/light-client-protocol-server/src/tests/components/mod.rs, util/light-client-protocol-server/src/tests/mod.rs, util/light-client-protocol-server/src/tests/prelude.rs, util/light-client-protocol-server/src/tests/utils/chain.rs, util/light-client-protocol-server/src/tests/utils/mod.rs, util/light-client-protocol-server/src/tests/utils/network_context.rs, util/types/schemas/extensions.mol, util/types/src/core/advanced_builders.rs, util/types/src/generated/extensions.rs, util/types/src/utilities/merkle_mountain_range.rs
Return missing items when asking a proof:
- Return missing block hashes for `GetBlocksProof`.
- Return missing transaction hashes for `GetTransactionsProof`.
=> feat(light-client): return missing items when asking a proof

Cargo.lock, script/Cargo.toml, script/src/verify.rs
**ChangeLogs**
<https://github.com/nervosnetwork/ckb-vm/releases/tag/v0.21.5>
<https://github.com/nervosnetwork/ckb-vm/releases/tag/v0.21.6>
<https://github.com/nervosnetwork/ckb-vm/releases/tag/v0.21.7>
=> Bump ckb-vm to v0.21.7

Cargo.lock, Makefile, devtools/doc/rpc.py, rpc/README.md, rpc/src/module/indexer.rs, util/indexer/Cargo.toml, util/indexer/src/service.rs, util/jsonrpc-types/src/indexer.rs, util/jsonrpc-types/src/lib.rs
* move indexer rpc types to jsonrpc-types
* Added documentation related to indexer rpc types
Tests 
- Unit test
```release-note
```
=> chore: improve indexer types docs

util/indexer/src/indexer.rs
It is simply an Off-by-one error, when a fork is encountered, the indexer will start backtracking blocks from `tip - keep_num`, but `tip - keep_num` happens to be the boundary of the prune.
Prune will now start with `tip - (keep_num + 1)`
Tests 
- Unit test
```release-note
```
=> fix(indexer): panic when rollback after prune

rpc/README.md, rpc/src/module/chain.rs, rpc/src/module/experiment.rs, rpc/src/module/mod.rs, test/src/rpc.rs, util/jsonrpc-types/src/experiment.rs, util/jsonrpc-types/src/lib.rs
Backport: https://github.com/nervosnetwork/ckb/pull/3669
Tests 
- Unit test
```release-note
```
=> backport: add rpc estimate_cycles

util/indexer/src/service.rs
backport https://github.com/nervosnetwork/ckb-indexer/pull/63
Tests 
- Unit test
```
curl http://localhost:8114/ -X POST -H "Content-Type: application/json" -d '{
"jsonrpc": "2.0",
"method": "get_transactions",
"params": [
{
"script": {
"code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
"hash_type": "type",
"args": "0x5f58632a123e7e731db0b59ce50fe16579c7d941"
},
"script_type": "lock",
"group_by_transaction": true
},
"desc",
"0x0"
],
"id": 1
}'
```
```release-note
```
=> chore: limit should be greater than 0

util/indexer/src/service.rs
indexer misuse of `tokio::sleep` resulted in high cpu usage
Replace `tokio::sleep` with `tokio::interval`
Tests 
- Unit test
```release-note
```
=> fix: indexer CPU usage

test/src/specs/tx_pool/pool_reconcile.rs
fix PoolResolveConflictAfterReorg random failed https://github.com/nervosnetwork/ckb/actions/runs/3494108211/jobs/5849597473
Tests 
- Unit test
```release-note
```
=> chore: fix PoolResolveConflictAfterReorg random failed

test/src/specs/tx_pool/pool_reconcile.rs, tx-pool/src/component/proposed.rs, tx-pool/src/component/tests/proposed.rs, tx-pool/src/pool.rs, tx-pool/src/process.rs
backport https://github.com/nervosnetwork/ckb/pull/3713
=> [backport] fix: check in-pool chidren for all newly added tx

tx-pool/src/block_assembler/mod.rs, util/dao/src/lib.rs
backport https://github.com/nervosnetwork/ckb/pull/3727
Tests 
- Unit test
```release-note
```
=> [backport] fix: blocktemplate dao potential inconsistent with transactions

network/src/network.rs
resolve disconnection problems
Tests
- Unit test
```release-note
```
=> fix: resolve disconnection problems

network/src/network.rs
resolve disconnection problems
Tests
- Unit test
```release-note
```
=> [backport]fix: resolve disconnection problems

util/launcher/src/migrations/add_chain_root_mmr.rs, util/types/src/utilities/merkle_mountain_range.rs
Fix a stupid design mistake according to the rfc change (nervosnetwork/rfcs#397).
Tests
- Unit test
```release-note
```
=> fix(light-client): according to the rfc change (nervosnetwork/rfcs#397)

Cargo.lock, devtools/doc/rpc.py, rpc/README.md, rpc/src/module/chain.rs, rpc/src/tests/fee_rate.rs, rpc/src/util/fee_rate.rs, tx-pool/src/component/container.rs, tx-pool/src/component/entry.rs, tx-pool/src/component/tests/container.rs, tx-pool/src/component/tests/proposed.rs, tx-pool/src/util.rs, util/jsonrpc-types/src/blockchain.rs, util/types/src/core/fee_rate.rs, util/types/src/core/tx_pool.rs
backport https://github.com/nervosnetwork/ckb/pull/3746
Tests 
- Unit test
```release-note
```
=> [backport] fix: get_fee_rate_statics compatibility 

util/launcher/src/migrations/add_chain_root_mmr.rs, util/types/src/utilities/merkle_mountain_range.rs
Backport #3744.
Tests
- Unit test
```release-note
```
=> [backport] fix(light-client): according to the rfc change (nervosnetwork/rfcs#397)

block-filter/src/filter.rs, notify/src/lib.rs, rpc/src/tests/examples.rs, util/app-config/src/configs/notify.rs, util/indexer/src/service.rs, util/launcher/src/shared_builder.rs, util/network-alert/src/tests/test_notifier.rs
backport 
Tests 
- Unit test
```release-note
```
=> [backport] fix: notify message blocking

rpc/src/tests/fee_rate.rs, rpc/src/util/fee_rate.rs
backport https://github.com/nervosnetwork/ckb/pull/3757
Tests 
- Unit test
```release-note
```
=> [backport] fix: fee_rate statistics target limit

db/src/iter.rs
fix comment typos 
- use `iterator` instead of `interator`
- Unit test
```release-note
```
=> [db] fix comment typos

.github/workflows/ci_aarch64_build_ubuntu.yaml, .github/workflows/ci_benchmarks_macos.yaml, .github/workflows/ci_benchmarks_ubuntu.yaml, .github/workflows/ci_benchmarks_windows.yaml, .github/workflows/ci_cargo_deny_ubuntu.yaml, .github/workflows/ci_integration_tests_macos.yaml, .github/workflows/ci_integration_tests_ubuntu.yaml, .github/workflows/ci_integration_tests_windows.yaml, .github/workflows/ci_linters_macos.yaml, .github/workflows/ci_linters_ubuntu.yaml, .github/workflows/ci_quick_checks_macos.yaml, .github/workflows/ci_quick_checks_ubuntu.yaml, .github/workflows/ci_unit_tests_macos.yaml, .github/workflows/ci_unit_tests_ubuntu.yaml, .github/workflows/ci_unit_tests_windows.yaml, .github/workflows/ci_wasm_build_ubuntu.yaml, bors.toml
Use GitHub Merge Queue instead.
Ref https:
//docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue # Please enter the commit message for your changes. Lines starting # with '#' will be ignored, and an empty message aborts the commit. #
Tests 
```release-note
```
=> chore: remove bors

network/src/network.rs
This is a historical restoration omission, https://github.com/nervosnetwork/ckb/pull/3738
Tests
- Unit test
```release-note
```
=> fix: omission modification

network/src/network.rs
This is a historical restoration omission, https://github.com/nervosnetwork/ckb/pull/3738
Tests
- Unit test
```release-note
```
=> [Backport] omission modification

Cargo.lock, chain/src/tests/load_code_with_snapshot.rs, resource/specs/dev.toml, resource/specs/staging.toml, rpc/README.md, rpc/src/module/chain.rs, script/fuzz/fuzz_targets/syscall_exec.rs, script/fuzz/fuzz_targets/transaction_scripts_verifier_data1.rs, spec/src/consensus.rs, spec/src/hardfork.rs, spec/src/lib.rs, util/constant/src/hardfork/mainnet.rs, util/constant/src/hardfork/testnet.rs, util/jsonrpc-types/src/blockchain.rs, util/jsonrpc-types/src/lib.rs, util/types/Cargo.toml, util/types/src/core/hardfork/ckb2021.rs, util/types/src/core/hardfork/ckb2023.rs, util/types/src/core/hardfork/helper.rs, util/types/src/core/hardfork/mod.rs, verification/src/tests/transaction_verifier.rs, verification/src/transaction_verifier.rs
Tests 
- Unit test
Side effects
```release-note
```
=> prepare 2023 deploy

devtools/doc/rpc.py, rpc/README.md, rpc/src/module/chain.rs, rpc/src/module/stats.rs, spec/src/consensus.rs, spec/src/tests/versionbits.rs, spec/src/versionbits/convert.rs, spec/src/versionbits/mod.rs, util/jsonrpc-types/src/blockchain.rs, util/jsonrpc-types/src/info.rs, util/jsonrpc-types/src/lib.rs
get_deployments_info rpc adds the returned period, threshold, and epoch which the current state started `since`.
Tests 
- Unit test
```release-note
```
=> feat: deployment since

devtools/doc/rpc.py, rpc/README.md, rpc/src/module/chain.rs, rpc/src/module/stats.rs, spec/src/consensus.rs, spec/src/tests/versionbits.rs, spec/src/versionbits/convert.rs, spec/src/versionbits/mod.rs, util/jsonrpc-types/src/blockchain.rs, util/jsonrpc-types/src/info.rs, util/jsonrpc-types/src/lib.rs
backport https://github.com/nervosnetwork/ckb/pull/3772
Tests 
- Unit test
```release-note
```
=> [backport] feat: deployment since

Cargo.lock, ckb-bin/Cargo.toml, ckb-bin/src/subcommand/migrate.rs, deny.toml, rpc/README.md, rpc/src/module/chain.rs, rpc/src/tests/examples.rs, rpc/src/tests/fee_rate.rs, rpc/src/util/fee_rate.rs, util/jsonrpc-types/src/blockchain.rs, util/jsonrpc-types/src/lib.rs
backport https://github.com/nervosnetwork/ckb/pull/3924
Tests 
- Unit test
Side effects
```release-note
```
=> [backport] fix rpc typo

rpc/README.md, rpc/src/module/chain.rs, rpc/src/tests/examples.rs, rpc/src/tests/fee_rate.rs, rpc/src/util/fee_rate.rs, util/jsonrpc-types/src/blockchain.rs, util/jsonrpc-types/src/lib.rs
Issue Number: close https://github.com/nervosnetwork/ckb/issues/3879
Deprecated the original typo's method and added a new corrected method.
Tests 
- Unit test
```release-note
```
=> fix: rpc typo statics -> statistics

Cargo.lock
Issue Number: close https://github.com/nervosnetwork/ckb/issues/3946
Patched versions  >=0.3.17
upgrade h2 to 0.3.18
Tests 
- Unit test
```release-note
```
=> fix: RUSTSEC-2023-0034 alert

pow/Cargo.toml, pow/src/dummy.rs, pow/src/eaglesong.rs, pow/src/eaglesong_blake2b.rs, pow/src/lib.rs, spec/src/consensus.rs, store/Cargo.toml, store/src/cache.rs, store/src/db.rs, store/src/lib.rs, store/src/snapshot.rs, store/src/store.rs, store/src/transaction.rs, store/src/write_batch.rs, sync/src/orphan_block_pool.rs, sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/mod.rs, sync/src/types/mod.rs, util/reward-calculator/src/lib.rs, verification/contextual/src/contextual_block_verifier.rs, verification/src/block_verifier.rs, verification/src/genesis_verifier.rs, verification/src/header_verifier.rs, verification/traits/src/lib.rs
This PR improve code comments
- Improve code comments for `ckb-pow,ckb-store,ckb-sync,ckb-verification`
Tests 
- Unit test
Side effects
- None
```release-note
```
=> docs: Improve code comments

docs/platform-support.md
What's Changed: Update platform support tiers.
Tests 
```release-note
```
=> chore: update platform-support.md

.github/workflows/benchmark.yml
postgres service is off https://discord.com/channels/674518700518408213/852364882081742918/1104234528718991452
ckb-bench.log not found in ${{ env.ANSIBLE_DIR }}
=> ci: fix benchmark action failed

script/fuzz/Cargo.toml, script/fuzz/README.md, script/fuzz/fuzz_targets/syscall_exec.rs, script/fuzz/fuzz_targets/transaction_scripts_verifier_data0.rs, script/fuzz/fuzz_targets/transaction_scripts_verifier_data2.rs
* Add fuzz test for script verifier of data2
* Fix script verifier fuzz test
Tests 
- Unit test
Side effects
```release-note
```
=> feat: fuzz scripts verifier data2

script/src/syscalls/spawn.rs, script/src/verify.rs
There are some unnecessary fields and clone in the `Spawn` syscall, we have `syscalls_generator` field already, these data can be fetched by its fields without clone.
Tests 
- Unit test
```release-note
```
=> chore: remove unnecessary clone in spawn syscall

.github/workflows/backport.yml
=> chore(ci): escape title in backport.yml

spec/src/hardfork.rs, util/constant/src/hardfork/testnet.rs
2023 edtion testnet activation time
Tests 
- Unit test
Side effects
```release-note
```
=> chore: 2023 testnet activation params

spec/src/consensus.rs
Fix the calculation of block reward in permanent difficulty mode 
Tests 
- Unit test
Side effects
```release-note
```
=> fix: permanent difficulty mode reward

script/src/verify.rs, spec/src/hardfork.rs, test/src/main.rs, test/src/specs/hardfork/mod.rs, test/src/specs/hardfork/v2021/mod.rs, test/src/specs/hardfork/v2021/vm_version1.rs, test/src/specs/hardfork/v2023/mod.rs, test/src/specs/hardfork/v2023/vm_version2.rs, verification/src/transaction_verifier.rs
Until the 2023 rule is enabled, rpc should reject Data2 transactions
Tests 
- Unit test
Side effects
```release-note
```
=> fix: 2023 vm version check

util/constant/src/hardfork/testnet.rs
Adjusted the activation time according to the test
Tests 
- Unit test
Side effects
```release-note
```
=> chore: adjust 2023 activation time

util/constant/src/hardfork/testnet.rs
backport 
* https://github.com/nervosnetwork/ckb/pull/4024
Tests 
- Unit test
Side effects
```release-note
```
=> backport 4024

Cargo.lock
backport #4030
Tests 
- Unit test
Side effects
```release-note
```
=> backport #4030

rpc/README.md, rpc/src/module/chain.rs, util/jsonrpc-types/src/blockchain.rs
backport
* https://github.com/nervosnetwork/ckb/pull/4034
Tests 
- Unit test
Side effects
```release-note
```
=> backport 4034

util/constant/src/hardfork/testnet.rs
Because it may take some time to fix some problems, we think it is better to postpone the launch of testnet
Tests 
- Unit test
Side effects
```release-note
```
=> chore: delay 2023 testnet launch

util/constant/src/hardfork/testnet.rs
backport
* https://github.com/nervosnetwork/ckb/pull/4037
Tests 
- Unit test
Side effects
```release-note
```
=> backport 4037

Cargo.lock
Fix hermit-abi yanked, reported by [security-audit](https://github.com/nervosnetwork/ckb/actions/runs/5462479954/jobs/9941907370?pr=4059) check.
- Upgrade hermit-abi 
Tests 
- Unit test
Side effects
- None
```release-note
```
=> Fix dependency `hermit-abi` yanked

Cargo.lock, Cargo.toml, rpc/Cargo.toml, sync/Cargo.toml, sync/src/relayer/mod.rs
Tests 
- Unit test
Side effects
- None
```release-note
```
=> Fix `Relayer::request_proposal_txs`

sync/src/types/mod.rs
Fix `PendingCompactBlockMap`'s comment.
Tests 
- Unit test
Side effects
- None
```release-note
```
=> docs: Fix `PendingCompactBlockMap` comment

miner/src/miner.rs, util/stop-handler/src/stop_register.rs
Issue Number: close #4062
Proposal: Trivial fix when nonce limitation reached.
Tests 
- Unit test
Side effects
```release-note
```
=> terminate miner process when nonce limit reached

spec/src/consensus.rs, spec/src/lib.rs
light client activation parameters
Tests 
- Unit test
Side effects
```release-note
```
=> [rc/v0.110.x] chore: light client activation parameters

spec/src/consensus.rs, spec/src/lib.rs
light client activation parameters
Tests 
- Unit test
Side effects
```release-note
```
=> chore: light client activation parameters

script/src/verify.rs
- Fix typo
Tests 
Side effects
- None
```release-note
```
=> Fix `TransactionScriptsVerifier::chunk_run` comment

network/src/protocols/mod.rs, network/src/protocols/support_protocols.rs
backport #4115
Tests
- Unit test
```release-note
```
=> backport #4115

Cargo.lock, script/Cargo.toml
backport https://github.com/nervosnetwork/ckb/pull/4119
Tests 
- Unit test
Side effects
```release-note
```
=> backport 4119

script/src/syscalls/spawn.rs, script/src/verify.rs
backport https://github.com/nervosnetwork/ckb/pull/4123
Tests 
- Unit test
Side effects
```release-note
```
=> backport 4123

sync/src/utils.rs
backport #4129 to v0.111.0
- Parse RelayV3's message name
Tests 
- Unit test
Side effects
- None
```release-note
```
=> Backport #4129

docs/hashes.toml, miner/src/worker/dummy.rs, resource/specs/dev.toml, spec/src/consensus.rs, spec/src/lib.rs, spec/src/tests/mod.rs, tx-pool/src/chunk_process.rs, tx-pool/src/process.rs, tx-pool/src/util.rs, verification/contextual/src/contextual_block_verifier.rs, verification/src/tests/transaction_verifier.rs, verification/src/transaction_verifier.rs
backport https://github.com/nervosnetwork/ckb/pull/4126
Tests 
- Unit test
Side effects
```release-note
```
=> [v0.110.x] backport 4126

.github/workflows/package.yaml, Cargo.lock, Cargo.toml, Makefile, rpc/Cargo.toml, sync/Cargo.toml, sync/src/relayer/mod.rs
backport 
* https://github.com/nervosnetwork/ckb/pull/4061
* https://github.com/nervosnetwork/ckb/pull/4099
Tests 
- Unit test
Side effects
```release-note
```
=> backport rc/v0.110.x

network/src/peer_store/addr_manager.rs, network/src/peer_store/peer_store_impl.rs, network/src/tests/mod.rs, network/src/tests/peer_store.rs
Backport  #4133
Tests
- Unit test
- 
```release-note
```
=> Backport  #4133

network/src/network.rs
reduce some debug log levle
Tests
- Unit test
```release-note
```
=> chore: reduce some log level

util/gen-types/src/core.rs
backport #4151
`ScriptHashType` should derive `Hash`
Tests 
- Unit test
Side effects
- None
```release-note
```
=> Backport #4151 to `rc/0.111.x`

Cargo.lock, db/Cargo.toml, util/indexer/Cargo.toml
Update RocksDB to 8.5.4
https://github.com/facebook/rocksdb/releases/tag/v8.5.4
https://github.com/facebook/rocksdb/releases/tag/v8.5.3
Tests 
- Unit test
Side effects
```release-note
```
=> chore: Update RocksDB to 8.5.4

Cargo.lock
This PR want to fix https://github.com/nervosnetwork/ckb/issues/4268
Tests 
- Unit test
Side effects
- None
```release-note
```
=> Upgrade zerocopy, fix RUSTSEC-2023-0074

.github/workflows/package.yaml
Need to merge:
- https://github.com/nervosnetwork/ckb-cli/pull/568
- https://github.com/nervosnetwork/ckb/pull/4179
- Upgrade `ckb-cli` to `v1.6.0`(static linked openssl)
Tests 
- Unit test
Side effects
- None
```release-note
```
=> Upgrade `ckb-cli` to `v1.6.0`

docker/hub/Dockerfile, docker/hub/Dockerfile-aarch64
Fix base image name for ckb's `Dockerfile`
Tests 
- Unit test
Side effects
- None
```release-note
```
=> Fix `Dockerfile`'s base image name

tx-pool/src/block_assembler/mod.rs
optimize block assembler notify fn, skip block template lock access and json conversion when notify config is empty.
Tests 
- Unit test
```release-note
```
=> chore: optimize block assembler notify fn

util/constant/src/hardfork/testnet.rs
Planned activation on the test network around Feb 5. Binary version 0.114 scheduled for release around Jan 20.
Tests 
- Unit test
- 
Side effects
```release-note
```
=> chore: 2nd hardfork testnet activation params

Makefile
https://nexte.st/book/other-options.html#runner-options
- Add `--no-fail-fast` argument for `cargo-nextest`
Tests 
Side effects
- None
```release-note
```
=> Add `--no-fail-fast` argument for `cargo-nextest`

Cargo.lock
Issue Number: close #4316
- Upgrade shlex from 1.2.0 to 1.3.0, fix RUSTSEC-2024-0006
Tests 
- Unit test
Side effects
- None
```release-note
```
=> Upgrade shlex from 1.2.0 to 1.3.0, fix RUSTSEC-2024-0006

ckb-bin/src/subcommand/daemon.rs
Fix typo, `cbk` should be `ckb`.
Tests 
Side effects
- None
```release-note
```
=> Fix ckb daemon error message

Cargo.lock
Issue Number: close #4367
- Upgrade mio from 0.8.7 to 0.8.11
Tests 
- Unit test
Side effects
- None
```release-note
```
=> Fix RUSTSEC-2024-0019 #4367, upgrade mio from 0.8.9 to 0.8.11

Cargo.lock
We have updated rust-toolchain to 1.75.0, then we can do `cargo update`
- Update `Cargo.lock` by `cargo update`
Tests 
- Unit test
Side effects
- None
```release-note
```
=> Update Cargo.lock by `cargo update`

devtools/ci/check-cargotoml.sh, resource/src/lib.rs
=> chore: fix typos

test/src/node.rs
Fix https://github.com/nervosnetwork/ckb/actions/runs/8467446233/job/23198302827
- Add `ckb_logger::` prefix for `info!` macro in integration test.
Tests 
- Unit test
Side effects
- None
```release-note
```
=> Add `ckb_logger::` prefix for `info!` macro

test/src/node.rs
Fix https://github.com/nervosnetwork/ckb/actions/runs/8476421326/job/23225927638
- Use `Debug` formatter for `kill_gracefully`'s `kill_output`
Tests 
- Unit test
Side effects
- None
```release-note
```
=> Use `Debug` formatter for ckb_test's kill_output

test/src/specs/tx_pool/mod.rs
Fix https://github.com/nervosnetwork/ckb/actions/runs/8477258515/job/23227915469
Tests 
- Unit test
Side effects
- None
```release-note
```
=> ckb-test: import `pool_persisted` on Windows

ckb-bin/src/subcommand/daemon.rs, freezer/src/freezer_files.rs, rpc/README.md, util/jsonrpc-types/src/blockchain.rs, util/jsonrpc-types/src/lib.rs, util/types/src/core/error.rs
=> chore: remove repetitive words in comment

test/src/specs/relay/get_block_proposal_process.rs, tx-pool/src/component/pool_map.rs, util/proposal-table/src/lib.rs
Fix some typos in comments
Tests 
- Unit test
Side effects
```release-note
```
=> Fix some typos in comments

rpc/README.md, rpc/src/module/experiment.rs, rpc/src/module/indexer.rs, rpc/src/server.rs, spec/src/tests/mod.rs
fix some typos in comments
Tests 
```release-note
```
=> rpc,spec: fix some typos in comments

sync/src/synchronizer/mod.rs
Backport #4439
When CKB is in the Header Sync phase, display the estimated time required to synchronize to the latest header.
```
2024-04-28 11:05:23.194 +00:00 BlockDownload INFO ckb_sync::synchronizer  best known header 730000-Byte32(0xbc76d5fde38937fa55761d87518c465346bd6cd50d37d53592c639fd83cb2a2c), CKB is syncing to latest Header to find the assume valid target: Byte32(0xc394fa4c5e5032c49f3502d4fd8054ead76ff693a54ac90757e441b5119afcaf). Please wait. Need 28 minutes to sync to the latest Header.
2024-04-28 11:05:28.299 +00:00 BlockDownload INFO ckb_sync::synchronizer  best known header 740000-Byte32(0x56ea0217b500acc00864b5d72c2c745f5edeb56e5645f46f509bae9ece0824ea), CKB is syncing to latest Header to find the assume valid target: …
```
=> Backport #4439 Implement Logging of Estimated Duration for Syncing to Most Recent Header

rpc/README.md, rpc/src/module/pool.rs
Backport #4447
- Remove unreachable error for test_tx_pool_accept
Tests 
- Unit test
Side effects
- None
```release-note
```
=> Backport #4447, Remove unreachable error for test_tx_pool_accept

ckb-bin/src/lib.rs, ckb-bin/src/subcommand/daemon.rs, devtools/init/README.md, util/light-client-protocol-server/src/tests/utils/network_context.rs
fix some typos
fix some typos
Tests 
- Unit test
Side effects
```release-note
```
=> chore: fix some typos

tx-pool/src/component/pool_map.rs, tx-pool/src/component/tests/pending.rs, tx-pool/src/pool.rs
this PR contains two minor refactor commits:
1. refactor fill_proposals fn, removed the length checking in each iteration and make it easier to understand.
2. refactor score_sorted_iter_by fn, removed the vec#contains for single status filtering.
Tests 
- Unit test
```release-note
```
=> chore: minor refactor on tx pool

resource/src/lib.rs, script/src/error.rs
fix some comments
Tests 
- Unit test
Side effects
```release-note
```
=> chore: fix some comments

util/launcher/src/lib.rs
Temporarily disable the use of data2 in the configuration to prevent misconfiguration from causing an inability to unlock.
Tests 
```release-note
```
=> chore: Disable use of data2 in block_assembler config

util/launcher/src/lib.rs
backport https://github.com/nervosnetwork/ckb/pull/4504
```release-note
```
=> [backport] chore: Disable use of data2 in block_assembler config

sync/src/synchronizer/get_blocks_process.rs
- Fix debug log message for GetBlockProcess
Tests 
- Unit test
Side effects
- None
```release-note
```
=> Fix debug log message for GetBlocksProcess

script/src/verify/tests/ckb_latest/features_since_v2021.rs
Fix the panic that may be caused by test not covering the branch
Tests
- Unit test
```release-note
```
=> test: fix test random panic

test/src/specs/sync/sync_invalid.rs
Improve Integration test
- Integration test: SyncInvalid, when node1 should wait to ban node0
Tests 
- Unit test
Side effects
- None
```release-note
```
=> Integration Test: SyncInvalid should wait node1 ban node0

test/src/node.rs
- Increase waiting_for_sync timeout to 120s
Tests 
Side effects
- None
```release-note
```
=> Integration Test: Increase wait_for_sync timeout to 120s

test/src/main.rs
- Let SyncChurn run on the last
Tests 
Side effects
- None
```release-note
```
=> Integration Test: Let SyncChurn run at last

test/src/node.rs, test/src/specs/tx_pool/send_large_cycles_tx.rs
- Integration Test: Add more log when node crash
Tests 
Side effects
- None
```release-note
```
=> Integration Test: Add more log when node crash

deny.toml, test/src/node.rs
- Integration Test: all specs wait unverifieid blocks finish before test
Tests 
- Unit test
Side effects
- None
```release-note
```
=> Integration Test: wait find unverified blocks finish for all specs

test/src/node.rs
Tests 
- Unit test
Side effects
```release-note
```
=> debug macos ci

tx-pool/src/process.rs
We need more logs for monitoring abnormal behaviors.
Add `info` logs for verification failures.
Tests 
- Unit test
```release-note
```
=> chore: add verify log for monitor

test/src/specs/fault_injection/randomly_kill.rs
- Ingtegration Test: Kill gracefully for RandomlyKill
Tests 
- Unit test
Side effects
- None
```release-note
```
=> Integration Test: kill_gracefully on RandomlyKill

.github/workflows/ci_integration_tests_windows.yaml
- Windows CI use windows-latest runner
Tests 
Side effects
- None
```release-note
```
=> CI: windows integration use windows-latest

.github/workflows/ci_integration_tests_windows.yaml, chain/src/init.rs, chain/src/init_load_unverified.rs, chain/src/lib.rs, chain/src/tests/find_fork.rs, chain/src/verify.rs, deny.toml, devtools/ci/check-relaxed.sh, devtools/ci/ci_main.sh, network/src/network.rs, rpc/README.md, rpc/src/module/pool.rs, script/src/verify/tests/ckb_latest/features_since_v2021.rs, shared/src/shared.rs, shared/src/types/header_map/kernel_lru.rs, sync/src/synchronizer/mod.rs, sync/src/tests/types.rs, test/src/main.rs, test/src/node.rs, test/src/rpc.rs, test/src/specs/fault_injection/randomly_kill.rs, test/src/specs/sync/sync_churn.rs, test/src/specs/tx_pool/replace.rs, test/src/specs/tx_pool/send_large_cycles_tx.rs, tx-pool/src/pool.rs, tx-pool/src/process.rs, tx-pool/src/service.rs, tx-pool/src/verify_mgr.rs, util/app-config/src/tests/bats_tests/cli_test.sh, util/systemtime/src/lib.rs
Backport: #4605, #4600, #4606, #4612, #4615
=> [Backport] merge several fixes into 118 for next rc release

util/rich-indexer/resources/create_postgres_index.sql, util/rich-indexer/resources/create_postgres_table.sql, util/rich-indexer/resources/create_sqlite_index.sql, util/rich-indexer/resources/create_sqlite_table.sql, util/rich-indexer/src/indexer/remove.rs, util/rich-indexer/src/store.rs
Simplify the code：
1. use `IF NOT EXISTS` to create SQL
2. early return on `or` judgment
Tests
- Unit test
```release-note
```
=> chore: simplify the code

Cargo.lock, Cargo.toml, rpc/Cargo.toml, rpc/src/server.rs
upgrade axum/jsonrpc-utils
Tests
- Unit test
```release-note
```
=> chore: upgrade axum

Cargo.lock
upgrade tentacle/libc/anyhow/bytes
Tests
- Unit test
```release-note
```
=> chore: upgrade deps

script/src/verify.rs
fix code fmt
Tests 
- Unit test
```release-note
```
=> chore: fix fmt

script/src/error.rs, script/src/syscalls/tests/mod.rs, util/types/src/core/error.rs
Fix cargo clippy
Tests 
- Unit test
```release-note
```
=> chore: fix clippy

script/src/syscalls/tests/mod.rs
This reverts commit 62fdfe7975a416baf98f5228b16b003b8c1168a2.
Tests 
- Unit test
Side effects
```release-note
```
=> Revert "chore: make clippy happy"

Cargo.lock, deny.toml, network/src/peer_store/addr_manager.rs, network/src/peer_store/mod.rs, network/src/peer_store/peer_store_impl.rs, network/src/peer_store/types.rs
1. Support encode/decode `Onion3` protocol
2. Temporarily disable onion3 protocol propagation between nodes
Tests
- Unit test
```release-note
```
=> chore: upgrade multiaddr

network/src/network.rs
- Add an log when a addr removed from network_state.public_addrs
Tests 
Side effects
- None
```release-note
```
=> log: add INFO log when a addr removed from network_state.pulic_addrs

network/src/network.rs
- Only print public_addr removed log when it realy removed
Tests 
Side effects
- None
```release-note
```
=> ckb-network: print remove public_addr log when it really removed

devtools/ci/ci_main.sh, network/src/network.rs, script/src/lib.rs, script/src/scheduler.rs, script/src/types.rs, shared/src/shared_builder.rs
Backport:
* https://github.com/nervosnetwork/ckb/pull/4820
* https://github.com/nervosnetwork/ckb/pull/4817
* https://github.com/nervosnetwork/ckb/pull/4819
* https://github.com/nervosnetwork/ckb/pull/4822
* https://github.com/nervosnetwork/ckb/pull/4815
Tests 
- Unit test
```release-note
```
=> backport rc/0.200.x

devtools/smoking_test/check-migrate.sh, util/fee-estimator/src/estimator/confirmation_fraction.rs
fix some typos in comments
Tests 
- Unit test
Side effects
```release-note
fix some typos in comments
```
=> chore: fix some typos in comments

deny.toml
allow all deny item
Tests 
- Unit test
```release-note
```
=> chore: allow deny

script/src/scheduler.rs
Tests 
- Unit test
Side effects
```release-note
```
=> chore: Removed unneeded comments after refactoring

.github/actions/ci_prologue/ci_prologue.sh, .github/workflows/backport.yml, .github/workflows/benchmark.yml, .github/workflows/ci_aarch64_build_ubuntu.yaml, .github/workflows/ci_benchmarks_macos.yaml, .github/workflows/ci_benchmarks_ubuntu.yaml, .github/workflows/ci_benchmarks_windows.yaml, .github/workflows/ci_cargo_deny_ubuntu.yaml, .github/workflows/ci_integration_tests_macos.yaml, .github/workflows/ci_integration_tests_ubuntu.yaml, .github/workflows/ci_integration_tests_windows.yaml, .github/workflows/ci_linters_macos.yaml, .github/workflows/ci_linters_ubuntu.yaml, .github/workflows/ci_quick_checks_macos.yaml, .github/workflows/ci_quick_checks_ubuntu.yaml, .github/workflows/ci_unit_tests_macos.yaml, .github/workflows/ci_unit_tests_ubuntu.yaml, .github/workflows/ci_unit_tests_windows.yaml, .github/workflows/package.yaml, .github/workflows/scheduled_audit.yaml, .github/workflows/smoking_test.yaml, Cargo.lock
Upgrade CI images: from Ubuntu 20.04 to Ubuntu 22.04
Tests 
- Unit test
```release-note
```
=> ci: upgrade ci images

.github/workflows/package.yaml
Upgrade ckb-cli to v1.14.0: https://github.com/nervosnetwork/ckb-cli/releases/tag/v1.14.0
Tests 
Side effects
- None
```release-note
```
=> CI: upgrade ckb-cli to 1.14.0,https://github.com/nervosnetwork/ckb-cli/releases/tag/v1.14.0

tx-pool/src/component/tests/chunk.rs, tx-pool/src/component/verify_queue.rs
Resolve: https://github.com/nervosnetwork/ckb/actions/runs/15485272643/job/43598488854
- Apply: `cargo clippy --fix`
Tests 
- Unit test
Side effects
- None
```release-note
```
=> Apply `cargo clippy --fix, fix: https://github.com/nervosnetwork/ckb/actions/runs/15485272643/job/43598488854

network/src/protocols/hole_punching/component/connection_request_delivered.rs, network/src/protocols/hole_punching/component/connection_sync.rs, tx-pool/src/component/tests/chunk.rs, tx-pool/src/component/verify_queue.rs, util/metrics/src/lib.rs
Add some monitoring metrics to the hole punching protocol.
Tests
- Unit test
```release-note
```
=> feat: hole punching protocol metrics

chain/src/init.rs, tx-pool/src/component/pool_map.rs, util/fee-estimator/src/estimator/confirmation_fraction.rs
fix some minor issues in the comments
Tests 
- Unit test
Side effects
```release-note
```
=> chore: fix some minor issues in the comments

network/src/network.rs, network/src/protocols/feeler.rs, network/src/protocols/identify/mod.rs, network/src/protocols/mod.rs, network/src/protocols/support_protocols.rs, rpc/src/module/miner.rs, rpc/src/module/test.rs, sync/src/relayer/mod.rs, sync/src/relayer/tests/block_transactions_process.rs, sync/src/relayer/tests/compact_block_process.rs, sync/src/relayer/tests/get_block_proposal_process.rs, sync/src/relayer/tests/get_transactions_process.rs, sync/src/relayer/tests/helper.rs, sync/src/tests/mod.rs, sync/src/tests/sync_shared.rs, sync/src/tests/synchronizer/functions.rs, sync/src/utils.rs, tx-pool/src/process.rs, tx-pool/src/service.rs, util/launcher/src/lib.rs, util/light-client-protocol-server/src/components/get_blocks_proof.rs, util/light-client-protocol-server/src/components/get_transactions_proof.rs, util/light-client-protocol-server/src/tests/utils/network_context.rs
After hardfork, the compatible network can be removed
Tests 
- Unit test
```release-note
```
=> chore: remove compatible network

script/src/scheduler.rs
In the ckb-script refactoring update of ckb v0.202, the ability to pass parameters to the root VM was accidentally disabled, causing some surrounding tools (currently known to be ckb-debugger) to break.
Provide a public function `set_root_vm_args` to set the args of the root vm.
Tests 
- Unit test
```release-note
```
=> feat(script): allows modification of the root VM's parameters

chain/src/utils/forkchanges.rs, chain/src/verify.rs, spec/src/consensus.rs, tx-pool/src/process.rs, tx-pool/src/service.rs, tx-pool/src/util.rs, verification/src/header_verifier.rs, verification/src/tests/header_verifier.rs
meepo have been active for over 1 months, the exact activation code is no longer interesting, rfc0048 was enforced back to genesis  is a code simplification, makes it easier to understand, and reduces technical debt.
Tests 
- Unit test
Side effects
```release-note
```
=> chore: bury hardfork activation
