nervosnetwork/ckb

Makefile
```
↪  make security-audit                                                                                                                                Wed Nov 28 19:21:09 CST 2018
cargo-audit 0.5.2
Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
Loaded 14 security advisories (from /Users/rain/.cargo/advisory-db)
Scanning Cargo.lock for vulnerabilities (353 crate dependencies)
error: Vulnerable crates found!
ID:	 RUSTSEC-2018-0003
Crate:	 smallvec
Version: 0.2.1
Date:	 2018-07-19
URL:	 https://github.com/servo/rust-smallvec/issues/96
Title:	 Possible double free during unwinding in SmallVec::insert_many
Solution: upgrade to: >= 0.6.3 OR ^0.3.4 OR ^0.4.5 OR ^0.5.1
ID:	 RUSTSEC-2018-0001
Crate:	 untrusted
Version: 0.5.1
Date:	 2018-06-21
URL: …
```
=> chore: add a make task `security-audit` to audit Cargo.lock

script/src/syscalls/fetch_script_hash.rs, script/src/syscalls/mod.rs
For some reason I forgot to add logic for fetching output cell lock
hash in VM syscalls, which is in fact possible to fetch.
=> fix: fix missing output lock hash

sync/src/synchronizer/mod.rs, sync/src/synchronizer/peers.rs, sync/src/tests/mod.rs, sync/src/tests/synchronizer.rs
Fix duplicated Headers messages between peers.
Fix the logic by correct the IBD and `sync` flag to their original intention.
=> fix: fix IBD sync process

chain/src/chain.rs, core/src/block.rs, core/src/header.rs, core/src/transaction.rs, shared/src/index.rs, shared/src/shared.rs, shared/src/store.rs, sync/src/relayer/compact_block_process.rs, sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/header_view.rs, sync/src/synchronizer/headers_process.rs, sync/src/synchronizer/mod.rs, verification/src/block_verifier.rs, verification/src/tests/dummy.rs
=> fix: remove hash caches to avoid JSON deserialization bug

rpc/src/server.rs
Now that we have `BlockNumber`.
=> refactor: replace from/to u64 type in favor of BlockNumber

chain/src/chain.rs, rpc/src/server.rs, rpc/src/types.rs, script/src/syscalls/mod.rs, script/src/verify.rs, src/cli/run_impl.rs
Although `outpoint` is well recgonized (especially in Bitcoin world) we have the type as `OutPoint` so it makes sense to follow the variable naming convention. 
See #91.
=> refactor: rename outpoint to out_point as its type is OutPoint

src/cli/args.rs
fix  panic when supply args but not specify subcommand
such as `./target/release/ckb -c nodes/node1.json`
=> fix: cli panic

Cargo.lock, core/src/script.rs, core/src/transaction.rs
use `size_of` replace the hardcode.
bump numext from 0.1.0 to 0.1.2 , use new const function get mem size.
=> refactor: Use `size_of` replace the hardcode

rpc/doc.md
1. [parameters](https://github.com/nervosnetwork/ckb/blob/develop/rpc/doc.md#parameters-5) of `send_transaction` are hard to read.
2. [`local_node_id`](https://github.com/nervosnetwork/ckb/blob/develop/rpc/doc.md#local_node_id) repeated
=> docs(rpc): fix layout and remove repeated doc

script/src/syscalls/mod.rs
This starts as a discussion in one [RFC](https://github.com/nervosnetwork/rfcs/pull/53#discussion_r243179777), turns out the syscall parameters used right now do not make too much sense. Since now we are still in development phase, it's better we fix this now than living with it forever.
=> fix: Regulate parameters used in syscalls

README.md
It can no longer parse this repository after upgrading to edition 2018
Refs https://github.com/srijs/deps.rs/pull/33
=> doc: remove deps.rs badge

shared/src/shared.rs, sync/src/relayer/mod.rs, sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/mod.rs
I searched through the `fn clone`, and found the other three places. Fixed one, but the other two could not simply derive Clone, it occurred some strange compile error. I reckon the problem is https://github.com/rust-lang/rust/issues/26925.
=> refactor: use derive clone and some tiny improvements

protocol/src/builder.rs, protocol/src/convert.rs, protocol/src/protocol.fbs, protocol/src/protocol_generated.rs, script/src/syscalls/builder.rs, script/src/verify.rs, sync/src/relayer/block_transactions_process.rs, sync/src/relayer/compact_block.rs, sync/src/relayer/get_block_proposal_process.rs, sync/src/relayer/get_block_transactions_process.rs, sync/src/synchronizer/get_blocks_process.rs, sync/src/synchronizer/get_headers_process.rs
This PR did code refactoring for H256 serialization. Needs rebase after https://github.com/nervosnetwork/ckb/pull/119 
TODO:
*NO* `difficulty` / U256 
*YES*`proposal_transactions` and `short_ids` / [u8; 10]
=> refactor: unify h256 and ProposalShortId serialization

README.md
In the original version of readme, the content of how to make contribution is mixed with the development flow.
IMO by adding a title to this part of content can make it more easier for contributors to find this information and thus helps to attract contributors.
This little change could make community developers feel like they are more than welcomed to this project. This project is not just for a certain group of developers at Cryptape. It's also for the community members who wants to make this world a better place.
So pls kindly consider this pr, thx.
=> docs: add how to contribute title to README

Cargo.lock, Cargo.toml, protocol/Cargo.toml, protocol/src/builder.rs, util/merkle-root/Cargo.toml, util/merkle-root/src/lib.rs, util/merkle-tree/Cargo.toml, util/merkle-tree/src/hash.rs, util/merkle-tree/src/lib.rs, util/merkle-tree/src/proof.rs, util/merkle-tree/src/tree.rs
This PR implements a Merkle Tree, replaced old `merkle_root` with this new struct and added proof generation function to `FilteredBlock`.
We changed the Merkle Tree internal nodes storage layout. It is a BREAKING change, need to delete old chain data and restart from genesis block.
Closes #131 
Closes #145
=> feat: add merkle-tree

devtools/release/bump.sh
Change `-i .bak` to `-i.bak`, which works for both BSD and Linux.
=> chore: make bump.sh compatible for Linux

.travis.yml, core/src/lib.rs
try to improve travis build time via `cargo sweep`
Ran for 15 min 23 sec without 3rd lib rebuilding:
https://travis-ci.com/nervosnetwork/ckb/builds/97910636
========outdated below========
~~reduce `rustup` installation time from 3xs to 0.7s~~
before: 33.68s
```
curl -sSf https://build.travis-ci.com/files/rustup-init.sh | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
info: downloading installer
info: syncing channel updates for '1.32.0-x86_64-apple-darwin'
```
after: 0.70s 
```
$ curl -sSf https://build.travis-ci.com/files/rustup-init.sh | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
info: downloading installer
info: updating existing rustup installation
Rust is installed now. Great!
```
=> chore: travis cache tweak

nodes_template/default.json, src/setup.rs
Chain config should be at the same level as `network`, as they're the same level modules.
This PR changes chain config to:
```json
"chain": {
"spec": "path/to/chain/spec.json"
}
```
=> refactor chain spec config

Cargo.lock, network/src/identify_service.rs, network/src/network.rs, network/src/network_service.rs, rpc/Cargo.toml, rpc/doc.md, rpc/src/module/net.rs, util/jsonrpc-types/src/lib.rs, util/jsonrpc-types/src/local_node.rs
* Rename RPC `local_node_id` to `local_node_info`
* Change RPC output:
```
{
"id": 2,
"jsonrpc": "2.0",
"result": {
"addresses": [
{
"address": "/ip4/0.0.0.0/tcp/12344/p2p/QmWRU2NSro4wKgVbFX6y8SPFkcJ1tE2X5xzk9msMhdRmdS",
"score": 1
}
],
"node_id": "QmWRU2NSro4wKgVbFX6y8SPFkcJ1tE2X5xzk9msMhdRmdS",
"version": "0.5.0"
}
}
```
=> feat: Upgrade RPC local_node_id to local_node_info

sync/src/synchronizer/mod.rs, sync/src/tests/relayer.rs, sync/src/tests/synchronizer.rs
=> test: skip verification in sync testing code

miner/src/client.rs, miner/src/lib.rs, miner/src/miner.rs, src/cli/miner.rs, sync/src/relayer/block_transactions_process.rs, sync/src/relayer/compact_block_process.rs, sync/src/relayer/mod.rs, sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/mod.rs, util/src/lib.rs
Upgradable reads block plain reads, this behavior does not match the docs
=> fix: remove use of upgradable reads

docs/data-structures.md
#308 
This document explains "What does each field mean?"
As for "Who is responsible to fill them?" and "How to generate them?" , I think it's more appropriate to document them it in another place, which I'm also working on in progress.
[preview](https://github.com/Mine77/ckb/blob/docs/add-data-structure/docs/data-structures.md)
=> docs: add documents for the data structure of Cell/Script/Transaction/Block

docs/data-structures.md
two updates:
* Add notice to explicitly inform that the version field is always 0, which is different from Bitcoin, where version is always 1.
* Add hash of transaction to the data structure.
=> docs: update version description and add hash of transaction [skip ci]

verification/src/block_verifier.rs, verification/src/error.rs, verification/src/tests/block_verifier.rs, verification/src/transaction_verifier.rs
* remove redundant EmptyVerifier
* enforce `type` field of a cellbase output cell must be absent
=> feat: enforce `type` field of a cellbase output cell must be absent

core/src/transaction_meta.rs, shared/src/cell_set.rs, shared/src/shared.rs
Index whether a tx is a cellbase in the chain, prepare for the cellbase outputs maturity checking.
Now saving the cellbase index and block number in the `TransactionMeta`, there is another implementation which creates a `HashMap<tx_hash, number>`. The second one may be a little memory saving, but this one is more simple. I think both are ok.
https://github.com/nervosnetwork/ckb/issues/54
=> feature: index whether a tx is a cellbase in the chain

Cargo.lock, bors.toml, db/Cargo.toml
rocksdb 0.11.0 -> 0.12.0
tokio-sync 0.1.3 -> 0.1.4
proptest 0.9.1 -> 0.9.2
=> chore: bump several deps

network/src/peer_store/sqlite.rs, network/src/peer_store/sqlite/peer_store.rs, network/src/protocols/mod.rs
* Peer Store no such table
* get peer index panic
=> fix: network panic errors

Makefile
Dir test is excluded from the workspace in c0992b15894a301ec040cb442745ace39db4ae1a .
This commit will check fmt and clippy in the test directory so we can discover
errors earlier.
=> chore: include dir test in ci

core/src/script.rs, script/src/verify.rs, util/crypto/src/secp/signature.rs
Should I delete this unit test?
https://github.com/nervosnetwork/ckb/blob/32be9aa704fce9c269b93b247b64e5a87dece575/util/crypto/src/secp/signature.rs#L159-L173
=> chore: use new constructors to make fixed structs more readable

Cargo.lock, db/Cargo.toml, db/src/diskdb.rs
I have test this patch with a corrupted database (from @TheWaWaR).
But I can not reproduce the bug by myself, so I did not write any test case.
The database works, but the data is still corrupted (**because `header` add new fields?**):
```
2019-04-09 07:39:24.154 +00:00 main WARN ckb_db::diskdb  Try repairing the rocksdb since Corruption: SST file is ahead of WALs ...
2019-04-09 07:39:24.384 +00:00 main WARN ckb_db::diskdb  Try opening the repaired rocksdb ...
thread 'main' panicked at 'header deserializing should be ok: Custom("invalid length 3, expected a 0x-prefixed hex string with 64 digits")', src/libcore/result.rs:997:5
stack backtrace:
```
Ref:
- [RocksDB: Repairer](https://github.com/facebook/rocksdb/wiki/RocksDB-Repairer)
- [RocksDB: WAL Recovery …
=> fix: try to repair a corrupted rocksdb automatically

core/src/script.rs, core/src/transaction.rs, miner/src/block_assembler.rs, protocol/src/builder.rs, protocol/src/convert.rs, protocol/src/protocol.fbs, protocol/src/protocol_generated.rs, protocol/src/protocol_generated_verifier.rs, script/src/syscalls/mod.rs, script/src/verify.rs, spec/src/lib.rs, util/jsonrpc-types/src/blockchain.rs
NOTE: This is a breaking change
=> feat: Remove version from Script

Cargo.lock, miner/src/block_assembler.rs, miner/src/miner.rs, rpc/Cargo.toml, rpc/src/module/chain.rs, rpc/src/module/miner.rs, rpc/src/module/pool.rs, rpc/src/module/trace.rs, test/Cargo.toml, test/src/node.rs, test/src/rpc.rs, test/src/specs/mining.rs, util/jsonrpc-types/Cargo.toml, util/jsonrpc-types/src/block_template.rs, util/jsonrpc-types/src/blockchain.rs, util/jsonrpc-types/src/proposal_short_id.rs
This PR actually contains 2 parts:
* refactor: Use TryFrom when parsing RPC request data
* feat: Change capacity field to String type in RPC
=> feat: Change all u64 fields in RPC to String

network/src/network.rs
fix https://github.com/nervosnetwork/ckb/issues/436
=> fix: RPC `local_node_info` returns duplicated addr

.gitignore, docker/hub/Dockerfile, docs/configure.md, docs/quick-start.md, resource/src/lib.rs, src/setup/app_config.rs, src/setup/mod.rs
This is a **BREAKING CHANGE**.
It is a mechanism to avoid starting ckb in a wrong directory by accident.
=> feat: ckb must loads config files from file system.

pow/src/cuckoo.rs, pow/src/lib.rs, src/setup/mod.rs, src/setup/sentry_config.rs, util/build-info/src/lib.rs
Add following tags to help locating bugs:
- `release.dirty`: is the binary built from a dirty git repository?
- `release.pre`: is a pre release?
- `spec.name`: chain spec name
- `spec.pow`: PoW engine
- `genesis`: hash of the genesis block
=> chore: add sentry tags

chain/src/chain.rs, chain/src/tests/basic.rs, chain/src/tests/util.rs, core/src/cell.rs, script/src/verify.rs, shared/src/chain_state.rs, shared/src/tx_pool/types.rs, spec/src/consensus.rs, sync/src/relayer/transaction_process.rs, sync/src/tests/relayer.rs, verification/src/block_verifier.rs, verification/src/error.rs, verification/src/tests/transaction_verifier.rs, verification/src/transaction_verifier.rs
#367 
> Updated,
> https://github.com/nervosnetwork/ckb/pull/367/files#diff-b2197becbc6452c42618e284e3dbf52eR226
> But I am not sure whether the cellbase_maturity and cell_set are correct, because the `max_cycles` coming from the function params, and the `cellbase_maturity` coming from the `self.consensus`.
> 
> @jjyr is going to take a look at this PR.@quake Do you prefer to merge it after your store refactoring, or it doesn't matter.
> Please rebase this PR to latest develop and ensure:
> 
> Make this a configurable option in chain spec.
> Only enable it in testnet chain spec. Disable it in dev and integration.
=> feature: cellbase maturity verify

miner/src/block_assembler.rs, rpc/README.md, rpc/src/module/chain.rs, util/jsonrpc-types/src/block_template.rs, util/jsonrpc-types/src/blockchain.rs, util/jsonrpc-types/src/cell.rs, util/jsonrpc-types/src/lib.rs
+ chore: let all jsonrpc types be public (for client)
+ feat: change all `u64` fields in RPC to String and hide internal `Script` struct
+ chore: replace unnecessary `TryFrom` by `From`
+ docs: fix README.md for JSON-RPC protocols
- It's too difficult to distinguish differences between old and new versions for all protocols, so I rewrite all examples after do tests.
- [`shell` is not a keyword for highlight](https://github.com/github/linguist/blob/2734ca0134c0afe3c62ecb1ec8c721a28c8b9e63/lib/linguist/languages.yml#L4626-L4633)
https://github.com/nervosnetwork/ckb/blob/dbfb81cea902ba4d923f78685ed0b0bfddce7a3a/util/jsonrpc-types/src/cell.rs#L11-L15
This piece of code wasn't list for review.
But, `Capacity` was changed from `u64` to `String`, and the `Script` was changed from …
=> Modify jsonrpc types

Cargo.lock, core/Cargo.toml, core/src/script.rs
=> fix: incorrect occupied capacity computation for `Script`

Cargo.lock, script/Cargo.toml
This is a hotfix for VM bug fixed at here: https://github.com/nervosnetwork/ckb-vm/pull/47
Since it would result in CKB hanging there forever, it's better we handle this earlier as a hotfix than next VM upgrade.
=> hotfix: fix VM hang bug for certain invalid programs

miner/src/block_assembler.rs, pow/src/dummy.rs, pow/src/lib.rs, resource/specs/integration.toml, spec/src/consensus.rs
When I do tests in my laptop, the speed of product block is too slow.
Ref: #389
=> feat: add parameters to control the block generation rate in dummy mode

chain/src/chain.rs, chain/src/tests/basic.rs, chain/src/tests/delay_verify.rs, core/src/cell.rs, shared/src/chain_state.rs, shared/src/tests/cell_set.rs
This refactor PR removes `OutPoint` clone which was required by `seen_inputs` HashMap, and also fixed the bug which has been resolved in testnet by https://github.com/nervosnetwork/ckb/pull/516
=> refactor: CellProvider

resource/specs/dev.toml, resource/specs/integration.toml, resource/specs/testnet.toml
Fix the [integration tests](https://travis-ci.com/nervosnetwork/ckb/jobs/194822193).
BREAKING CHANGE:
- `initial_block_reward` in configuration files have to be updated.
The unit of it is changed from "CK Byte" to "CK Shannon".
=> fix: apply the new capacity to all configuration files

docs/get-ckb.md
for Ubuntu  apt install add param -y, to spare user manually type Y
=> chore: ubuntu apt add -y,avoid manually type Y

resource/ckb.toml
This is an experience value, refer to [bitcoin](https://github.com/bitcoin/bitcoin/blob/master/src/net.h#L42-L45).
=> chore: Change default ping interval and timeout

network/src/network.rs
When feeler added to peer registry in outbound peer service, the feeler will removed when peer disconnect. But if dial error, the feeler PeerId will remain in memory cause memory leak.
=> [ᚬtestnet] fix: Remove feeler in peer registry when dial error

Cargo.toml, src/main.rs, src/subcommand/mod.rs, src/subcommand/prof.rs, src/subcommand/run.rs, util/app-config/src/args.rs, util/app-config/src/cli.rs, util/app-config/src/lib.rs
Support `ckb prof` command
1. `cargo install flamegraph`
2. `sudo cargo flamegraph --bin ckb -- -C <node_dir> prof 1 500`
`prof` will re-process block `1..500`, then output the flame graph.
=> feat: support ckb prof command

Cargo.lock, shared/src/tx_pool/types.rs, sync/Cargo.toml, sync/src/relayer/transaction_process.rs, verification/src/error.rs
Refactoring ugly code,
Add `is_bad_tx` function on `PoolError` and `TransactionError`, use this method to detect a tx is intended bad tx or just caused by the different tip.
=> fix: testnet relay

miner/src/block_assembler.rs, rpc/README.md, rpc/src/module/chain.rs, rpc/src/module/pool.rs, shared/src/chain_state.rs, shared/src/shared.rs, shared/src/store.rs, shared/src/tx_pool/pool.rs, traits/src/chain_provider.rs, util/jsonrpc-types/src/blockchain.rs, util/jsonrpc-types/src/lib.rs, verification/src/tests/dummy.rs
1. Modify the return value of the `get_transaction` interface
2. Modify the return type of the `get_transaction`
=> refactor: merge two transaction rpc interface

benches/benches/process_block.rs, chain/src/tests/find_fork.rs, chain/src/tests/util.rs, miner/src/block_assembler.rs, shared/src/chain_state.rs, shared/src/error.rs, shared/src/shared.rs, shared/src/tests/no1.rs, shared/src/tests/no2.rs, shared/src/tests/shared.rs, src/subcommand/export.rs, src/subcommand/import.rs, src/subcommand/prof.rs, src/subcommand/run.rs, sync/src/synchronizer/mod.rs, sync/src/tests/relayer.rs, sync/src/tests/synchronizer.rs, verification/src/tests/commit_verifier.rs, verification/src/tests/uncle_verifier.rs
At startup:
- Read genesis hash from configuration files.
- Try to fetch tip header from database.
- (new) If tip header is existed, then fetch the 0th block hash from database.
- (new) Check if the 0th block hash was same as the genesis hash.
Replace several `expect(..)` by `Result`.
Add a lot of `unwrap()` in tests.
=> feat: check if genesis hash in config file was same as 0th block hash in db

core/src/cell.rs, script/src/verify.rs, shared/src/chain_state.rs, verification/src/tests/transaction_verifier.rs, verification/src/transaction_verifier.rs
Add lifetime to ResolvedTransaction, avoiding transaction clone
=> refactor: add lifetime to ResolvedTransaction

rpc/README.md, test/src/specs/pool.rs, test/src/specs/transaction_relay.rs, util/jsonrpc-types/src/blockchain.rs
Make `block_hash` always exist
Although I think the meaning of the block hash exist is not particularly large, but for the sake of unification...
This modification may present potential risks, and if someone does not build the state according to the standard, unexpected results may occur.
=> chore: make block hash always exist

resource/ckb-miner.toml, resource/ckb.toml
It helps to filter out events generated during development.
=> chore: enable sentry only in testnet

Cargo.lock, miner/src/block_assembler.rs, network/Cargo.toml, network/src/network.rs, network/src/protocols/mod.rs, rpc/src/module/miner.rs, rpc/src/module/pool.rs, src/subcommand/run.rs, sync/src/lib.rs, sync/src/net_time_checker.rs, sync/src/relayer/compact_block_process.rs, sync/src/relayer/get_block_proposal_process.rs, sync/src/relayer/get_block_transactions_process.rs, sync/src/relayer/mod.rs, sync/src/relayer/transaction_process.rs, sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/get_blocks_process.rs, sync/src/synchronizer/get_headers_process.rs, sync/src/synchronizer/headers_process.rs, sync/src/synchronizer/mod.rs, sync/src/tests/mod.rs, sync/src/tests/relayer.rs, sync/src/tests/synchronizer.rs, sync/src/types.rs, test/src/net.rs, test/src/specs/protocols.rs
**Main changes**:
1. Adjust relay filter size to avoid message flood
2. Send `getheaders` message when get UnknownParent Error
3. Fix send message to wrong protocol cause peer banned
4. Update `p2p` dependency
5. Fix BlockAssembler hold chain state lock most of the time when cellbase is large
=> fix: Testnet hotfix

network/src/protocols/mod.rs
Send network message to wrong protocol, this will cause the sender peer been banned.
=> fix: Send network message to wrong protocol

sync/src/relayer/mod.rs, sync/src/synchronizer/headers_process.rs, sync/src/synchronizer/mod.rs
Should only disconnect outbound not protected peer and the message length is less `MAX_HEADERS_LEN`
=> fix: Disconnect wrong peer when process getheaders message

Makefile, devtools/ci/install.sh, devtools/ci/script.sh
Since #96 is closed, we are able to run security-audit in CI now.
=> chore: run security-audit in CI

sync/src/relayer/compact_block_process.rs, sync/src/synchronizer/mod.rs
When IBD, received compact block message, can't find it's parent, do nothing
=> fix: Initial block download message storm

Cargo.lock, util/app-config/Cargo.toml
All crates are v0.11.0-pre, only ckb-app-config is v0.9.0-pre.
I'm not sure if it's a typo or not.
=> chore: fix version of ckb-app-config, bump to v0.11.0-pre

sync/src/relayer/mod.rs, sync/src/relayer/transaction_hash_process.rs, sync/src/relayer/transaction_process.rs, sync/src/types.rs
Only ask a transaction by hash from one peer, if 30 seconds passed we not get the transaction, we send the get transaction message to another peer.
=> perf: Improve relay tx by hash performance

rpc/README.md, rpc/src/module/pool.rs, shared/src/tx_pool/pool.rs, test/src/node.rs, test/src/rpc.rs, util/jsonrpc-types/src/lib.rs, util/jsonrpc-types/src/pool.rs
Add a new RPC interface `tx_pool_info` to get transaction pool information.
=> feat: Add tx_pool_info RPC

sync/src/types.rs
use the last header as the `base` to avoid scan from tip.
=> sync: improve the performance of get_locator

sync/src/relayer/mod.rs
Ask transactions in initial block download will cost a lot bandwidth and CPU.
=> fix: Stop ask for transactions when initial block download

rpc/src/module/pool.rs, sync/src/relayer/transaction_hash_process.rs
- Relay transaction body when send transaction from RPC
- Insert into known list when tx in pool
- Do not handle relay tx hash when initial block download
=> perf: Improve relay tx performance

spec/src/lib.rs, test/src/node.rs
Revert https://github.com/nervosnetwork/ckb/commit/91b8e06f3409875ff63e69ca7e6cc749a10e3d00 , we should use script reference hash in the integeration test, which will cover all VM related code.
=> chore: revert 91b8e06f3409875ff63e69ca7e6cc749a10e3d00

miner/src/miner.rs
call `try_update_block_template` will take 200 ~ 400ms when node have too many txs
=> fix: remove rpc call to improve miner profermance

Cargo.lock, network/Cargo.toml, sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/mod.rs, sync/src/types.rs
Avoid send too much GetHeaders when received CompactBlock (this will cause message flood)
=> fix: Sync message flood

sync/src/relayer/block_proposal_process.rs, sync/src/relayer/mod.rs
* Clean relayer's `inflight_proposals` after received the corresponding proposal transactions
=> fix: clean corresponding cache when receive proposals

test/src/main.rs, test/src/specs/mod.rs, test/src/specs/transaction.rs, test/src/specs/tx_pool/depend_tx_in_same_block.rs, test/src/specs/tx_pool/different_txs_with_same_input.rs, test/src/specs/tx_pool/mod.rs
This integration test is needed to check `BlockTemplate` generation, although RBF was not implemented yet.
=> chore: add an integration test for RBF (Replace-By-Fees)

script/src/syscalls/load_cell.rs, script/src/syscalls/load_cell_by_field.rs, script/src/verify.rs
`ResolvedTransaction`'s outputs meta are always built from memory, no need to do unnecessary store lookup.
=> perf: avoiding unnecessary store lookup and trait bound tweak

sync/src/synchronizer/block_process.rs, sync/src/synchronizer/get_blocks_process.rs, sync/src/types.rs
* Ignore "block" message if we are not interested (never requested before or already processed)
* Limit length of "getblocks" message
=> Ignore staled block

sync/src/relayer/block_transactions_process.rs, sync/src/relayer/compact_block.rs, sync/src/relayer/compact_block_process.rs, sync/src/relayer/compact_block_verifier.rs, sync/src/relayer/error.rs, sync/src/relayer/get_block_proposal_process.rs, sync/src/relayer/mod.rs, sync/src/relayer/tests/compact_block_process.rs, sync/src/relayer/tests/compact_block_verifier.rs, sync/src/relayer/tests/mod.rs, sync/src/synchronizer/mod.rs
* Implement `CompactBlockVerifier` to verify the validity of CompactBlock, which be passed to `Relayer::reconstruct_block` function. The correctness of reconstructed block will be verified by `BlockVerifier` and `TransactionsVerifier`.
* test: Add unit tests for `Relayer::reconstruct_block` and `CompactBlockVerifier`
* perf: Use `HashSet::contains` to check whether a short id be contained in staging pool. It will decrease the time-complexity.
=> feat: verify compact block

sync/src/relayer/tests/compact_block_process.rs
[The CI for develop is failed.](https://travis-ci.com/nervosnetwork/ckb/jobs/197935693)
Because `fn calculate_difficulty(..)` was deleted by #579, but #614 hadn't been tested with the latest code.
=> fix: a bug caused by merging a stale branch

core/src/cell.rs, miner/src/block_assembler.rs, verification/src/block_verifier.rs, verification/src/error.rs, verification/src/tests/block_verifier.rs, verification/src/transaction_verifier.rs
This PR allows the miner to set cellbase's output type, and cellbase will be verified with the same rule as a normal transaction.
=> feat: cellbase type script

devtools/ci/script.sh
For example, #541 and #646 don't have to run unit tests, and both of them should have to run integration tests.
Now, each reviewers have to run integration tests in his own laptop (not in CI) for reviewing (or approving).
Use the last commit message to control CI checks.
- Only one tag is allowed for **only one** commit message.
There are only few tags at present:
- `[only integration]`: only run integration tests
- `[skip tests]`: skip all tests
- `[all tests]`: run all tests
- The tag should be written **at start** of the commit message, so reviewers can see it clearly.
Examples:
- `ci: [only integration] control CI checks by the last commit message`
=> ci: [only integration] control CI checks by the last commit message

core/src/extras.rs, util/jsonrpc-types/src/blockchain.rs
Hide the real `String` type just as the way we use `BlockNumber`.
=> fix: Use the String alias type EpochNumber

Cargo.lock, chain/src/chain.rs, resource/ckb.toml, resource/specs/dev.toml, resource/specs/testnet.toml, script/Cargo.toml, script/src/lib.rs, script/src/verify.rs, shared/Cargo.toml, shared/src/chain_state.rs, shared/src/shared.rs, spec/src/consensus.rs, spec/src/lib.rs, src/subcommand/run.rs, test/integration.toml, util/app-config/Cargo.toml, util/app-config/src/app_config.rs, verification/src/block_verifier.rs, verification/src/transaction_verifier.rs
#642 made a mistake: the flag for enabling assembly based VM is mistakenly put into chain spec. Since this shouldn't affect consensus, it should be a CKB config, not a chain spec config. This PR fixes this.
=> refactor: move VM config from chain spec to CKB config file

core/src/script.rs, script/src/common.rs, script/src/syscalls/load_cell.rs, script/src/syscalls/load_cell_by_field.rs, script/src/syscalls/load_header.rs, script/src/syscalls/load_input_by_field.rs, script/src/syscalls/load_script_hash.rs, script/src/syscalls/mod.rs, script/src/verify.rs
All the other methods to load current cell's information, such as
capacity, data, etc. are also removed in this commit. This way we can
enable group based transaction validation which saves cycles for
duplicate scripts.
TODO:
=> feat: Add syscall to load current script hash

rpc/src/module/chain.rs, shared/src/tx_pool/pool.rs
`get_transaction` RPC information is inconsistent with the transaction pool display
=> fix: Information is inconsistent with the transaction pool display

script/src/lib.rs
ckb-fake-env need this function, but it's private
=> chore: export build_tx

core/src/difficulty.rs, script/src/verify.rs, test/src/node.rs, util/crypto/src/secp/signature.rs, verification/src/tests/block_verifier.rs, verification/src/tests/transaction_verifier.rs
Remove a useless test. Initially, some const hashes are constructed by `[u8; N]`, so there need some tests to ensure correctness. Now, they are constructed in the same way as the tests, so the tests are redundant.
=> style: use more handsome constructors for hashes

resource/ckb.toml, rpc/README.md, rpc/src/config.rs, rpc/src/module/mod.rs, rpc/src/module/stats.rs, rpc/src/server.rs, src/subcommand/run.rs, sync/src/synchronizer/mod.rs, util/jsonrpc-types/src/chain_info.rs, util/jsonrpc-types/src/lib.rs, util/jsonrpc-types/src/sync.rs
* Add rpc `get_blockchain_info`
* Add rpc `get_peers_state`, currently only return the info of blocks synchronizing in flight.
=> feat: rpc get blockchain info

Cargo.lock, script/Cargo.toml, script/src/cost_model.rs, script/src/lib.rs, script/src/verify.rs
Noticeable changes here include:
* Shrink VM memory from 16MB to 4MB now for both resource usage and performance
* Use Bytes in VM API to avoid unnecessary copying
* Use i8 as VM return code for better debugging
=> feat: upgrade VM to latest version

core/src/block.rs, core/src/header.rs, core/src/transaction.rs, db/src/rocksdb.rs, miner/src/block_assembler.rs, store/src/store.rs, verification/src/tests/uncle_verifier.rs
- perf: store transaction hashes into database to avoid computing them again
**BREAKING CHANGE**: The format of block data in database is changed.
- chore: add `unsafe` to few constructors which may cause bugs and rename them to `xxx_unchecked`
#549
=> perf: store transaction hashes into database to avoid computing them again

rpc/src/module/experiment.rs, test/src/node.rs, test/src/rpc.rs, test/src/specs/mining/size_limit.rs, test/src/specs/sync/block_sync.rs, test/src/specs/tx_pool/valid_since.rs, util/jsonrpc-types/src/experiment.rs, util/jsonrpc-types/src/lib.rs
* Move `DryRunResult` into jsonrpc-types
* Complete rpc-client used in integration testing
=> feat: move DryRuResult into jsonrpc-types

chain/src/chain.rs, core/src/cell.rs, shared/src/chain_state.rs
Transactions are expected to be sorted within a block
Transactions have to appear after any transactions upon which they depend
=> feat: enforce resolve txs order within block

db/src/rocksdb.rs
This is due to a breaking change in #718
=> feat: upgrade database version

chain/src/chain.rs, chain/src/tests/basic.rs, chain/src/tests/find_fork.rs, miner/src/block_assembler.rs, rpc/src/module/chain.rs, rpc/src/module/experiment.rs, rpc/src/module/miner.rs, rpc/src/module/pool.rs, rpc/src/module/stats.rs, rpc/src/module/test.rs, rpc/src/test.rs, shared/src/shared.rs, shared/src/tests/shared.rs, shared/tx-pool-executor/src/tx_pool_executor.rs, src/subcommand/prof.rs, sync/src/relayer/block_transactions_process.rs, sync/src/relayer/compact_block_process.rs, sync/src/relayer/get_block_proposal_process.rs, sync/src/relayer/get_transaction_process.rs, sync/src/relayer/mod.rs, sync/src/relayer/tests/compact_block_process.rs, sync/src/relayer/transaction_hash_process.rs, sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/headers_process.rs, sync/src/synchronizer/mod.rs, sync/src/tests/synchronizer.rs, sync/src/types.rs, util/instrument/src/iter.rs, util/src/lib.rs
- chore: use `try_lock_for(...)` to replace `lock()` for ChainState
`sed -i "s/[.]chain_state()[.]lock()/.lock_chain_state()/g" $(grep -rl "[.]chain_state()[.]lock()" [^t]*)`
- chore: use `try_lock_for(...)` to replace `lock()` in TxsVerifyCache
`sed -i "s/[.]txs_verify_cache()[.]lock()/.lock_txs_verify_cache()/g" $(grep -rl "[.]txs_verify_cache()[.]lock()" [^t]*)`
Panic if it's likely to reach a deadlock (wait for 300 seconds).
https://github.com/nervosnetwork/ckb/blob/4b890724d375f845773b57b5ee45b82bee9785f7/util/src/lib.rs#L18-L23
=> feat: panic if it's likely to reach a deadlock

spec/src/lib.rs
BREAKING CHANGE: It changed the consensus rule and may fail to verify the old chain.
=> fix: genesis epoch remainder reward

.travis.yml
Allow building any branch in fork repository.
The `fork` condition does not work like what Travis doc says.
=> chore: fix travis condition

miner/src/block_assembler.rs, shared/src/shared.rs
From observation, the delay time of `get_block_template` can up to seconds(5s on my machine) when node under heavy load,
it causes the whole test network new block time to increase.
The main issue is the unnecessary acquisition of the chain_state lock, the second issue is frequently missing cache.
This PR fixes the two issues.
=> [ᚬrylai-testbed] perf: delay acquire chain_state lock until tried cache

traits/src/block_median_time_context.rs
* Correct block_median_count when verifying a compact block
=> [ᚬrc/v0.12.0] fix: correct block_median_count

src/subcommand/init.rs
Print the warning when running `ckb init`. Remind user to change the default
block assembler config before mining.
=> [ᚬrc/v0.12.0] chore: print warning about default miner key

docs/get-ckb.md
`rustup override` locks the version in the directory. It will cause problems
when the required Rust version has changed, but user forget to override the
new version.
=> [ᚬrc/v0.12.0] docs: no rustup override in docs

network/src/services/dns_seeding/seed_record.rs
Change record hash function from `sha3_256` to `blake2b_256`
=> [ᚬrc/v0.12.0] fix: Change dns seed record hash function to blake2b_256

core/src/script.rs, script/src/syscalls/mod.rs, script/src/verify.rs
NOTE: this is a breaking change.
=> [ᚬrc/v0.12.0] fix: load_script_hash should use script's own hash for lock script

network/src/benches/sqlite_peer_store.rs, network/src/network.rs, network/src/peer_registry.rs, network/src/peer_store.rs, network/src/peer_store/sqlite/db.rs, network/src/peer_store/sqlite/peer_store.rs, network/src/peer_store/types.rs, network/src/protocols/discovery.rs, network/src/protocols/identify.rs, network/src/services/outbound_peer.rs, network/src/tests/peer_registry.rs, network/src/tests/sqlite_peer_store.rs
1. Add retry and refresh address feature to peer_store
2. remove temp code
3. ban through addr instead peer_id
Discovery protocol will not return addresses which node can't reach to node's peers.
Feeler protocol will give up an address if reach a certain condition.
BREAKING CHANGE: peer store db file must be deleted manually.
=> [ᚬrc/v0.12.0]  feat: peer_store support retry and refresh

docs/run-ckb-with-docker.md
=> docs: Add missing container name in run-ckb-with-docker.md

test/src/main.rs, test/src/net.rs, test/src/node.rs, test/src/rpc.rs, test/src/specs/mining/basic.rs, test/src/specs/p2p/disconnect.rs, test/src/specs/p2p/discovery.rs, test/src/specs/p2p/malformed_message.rs, test/src/specs/relay/block_relay.rs, test/src/specs/relay/transaction_relay.rs, test/src/specs/sync/block_sync.rs, test/src/specs/sync/invalid_locator_size.rs
* Enable "sync_timeout" test case
* Refactor RpcClient, test cases can share the same RpcClient instance, to avoid wasting connections resource.
=> tests: share one rpc client in tests

spec/src/lib.rs, test/integration.toml, util/app-config/src/app_config.rs
Only `ckb_dev` is allowed in the chainspec loaded from file.
=> [ᚬrylai] feat: limit name in chainspec

Cargo.lock, Cargo.toml, docs/quick-start.md, docs/run-ckb-with-docker.md, resource/ckb.toml, rpc/src/config.rs, rpc/src/server.rs, src/main.rs, src/subcommand/cli/mod.rs, src/subcommand/cli/secp256k1.rs, src/subcommand/init.rs, src/subcommand/run.rs, test/src/node.rs, util/app-config/src/app_config.rs, util/app-config/src/cli.rs, util/app-config/src/lib.rs, util/crypto/src/secp/pubkey.rs
- Remove the default block assembler config. If user want to mine, they must configure it.
- Add subcommand `ckb cli secp256k1` to generate block assembler config
=> [ᚬrylai] feat: secp256k1 block assembler

util/app-config/src/cli.rs
* Fix typos
* Display messages in the 3rd person
This is an attempt to unify the message style. Personally I like to NOT use the 3rd parson, but `clap`'s `help` and `version` uses that. (Anyway to override that?)
BTW, would `perf` be a better subcommand name than `prof`? @jjyr 
Specifically, now we have three styles: `Prints`, `Import`, `Profling` (should be `Profiling`).
```shell
ckb 0.13.0-pre
Nervos Core Dev <dev@nervos.org>
Nervos CKB - The Common Knowledge Base
USAGE:
ckb [OPTIONS] <SUBCOMMAND>
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
OPTIONS:
-C <path>        Runs as if ckb was started in <path> instead of the current working directory.
SUBCOMMANDS:
cli       CLI tools
export    Export ckb data
help      Prints this message or the …
```
=> chore: improve command line messages

miner/src/block_assembler.rs, resource/ckb.toml, rpc/README.md, rpc/json/rpc.json, rpc/src/module/experiment.rs, rpc/src/module/pool.rs, shared/src/chain_state.rs, shared/src/tx_pool/orphan.rs, shared/src/tx_pool/pending.rs, shared/src/tx_pool/pool.rs, shared/src/tx_pool/proposed.rs, shared/src/tx_pool/types.rs, shared/tx-pool-executor/src/tx_pool_executor.rs, src/subcommand/prof.rs, test/src/main.rs, test/src/node.rs, test/src/rpc.rs, test/src/specs/tx_pool/limit.rs, test/src/specs/tx_pool/mod.rs, util/jsonrpc-types/src/pool.rs, verification/src/contextual_block_verifier.rs, verification/src/error.rs, verification/src/transaction_verifier.rs
1. apply tx_pool limit
2. tx size verify, enforce tx size below  block size limit
```diff
[tx_pool]
- max_pool_size = 10000
- max_orphan_size = 10000
- max_proposal_size = 10000
- max_cache_size = 1000
- max_pending_size = 10000
- txs_verify_cache_size = 100000
+ max_mem_size = 20_000_000 # 20mb
+ max_cycles = 200_000_000_000
+ max_verfify_cache_size = 100_000
```
```diff
+ "total_tx_cycles": "2",
+ "total_tx_size": "156",
```
=> feat: apply tx_pool limit

resource/ckb-miner.toml, resource/ckb.toml, rpc/src/module/experiment.rs, rpc/src/module/miner.rs, rpc/src/module/pool.rs, rpc/src/module/test.rs
The old target is same as the target in [`jsonrpc-core`](https://github.com/paritytech/jsonrpc/blob/master/core/src/io.rs#L177).
I rename it to `rpc-server` since we have `rpc` client in some tests.
=> chore: rename the target in log for rpc module

rpc/src/module/stats.rs, shared/src/chain_state.rs, shared/src/tests/shared.rs, shared/tx-pool-executor/src/tx_pool_executor.rs, sync/src/relayer/compact_block_process.rs, sync/src/synchronizer/headers_process.rs, traits/src/block_median_time_context.rs, verification/src/contextual_block_verifier.rs, verification/src/header_verifier.rs, verification/src/tests/transaction_verifier.rs, verification/src/transaction_verifier.rs
At present, the way calculating the passed median time is that collects block timestamps one by one by block_number. This PR change to collects blocks timestamps by tracing parents. The new way is more robust.
In addition to this, I use assert-style to rewrite the calculation of passed median time.
=> feat: Calculate median time by tracing parents

Cargo.lock, network/Cargo.toml, network/src/compress.rs, network/src/lib.rs, network/src/network.rs, network/src/protocols/mod.rs
BREAKING CHANGE: protocol communication break
On the test net monitoring, the bandwidth usage is often in a full state. We try to use the snappy compression algorithm to reduce network transmission consumption.
After testing, the compression yield of flatbuffer format is very high, cpu consumption is relatively acceptable.
The following is the data transmission on the test net:
```
2019-05-20 16:27:41.875 +08:00 tokio-runtime-worker-7 DEBUG compress  raw_data len: 625400, compress used time: 3.635121ms, compress_data size: 335401, compression ratio: 0.536298369043812, decompress used time: 1.496667ms
2019-05-20 16:27:42.128 +08:00 tokio-runtime-worker-6 DEBUG compress  raw_data len: 633544, compress used time: 3.789752ms, compress_data size: 335462, compression ratio: 0.5295007134468955, …
```
=> feat: Use snappy to compress large messages

network/src/network.rs
Error type like `ListenError` should not report to sentry
=> chore: Handle more error type from p2p service

ckb-bin/src/subcommand/run.rs, sync/src/relayer/mod.rs, sync/src/synchronizer/mod.rs, sync/src/types.rs
* Handle disconnected inside `Peers`
* Rename `n_sync_started`/`n_protected_outbound_peers`
* Remove imlicitly clone for `Peers`
=> feat: Peers handle disconnect

test/src/main.rs, test/src/specs/tx_pool/valid_since.rs, test/src/utils.rs, traits/src/block_median_time_context.rs, verification/src/transaction_verifier.rs
**BREAKING CHANGE**: Original implementation use `[Tip-BlockMedianCount .. Tip-1]` to calculate the current block median time. According to the notion of BlockMedianTime in [bip-0113](https://github.com/bitcoin/bips/blob/master/bip-0113.mediawiki#specification) , here change to use `[Tip-BlockMedianCount+1 .. Tip]` instead.
=> fix: calculate the current median time from tip

chain/src/chain.rs, core/src/transaction.rs, core/src/transaction_meta.rs, db/src/cachedb.rs, db/src/lib.rs, db/src/memorydb.rs, db/src/rocksdb.rs, rpc/src/module/chain.rs, shared/src/cell_set.rs, shared/src/chain_state.rs, store/src/lib.rs, store/src/store.rs
- feat: add a function to traverse all keys for database
- feat: save cell set into database (but not used)
BREAKING CHANGE: Add new column to store cell set into database.
- refactor: loading CellSet do not have to load all blocks
- perf: delete transactions whose all cells are dead
- fix: the order to apply cell set diff is very important
#228
- I insist on the opinion: save live cells is better than save transactions which include at least one live cell.
We can use a only-key-and-no-value database (for example, Redis) to store live cells (`CellOutPoint` as key). 
I tried, but it's too difficult to adapt to current logic, so I gave up.
- I didn't change current design about how to use `CellSet`, I just made them be persisted.
- **All transactions** which include at least one live cell, …
=> feat: limit TXO set memory usage

sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/headers_process.rs, sync/src/synchronizer/mod.rs, sync/src/types.rs
* `best_known_header` and `last_common_header` are both  state of peer. So I move them into `PeerState`. And add wrap functions for them, so that hides the locks outside.
=> refactor: move best_known_headers/last_common_headers into peer_state

spec/src/consensus.rs
tweak block_cycles_limit and min_block_interval
=> feat: tweak consensus params

Cargo.lock, script/Cargo.toml
This upgrade contains the following changes:
* #57 calculate address first before cond operation @xxuejie
* #60 fix broken bench tests @mohanson
* #61 VM panics when ELF uses invalid file offset @xxuejie
* #63 out of bound read check in assembly VM
* #59 fix a bad way to using machine @mohanson
* #61 add an example named is13 @mohanson
=> [ᚬrc/v0.13.0] feat: upgrade CKB VM to latest version

pow/src/cuckoo.rs
The last point can be equal to the max edge.
=> [ᚬrc/v0.13.0] fix: cuckoo cycle max edge verification

sync/src/relayer/block_transactions_process.rs, sync/src/relayer/compact_block_process.rs, sync/src/relayer/mod.rs, test/src/specs/relay/compact_block.rs
* test: Add test for losing BlockTXN messages
* fix: Remove relayer's compact_block_filter, filter duplicated compact blocks via BlocksInFlight
Currently, we discard the new arriving compact blocks if we had already received the same one, via `RelayState::compact_block_filter`. The purpose is avoiding re-processing/re-requesting the same compact blocks. But the problem is, if we failed to reconstruct a compact block, we cannot process this compact block anymore, before receiving the corresponding transactions from peer1. That's terrible if peer1's inventory was lost on the way.
Here I remove `RelayState::compact_block_filter`, and insteadly use `Peers::blocks_inflight` to avoid re-requesting to same peers.
* fix: Cache pending compact block at peer-level, but not global-level
=> feat: synchronizer and relayer share BlocksInflight

miner/src/client.rs
=> feat: make a better error message for miner when method not found

util/crypto/src/secp/signature.rs
Cause we already use witness, the low S rule for signature is unnecessary.
See https://github.com/bitcoin/bips/blob/master/bip-0062.mediawiki#new-rules
=> refactor: remove low S check from util-crypto

.gitignore, .travis.yml, Cargo.lock, Makefile, devtools/cov/rustc-proptest-fix
@quake 
There are many crates for code coverage in Rust: cargo-tarpaulin, grcov, cov, cargo-travis, but all are not matured.
I have investigated the most two popular crates: cargo-tarpaulin and grcov. There were some bugs for both of them. And finally, I figured cargo-tarpaulin out, and It's also newer and well maintained than others.
There are two features of tarpaulin, I think it's enough for us now:
- Line coverage
- Uploading coverage to https://coveralls.io or https://codecov.io
The result is as below:
```
[INFO tarpaulin] Coverage Results:
|| Uncovered Lines:
|| chain/src/chain.rs: 118-122, 124-125, 172, 181, 184, 188-190, 195, 213, 215-216, 228-229, 242, 244, 247, 249, 251, 257, 261, 268, 270, 273-274, 281, 309-311, 315, 321-322, 335, 344-347, 368, 373-376, 419, 421, 423-425, 428, …
```
=> test: add code coverage

test/src/net.rs, test/src/node.rs, test/src/specs/relay/compact_block.rs, test/src/specs/relay/transaction_relay.rs, test/src/specs/sync/chain_forks.rs, test/src/specs/sync/sync_timeout.rs, test/src/specs/tx_pool/pool_reconcile.rs, test/src/specs/tx_pool/pool_resurrect.rs
Change all `waiting_for_sync` timeout value to 60 seconds, resolve integration test fail issue on poor CI server.
=> chore: use large timeout value for integration test

Cargo.lock, script/Cargo.toml
This commit contains no CKB VM changes, it merely switch from git
commit to published CKB VM versions
=> chore: switch to CKB VM published crate versions

benches/benches/process_block.rs, chain/src/chain.rs, chain/src/tests/basic.rs, chain/src/tests/delay_verify.rs, chain/src/tests/find_fork.rs, miner/src/block_assembler.rs, rpc/src/module/chain.rs, rpc/src/module/experiment.rs, shared/src/chain_state.rs, shared/src/shared.rs, shared/tx-pool-executor/src/tx_pool_executor.rs, spec/src/consensus.rs, store/src/store.rs, sync/src/relayer/compact_block_process.rs, sync/src/relayer/get_block_transactions_process.rs, sync/src/relayer/tests/compact_block_process.rs, sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/get_blocks_process.rs, sync/src/synchronizer/headers_process.rs, sync/src/synchronizer/mod.rs, sync/src/types.rs, traits/src/chain_provider.rs, util/instrument/src/iter.rs, verification/src/block_verifier.rs, verification/src/contextual_block_verifier.rs, verification/src/tests/commit_verifier.rs, verification/src/tests/dummy.rs, verification/src/tests/uncle_verifier.rs
```diff
pub trait ChainProvider: Sync + Send {
type Store: ChainStore;
fn store(&self) -> &Arc<Self::Store>;
...
-    fn block_body(&self, hash: &H256) -> Option<Vec<Transaction>>;
-    fn block_header(&self, hash: &H256) -> Option<Header>;
-    fn block_proposal_txs_ids(&self, hash: &H256) -> Option<Vec<ProposalShortId>>;
-    fn uncles(&self, hash: &H256) -> Option<Vec<UncleBlock>>;
-    fn block_hash(&self, number: BlockNumber) -> Option<H256>;
-    fn block_ext(&self, hash: &H256) -> Option<BlockExt>;
-    fn block_number(&self, hash: &H256) -> Option<BlockNumber>;
-    fn block(&self, hash: &H256) -> Option<Block>;
-    fn get_transaction(&self, hash: &H256) -> Option<(Transaction, H256)>;
...
}
```
=> refactor: Remove redundant interface from ChainProvider

util/build-info/src/lib.rs
The full `git describe` output easily cause confusion, this change will only
show the 7 hex digests commit sha and the dirty flag, such as
ckb 0.15.0-pre (rylai-v4 d7d3baca-dirty 2019-06-06)
=> feat: simplify git describe info in version

core/src/cell.rs
@quake 
The intention of the test case with `is_err` is ambiguous.
=> test: replace is_err in core test

script/src/syscalls/load_code.rs, script/src/syscalls/mod.rs, script/src/verify.rs
This newly added syscall can be used to load cell data into VM as
executable memory. This can be used to dynamically load code into VM
on demand.
=> feat: Add load_code syscall

Cargo.lock, network/Cargo.toml, network/src/config.rs, network/src/network.rs, resource/ckb.toml, test/src/net.rs
1. upgrade p2p dependence
2. support `upnp` optional
changelog: https://github.com/nervosnetwork/p2p/blob/master/CHANGELOG.md
=> feat: Upgrade p2p

Cargo.lock, sync/Cargo.toml, sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/mod.rs, sync/src/tests/synchronizer.rs, sync/src/types.rs
**NOTE**: The [implementation](https://github.com/bitcoin/bitcoin/blob/5d2ccf0ce9ca1571c650a69319fb9c1e0b626ecb/src/chain.cpp#L70-L120) and [test](https://github.com/bitcoin/bitcoin/blob/5d2ccf0ce9ca1571c650a69319fb9c1e0b626ecb/src/test/skiplist_tests.cpp#L13-L44) is almost copy from bitcoin.
=> perf(sync): Fix get ancestor performance issue

chain/src/tests/basic.rs, chain/src/tests/util.rs
1. Before in the test `test_chain_fork_by_hash`, the `chain1` was always equal to the `chain2`, the assert statement was always passed.
Either 
```
assert_eq!(
shared.store().get_block_hash(8),
best.blocks().get(7).map(|b| b.header().hash().to_owned())
);
```
or replacing `best` to `chain1`/`chain2`
```
assert_eq!(
shared.store().get_block_hash(8),
chain1.blocks().get(7).map(|b| b.header().hash().to_owned())
);
assert_eq!(
shared.store().get_block_hash(8),
chain2.blocks().get(7).map(|b| b.header().hash().to_owned())
);
```
2. `test_chain_fork_by_hash` had the same problem before.
=> test: Fix test in chain

ckb-bin/src/subcommand/run.rs, rpc/src/module/stats.rs, sync/src/relayer/block_proposal_process.rs, sync/src/relayer/block_transactions_process.rs, sync/src/relayer/compact_block_process.rs, sync/src/relayer/get_block_proposal_process.rs, sync/src/relayer/mod.rs, sync/src/relayer/tests/compact_block_process.rs, sync/src/relayer/transaction_hash_process.rs, sync/src/relayer/transaction_process.rs, sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/block_process.rs, sync/src/synchronizer/get_headers_process.rs, sync/src/synchronizer/headers_process.rs, sync/src/synchronizer/mod.rs, sync/src/types.rs
* Flatten some fields originally in `Synchronizer`, `Relayer` and `Peers` into `SyncSharedState`
----
This PR intends to make `Synchronizer` and `Relayer` share the same global state. So I try to move their fields into `SyncSharedState`.
Here only refactor around the "fields", and will refactor the "methods" in another PR.
=> refactor: flatten fields into shared

util/jsonrpc-types/src/bytes.rs
fix #974 
1. Not 0x-prefixed hex string, error message:
```
Config Error: Error { inner: ErrorInner { kind: Custom, line: None, col: 0, message: "invalid value: string \"7f52f0fccdd1d11391c441adfb174f87bca612b0\", expected a 0x-prefixed hex string", key: ["block_assembler", "args"] } }
```
2. The illegal 0x-prefixed hex string
```
Config Error: Error { inner: ErrorInner { kind: Custom, line: None, col: 0, message: "invalid length 43, expected even length", key: ["block_assembler", "args"] } }
```
=> fix: fix confusing JsonBytes deserializing error message

Cargo.lock, ckb-bin/src/subcommand/cli/secp256k1_lock.rs, resource/Cargo.toml, resource/build.rs, resource/ckb.toml, resource/src/lib.rs, resource/src/template.rs, util/hash/src/lib.rs
Generate the code hash constants in ckb-resource, and use the constants
instead of the hard code hash in different locations.
=> [ᚬrc/v0.14.0] feat: avoid hard code code_hashes

.travis.yml
The binary built using Ubuntu 18 requires a higher version of stdlibc++, which
is not available in Ubuntu 16.
Related: [Dockerfile](https://github.com/nervosnetwork/ckb-docker-builder/blob/xenial-rust-1.34.2/Dockerfile) for the builder.
=> [ᚬrc/v0.14.0] chore: package linux binary using Ubuntu 16

ckb-bin/src/subcommand/cli/secp256k1_lock.rs, ckb-bin/src/subcommand/init.rs, resource/ckb.toml, resource/src/template.rs, util/app-config/src/app_config.rs, util/app-config/src/args.rs, util/app-config/src/cli.rs, util/app-config/src/lib.rs
- `ckb init` accepts options `--ba-code-hash` and `--ba-arg` (which can
repeat multiple times) to set block assembler.
- `ckb cli secp256k1-lock` adds an output format `cmd` to prints the
command line options for `ckb init` to set block assembler.
The two commands can combine into one to init the directory with a secp256k1 compressed pub key:
ckb init $(ckb cli secp256k1-lock <pubkey> --format cmd)
Depends on: #999
=> [ᚬrc/v0.14.0] feat: `ckb init` supports setting block assembler

chain/src/tests/basic.rs, chain/src/tests/util.rs, resource/specs/dev.toml, resource/specs/testnet.toml, rpc/README.md, rpc/json/rpc.json, spec/src/consensus.rs, test/integration.toml, test/src/node.rs, test/src/specs/relay/transaction_relay.rs
- Change target epoch duration to 4 hours
- Reduce epoch reward to 1/4
- Increase secondary epoch reward to 600,000 bytes
=> [ᚬrc/v0.14.0] feat: Tweak consensus parameters

core/src/lib.rs, miner/src/block_assembler.rs, miner/src/config.rs, resource/ckb.toml, test/src/node.rs, test/src/specs/mining/bootstrap.rs
Allow miner add an arbitrary message into the cellbase
closed #888
=> feat: Allow miner add an arbitrary message into the cellbase

.travis.yml
This PR tries to fix the following error in CI:
found possibly newer version of crate `*` which `*` depends on
Travis separate cache via OS, Language and Env. So the new env option added to
job Linters can force it to use its own cache.
=> chore(ci): force job Linters using its own cache

miner/src/worker/dummy.rs
* fix: Avoid dummy worker re-solve the same works. Resolving the same works and submit to chain, will increase the useless uncle blocks.
=> fix: avoid dummy worker re-solve the same works

resource/ckb.toml, spec/src/lib.rs, util/app-config/src/app_config.rs
Some command still uses the bundled config file, for example, following
command will fail in Windows when `ckb.toml` not found in current directory:
ckb cli hashes
=> fix: use Rust VM runner in bundled config file

ckb-bin/src/subcommand/cli/hashes.rs, docs/hashes.toml, spec/src/lib.rs
It makes no sense since most system cells require args to work.
=> feat: remove script_hash from docs/hashes.toml

.travis.yml, azure-pipelines.yml
Integration tests will become slower and slower, we don't want to run all the
test suites.
Later we may pick random n test specs to run in PR.
=> chore(ci): skip integration in PR

ckb-bin/src/subcommand/init.rs, util/app-config/src/args.rs, util/app-config/src/cli.rs, util/app-config/src/lib.rs
1. `ckb init` allow set ba-data
2. Verify that the input is valid hex
=> feat: ckb init allow set ba-data

rpc/README.md, rpc/json/rpc.json
It always returns `null`, instead of empty array.
=> fix: RPC doc for deindex_lock_hash

resource/ckb-miner.toml, resource/specs/dev.toml
makes it easy to run dev chain
=> chore: change dev default pow engine to `Dummy`

sync/src/synchronizer/block_pool.rs
* `orphan_block_pool` use `ParentHash` rather than `BlockHash` as key. So when we want to check whether we have received the same block as the arrived one, based `orphan_block_pool`, we should check deeply.
=> fix: Check new block based on orphan block pool

chain/src/chain.rs, chain/src/tests/basic.rs, chain/src/tests/delay_verify.rs, chain/src/tests/util.rs, core/src/block.rs, core/src/transaction.rs, miner/src/block_assembler.rs, miner/src/client.rs, shared/src/cell_set.rs, shared/src/chain_state.rs, shared/src/tx_pool/orphan.rs, shared/src/tx_pool/proposed.rs, shared/tx-pool-executor/src/tx_pool_executor.rs, test/src/node.rs, test/src/utils.rs
fix bug:
* deleted full-dead cell from storage, but haven't erased it from memory.
* should recover full-dead cell when fork occurs
=> [ᚬrc/v0.14.0]  fix: cellset consistency

rpc/src/test.rs
Close the server before exit RPC test.
=> fix: random failure caused by dirty exit in RPC test

network/src/errors.rs, network/src/protocols/mod.rs, sync/src/net_time_checker.rs, sync/src/relayer/block_proposal_process.rs, sync/src/relayer/compact_block_process.rs, sync/src/relayer/get_block_proposal_process.rs, sync/src/relayer/get_block_transactions_process.rs, sync/src/relayer/get_transaction_process.rs, sync/src/relayer/mod.rs, sync/src/relayer/transaction_process.rs, sync/src/synchronizer/get_blocks_process.rs, sync/src/synchronizer/get_headers_process.rs, sync/src/synchronizer/headers_process.rs, sync/src/synchronizer/mod.rs, sync/src/tests/mod.rs, sync/src/types.rs, util/network-alert/src/alert_relayer.rs
* feat: Reveal network errors. Currently, when `CKBProtocolContext` receives an error from p2p, it only logs the error and doesn't return to the caller. I change to `CKBProtocolContext` return the error to the caller, and caller handles it.
* perf: Short-circuiting break if occurs network error, `Synchronizer` responses `Blocks` and `Transactions`. This is the original intention of this PR. To achieve it, I have to make  `CKBProtocolContext` reveals the network errors, which introduces most of the change code.
=> perf: Reveal network errors and involver handle it

sync/src/types.rs
* refactor: Define a `Filter` struct
* ~~feat: Use LruCache to avoid memory leaking~~
~~If we use native HashMap/HashSet as cache/filter, we have to prevent memory overflow by timely check or else. Replacing HashMap/HashSet with LruCache help us limit the memory usage, and reduce works around pruning staled items.~~
=> refactor: Define a general Filter struct

Cargo.lock, util/network-alert/Cargo.toml, util/network-alert/src/notifier.rs, util/network-alert/src/tests/test_notifier.rs
As @keroro520 mentioned, there is a potential bug in case like: `"0.10.0" < "0.9.10"`
=> fix: potential error in alert version compare

rpc/README.md, rpc/json/rpc.json, rpc/src/module/chain.rs
Add two RPC methods
- `get_header`
- `get_header_by_number`
**Usage scenario:**
- `ckb-cli` get genesis block header to distinguish `testnet` and `mainnet`
- `SPV` client just get headers to verify a transaction
=> feat: Add get_header and get_header_by_number RPC methods

script/src/syscalls/debugger.rs, script/src/verify.rs
Current `Debugger` only log the output and can not detected by outside.
Here we pass a callback to process debug output.
=> feat: Allow TransactionScriptsVerifier set custom debugger printer

sync/src/synchronizer/block_fetcher.rs
Node should fetch download from all peers which have better chain,
no matter it's known best's ancestor or not.
=> [ᚬrc/v0.15.z] fix: sync block download filter

resource/ckb-miner.toml, resource/ckb.toml, util/app-config/src/sentry_config.rs
```toml
[sentry]
dsn = "https://48c6a88d92e246478e2d53b5917a887c@sentry.io/1422795"
org_ident = "ckb-dev"
org_contact = "test@example.org"
```
=> [ᚬrc/v0.15.z] feat: allow providing extra sentry info in config

shared/tx-pool-executor/src/tx_pool_executor.rs
* fix: The block number of the coming block should be `tip_number + 1`
-------
NOTE: **This is a breaking change**
=> fix: correct block number from tx_pool_excutor

benches/benches/process_block.rs, chain/src/chain.rs, chain/src/tests/basic.rs, store/src/store.rs, sync/src/synchronizer/block_process.rs, sync/src/synchronizer/get_blocks_process.rs, sync/src/synchronizer/headers_process.rs, sync/src/synchronizer/mod.rs
* fix fetch invalid block
* fix response invalid block
* fix repeat process block overwrite block ext
=> [ᚬrc/v0.15.z] hotfix rc0.15

rpc/src/test.rs
Close the server before exit RPC test.
=> [ᚬrc/v0.15.z] fix: random failure caused by dirty exit in RPC test

sync/src/types.rs
Backports the following commits to rc/v0.15.z:
- fix: ibd should remain false once returned false (#1097)
=> [ᚬrc/v0.15.z] fix: ibd should remain false once returned false

test/src/main.rs, test/src/net.rs, test/src/node.rs, test/src/specs/p2p/malformed_message.rs, test/src/specs/relay/block_relay.rs, test/src/specs/relay/compact_block.rs, test/src/specs/relay/transaction_relay.rs, test/src/specs/sync/block_sync.rs, test/src/specs/sync/chain_forks.rs, test/src/specs/sync/invalid_locator_size.rs, test/src/specs/sync/sync_timeout.rs
fix integration test for backport #1169 and this PR needs backport to rc/v0.16
=> test: fix integration test for backport #1169

util/app-config/src/cli.rs
`--ba-data` requires any of them, so they are included in a `ArgGroup`. But
`ArgGroup` requires one and only one must be present by default, which is
disabled with `multiple(true)`
=> fix: `--ba-code-hash` `--ba-arg` can be used together

chain/src/tests/basic.rs, core/src/cell.rs, core/src/transaction_meta.rs, protos/schemas/common.fbs, protos/src/convert/from_common.rs, protos/src/convert/to_common.rs, protos/src/generated/common.rs, script/src/verify.rs, shared/src/cell_set.rs, shared/src/chain_state.rs, shared/tx-pool-executor/src/tx_pool_executor.rs, store/src/store.rs, sync/src/relayer/compact_block_process.rs, sync/src/synchronizer/headers_process.rs, traits/src/block_median_time_context.rs, verification/src/contextual_block_verifier.rs, verification/src/tests/transaction_verifier.rs, verification/src/transaction_verifier.rs
When calculates block_median_time, we need to locate the specific blocks.
Using block_hash instead block_number to locate the specific blocks is more accurate.
* feat: Add `hash: H256` into `BlockInfo`
* fix: Locate blocks by block_hash when calculate block_median_time
-------
**BREAKING CHANGE**: The format of `TransactionMeta`  is changed, which is affected by `BlockInfo`
=> fix: locate blocks by hash

Cargo.lock, chain/src/tests/reward.rs, chain/src/tests/util.rs, rpc/src/test.rs, script/src/verify.rs, shared/src/cell_set.rs, shared/tx-pool-executor/src/tx_pool_executor.rs, sync/src/relayer/mod.rs, sync/src/relayer/tests/reconstruct_block.rs, sync/src/tests/mod.rs, sync/src/tests/sync_shared_state.rs, sync/src/tests/synchronizer.rs, sync/src/tests/util.rs, sync/src/types.rs, test/src/main.rs, test/src/rpc.rs, test/src/specs/relay/compact_block.rs, test/src/utils.rs, util/test-chain-utils/Cargo.toml, util/test-chain-utils/src/chain.rs, util/test-chain-utils/src/lib.rs, verification/src/tests/commit_verifier.rs
Originally we use `known_blocks` to avoid re-relay the same blocks to the same peers.
But now our code ensures that, as for the same blocks, we accept and relay only once. So this block-filter is useless.
=> chore: Remove useless known_blocks filter

sync/src/types.rs
=> test: skip-list test consumes too much time

sync/src/block_status.rs, sync/src/lib.rs, sync/src/relayer/compact_block_process.rs, sync/src/relayer/mod.rs, sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/block_pool.rs, sync/src/synchronizer/block_process.rs, sync/src/synchronizer/headers_process.rs, sync/src/synchronizer/mod.rs, sync/src/tests/sync_shared_state.rs, sync/src/types.rs
* refactor: Move `orphan_block_pool` into `SyncSharedState`
* feat: Rewrite `BlockStatus` and `block_status_map`
* perf: Use `BlockStatus` to avoid re-processing the same headers/blocks
=> refactor: Use BlockStatus to filter things

test/src/specs/mining/basic.rs
https://github.com/nervosnetwork/ckb/pull/1214 resets `current_time` of block template. We should adjust the compare function.
=> test: Compare block template

rpc/src/module/stats.rs, shared/src/chain_state.rs, shared/src/tests/shared.rs, shared/tx-pool-executor/src/tx_pool_executor.rs, sync/src/relayer/compact_block_process.rs, sync/src/synchronizer/headers_process.rs, traits/src/block_median_time_context.rs, verification/src/contextual_block_verifier.rs, verification/src/header_verifier.rs, verification/src/tests/transaction_verifier.rs, verification/src/transaction_verifier.rs
* Remove `block_number` from API `BlockMedianTimeContext::block_median_time`. 
Originally we pass `block_number` as a parameter to help calculate the span
```
span_start = min(0, block_number-customed_span)
span = [span_start, block_number]
```
In fact, it is unnecessary to calculate the span if we can know whether we reach the genesis during traveling the blocks. We can get it with the help of `timestamp_and_parent`!
So I reduce the `block_number` from `block_median_time`, to make the API more simplified.
=> feat: Remove block_number from BMT

Cargo.lock, util/test-chain-utils/Cargo.toml, util/test-chain-utils/src/lib.rs, util/test-chain-utils/src/median_time.rs, verification/src/tests/header_verifier.rs, verification/src/tests/transaction_verifier.rs
Create `MockMedianTime`, a testing util type, so that tests can share the same mocked implementation of `BlockMedianTimeContext`
=> test: Create a mock block_median_time

Cargo.lock, miner/Cargo.toml, miner/src/miner.rs
The default systemd init script redirects stderr to /dev/null. This change
ensure the daemon will log the found blocks as info level log.
=> feat: log found block as info when stderr is not tty

sync/src/relayer/mod.rs
=> fix: should check tx from pool when the short_id set is not empty

test/src/main.rs, test/src/specs/sync/invalid_block.rs, test/src/specs/sync/mod.rs, test/src/utils.rs
A bug we meet during the last testnet: A fork contains an invalid block. When we try to switch the fork as the main chain, it should be failed as expected.
=> test: sync fork contains invalid blocks

build.rs
Ignore the error when failed to read .git/HEAD.
Closes https://github.com/nervosnetwork/ckb/issues/1231
=> fix: build.rs failed without git dir

sync/src/relayer/mod.rs
=> [ᚬrc/v0.16] fix(relayer): should check tx from tx_pool when the short_id set is not empty

network/src/config.rs, network/src/network.rs, test/src/net.rs, test/src/specs/alert/alert_propagation.rs, test/src/specs/mod.rs, test/src/specs/p2p/discovery.rs, test/src/specs/sync/block_sync.rs, test/src/specs/sync/chain_forks.rs, test/src/specs/sync/sync_timeout.rs
optional start `OutboundPeerService` and `DnsSeedingService`, and fix random failure integration test `BlockSyncDuplicatedAndReconnect `
=> chore: optional start some network service

sync/src/types.rs
`rng.gen_range(0, 0);` 
The above code will [panic](https://rust-random.github.io/rand/rand/trait.Rng.html#panics).
=> fix: Skiplist test use gen_range the wrong way

indexer/src/store.rs
- Insert a `CellOutput`
https://github.com/nervosnetwork/ckb/blob/bd7865a76e5b53608f698a5fbeafc1f797ceb69d/indexer/src/store.rs#L548-L555
- Select as `Option<CellOutput>`
https://github.com/nervosnetwork/ckb/blob/bd7865a76e5b53608f698a5fbeafc1f797ceb69d/indexer/src/store.rs#L516-L522
https://github.com/nervosnetwork/ckb/blob/bd7865a76e5b53608f698a5fbeafc1f797ceb69d/indexer/src/types.rs#L36-L41
=> fix: there is an incorrect deserialization in indexer

network/src/config.rs, resource/ckb.toml
* Most people don't care `whitelist_peers/whitelist_only` and `public_addresses`. So I think it may be better to hide them.
=> chore: Disable whitelist-only mode by default

Cargo.lock, network/Cargo.toml, network/src/config.rs, network/src/lib.rs, network/src/protocols/mod.rs, network/src/protocols/test.rs, sync/src/synchronizer/get_blocks_process.rs, sync/src/synchronizer/mod.rs, sync/src/tests/mod.rs, test/src/net.rs
Do not send blocks to peer when session send buffer is full.
=> feat: Network flood control

ckb-bin/src/lib.rs, ckb-bin/src/subcommand/init.rs, ckb-bin/src/subcommand/run.rs, util/app-config/src/args.rs, util/app-config/src/cli.rs, util/app-config/src/lib.rs
Unless start the node with `ckb run --ba-advanced`
=> feat: only allow default secp256k1 block assembler

sync/src/types.rs
fix: Clear the newly inserted block from block_status_map.
We don't know whether the actual block status is BLOCK_VALID or BLOCK_INVALID.
So we just simply remove the corresponding in-memory block status,
and the next time `get_block_status` would acquire the real-time
status via fetching block_ext from the database.
=> fix: Clean status of new inserted block

network/src/network.rs, network/src/protocols/disconnect_message.rs, network/src/protocols/feeler.rs, network/src/protocols/mod.rs, network/src/protocols/ping.rs, network/src/protocols/string_message.rs, sync/src/relayer/tests/helper.rs, sync/src/synchronizer/headers_process.rs, sync/src/synchronizer/mod.rs, sync/src/tests/mod.rs
* Add a new p2p protocol `StringMessageProtocol` for send simple string message
* Send a message to remote peer when disconnect
=> feat: Send a message to remote peer when disconnect

miner/src/block_assembler.rs, rpc/src/module/miner.rs, sync/src/relayer/compact_block_process.rs, sync/src/types.rs, verification/src/block_verifier.rs
https://github.com/nervosnetwork/ckb/blob/develop/verification/src/block_verifier.rs#L161-L173
https://github.com/nervosnetwork/ckb/blob/develop/sync/src/types.rs#L786
https://github.com/nervosnetwork/ckb/blob/develop/sync/src/types.rs#L811
Should find parent from header_map firstly, otherwise, it may not find the parent and lead to the UnknownParent.
todo:
=> fix: header verifier with wrong header resolver

chain/src/tests/reward.rs, core/src/lib.rs, core/src/reward.rs, miner/src/block_assembler.rs, rpc/README.md, rpc/json/rpc.json, rpc/src/module/chain.rs, rpc/src/test.rs, shared/src/shared.rs, sync/src/synchronizer/mod.rs, sync/src/tests/synchronizer.rs, sync/src/tests/util.rs, traits/src/chain_provider.rs, util/jsonrpc-types/src/blockchain.rs, util/jsonrpc-types/src/lib.rs, util/reward-calculator/src/lib.rs, verification/src/contextual_block_verifier.rs
Firstly fix test:  `cellbase` should have `witness`, otherwise the RPC test will panic.
https://github.com/nervosnetwork/ckb/pull/1297/commits/25445bc4ab1c35e160fefe2bacd89ada32fcda76
=> feature: add get_block_finalized_reward_info rpc

network/src/peer_store/sqlite/peer_store.rs, network/src/tests/sqlite_peer_store.rs
Fix network continually retry failed dialing.
* node will not retry to dial a failed address within 1 minute
* node will stop trying to dial a *terrible* address after 3 failed retries
* node will try to dial a terrible address after 7 days since the last try.
=> fix: network continuely retry dialing on failed address

resource/ckb.toml, shared/src/shared.rs, shared/src/tx_pool/pool.rs, shared/src/tx_pool/types.rs
fix typo `max_verfify_cache_size` => `max_verify_cache_size`, txs verify cache should use this config value instead of a hardcoded value.
added a new config param for conflict txs cache capacity
=> fix: tx pool config typo and new config param

Cargo.lock, script/Cargo.toml, script/src/syscalls/debugger.rs, script/src/syscalls/load_cell.rs, script/src/syscalls/load_code.rs, script/src/syscalls/load_header.rs, script/src/syscalls/load_input.rs, script/src/syscalls/load_witness.rs, script/src/syscalls/mod.rs, script/src/syscalls/utils.rs, script/src/verify.rs
Please refer to the following URLs for changes from 0.13.0 to 0.15.1 in CKB VM.
https://github.com/nervosnetwork/ckb-vm/releases/tag/v0.14.0
https://github.com/nervosnetwork/ckb-vm/releases/tag/0.15.0
https://github.com/nervosnetwork/ckb-vm/releases/tag/0.15.1
One important note is that even though CKB VM supports the all new AOT mode right now, we are still only using the ASM interpreter in CKB since the performance is already good enough.
=> feat: Upgrade CKB VM to 0.15.1

Cargo.lock, chain/src/chain.rs, core/src/uncle.rs, miner/src/block_assembler.rs, miner/src/candidate_uncles.rs, miner/src/lib.rs, notify/src/lib.rs, shared/src/error.rs, verification/Cargo.toml, verification/src/contextual_block_verifier.rs, verification/src/error.rs, verification/src/tests/uncle_verifier.rs, verification/src/uncles_verifier.rs
Append uncle verification rule:  A block B1 is considered to be the uncle of another block B2, B1's parent is either B2's ancestor or embedded in B2 or its ancestors as an uncle
=> feat: uncle descendant limit

Cargo.lock, protocol/Cargo.toml, protocol/src/builder.rs, protocol/src/lib.rs, protocol/src/protocol.fbs, protocol/src/protocol_generated.rs, protocol/src/protocol_generated_verifier.rs, shared/src/tx_pool/pool.rs, sync/src/relayer/block_transactions_verifier.rs, sync/src/relayer/compact_block.rs, sync/src/relayer/compact_block_verifier.rs, sync/src/relayer/error.rs, sync/src/relayer/mod.rs, sync/src/relayer/tests/block_transactions_verifier.rs, sync/src/relayer/tests/compact_block.rs, sync/src/relayer/tests/compact_block_verifier.rs, sync/src/relayer/tests/reconstruct_block.rs
This PR changes `CompactBlock#short_id` to `ProposalShortId`, and `reconstruct_block` will try to get tx from the entire tx pool instead of proposal tx pool only.
=> refactor: using ProposalShortId in CompactBlock

.travis.yml
Most of the time the installing of cargo-sweep is more than 190s, sometimes even more than 240s
https://travis-ci.com/nervosnetwork/ckb/jobs/218871807
https://travis-ci.com/nervosnetwork/ckb/jobs/218871808
https://travis-ci.com/nervosnetwork/ckb/jobs/218871809
cargo-sweep make the ci very slow, it cleans something that we need.
After remove `cargo sweep -f`, only 8 minutes 50 seconds for Clippy,
https://travis-ci.com/nervosnetwork/ckb/jobs/219325780#L249
https://travis-ci.com/nervosnetwork/ckb/jobs/219325476#L252
https://travis-ci.com/nervosnetwork/ckb/jobs/219351657#L250
but the ci cache will quickly bloat.
https://gist.github.com/jkcclemens/000456ca646bd502cac0dbddcb8fa307
solution:
1. ~~use release mode, cut down the cache.~~ 
3. sweep the cache periodically.
~~before: uint test on …
=> ci: speed up ci

sync/src/synchronizer/headers_process.rs, sync/src/types.rs, test/src/specs/sync/ibd_process.rs
The ibd with non-protect/whitelist node has no sense, because after the headers are synchronized,
the node must be disconnected.
Furthermore, if ibd with the non-protected node, there may be a state that cannot be synchronized for a long time：
1. Assume that it has been impossible(long time) to randomize to the protected node
2. Random to the protected node, if the `shared_best_header` is the same as the protected node, [unable to start syncing](https://github.com/nervosnetwork/ckb/blob/develop/sync/src/synchronizer/headers_process.rs#L170), may stop sync with this node and then randomize to another node, go back to 1, else sync with protected node
=> fix: ibd only with protect/whitelist peers

script/src/lib.rs, script/src/verify.rs
Note this only applies to `Type` as a HashType, since if multiple
cells have the same data hash, the content must be the same.
=> fix: Reject hash type referencing via type with multiple matches

resource/ckb-miner.toml
Long `poll_interval` can prevent dummy miner re-poll frequently, so that avoid generating uncle blocks.
=> chore: Set long poll interval for dummy miner

.gitignore, Cargo.lock, Cargo.toml, chain/src/tests/basic.rs, core/src/extras.rs, protos/schemas/common.fbs, protos/src/convert/from_common.rs, protos/src/convert/to_common.rs, protos/src/generated/common.rs, rpc/README.md, rpc/json/rpc.json, spec/Cargo.toml, spec/src/consensus.rs, spec/src/lib.rs, util/dao/src/lib.rs, util/rational/Cargo.toml, util/rational/src/lib.rs, verification/src/tests/uncle_verifier.rs
Apply new difficulty adjustment mechanism
https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0020-ckb-consensus-protocol/0020-ckb-consensus-protocol.md#dynamic-difficulty-adjustment-mechanism
=> feat: difficulty adjustment rfc version

core/src/extras.rs, db/src/db.rs, db/src/transaction.rs, protos/schemas/storage.fbs, protos/src/convert/from_storage.rs, protos/src/convert/to_storage.rs, protos/src/generated/extra_methods.rs, protos/src/generated/storage.rs, store/src/db.rs, store/src/store.rs, store/src/transaction.rs, util/reward-calculator/src/lib.rs
This PR splits block body (transactions) into small value store and use rocksdb prefix seek API to improve the DB fetch performance.
=> perf: refactoring block body store

script/src/type_id.rs, script/src/verify.rs
While previous implementation allows cells to have different type IDs
when they are created in different transactions. One quirk of the
solution, is that all cells in a single transaction will have the same
type ID, since the type ID script arg only hashs all inputs in the
transaction. This commit fixes the problem by hashing the cell's own
index in outputs as well, this way different cells created together
can also have different type IDs.
Notice while we implement it in Rust, the logic here can also be
implemented via a script running in CKB VM
=> fix: Multiple type ID cell creation in single transaction

Makefile, test/src/main.rs
* `make ci` runs prior checks `fmt/clippy/test` first.
=> chore: Run niche checks posteriorly

sync/src/lib.rs, sync/src/synchronizer/block_fetcher.rs, test/src/main.rs, test/src/specs/sync/chain_forks.rs
* fix: Two long forks(> 128) cannot synchronize with each other
=> [ᚬrc/v0.18] fix: failed to sync for long forks

chain/src/chain.rs, miner/src/block_assembler.rs, rpc/src/module/chain.rs, script/src/verify.rs, shared/src/chain_state.rs, shared/src/tx_pool.rs, shared/src/tx_pool/commit_txs_scanner.rs, shared/src/tx_pool/pending.rs, shared/src/tx_pool/pool.rs, shared/src/tx_pool/proposed.rs, shared/src/tx_pool/types.rs, shared/tx-pool-executor/src/tx_pool_executor.rs, test/src/node.rs, test/src/specs/mining/size_limit.rs, util/dao/src/lib.rs, util/types/src/core/cell.rs, verification/src/tests/transaction_verifier.rs
Changes:
1. proposed pool and pending pool track txs in-pool ancestors and record the `ancestors_fee`, `ancestors_size`, `ancestors_cycles` for each tx.
2. proposed pool and pending pool are sort txs by tx's in-pool ancestors fee rate(aka ancestors score).
3. block_assembler package txs by the sort that tx_pool provides.
=> feat: tx_pool support sort by fee rate

Cargo.lock, miner/Cargo.toml, miner/src/lib.rs, miner/src/miner.rs, network/src/protocols/test.rs
1. Remove unnecessary lock
2. The discovery test of the occasional fails due to the timeout caused by resource competition, the test that can be passed on a more long time or run it on single
=> chore: remove unnecessary lock

docs/quick-start.md, docs/run-ckb-with-docker.md
* chore: Correct typo block_assember to block_assembler.
https://gist.github.com/apiraino/76d878104d3b6f649e6a3db8f6510914
=> chore: Correct typo block_assember to block_assembler

sync/src/relayer/block_transactions_process.rs, sync/src/relayer/compact_block_process.rs, sync/src/relayer/compact_block_verifier.rs, sync/src/relayer/error.rs, sync/src/relayer/mod.rs, sync/src/relayer/tests/block_transactions_process.rs, sync/src/relayer/tests/compact_block_process.rs, sync/src/relayer/tests/mod.rs, sync/src/relayer/tests/reconstruct_block.rs, util/types/src/extension/shortcuts.rs
nodes should attempt to reconstruct the full block by taking the prefilledtxn transactions
from the original CompactBlock message and placing them in the marked positions,
then for each short transaction ID from the original compact_block message, in order,
find the corresponding transaction either from the BlockTransactions message or
from other sources and place it in the first available position in the block
then once the block has been reconstructed, it shall be processed as normal,
keeping in mind that short_ids are expected to occasionally collide,
and that nodes must not be penalized for such collisions, wherever they appear.
=> fix: compact block short_id collides

resource/Cargo.toml
When `ckb-releases` is used external, it may uses a newer version of
ckb-system-scripts if the caret requirement is used in Cargo.toml, since the
version is only locked in the Cargo.lock in this repository.
This change ensures that when this is used as a crate externally, it always
use the exact version of ckb-system-scripts.
=> chore: lock exact ckb-system-scripts version

sync/src/lib.rs, sync/src/synchronizer/in_ibd_process.rs, sync/src/synchronizer/mod.rs, sync/src/types.rs
* fix: `ibd_process` will improperly substrate `n_sync_started` without checking whether the peer is `sync_started == true`, and then cause panic when disconnects peers.
* feat: Add `suspend_sync` function to help suspend the synchronization to the specified peers.
* feat: Assert `sync_started/n_protected_outbound_peers` overflow.
=> fix: check sync_started before handle InIBD

resource/ckb.toml, store/src/config.rs, store/src/lib.rs, store/src/store.rs
If we ran the test case `test_switch_valid_fork` separately as `cargo test test_switch_valid_fork`, the test case would fail. But when we ran `cargo test`, it passed, it was weird.
In https://github.com/nervosnetwork/ckb/blob/ba72c852d2e70176dfff0b2b3992be79dd59ef41/sync/src/tests/sync_shared_state.rs#L204-L259, there was only one store instance. After diving into it, the problem is that before we called the `get_block_ext` and cached the result, but after the fork chain became to the main chain, we called the `get_block_ext` again, it would return the stale data.
The `block_ext` is different from other data in DB, we would change it in DB, so the cache may be stale. I have not found a good way to update/clean the stale keys, so just remove it.
I think we had better not to set the …
=> fix: remove the block_ext cache

ckb-bin/src/subcommand/cli/secp256k1_lock.rs, ckb-bin/src/subcommand/init.rs, ckb-bin/src/subcommand/run.rs, docs/hashes.toml, resource/ckb.toml, resource/specs/dev.toml, resource/specs/staging.toml, resource/specs/testnet.toml, spec/src/consensus.rs, test/Cargo.toml, test/src/node.rs, util/app-config/src/cli.rs, util/jsonrpc-types/src/blockchain.rs
Co-authored-by: Quake <quake@nervos.org>
Co-authored-by: Qian Linfeng <thewawar@cryptape.com>
=> [ᚬrc/v0.19] feat: Use secp256k1 referenced by hash type "type" as the default lock.

test/src/main.rs, test/src/net.rs, test/src/node.rs, test/src/specs/mod.rs, test/src/specs/p2p/discovery.rs, test/src/specs/relay/compact_block.rs, test/src/specs/sync/block_sync.rs, test/src/utils.rs
* feat(test): Tail nodes' logs when fails
We treat tests are failed when
- tests panicked
- any thread in nodes has panicked(via searching nodes' logs)
* chore(test): Refactor Net and Node
=> feat(test): tail failed logs

store/src/store.rs, store/src/transaction.rs, test/src/main.rs, test/src/specs/sync/block_sync.rs, util/types/src/core/advanced_builders.rs, verification/src/contextual_block_verifier.rs
fix the issue from https://github.com/nervosnetwork/ckb/pull/1478,
PR#1478 stored uncle header in `COLUMN_BLOCK_HEADER`, broken conventional consistency.
many codes rely on header-body-ext consistency.
=> fix: block header should keep consistency with ext in storage

network/src/errors.rs, network/src/network.rs, network/src/protocols/identify.rs, network/src/services/outbound_peer.rs, rpc/src/module/net.rs
Fix broken observe address feature.
Observe address is a feature to leverage remote peers to report external IPs for a node.
In p2p network, when a node establishes outbound connections, the remote peers can observe the external IP of the node, remote peers should report the external IP through identify protocol, to help the node find out it's IP, it's kinda like the DDNS.
We have this feature built-in the original design, see the [identity protocol](https://github.com/nervosnetwork/p2p/blob/master/protocols/identify/src/protocol.fbs#L11) for details.
However, after a few development cycles, the observe address feature is broken.
In the current version, a node will not discovery external IPs through identify protocol. call `local_node_info` …
=> fix: use remote peer observed address

resource/specs/testnet.toml, shared/src/tx_pool.rs, spec/src/consensus.rs, spec/src/lib.rs, test/src/main.rs, test/src/rpc.rs, test/src/specs/tx_pool/mod.rs, test/src/specs/tx_pool/send_secp_tx.rs, util/crypto/src/secp/generator.rs
Increase the capacity of a block.
A block can contain 3875 typical 2 in 2 out txs.
=> chore: update block capacity

test/src/node.rs
Only print the stderr when the command fails.
=> chore: Suppress ckb init warnings in integration test

test/src/specs/sync/chain_forks.rs
In block builder, `transactions` extends transactions. In the test we really
want to replace all the transactions.
=> Fix invalid usage of vector builder method.

Cargo.lock, benches/Cargo.toml, benches/benches/bench_main.rs, benches/benches/benchmarks/mod.rs, benches/benches/benchmarks/next_epoch_ext.rs, util/rational/src/lib.rs
updated:
1. https://github.com/rust-num/num-rational/pull/42
2. For mul/div Rational or U256, we use new_raw is well, the same as add/sub U256, we assume that the Rational is already reduced when initialized.
3. for add/sub Rational, we compare the denom firstly.
=> [HOLD] fix: conduct GCD before rational ops

Cargo.lock, benches/Cargo.toml, docs/hashes.toml, miner/src/block_assembler.rs, resource/Cargo.toml, resource/specs/testnet.toml, rpc/README.md, rpc/json/rpc.json, spec/src/consensus.rs, test/src/node.rs, test/src/specs/mining/size_limit.rs, test/src/specs/tx_pool/limit.rs, test/src/specs/tx_pool/send_secp_tx.rs, util/types/schemas/ckb.mol, util/types/src/generated/types.rs
This PR contains 3 commits. The first two update the schema:
- Use struct instead of table to serialize on-chain data to make the
serialized data more compact.
- Reorder the fields to make the structure alignment friendly.
The last one regenerates code from the schema and updates all the hashes.
=> feat: Refactor serialization schema for performance.

script/data-loader/src/lib.rs, script/src/syscalls/load_header.rs, script/src/syscalls/mod.rs, script/src/syscalls/utils.rs, store/src/data_loader_wrapper.rs
Note this only adds epoch related data as header fields for now, later we will revise all syscalls to make sure the missing parts are fill in if needed(such as other header fields)
=> feat: Add load_header_by_field syscall for fetching epoch data

test/src/main.rs, test/src/specs/sync/block_sync.rs
Whether peer's chain is known best's ancestor is irrelevant here.
=> test: Node should fetch blocks from all peers with better chains

Cargo.lock, indexer/Cargo.toml, indexer/src/store.rs
This PR fixed an accidental bug of incorrect indexer store state when syncing indexer state and deindex an index in the same time.
=> fix: indexer store should lock the state when syncing data

store/src/db.rs, store/src/store.rs, store/src/transaction.rs, util/types/src/prelude.rs
This week, sentry reported few panics that the data from the storage can not deserialize.
After reviewing the code, I think it should be impossible.
I added the hex string of the bytes to sentry messages. So, next time, we can figure it out.
=> chore: let sentry capture panics when failed to verify the data from the storage

devtools/doc/rpc.py, rpc/README.md, rpc/json/rpc.json
Do not let a module appear in multiple places.
Update: doc tool was updated to only group RPC methods by module name in the generated doc. We keep the `rpc.json` intact as the unit tests depend on that file's content order to run successfully.
=> docs: Group methods of same module together

Cargo.lock, util/jsonrpc-types/Cargo.toml, util/jsonrpc-types/src/bytes.rs
To fill the line number and column number is a terrible thing.
=> test: make a unit test more flexible

util/jsonrpc-types/src/bytes.rs, util/types/src/conversion/blockchain.rs
Use interfaces is better than use the implementation details.
=> chore: hide the implementation details

script/src/syscalls/mod.rs, spec/src/consensus.rs, util/dao/src/lib.rs, util/types/schemas/ckb.mol, util/types/src/conversion/storage.rs, util/types/src/core/extras.rs, util/types/src/generated/types.rs
- The constructor is too complex, it's difficult to review when we just see the invocation of `new(...)`
- The field `block_reward` is `base_block_reward` in actual, so rename it to the corrected name.
=> chore: replace constructor of EpochExt by builder

spec/src/consensus.rs
The constructor accepts the parameter `epoch_reward` but it is not used to
initialize the field `epoch_reward`.
When a chain spec does not use the default epoch reward, it will still
reverted to the default epoch reward starting from the second epoch.
=> fix: Consensus constructor should init epoch reward from parameter.

util/types/src/extension/shortcuts.rs, verification/src/block_verifier.rs
Verify output length when cellbase is validated.
`is_cellbase` don't care about it's output length
=> chore: Verify output length when cellbase is validated

spec/src/lib.rs, test/src/specs/indexer/genesis_issued_cells.rs
Besides genesis message cell's lock script, all other cells' lock scripts must exists in genesis block.
=> feat: Check system cells lock script when build genesis block

sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/mod.rs
* Fetch blocks even if orphan_pool already cached
* Process blocks even if orphan_pool already cached
Although this change will introduce re-processing the same blocks, but it fix the data race problem between orphan_pool and storage
=> [ᚬrc/v0.19] Fix orphan block race storage

benches/benches/benchmarks/overall.rs, ckb-bin/src/subcommand/init.rs, miner/src/block_assembler.rs, miner/src/config.rs, resource/ckb.toml, test/src/node.rs, test/src/specs/mining/bootstrap.rs, test/src/specs/tx_pool/send_secp_tx.rs, util/app-config/src/args.rs, util/app-config/src/cli.rs, util/app-config/src/lib.rs, verification/src/block_verifier.rs, verification/src/error.rs, verification/src/tests/block_verifier.rs
Because the ckb reward is delayed, the ownership of the cellbase of the current block is not the miner who digs out the block, so cellbase's output data must be disabled.
=> feat: cellbase output data must be empty

sync/src/types.rs
Sentry reported this `panic` in our latest release -- `v0.20.0 (rylai-v9 024408e 2019-09-07)` again.
=> chore: let sentry capture more details when failed to `get_locator`

test/src/main.rs, test/src/specs/sync/block_sync.rs
Case:
1. `target_node` maintains an unverified fork
2. Expect that when other peers request `target_node` for the blocks on the unverified
fork(referred to as fork-blocks), `target_node` should discard the request because
these fork-blocks are unverified yet or verified failed.
=> test: Request unverified blocks

Cargo.lock, ckb-bin/Cargo.toml, network/Cargo.toml, script/Cargo.toml, util/crypto/Cargo.toml, util/fixed-hash/core/Cargo.toml, util/hash/Cargo.toml, util/jsonrpc-types/Cargo.toml
Related changes:
https://github.com/nervosnetwork/faster-hex/pull/9
https://github.com/nervosnetwork/blake2b-rs/pull/5
=> chore: Bump faster-hex and blake2b-rs versions

Cargo.lock, chain/src/chain.rs, ckb-bin/Cargo.toml, ckb-bin/src/subcommand/init.rs, ckb-bin/src/subcommand/prof.rs, ckb-bin/src/subcommand/run.rs, devtools/azure/windows-dependencies.yml, resource/ckb.toml, resource/src/lib.rs, resource/src/template.rs, rpc/src/module/experiment.rs, script/Cargo.toml, script/src/lib.rs, script/src/verify.rs, shared/Cargo.toml, shared/src/shared.rs, shared/src/tx_pool/pool.rs, shared/src/tx_pool_ext.rs, shared/tx-pool-executor/src/tx_pool_executor.rs, traits/Cargo.toml, traits/src/chain_provider.rs, util/app-config/Cargo.toml, util/app-config/src/app_config.rs, verification/src/contextual_block_verifier.rs, verification/src/tests/commit_verifier.rs, verification/src/tests/uncle_verifier.rs, verification/src/transaction_verifier.rs
NOTE: one side effect here, is that CKB will only be able to run on
64-bit Windows, Linux and maxOS platforms with this change. We can
discuss if this will bring future problems. One alternative solution
here, is that we can still remove ScriptConfig and leave only one VM
here, then use conditional compilation to revert to Rust based VMs on
32-bit platforms, or ARM processors. This way on each platform, we are
still only supporting just one VM for simplicity
=> feat: Keep only one version of VM by removing ScriptConfig

test/src/specs/sync/chain_forks.rs
Add comment to declare the purpose of the `sleep` and ajust it to a smaller value.
=> test: sleep less time in test

script/Cargo.toml, script/build.rs, script/src/verify.rs
This commit adds 2 changes:
* It adds a feature to allow disabling logging, hence saving us a
lot of depdendencies
* It adds a feature to allow compiling without assembly interpreter
mode. In CKB we won't allow this since we want only one interpreter,
but when integrating with alternative projects, such as web
debugger, this can be quite helpful
=> feat: script package build adjustment

sync/src/relayer/block_transactions_process.rs, sync/src/relayer/block_uncles_verifier.rs, sync/src/relayer/compact_block_process.rs, sync/src/relayer/error.rs, sync/src/relayer/mod.rs, sync/src/relayer/tests/block_transactions_process.rs, sync/src/relayer/tests/compact_block_process.rs, sync/src/relayer/tests/reconstruct_block.rs, sync/src/synchronizer/block_pool.rs, sync/src/types.rs, util/types/schemas/ckb.mol, util/types/src/extension/shortcuts.rs, util/types/src/generated/types.rs
The peer should already have the uncle blocks at a high probability. If the peer cannot find the uncle locally, use download uncle to get the header and proposals.
=> feat(Improvement): Compact Block only includes uncle blocks hash

network/src/config.rs, network/src/peer_store/peer_store_db.rs, network/src/services/dump_peer_store.rs, network/src/tests/peer_store_db.rs, util/app-config/src/cli.rs
This error cause peer store persistent error:
1. peer store will not persistent at exit(will still persistent to file every 1 hour when the node is running).
2. peer store persistent failed if `tmp dir` and `ckb dir` use a different file system.
A node will connect to bootnodes on start if the above error happened, other functions are not affected.
* Fix dump error when tmp files use a different file system [detail](https://stackoverflow.com/questions/24209886/invalid-cross-device-link-error-with-boost-filesystem?answertab=votes#tab-top).
* Fix peer store do not dump data on exit.
=> fix: peer store persistent

rpc/src/module/miner.rs, test/src/node.rs, test/src/rpc.rs
feat: Change return type of RPC `submit_block` from `Result<Option<H256>>` to `Result<H256>`
feat: Announce only new block
=> feat: Change return type of RPC submit block 

shared/src/shared.rs, tx-pool/src/lib.rs, tx-pool/src/service.rs
* chore: typo `builer` -> `builder`
=> chore: Correct typo builder

chain/src/chain.rs, db/src/lib.rs, error/src/internal.rs, error/src/lib.rs, script/src/verify.rs, shared/src/shared.rs, tx-pool/src/pool.rs, tx-pool/src/service.rs, verification/src/error.rs
* chore: Use `failure::Context` to manage internal error
* chore: Remove derivation from Fail for error_kinds
NOTE: The previous implementation shows incomplete error messages. Here is an example:
```
Before: Internal(Database)
Now: Internal(Database(failed to open the database: Invalid argument: You have to open all column families. Column families not opened: 12))
```
=> chore: manage internal error

Cargo.lock, network/Cargo.toml, network/src/network.rs, network/src/protocols/discovery.rs, network/src/protocols/test.rs
=> chore: upgrade p2p and ring

chain/src/chain.rs, test/src/specs/mining/size_limit.rs, test/src/specs/tx_pool/limit.rs, tx-pool/src/pool.rs, tx-pool/src/process/submit_txs.rs, util/types/src/core/views.rs, util/types/src/extension/serialized_size.rs, verification/src/block_verifier.rs, verification/src/tests/block_verifier.rs, verification/src/transaction_verifier.rs
- `block.serialized_size()` -> `block.serialized_size_without_uncle_proposals()`
- `tx.serialized_size()` -> `tx.serialized_size_in_block()`
=> chore: better name for `serialized_size(..)` methods to avoid ambiguity

chain/src/tests/basic.rs, chain/src/tests/delay_verify.rs, db/src/db.rs, error/src/lib.rs, error/src/util.rs, script/src/verify.rs, util/types/src/core/cell.rs, verification/src/tests/block_verifier.rs, verification/src/tests/commit_verifier.rs, verification/src/tests/header_verifier.rs, verification/src/tests/transaction_verifier.rs, verification/src/tests/uncle_verifier.rs
Support user-defined output when assert failed
=> chore: change `assert_error_eq` from function to macro

chain/src/tests/block_assembler.rs, tx-pool/src/block_assembler/mod.rs
Now for the blank block, the `serialized_size` and `as_slice().len()` are the same, but I think we should use `serialized_size`.
=> fix: use serialized_size while calculate_txs_size_limit

Cargo.lock, ckb-bin/Cargo.toml, ckb-bin/src/subcommand/init.rs, resource/ckb-miner.toml, resource/ckb.toml, resource/src/lib.rs, resource/src/template.rs, spec/src/lib.rs, util/app-config/src/app_config.rs, util/app-config/src/args.rs, util/app-config/src/cli.rs, util/app-config/src/lib.rs
Add a new option `ckb init --import-spec <file>`.
It allows copying the spec file in `ckb init` from `<file>`. Specially, when `<file>` is "-", read the spec file from stdin encoded in base64.
=> [ᚬrc/v0.22] feat: Allow setting the spec file in ckb init.

test/src/specs/sync/chain_forks.rs, test/src/utils.rs
https://github.com/nervosnetwork/ckb/pull/1605 did not correctly resolve conflict before merging. Hence it breaks CI for develop-branch. Here comes this PR to fix it.
=> fix(test): First 11 cellbases have not outputs

test/src/node.rs, test/src/specs/mining/uncle.rs, test/src/specs/sync/chain_forks.rs
Fix panic of ForksContainSameUncle. The reason is that the uncle block has the same hash with the main chain block.
=> fix: fix construct_uncle in integration test

test/src/node.rs
The number of logs is acceptable after #1474.
=> chore(test): Allow CI debug logs

spec/src/consensus.rs
=> chore: issuance comment

Cargo.lock, ckb-bin/Cargo.toml, ckb-bin/src/subcommand/init.rs, resource/ckb-miner.toml, resource/ckb.toml, resource/src/lib.rs, resource/src/template.rs, spec/src/lib.rs, util/app-config/src/app_config.rs, util/app-config/src/args.rs, util/app-config/src/cli.rs, util/app-config/src/lib.rs
Add a new option `ckb init --import-spec <file>`.
It allows copying the spec file in `ckb init` from `<file>`. Specially, when `<file>` is "-", read the spec file from stdin encoded in base64.
=> feat: Allow setting the spec file in ckb init.

test/src/specs/p2p/whitelist.rs, test/src/specs/sync/ibd_process.rs
generated blocks in the connected state
=> test: generated blocks in the connected state

util/types/src/extension/calc_hash.rs
Uncles hash is the blake2b on concatenated uncle block hashes.
=> fix: resolve uncles hash calculation issue

test/src/net.rs, test/src/specs/p2p/malformed_message.rs, test/src/specs/relay/compact_block.rs, test/src/specs/relay/get_block_transactions_process.rs, test/src/specs/sync/block_sync.rs
There are some relayer-notify jobs in sync, see https://github.com/nervosnetwork/ckb/blob/develop/sync/src/relayer/mod.rs#L44-L46. This would dislocate the message order.
=> test: fix compact_block_missing_fresh_txs integration test

benches/benches/benchmarks/overall.rs, benches/benches/benchmarks/util.rs, chain/src/tests/reward.rs, indexer/src/store.rs, script/src/syscalls/mod.rs, script/src/verify.rs, spec/src/lib.rs, test/src/node.rs, test/src/specs/dao/mod.rs, test/src/specs/dao/satoshi_dao_occupied.rs, test/src/specs/indexer/genesis_issued_cells.rs, test/src/specs/mining/bootstrap.rs, test/src/specs/tx_pool/send_secp_tx.rs, tx-pool/src/component/proposed.rs, tx-pool/src/process/block_template.rs, util/dao/src/lib.rs, util/jsonrpc-types/src/blockchain.rs, util/test-chain-utils/src/chain.rs, util/types/schemas/ckb.mol, util/types/src/conversion/blockchain.rs, util/types/src/core/blockchain.rs, util/types/src/core/cell.rs, util/types/src/extension/check_data.rs, util/types/src/generated/types.rs, verification/src/transaction_verifier.rs
This PR changes enum types in ckb.mol (`ScriptHashType` and `DepType`) from `[byte; 1]` to `byte`, it simplifies builder API and avoids some unnecessary conversions.
=> refactor: change enum from `[byte; 1]` to `byte`

test/src/main.rs
These cases will fail occasionally because of some unknown asynchronous issues.
=> test: Comment IBD cases

test/src/specs/indexer/basic.rs, tx-pool/src/component/container.rs, tx-pool/src/component/pending.rs, tx-pool/src/component/proposed.rs, tx-pool/src/process/chain_reorg.rs
Before this part, https://github.com/nervosnetwork/ckb/blob/develop/test/src/specs/indexer/basic.rs#L59-L75 code's  log is that 
```
2019-10-15 11:49:52.672 +08:00 ChainService INFO ckb-chain  block: 13, hash: Byte32(0x75cddba4ee0b6b15a03be7667c3e44af045282dfc0b151699be84cd4eb275556), total_diff: 0xe00, txs: 1
2019-10-15 11:49:52.673 +08:00 http.worker3 DEBUG ckb-rpc  [block_relay] announce new block 13 Byte32(0x75cddba4ee0b6b15a03be7667c3e44af045282dfc0b151699be84cd4eb275556) 1571111392673
2019-10-15 11:49:52.675 +08:00 GlobalRuntime-1 DEBUG ckb-tx-pool  tx proposed, add to gap Byte32(0x569c112c72a1248a12ece2bd1c1fbdd793d9b4ea698b93c60af21fe45efd9f42)
2019-10-15 11:49:52.676 +08:00 GlobalRuntime-1 DEBUG ckb-tx-pool  tx proposed, add to gap …
```
=> fix: tx sorted_keys order by relation

Cargo.lock, script/Cargo.toml
See https://github.com/nervosnetwork/ckb-vm/releases/tag/0.18.0 for
changes in CKB VM 0.18.0
=> feat: Upgrade CKB VM to 0.18.0

docs/hashes.toml, resource/specs/testnet.toml, spec/src/consensus.rs, spec/src/lib.rs, util/dao/utils/src/lib.rs
Genesis block should have `primary_block_reward` and `secondary_block_reward`, as it is the first block of the first epoch.
=> fix: Exclude primary/secondary issuance in genesis

.travis.yml, Makefile, test/src/lib.rs, test/src/main.rs, test/src/utils.rs, test/src/worker.rs
Use `make integration CKB_TEST_ARGS="-c 8"` to run integration tests in 8 concurrent workers.
The default concurrent number is 4, which can reduce 3~4x times of integration tests on my machine.
For CI the concurrent number is set to 1 (our CI sucks), we can increase this value when we enhance the performance of CI.
=> refactor: support run integration tests concurrently

test/src/specs/tx_pool/valid_since.rs
reason: https://github.com/nervosnetwork/ckb/blob/develop/verification/src/transaction_verifier.rs#L536
In the test, the cell timestamp is calculated from the block which packaged the cell. but it should be calculated from its parent.
@u2 @keroro520 @quake
=> fix: fix valid since test

rpc/README.md, rpc/json/rpc.json, util/dao/utils/src/lib.rs
The reason is that `U` in genesis DAO is too small. When generating transactions that occupy many capacities than `U`, the DAO calculation overflow.
=> fix: fix benchmark overflow

shared/src/shared.rs
fix issue: ckb will crash when running on an os which tmpfs is full or doesn't exist.
cause: The `ShareBuilder` will try to create an empty tmp folder for rocksdb in the `Default` trait implementation: https://github.com/nervosnetwork/ckb/blob/a45618c1b32d0d0a42a97f4f1491039fd7228155/shared/src/shared.rs#L239 , demo:  https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2b4046c1197c8538651932d862ea3772
before this fix, we will always see the log when starting ckb node:
```
2019-10-28 11:09:31.014 +09:00 main INFO ckb-db  Initialize a new database
```
=> fix: avoids creating tmp folder for db initialization

test/Cargo.toml, test/src/node.rs, test/src/rpc.rs, test/src/rpc/error.rs, test/src/rpc/id_generator.rs, test/src/rpc/macros.rs, test/src/specs/tx_pool/valid_since.rs, test/src/utils.rs, util/jsonrpc-types/src/cell.rs, util/jsonrpc-types/src/indexer.rs
* replace https://crates.io/crates/jsonrpc-client-core
This https://crates.io/crates/jsonrpc-client-core is unruly and still uses tokio-core which is deprecated, 
the maintainers are not around to work on this project. 
https://dev.azure.com/nervosnetwork/ckb/_build/results?buildId=7366
we catch some  `Canceled` error is not being handled elegantly, lead to lock been poisoned.
* singleton http-clinet 
We don't need to instantiate http-clinet for every test-case, every simulate node.
=> refactor: replace non-maintained jsonrpc client

Cargo.lock, benches/Cargo.toml, docs/hashes.toml, resource/Cargo.toml, resource/specs/testnet.toml, test/src/main.rs, test/src/specs/dao/mod.rs, util/dao/Cargo.toml, util/dao/src/lib.rs
Depends on https://github.com/nervosnetwork/ckb-system-scripts/pull/59
=> feat: Adapt to 2-phase Nervos DAO implementation

Cargo.lock, db/Cargo.toml
See https://github.com/nervosnetwork/rust-rocksdb/pull/1 for changes for the rocksdb library.
While this won't affect CKB, it provides a different rocksdb version that can aid ReadOnly mode when using ckb packages.
=> feat: Upgrade rocksdb with ReadOnlyDB changes

tx-pool/src/component/mod.rs
`TWO_IN_TWO_OUT_BYTES / TWO_IN_TWO_OUT_CYCLES ~= 0.000_17f64`
=> chore: adjust DEFAULT_BYTES_PER_CYCLES

error/src/lib.rs, rpc/src/module/alert.rs, rpc/src/module/experiment.rs, rpc/src/module/pool.rs, test/src/specs/dao/dao_tx.rs, test/src/specs/tx_pool/valid_since.rs
fix #1389
before:
```
{"jsonrpc":"2.0","error":{"code":-32603,"message":"Internal error"},"id":2}
```
after:
```
{"jsonrpc":"2.0","error":{"code":-3,"message":"Dao: InvalidOutPoint"},"id":2}
```
=> fix: error message on calculate dao max withdraw

sync/src/lib.rs, sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/get_blocks_process.rs
cleanup code for unused `PER_FETCH_BLOCK_LIMIT` const, it should be replaced by `MAX_BLOCKS_IN_TRANSIT_PER_PEER `, and add limit checking to `GetBlocks` message.
=> chore: code cleanup and add limit checking to `GetBlocks` message

util/dao/src/lib.rs
This small bug will not cause any validity problems.
=> fix: Calculate interest with older withdraw header

docs/hashes.toml, resource/specs/testnet.toml, src/main.rs
- Remove code name.
- Rename testnet genesis message.
=> chore: remove code name and rename testnet genesis message

test/src/specs/relay/compact_block.rs
When the peer receives a `CompactBlock` with a fresh tx, we expect that it requests us the target fresh tx via `RelayProtocol::GetBlockTransactions`. But in some cases, the peer can request via `SyncProtocol::GetBlocks`.
=> fix(test): Handle case that sync reply before relay

.travis.yml, azure-pipelines.yml, devtools/windows/ckb-init-mainnet.bat, devtools/windows/ckb-reinit-mainnet.bat, devtools/windows/ckb-run.bat, docs/quick-start.md
- Static link openssl in macOS package, so it will not require openssl as a runtime dependency.
- Add bat files in Windows package to ease starting a node in Windows.
=> refactor: enhance the binary packages.

util/build-info/src/lib.rs
The default abbrev length is different in different git versions.
=> chore: ensure commit abbrev in version consistent

util/jsonrpc-types/src/blockchain.rs
Keep the order consistent with molecule schema.
=> chore: reorder jsontypes fields

rpc/src/module/experiment.rs
Neuron will request `calculate_dao_maximum_withdraw` to calculate NervosDAO interest. So when a fresh node does not synchronize completely, a `calculate_dao_maximum_withdraw` request may trigger an error.
It is unnecessary to write this error into logs.
=> chore: omit calculate_dao_maximum_withdraw log

chain/src/tests/basic.rs, network/src/protocols/mod.rs, sync/src/relayer/tests/helper.rs, sync/src/synchronizer/mod.rs, sync/src/tests/mod.rs
After exiting the `ibd` mode, the invalid notify should be removed. Frequent switching of the context is also expensive in the Tokio runtime.
on tokio 0.1, `notify` submit to global queue will cause a  thundering herd on all task thread, it will cause all thread to catch the same mutex lock
=> perf: after exiting the ibd mode, the invalid notify should be removed

Cargo.lock, network/Cargo.toml, network/src/network.rs
I hard code the default maximum number of connections to 1024, because I haven't figured out whether it needs to be handled as a configuration item by the user
see https://github.com/nervosnetwork/p2p/blob/master/CHANGELOG.md
=> chore: upgrade p2p to 0.2.7

Cargo.lock, script/Cargo.toml
Please refer to https://github.com/nervosnetwork/ckb-vm/releases/tag/0.18.1 for changes in this release.
=> feat: Upgrade ckb-vm to 0.18.1

Cargo.toml, Makefile, devtools/release/make-with-debug-symbols
1. [Stable releases of cargo don't support custom profiles.](../../../rust-lang/cargo/issues/6988)
2. We can't use another manifest file in same directory since `error: the manifest-path must be a path to a Cargo.toml file`.
3. I try to put a debug version of `Cargo.toml` in another  directory, it's conflicted with the original `Cargo.toml`. Each crate should be in only one workspace.
4. Add arguments into `RUSTFLAGS` to control `rustc`, but it's unable to achieve the same effect.
According to [The Cargo Book](https://doc.rust-lang.org/cargo/reference/manifest.html#the-profile-sections): `debug = true` is equivalent to `-C debuginfo=2` compiler flag.
According to `rustc --help`, `-g` is equivalent to `-C debuginfo=2`.
But when use `debug = true`, the size of debug symbols in executable …
=> feat: no debug symbols as default and add a command to build with debug symbols

network/src/peer_store/peer_store_impl.rs, network/src/tests/peer_store.rs
The old code use `last_connected_at_ms > expired_ms` to detect a recently connected address, but the condition is wrong if a peer keeps connected for a long time(`ADDR_TIMEOUT_MS = 7days`), because when the peer is connected, a feeler protocol will not refresh the address's `last_connected_at_ms`.
This PR fixes the condition of `fetch_random_addrs`. this function should return address that belongs to currently connected peers. When a peer disconnected, the feeler protocol will be able to refresh the address's `last_connected_at_ms`.
=> fix: fetch_random_addrs should be able to return peers addrs

network/src/peer_store/peer_store_impl.rs, network/src/peer_store/types.rs, network/src/protocols/discovery.rs
* Consider space-efficient, we do not store p2p phase of multiaddr in peer store.
* Reattach the p2p phase when we send multiaddr to other nodes.
---
Closes https://github.com/nervosnetwork/ckb/issues/1872
=> fix: remove duplicate p2p phase in discovery protocol

network/src/network.rs, network/src/protocols/identify.rs
after this pr, all protocol will open after `identify` open, avoid feeler interacting with different networks and compatible with older versions
=> feat: move feeler behind identify

Cargo.lock, devtools/azure/windows-dependencies.yml, script/Cargo.toml
See [here](https://github.com/nervosnetwork/ckb-vm/releases/tag/0.18.2) for CKB VM changes.
=> feat: Use scoop to replace chocolatey for more stable CI

.dockerignore, docker/docker-entrypoint.sh, docker/hub/Dockerfile, docs/run-ckb-with-docker.md
This PR changes the behavior of the docker image.
Before the configuration are generated when building the image.
After the changes, the docker image uses a shell script as the entrypoint instead. The shell script will auto init the ckb directory when no config files are found. The environment variable `CKB_CHAIN` can control which chain spec to init.
=> chore: auto init ckb dir in Docker

Cargo.lock, resource/ckb.toml, rpc/Cargo.toml, rpc/src/config.rs, rpc/src/module/alert.rs, rpc/src/module/chain.rs, rpc/src/module/experiment.rs, rpc/src/module/indexer.rs, rpc/src/module/miner.rs, rpc/src/module/net.rs, rpc/src/module/pool.rs, rpc/src/module/stats.rs, rpc/src/module/test.rs, rpc/src/server.rs, rpc/src/test.rs
This PR adds tcp and websocket support for rpc, this is required for #1867 
test tcp:
```shell
telnet localhost 18114
> {"id":2,"jsonrpc":"2.0","method":"get_tip_block_number","params":[]}
< {"jsonrpc":"2.0","result":"0x337e","id":2}
```
test websocket:
```javascript
let socket = new WebSocket("ws://localhost:28114");
socket.onmessage = function(event) {
console.log(`Data received from server: ${event.data}`);
};
socket.send('{"id":2,"jsonrpc":"2.0","method":"get_tip_block_number","params":[]}');
```
=> feat: add tcp and websocket to rpc service

spec/src/consensus.rs, spec/src/lib.rs
Provide `max_block_bytes` option supports configurable block bytes limit.
=> feat(spec): configurable block bytes limit

network/src/protocols/test.rs
move dail different net behind dail same net, because identify will ban node when they are on the different net
=> test: move dail different net behind dail same net

Cargo.lock, Cargo.toml, chain/src/chain.rs, ckb-bin/src/subcommand/run.rs, notify/Cargo.toml, notify/src/lib.rs, resource/ckb.toml, rpc/Cargo.toml, rpc/src/module/alert.rs, rpc/src/module/stats.rs, rpc/src/test.rs, shared/Cargo.toml, shared/src/shared.rs, util/app-config/Cargo.toml, util/app-config/src/app_config.rs, util/network-alert/Cargo.toml, util/network-alert/src/alert_relayer.rs, util/network-alert/src/config.rs, util/network-alert/src/notifier.rs, util/network-alert/src/tests/test_notifier.rs
This PR resolve https://github.com/nervosnetwork/ckb/issues/1860 and refactor network alert script notification by adding a notify service, and it's required to implement https://github.com/nervosnetwork/ckb/issues/1867
**configuration  file breaking change**
```diff
-# [alert_notifier]
-# # Script will be notified when node received an alert, first arg is alert message string.
-# notify_script = "echo"
+# [notifier]
+# # Execute command when the new tip block changes, first arg is block struct in json format string.
+# new_block_notify_script = "your_new_block_notify_script.sh"
+# # Execute command when node received an network alert, first arg is alert message string.
+# network_alert_notify_script = "your_network_alert_notify_script.sh"
```
=> feat: notify service

network/src/protocols/disconnect_message.rs
The disconnect reason from peer is a useful information to check out network
issues.
=> chore: print disconnect reason as info level log

Cargo.lock, ckb-bin/src/subcommand/run.rs, devtools/doc/rpc.py, resource/ckb.toml, rpc/Cargo.toml, rpc/README.md, rpc/json/rpc.json, rpc/src/config.rs, rpc/src/lib.rs, rpc/src/module/mod.rs, rpc/src/module/subscription.rs, rpc/src/server.rs, rpc/src/service_builder.rs, rpc/src/test.rs
resolve #1867 
tcp rpc subscription example:
```
telnet localhost 18114
> {"id": 2, "jsonrpc": "2.0", "method": "subscribe", "params": ["new_tip_header"]}
< {"jsonrpc":"2.0","result":0,"id":2}
< {"jsonrpc":"2.0","method":"subscribe","params":{"result":"...block header json...","subscription":0}}
< {"jsonrpc":"2.0","method":"subscribe","params":{"result":"...block header json...","subscription":0}}
< ...
> {"id": 2, "jsonrpc": "2.0", "method": "unsubscribe", "params": [0]}
< {"jsonrpc":"2.0","result":true,"id":2}
```
websocket rpc subscription example:
```
let socket = new WebSocket("ws://localhost:28114")
socket.onmessage = function(event) {
console.log(`Data received from server: ${event.data}`);
}
socket.send(`{"id": 2, "jsonrpc": "2.0", "method": "subscribe", "params": …
```
=> feat: add rpc subscription

ckb-bin/src/subcommand/run.rs, network/src/network.rs, network/src/services/mod.rs, network/src/services/protocol_type_checker.rs, rpc/src/test.rs, test/src/net.rs
Add a new background network service, ProtocolTypeChecker:
CKB evicts inactive peers in `sync` protocol; but due to P2P connection design, a malicious peer may choose not to open `sync` protocol, to sneak from the eviction mechanism; this service periodically check peers opened sub-protocols, to make sure no malicious connection.
Currently, 2 sub-protocols types are valid:
1. fully-opened: all sub-protocols(except feeler) are opened.
2. feeler: only open feeler protocol is open.
Other protocols will be closed after a timeout.
=> feat: periodically disconnect peers which open invalid sub-protocols

rpc/Cargo.toml, rpc/README.md, rpc/json/rpc.json, rpc/src/module/pool.rs, rpc/src/test.rs, spec/src/consensus.rs, test/src/rpc.rs, test/src/specs/tx_pool/send_secp_tx.rs, test/src/specs/tx_pool/valid_since.rs, test/src/utils.rs, util/types/src/extension/shortcuts.rs, verification/src/lib.rs, verification/src/transaction_verifier.rs
=>  feat: add `outputs_validator` to `send_transaction` rpc

rpc/README.md, rpc/json/rpc.json, rpc/src/module/chain.rs, rpc/src/test.rs, test/src/rpc.rs, test/src/specs/mining/fee.rs, tx-pool/src/block_assembler/mod.rs, util/jsonrpc-types/src/blockchain.rs, util/jsonrpc-types/src/lib.rs, util/reward-calculator/src/lib.rs, util/snapshot/src/lib.rs, util/types/src/core/mod.rs, util/types/src/core/reward.rs, verification/src/contextual_block_verifier.rs
Replace the JSON-RPC method [`get_cellbase_output_capacity_details`].
According to [CKB RFC-0015](https://github.com/nervosnetwork/rfcs/blob/dda4478/rfcs/0015-ckb-cryptoeconomics/0015-ckb-cryptoeconomics.md#collecting-state-rent-with-secondary-issuance-and-the-nervosdao):
> Then 60% of the secondary issuance goes to the miners, 35% of the issuance goes to the NervosDAO to be distributed to the locked tokens proportionally.
Only 60% of the secondary issuance goes to the miners.
But we can't see it from the response of [`get_cellbase_output_capacity_details`].
According to [CKB v0.25.2 Code](https://github.com/nervosnetwork/ckb/blob/dda4ed9/util/reward-calculator/src/lib.rs#L87-L215):
```rust
/// Miner get (tx_fee - 40% of tx fee) for tx commitment.
/// Be careful of the rounding, tx_fee - …
```
=> feat: add a new json rpc method `get_block_economic_state`

Cargo.lock
The new rust toolchain (v1.41.0) can not work well with v1 format `Cargo.lock`.
I met a bug when I tried to upgrade two dependencies: `molecule` and `bytes`.
```
cargo build  --release                                                         
Compiling backtrace-sys v0.1.32                                             
Compiling rand v0.5.6                                                       
Compiling molecule v0.5.0                                                   
Compiling backtrace v0.3.40                                                 
error: expected one of `!` or `::`, found `(`                                  
--> /opt/local/cargo/registry/src/github.com-1ecc6299db9ec823/molecule-0.5.0/src/lib.rs:54:35                                                                
| …
```
=> chore: translate Cargo.lock to the v2 format

rpc/README.md, rpc/json/rpc.json, rpc/src/module/pool.rs
Make it backward compatible with the previous version. We should upgrade SDK
to support this flag by default when version is 0.28.0 or above, instead of
introducing the breaking change directly in the RPC.
=> feat: null outputs_validator means passthrough.

Makefile
`spin` is a stable synchronization primitive implementation, not updating for 5 months is not a security issue, just ignore this warning
=> chore: ignore spin warning

Cargo.toml, Makefile, ckb-bin/Cargo.toml, ckb-bin/src/helper.rs, util/Cargo.toml
we should disable deadlock detection by default.  
use the `deadlock_detection` feature flag enable  deadlock detection.
=> feat: uses feature flags to enable deadlock detection

Cargo.lock, Makefile, devtools/ci/check-cargotoml.sh, error/Cargo.toml, script/Cargo.toml
See the release notes for CKB VM 0.19.1 for more details:
https://github.com/nervosnetwork/ckb-vm/releases/tag/0.19.1
=> feat: Bump CKB VM to fix a performance regression

Cargo.lock, db/Cargo.toml
Cargo fetch the git repository is unbearably slow
Replace it with published crate.
explicitly `features = ["snappy"]` for backward compatibility.
=> feat: replace rocksdb wrapper

Cargo.toml
**This PR can be reviewed but it requires test before merge.**
Currently, ckb has two allocators:
- When we compile the latest version CKB on Linux, the code written by Rust will use Jemalloc.
https://github.com/nervosnetwork/ckb/blob/dad394ea3f50f518a40e5a8a457dfb6811ba245a/Cargo.toml#L72-L73
https://github.com/nervosnetwork/ckb/blob/dad394ea3f50f518a40e5a8a457dfb6811ba245a/src/main.rs#L4-L6
- But the code written by C will use system allocator, since [the `jemalloc` will compiled with `--with-jemalloc-prefix=_rjem_`](https://github.com/gnzlbg/jemallocator/blob/c27a859e98e3cb790dc269773d9da71a1e918458/jemalloc-sys/README.md#cargo-features), 
>* `unprefixed_malloc_on_supported_platforms`: when disabled, configure
>  `jemalloc` with `--with-jemalloc-prefix=_rjem_`. Enabling this causes …
=> feat: use same allocator for all

.gitignore, Makefile, test/run.sh, test/src/main.rs
Collecting the failed specs so we can known which specs fail most and should be disabled until fixed.
#2bm04k[closed]
=> chore: send failed integration test to sentry

sync/src/relayer/compact_block_process.rs, sync/src/relayer/tests/compact_block_process.rs, sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/mod.rs
Fix the stuttering problem of multi-node download on ibd concurrent download and no-ibd concurrent download.
If the `last common` tag is incorrect, it will cause the `index_height` and `tip` to be too far apart, which will cause `get_ancestor` and `contains_block_status` to be penetrated to RocksDB. When the gap exceeds 500k, it means that each time you look for the `can fetch` block, it will take up to Millions of cache breakdowns, this problem will increase rapidly with the number of synchronizable nodes and chain height, which will lead to pauses.
https://github.com/nervosnetwork/ckb/blob/e76cbe076586d362ce7f676635caf1e84f1cc9d4/sync/src/synchronizer/block_fetcher.rs#L40-L52
https://github.com/nervosnetwork/ckb/blob/e76cbe076586d362ce7f676635caf1e84f1cc9d4/sync/src/synchronizer/block_fe …
=> fix: fix bug on last common marked

sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/get_headers_process.rs, sync/src/synchronizer/mod.rs, sync/src/types.rs
As the chain height rises gradually, the synchronization duration increases linearly. This PR is the beginning of improving the synchronization time.
ckb synchronization is roughly divided into two blocks:
- ibd(init block download), when tip block timestamp < now - 24h
- Normal synchronization, when tip block timestamp > now - 24h
In the ibd process, currently only request a header map from a random node, and then initiate a download block request to the node based on the node's best-known header and the last common block calculated by the current tip.
In principle, block download does not limit the number of nodes requested, but because the ibd process only interacts with a node's header map during the ibd process, currently ibd can only download blocks from one node.
This pr uses the …
=> feat: concurrent download blocks on ibd

sync/src/types.rs
After allowing ibd multi-node download, the premise of enabling multi-node download is to update the best-known header of the corresponding node as soon as possible.
However, as the chain height continues to increase, the exponentially descending abstraction header of the locator will cause the minimum height header in the locator to become higher and higher, that is, it will take longer and longer to enable ibd multi-node download.
So, slightly improve the step insertion method of the locator so that the minimum height within it is as low as possible
=> feat: enhanced locator

Cargo.lock, chain/Cargo.toml, chain/src/cell.rs, chain/src/chain.rs, rpc/src/module/chain.rs, shared/Cargo.toml, shared/src/lib.rs, shared/src/shared.rs, store/src/db.rs, store/src/store.rs, util/snapshot/Cargo.toml, util/snapshot/src/lib.rs
memory cellset is useless burden, https://github.com/nervosnetwork/ckb-bench/issues/9 shows it didn't have much effect, but will increasing amounts of memory infinity.
remove memory cellset
=> feat: remove memory cellset

sync/src/synchronizer/block_fetcher.rs, sync/src/types.rs
This PR introduces 2 optimizations related to `get_ancestor`
https://github.com/nervosnetwork/ckb/pull/1959/files#diff-86d69964b227ca1248fadb84da967a96
* [Original]  `BlockFetcher::fetch` would involve `get_ancestor` multiple times for continuous headers.
For example, assume `block-chain-tip = 100, header-chain-tip=999`, `get_ancestor` would be involved at least 16(`MAX_BLOCKS_IN_TRANSIT_PER_PEER = 16`) times:
- `get_ancestor(101)`
- `get_ancestor(102)`
- ...
- `get_ancestor(115)`
* [Now] While we can save 15 times of involving `get_ancestor` with the help of tracing parents:
- `get_ancestor(115)`
- get `headers[100...114]` by tracing parents
https://github.com/nervosnetwork/ckb/pull/1959/files#diff-9912cd1cc8b513bd52d8bfe461cadfd0
* [Original] `get_ancestor` locate the header of the …
=> perf: improve get_ancestor efficiency

sync/src/types.rs
When build skip list want a header not exists in header map, we should get it from main chain directly, otherwise it will search it by parent hash linearly.
=> perf: Fix build_skip performance bug

chain/src/chain.rs, sync/src/relayer/block_transactions_process.rs, sync/src/relayer/compact_block_process.rs, sync/src/relayer/get_block_proposal_process.rs, sync/src/relayer/get_block_transactions_process.rs, sync/src/relayer/get_transactions_process.rs, sync/src/relayer/mod.rs, sync/src/synchronizer/get_blocks_process.rs, sync/src/synchronizer/get_headers_process.rs, sync/src/synchronizer/mod.rs, sync/src/types.rs, util/logger/src/lib.rs
Add some metrics:
* chain:
- blocks chain tip number
- headers chain tip number
* sync/relay
- in/out messages
- blocks_in_flight state
* get_ancestor
- steps, elpased, base_number, target_number
=> feat: Log more sync and relay metrics

ckb-bin/src/lib.rs, ckb-bin/src/subcommand/miner.rs, miner/src/miner.rs, util/app-config/src/args.rs, util/app-config/src/cli.rs, util/app-config/src/lib.rs
```bash
ckb miner -C . --limit 10 # Exit after 10 nonces found
ckb miner -C . -l 5       # Exit after 5 nonces found
ckb miner -C .            # Run forever
ckb miner -C . --limit 0  # Run forever, too
```
Ref:
- [CKB-Cli Issue-256: Mining with CKB-Cli (for dev chain)](https://github.com/nervosnetwork/ckb-cli/issues/259)
=> feat: add an option to control how many blocks the miner has to mine

util/logger/src/lib.rs
Filter metrics via `log_enabled!` inside `metric!`.
Enable metrics collection via configuring log filter. Here are some examples:
* `filter=info,ckb-metrics=trace`: enable all metrics collection
* `filter=info,ckb-metrics=trace,ckb-metrics-sync=off`: enable all metrics collection except topic "sync"
* `filter=info,ckb-metrics-sync=trace`: only enable metrics collection of topic "sync"
=> feat: Add metrics filter

rpc/src/server.rs, rpc/src/test.rs
RPC servers currently don't wait for threads to cleanup, leading rpc-test to segfaults.
Should be reverted once upstream fix is released.
=> fix: wait for RPC server to cleanup on shutdown

sync/src/orphan_block_pool.rs, sync/src/types.rs
Currently, `last_common_header` may be incorrectly updated when inserting block from the orphan pool.
https://github.com/nervosnetwork/ckb/blob/0911bdce06aff45df4162dec10c577ff26a9fa63/sync/src/types.rs#L738-L753
Record block origin in the orphan pool.
=> fix: orphan_block_pool should record block origin

rpc/src/module/pool.rs, util/jsonrpc-types/src/lib.rs, util/jsonrpc-types/src/pool.rs
- `OutputsValidator` is in `ckb_rpc::module::pool`.
- `OutputsValidator` is `public` but `ckb_rpc::module::pool` is private.
- `OutputsValidator` is not re-exported.
- So, no one can use `OutputsValidator`.
- Move `OutputsValidator` to `ckb-jsonrpc-types`
- Export `OutputsValidator`
=> chore: export OutputsValidator

sync/src/lib.rs, sync/src/synchronizer/block_fetcher.rs
The "sync" protocol downloads different blocks from multiple peers. In the case of different download speeds between peers, that will cause some disordering blocks backlog in `orphan_pool`.
To avoid the explosion of disordering blocks, we limit the download speed based on `BLOCK_DOWNLOAD_WINDOW`:
```
// Size of the "block download window": how far ahead of our current height do we fetch?
// Larger windows tolerate larger download speed differences between peers, but increase the
// potential degree of disordering of blocks.
pub const BLOCK_DOWNLOAD_WINDOW: u64 = 1024 * 8; // 1024 * default_outbound_peers
```
----
`BLOCK_DOWNLOAD_WINDOW` should be good enough to limit the disordering blocks but meanwhile, tolerate download speed differences between peers. I am not sure whether `1024 * 8` …
=> feat: avoid explosion of disordering blocks based on BLOCK_DOWNLOAD_WINDOW

Cargo.lock
Fix：
- bug in work-stealing queue
feature:
- automatic cooperative task yielding
=> chore: upgrade tokio

Cargo.lock, ckb-bin/src/subcommand/run.rs, rpc/Cargo.toml, rpc/src/server.rs, rpc/src/test.rs
> Release notes
> * Wait for http server to close on Drop. 
> * Add "Accept:application/json" header for all requests. 
> * Client call with named params 
Additional commits viewable in <a href="https://github.com/paritytech/jsonrpc/compare/jsonrpc-http-server-v14.0.5...v14.1.0">compare view</a>
As described in https://github.com/nervosnetwork/ckb/pull/1996, it can be revert.
=> chore: bump jsonrpc from 14.0.5 to 14.1.0

Cargo.lock, ckb-bin/Cargo.toml, ckb-bin/src/subcommand/prof.rs, util/app-config/src/args.rs, util/app-config/src/cli.rs, util/app-config/src/lib.rs
Previously, the prof command can not configure the execution path. it hard coding in system temporary folder. 
But the system temporary folder usually has some limit, such as Linux putting a limit on `/tmp` size if it is mounted as `tmpfs` is to prevent a DOS attack. although the settings can be changed, I'm afraid it's not worth to do so. 
So, this PR proposal appends a new arg to prof command to support specify execution path.
=> feat: prof command support specify execution path

Cargo.lock, ckb-bin/src/subcommand/run.rs, util/types/Cargo.toml, util/types/src/core/cell.rs
The goal of this PR is to optimize transaction resolve.
Currently, transaction resolve is inefficient, cause system-cell is uncached, every transaction depends on system cell will read system-cell from disk repeatedly. this PR proposal a system-cell cache implementation.
=> perf: cache system cell for resolve deps

util/jsonrpc-types/src/cell.rs, util/types/src/core/cell.rs
After we switched the serialization format to molecule, the memory [layout](https://github.com/nervosnetwork/ckb/blob/07edc0b826765bace64509c8908752690652add5/util/types/src/core/cell.rs#L25) of `CellMeta` is simplified into a combination of several bytes struct and primitives type, we are able to allocate it on stack directly and therefore I proposed this PR.
And relative enum variant size passed the clippy check: https://rust-lang.github.io/rust-clippy/master/#large_enum_variant
=> chore: change `Box<CellMeta>` to `CellMeta`

Cargo.lock, network/src/protocols/mod.rs, sync/Cargo.toml, sync/src/lib.rs, sync/src/relayer/block_transactions_process.rs, sync/src/relayer/compact_block_process.rs, sync/src/relayer/tests/compact_block_process.rs, sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/get_blocks_process.rs, sync/src/synchronizer/mod.rs, sync/src/tests/inflight_blocks.rs, sync/src/types.rs, test/src/specs/relay/compact_block.rs, test/src/specs/sync/block_sync.rs, test/src/specs/sync/get_blocks.rs
This implementation aims to optimize the task scheduling of the download block. 
It contains a simple task counter to allocate the number of tasks for each node, record and filter the relatively good nodes for download.
After about a week of testing and continuous adjustments, the current PR data is relatively satisfactory, but the possibility of continued adjustments in the future is not ruled out
This PR changes a number of things, including but not limited：
1. Raise the maximum inflight block limit per node to 32-128, but the default is 16, and dynamically adjust this data
2. Remove redundant designs where the same block can be requested from two nodes
3. ~When inserting a orphan block, the countdown for 1 second at the tip + 1 corresponding to `trace_number`, if still not completed, …
=> feat: Optimize block download tasks with a simple task scheduler

Cargo.toml, ckb-bin/Cargo.toml, util/memory-tracker/Cargo.toml, util/memory-tracker/src/jemalloc-mock.rs, util/memory-tracker/src/jemalloc.rs, util/memory-tracker/src/lib.rs, util/memory-tracker/src/process-mock.rs
Here is a potential issue which was introduced by #1940.
- Since our `rust-toolchain` is still be `1.41.0`, there will be no errors or warnings when we build the project. (This is why #1940 was merged)
https://github.com/nervosnetwork/ckb/blob/22829ae85db1643480bd810150f9619250aac92e/rust-toolchain#L1
- But if you update the `rust-toolchain` to `1.42.0`, when you build the whole project (just execute `make prod`), you will get two warnings:
> warning: ckb/Cargo.toml: Found `feature = ...` in `target.'cfg(...)'.dependencies`. This key is not supported for selecting dependencies and will not work as expected. Use the [features] section instead: https://doc.rust-lang.org/cargo/reference/features.html
> warning: ckb/Cargo.toml: Found `feature = ...` in `target.'cfg(...)'.dependencies`. This …
=> fix: remove unsupport configurations in Cargo.toml

network/src/network.rs
After bump `tokio` from `0.1` to `0.2`, [`name_prefix(..)`] was removed, and it was replace by [`thread_name(..)`].
[`name_prefix(..)`]: https://docs.rs/tokio/0.1.22/tokio/runtime/struct.Builder.html#method.name_prefix
[`thread_name(..)`]: https://docs.rs/tokio/0.2.20/tokio/runtime/struct.Builder.html#method.thread_name
=> fix: fix a typo of a thread name

Cargo.lock, ckb-bin/src/subcommand/run.rs, network/Cargo.toml, network/src/lib.rs, network/src/network.rs, network/src/protocols/discovery/protocol.rs, network/src/protocols/mod.rs, sync/src/relayer/mod.rs, test/src/net.rs
1. Upgrade p2p, use new `BlockingFlag` to optimize performance
2. Upgrade tokio, allow recursive call `block_in_place`
p2p release note:
```
Bug Fix
Fix session proto open/close by user part(#220)
Features
Replace unsplit with assignment(#225)
Upgrade tokio util(#224)
Avoids unnecessary session id checking(#223)
Check all underscore(#228)
Use flag to control how to use block_in_place(#226)
More test(#227/#220)
```
tokio release note:
```
Fix
rt: support block_in_place in more contexts
stream: no panic in merge() and chain() when using size_hint()
task: include visibility modifier when defining a task-local
sync: broadcast closing the channel no longer requires capacity 
Added
rt: runtime::Handle::block_on
```
=> chore: upgrade p2p/tokio

test/src/utils.rs
Currently, it's too hard to distinguish between integration test logs and other temporary logs, especially when make integration test to be automated.
=> test: save integration test logs in a specified directory

ckb-bin/src/subcommand/run.rs, network/src/protocols/mod.rs, test/src/net.rs
this PR removed the unnecessary closure and trait bounds from the `handler` field of `CKBProtocol`
=> chore: remove unnecessary closure from CKBProtocol

.travis.yml, ckb-bin/src/subcommand/prof.rs, db/src/db.rs, indexer/src/store.rs, network/src/behaviour.rs, network/src/config.rs, network/src/protocols/discovery/substream.rs, network/src/protocols/ping.rs, network/src/services/protocol_type_checker.rs, rpc/src/server.rs, rpc/src/test.rs, sync/src/synchronizer/mod.rs, sync/src/types.rs, test/src/main.rs, test/src/specs/mod.rs, tx-pool/src/service.rs, util/instrument/src/export.rs, util/instrument/src/import.rs, util/jsonrpc-types/src/bytes.rs, util/types/src/core/advanced_builders.rs, util/types/src/core/views.rs, verification/src/tests/uncle_verifier.rs
Within CI, using the latest `fmt` and `clippy`, but allow it fail
=> chore: fix clippy warn

devtools/azure/windows-dependencies.yml, test/src/net.rs, test/src/worker.rs
- Fix `AddrInUse: Only one usage of each socket address (protocol/network address/port) is normally permitted.` when running integration tests in windows.
CI Result Preview: [CKB GitHub Action](https://github.com/nervosnetwork/ckb/runs/650909401)
- In fact, `scoop install msys2` doesn't install `msys2`, it just installs a `msys2-installer`, so we can just remove this task from Azure Windows CI.
CI Result Preview: [CKB GitHub Action](https://github.com/nervosnetwork/ckb/runs/651041405)
=> test: use unique ports for each node in integration tests

network/src/network.rs, network/src/peer_store/peer_store_db.rs, network/src/tests/peer_store_db.rs
`PeerStore#load_from_dir` should return an empty peer store instead of panic when failed to load data from file system.
=> fix: should use an empty peer store when failed to load data from file

network/src/network.rs, network/src/peer_store/peer_store_db.rs, network/src/tests/peer_store_db.rs
=> [backport] #2063 fix: should use an empty peer store when failed to load data from file

Cargo.lock, db/Cargo.toml
bump ckb-rocksdb from 0.12.3 to 0.13.0
https://github.com/nervosnetwork/rust-rocksdb/pull/8 fix compilation issue on vs2019-win2019
=> chore(deps): bump ckb-rocksdb from 0.12.3 to 0.13.0

docs/hashes.toml, resource/specs/testnet.toml
The new genesis hash is
0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606
Chain info updated: https://github.com/nervosnetwork/ckb/wiki/Chains
=> feat: reset testnet aggron to v4

docs/hashes.toml, resource/specs/testnet.toml
The new genesis hash is
0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606
Chain info updated: https://github.com/nervosnetwork/ckb/wiki/Chains
=> [backport/v0.32] feat: reset testnet aggron to v4

util/app-config/src/lib.rs
Previously, the fields in Setup in app-config package remains private,
meaning the only way we can initialize a Setup struct, is via the
exposed from_matches method. But since from_matches only accepts
matches initialized from clap, this means the only way we can
initialize CKB, would be from a binary via argv. This commit changes
the code so fields from Setup struct are exposed, which can enable us
to use much of CKB code as a library, not necessarily a binary.
=> feat: Expose fields from setup struct

Makefile
The `net2` crate has been deprecated and users are encouraged to considered `socket2` instead.
But there are but a lot of required crates are dependent on it.
=> chore: skip audit for a deprecated crate: net2

network/src/network.rs, rpc/README.md, rpc/json/rpc.json, rpc/src/module/net.rs
The RPC `get_peers` miss the peer connected address. Hence it may be empty addresses returned for inbound peers. e.g.
```json
{
"addresses" : [],
"version" : "0.29.0 (a6733e6 2020-02-26)",
"node_id" : "QmPoPDhGPbNfAuDM1kmQFyY8cocC2SXipi6gYV6BmAj2w7",
"is_outbound" : false
}
```
This PR:
* Includes connected address in the returning addresses
* Uses the score recorded in `peer_store` as the returning peer score
=> fix: return connected address in RPC `get_peers`

sync/src/orphan_block_pool.rs
resolved potential deadlock in `OrphanBlockPool`  and a unit test which simulates deadlocking was added also.
=> fix: orphan block pool deadlock

sync/src/relayer/mod.rs, sync/src/synchronizer/block_fetcher.rs, sync/src/types.rs, test/src/main.rs, test/src/specs/sync/block_sync.rs
relayer and sync have some known problems in the critical zone of switching, which are inherent to the request/response architecture.
Previous attempts to fix the problem by allowing duplicate downloads, but this solution results in wasted network resources and slowed sync speed.
This typical problem can be solved by the node itself, and the current PR gives a temporary solution to try to check the orphan pool with a very low-frequency timer.
=> fix: Fix collaboration issues between two protocol

test/src/specs/sync/block_sync.rs
Need to fully confirm the `getblocks` request to continue the test
=> test: Need to fully confirm the getblocks request to continue the test

network/src/network.rs
this PR resolved an unexpected shutdown issue when we got a `ProtoHandleBlock` error in p2p layer
=> fix: resolve ProtocolHandleError scope issue

network/src/network.rs
This PR fixes a possible deadlock bug caused by conflicting lock order in network/src/network.rs.
|add_observed_addrs|try_dial_observed_addrs|
|---|---|
|public_addrs.write()||
||[pending_observed_addrs.write()](pending_observed_addrs.write())|[(https://github.com/nervosnetwork/ckb/blob/7f241840b7bfd724c447bf3c0ffa051f2e211d82/network/src/network.rs#L478)|
||[dial_inner](https://github.com/nervosnetwork/ckb/blob/7f241840b7bfd724c447bf3c0ffa051f2e211d82/network/src/network.rs#L481)|
||[can_dial](https://github.com/nervosnetwork/ckb/blob/7f241840b7bfd724c447bf3c0ffa051f2e211d82/network/src/network.rs#L430)|
||[public_addrs.read()//deadlock!](https://github.com/nervosnetwork/ckb/blob/7f241840b7bfd724c447bf3c0ffa051f2e211d82/network/src/network.rs#L362)| …
=> network: fix deadlock caused by conflicting lock order

db/src/db.rs, shared/src/shared.rs, store/src/db.rs
`Shared::store` doesn't need `Arc`, since `ChainDB` only contains `Arc`.
https://github.com/nervosnetwork/ckb/blob/12d8812c80cf6712dcdbae138c85b114788dded2/shared/src/shared.rs#L23-L24
https://github.com/nervosnetwork/ckb/blob/12d8812c80cf6712dcdbae138c85b114788dded2/store/src/db.rs#L18-L21
https://github.com/nervosnetwork/ckb/blob/12d8812c80cf6712dcdbae138c85b114788dded2/db/src/db.rs#L16-L18
=> chore: remove useless `Arc`

Cargo.lock, rpc/Cargo.toml, rpc/json/rpc.json, rpc/src/test.rs, tx-pool/src/service.rs
to speedup unit test, this PR skip rpc `fee_estimate` in unit test and cleanup some unnecessary helper methods, corresponding rpc has been covered in integration test
=> chore: skip fee estimate rpc test

Cargo.lock, ckb-bin/src/subcommand/miner.rs, ckb-bin/src/subcommand/run.rs, db/src/db.rs, db/src/lib.rs, docs/ckb-debugging.md, store/src/db.rs, util/memory-tracker/Cargo.toml, util/memory-tracker/src/lib.rs, util/memory-tracker/src/process.rs, util/memory-tracker/src/rocksdb.rs, util/memory-tracker/src/utils.rs
[Set `memory_tracker.interval` to be a non-zero number in the configuration file](https://github.com/nervosnetwork/ckb/blob/22829ae/docs/ckb-debugging.md#tracking-memory-usage-in-logs) and restart CKB, then we can monitor RocksDB memory usages in logs, without re-compile the binary.
Ref: [RocksDB: Memory usage in RocksDB](https://github.com/facebook/rocksdb/wiki/Memory-usage-in-RocksDB)
=> feat: monitor rocksdb memory usages in logs (optional; default: disable)

network/src/network.rs, network/src/protocols/mod.rs, sync/src/relayer/mod.rs, sync/src/synchronizer/mod.rs
Peer protocols are updated via: https://github.com/nervosnetwork/ckb/blob/b8a4743c4ae9368f5d56880c74d7edb7580d0d45/network/src/network.rs#L765 and https://github.com/nervosnetwork/ckb/blob/b8a4743c4ae9368f5d56880c74d7edb7580d0d45/network/src/network.rs#L792
it's unnecessary to update it again in each protocol handler
=========update=========
Changed the sync/relay protocol hander mode to `ProtocolHandle::Callback` according to review comment
=> chore: remove duplicate code of peer protocols insert/remove

ckb-bin/src/subcommand/init.rs, resource/src/lib.rs, resource/src/template.rs, rpc/src/test.rs, util/app-config/src/app_config.rs
This PR changed `TemplateContext` key/value from fixed field to hashmap, it made the `ckb-resource` crate easier to use in 3rd party applications
=> refactor: use generic key / value in template context

rpc/README.md, rpc/json/rpc.json, rpc/src/module/net.rs, test/src/rpc.rs, util/jsonrpc-types/src/lib.rs, util/jsonrpc-types/src/net.rs
We are planing to add more fields to network related rpc `local_node_info` and `get_peers`, for example, add uptime to `local_node_info`, add best_known_header to `get_peers`, this PR split json rpc type `Node` to `LocalNode` and `RemoteNode`, make it easier to add different fields to these rpc in the future.
This PR is compatible with previous version, only one field `is_outbound` is removed from `local_node_info`, which is always null in old rpc.
=> chore: split json rpc type `Node` to `LocalNode` and `RemoteNode`

sync/src/lib.rs, sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/mod.rs, sync/src/tests/inflight_blocks.rs, sync/src/types.rs
Problems with the current scheduler:
1. The calculation is too frequent
2. Inability to adapt to complex network environments, e.g., increased network latency as the number of nodes increases, network latency exceeding expectations, etc.
This PR implements an adaptive scheduler based on past data, removing most of the redundant calculations. Translating the overall data into 4 intervals:
| fast | normal | penalty | double penalty |
The dividing line is the 1/3 position, 4/5 position, 1/10 position.
There is a 14/30 normal area, 1/10 penalty area, 1/10 double penalty area, 1/3 accelerated reward area.
Replace the 30-second clear-out strategy with a doubling penalty.
10%-20% increase in sync performance from testing, from 220-240 block/s to 250-270 block/s on a dual-core machine
the …
=> Optimize scheduler

rpc/src/module/debug.rs, util/memory-tracker/src/jemalloc.rs, util/memory-tracker/src/lib.rs
RPC `jemalloc_profiling_dump` will generate the target heap file with a timestamp to the working directory. Returning the target filename will be convenient for the command-sender to know which heap file is the current one.
Examples of the proposed responses of RPC `jemalloc_profiling_dump`:
* Success : `{"jsonrpc":"2.0","result":"ckb-jeprof.1587964630.heap","id":2}`
* ~~Fail: `{"jsonrpc":"2.0","error":{"code":-32603,"message":"jemalloc profiling dump: unsupported"},"id":2}`~~ // It never return errors at the current implementation.
=> feat: return filename of jemalloc_profiling_dump

chain/src/chain.rs, rpc/src/module/test.rs, store/src/transaction.rs, test/src/main.rs, test/src/rpc.rs, test/src/specs/mod.rs, test/src/specs/rpc/mod.rs, test/src/specs/rpc/truncate.rs, tx-pool/src/process.rs, tx-pool/src/service.rs
For convenient to reproduce a specified environment when test, this PR adds RPC `truncate(target_tip_hash)` to roll-back the blockchain downto the target block. It trigger the below behaviours:
* Roll-back the blockchain status, like cellset and transactions, downto the height corresponding to `target_tip_hash`. In short, reset the tip to the target block.
* Delete the truncated blocks from database.
* Clear the tx-pool, which may hold dirty transactions/proposals.
=> feat: add RPC truncate

Cargo.lock, ckb-bin/src/helper.rs, ckb-bin/src/subcommand/run.rs, network/Cargo.toml, network/src/lib.rs, network/src/network.rs, network/src/protocols/test.rs, rpc/src/module/net.rs, rpc/src/test.rs, test/src/net.rs
This PR changed `NetworkService`'s exit_condvar to generic type and removed node_version from `start` fn, make it easier to use `ckb-network` crate as a lib
=> refactor: use generic type in NetworkService 

sync/src/orphan_block_pool.rs, sync/src/relayer/compact_block_process.rs, sync/src/relayer/mod.rs, sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/block_process.rs, sync/src/synchronizer/headers_process.rs, sync/src/synchronizer/mod.rs, sync/src/tests/sync_shared.rs, sync/src/types.rs
* `peer.best_known_block` refers to the best-known block we know this peer has announced; `peer.last_common_header` refers to the last block we both stored between local and peer. This PR proposes the logic to update the two fields:
- When we receive `CompactBlock` or `SentHeader` from `peer`, we update the `peer.best_known_block` if the arrival one has greater `total_difficulty`.
- When we insert a block which is from `peer`, we don't update the corresponding `last_common_header`(remove lines [CompactBlock](https://github.com/nervosnetwork/ckb/pull/2081/files#diff-98eccb89a5611099d6adca819c9c8b08L100), [SendBlock](https://github.com/nervosnetwork/ckb/pull/2081/files#diff-402ee94ba649e0f53da25c4da84ec58dL50-L56)).
- We update the `last_common_header` only in `find_blocks_to_fetch`. There …
=> feat: update last_common_header only in find_blocks_to_fetch

ckb-bin/src/subcommand/run.rs, network/src/lib.rs, network/src/network.rs, network/src/protocols/identify/mod.rs, network/src/protocols/mod.rs, network/src/protocols/support_protocols.rs, network/src/protocols/test.rs, network/src/services/protocol_type_checker.rs, rpc/src/module/alert.rs, rpc/src/module/miner.rs, rpc/src/module/test.rs, sync/src/lib.rs, sync/src/relayer/tests/compact_block_process.rs, sync/src/synchronizer/get_headers_process.rs, sync/src/synchronizer/mod.rs, sync/src/tests/synchronizer.rs, sync/src/types.rs, test/src/specs/mod.rs, test/src/specs/p2p/malformed_message.rs, test/src/specs/relay/compact_block.rs, test/src/specs/relay/get_block_transactions_process.rs, test/src/specs/relay/transaction_relay.rs, test/src/specs/sync/block_sync.rs, test/src/specs/sync/get_blocks.rs, test/src/specs/sync/invalid_block.rs, test/src/specs/sync/invalid_locator_size.rs
To eliminate dependence of `ckb-sync` crate,  this PR refactored network protocol related variables and move them to a new enum: `SupportProtocols`
=> refactor: move network protocol related variables to SupportProtocols

network/src/protocols/mod.rs
This PR added a debug level log to `disconnect` fn , make it easier to count or analysis disconnect  reason, e.g. count the disconnection frequency of sync scheduler:
```
ag "disconnect peer.*sync disconnect" data/logs
5535516:2020-06-22 16:42:00.570 +09:00 NetworkRuntime DEBUG ckb_network::protocols  disconnect peer: SessionId(6), message: sync disconnect
5547983:2020-06-22 16:42:19.008 +09:00 NetworkRuntime DEBUG ckb_network::protocols  disconnect peer: SessionId(7), message: sync disconnect
5557093:2020-06-22 16:42:32.435 +09:00 NetworkRuntime DEBUG ckb_network::protocols  disconnect peer: SessionId(8), message: sync disconnect
5557094:2020-06-22 16:42:32.435 +09:00 NetworkRuntime DEBUG ckb_network::protocols  disconnect peer: SessionId(5), message: sync disconnect
5564416:2020-06-22 …
```
=> chore: add debug log to disconnect fn

test/src/node.rs
Integration tests are randomly failed at spec [pack_uncles_into_epoch_starting](https://github.com/nervosnetwork/ckb/blob/199c643b16f78f0915e8a0ca51f553a4e0401d1b/test/src/specs/mining/uncle.rs#L133-L169):
> ERROR ckb_rpc::module::miner  [] submit_block error: Error { kind: HeaderError { kind: BlockTimeTooOld { min: N, actual: N }
- You need a **high-performance** machine.
- Build ckb  in release mode.
```bash
cargo build --release --features deadlock_detection
```
- Build ckb-test in release mode.
```bash
cd test; cargo build --release
```
- Run tests:
```bash
while true; do sleep 1; target/release/ckb-test --bin ../target/release/ckb --port 9000 pack_uncles_into_epoch_starting && rm -rf /tmp/ckb-it-* || break; done
```
- Leave your machine alone and go to drink a cup of tea or coffee.
- …
=> test: construct valid uncle blocks no matter how well the host is

rpc/README.md, rpc/json/rpc.json, rpc/src/module/pool.rs, rpc/src/test.rs
The adding RPC `cleat_tx_pool` removes all the memoried transactions from tx-pool.
=> feat: add RPC `clear_tx_pool`

sync/src/orphan_block_pool.rs, sync/src/types.rs, util/src/lib.rs, util/src/shrink_to_fit.rs
Cause rust hash table capacity does not shrink automatically, we need explicit call `shrink` for predictable limit memory usage.
=> fix: shrink state map

shared/src/lib.rs, shared/src/migrations.rs, shared/src/shared.rs, store/src/lib.rs, util/types/schemas/extensions.mol, util/types/src/generated/extensions.rs
storage structs `HeaderView`, `EpochExt` and `TransactionInfo` are fixed size, we should use molecule `struct` instead of `table`, it reduces storage size and improves the performance a little bit.
run a simple test with `ckb replay --profile 1 20000 --tmp-target /tmp` on my local pc:
```
before: avg 37.2 sec
after: avg 36.1 sec
```
f.y.i, this migration took 15 ~ 20 sec to finish on my local pc with current tip number, I think it's acceptable.
=> pref: change storage molecule table to struct

db/src/db.rs, util/app-config/src/configs/db.rs
Append `[db.options]` to `ckb.toml` and don't add any options, then `ckb run -C .` will panic since:
- In `rust-rocksdb`:
https://github.com/nervosnetwork/ckb/blob/32042c81f1ec4fdaf7358b63dc2417d9363d9944/db/src/db.rs#L72-L74
- In [`rocksdb::db/c.cc::rocksdb_set_options(..)`](https://github.com/facebook/rocksdb/blob/a9a973869afd987a6b728b833b2896dbb38bc02f/db/c.cc#L2216-L2217)
```c++
SaveError(errptr,
db->rep->SetOptions(options_map));
```
- In [`rocksdb::db/db_impl/db_impl.cc::SetOptions(..)`](
https://github.com/facebook/rocksdb/blob/a9a973869afd987a6b728b833b2896dbb38bc02f/db/db_impl/db_impl.cc#L951-L956)
```c++
if (options_map.empty()) {
ROCKS_LOG_WARN(immutable_db_options_.info_log,
"SetOptions() on column family [%s], empty input",
cfd->GetName().c_str());
return …
```
=> fix: panic if db options is empty

script/data-loader/src/lib.rs, script/src/syscalls/load_header.rs, script/src/syscalls/mod.rs, store/src/data_loader_wrapper.rs
`get_block_ext` fn is unused and epoch related information should be loaded via header's epoch field, cleanup code and tweak unit test.
=> chore: remove unused fn from `DataLoader` trait

Cargo.lock, error/src/internal.rs, error/src/lib.rs, rpc/Cargo.toml, rpc/src/error.rs, rpc/src/module/alert.rs, rpc/src/module/chain.rs, rpc/src/module/experiment.rs, rpc/src/module/miner.rs, rpc/src/module/net.rs, rpc/src/module/pool.rs, rpc/src/module/test.rs, rpc/src/service_builder.rs, test/src/specs/tx_pool/valid_since.rs, tx-pool/src/error.rs, tx-pool/src/process.rs, util/jsonrpc-types/src/pool.rs
This PR reworks on the RPC errors:
* Use JSONRPC error code to differentiate different errors. Also prefix the error code in the message to be search engine friendly.
* Make error message simple and easy to understand. The dump of the error is added as the data instead.
* Avoid reusing the same error message for different reasons.
* The error object `date` field is always absent before, now it can be a string which contains the detailed error information.
* The `code` in error object is always -3 for all the CKB internal errors, now it can have different values to differentiate different errors. Check the file `rpc/src/error.rs`.
* The error messages have been updated to improve readability.
See [JSON-RPC spec](https://www.jsonrpc.org/specification#error_object).
┌ `CKBInternalError (-1)` …
=> feat(rpc): Re-organize RPC errors

util/occupied-capacity/core/src/units.rs, verification/src/error.rs, verification/src/tests/transaction_verifier.rs, verification/src/transaction_verifier.rs
This PR adds extra information in transaction verification errors, such as:
* Which `input`, `cell_dep`, `header_dep` or `output` causes the error
* If there's a limit, what's the value of the limit.
There're also ambiguous error messages. For example, the pool has its own cycles limit on a single transaction, which is configurable in the config file. The block also as a limit on all the transactions in the block. Apparently, for a single transaction, the cycles should not exceed the block limit. This PR also avoids using the same error for different reasons.
=> feat(rpc): Improve error messages from send transaction RPC

sync/src/relayer/compact_block_process.rs, sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/headers_process.rs, sync/src/types.rs
I added some log outputs when do tests, I got the follow results:
- Sync chain from height `0` to `tip`:
- If always query the header map first.
- Query the header map first but not found: about `tip/2 ~ tip` times (mark as `x`)
- If not found in the header map, it must be in the store.
- If query header from store first when the block in that height was already inserted into the chain database.
- Query the header map first but not found: about `tip/4 ~ tip/6` times (mark as `y`)
- Query the store first but not found: `0`
- The result of my last test: `tip = 2_230_953; x = 1_179_787; y = 552_325`
=> improvement: reduce times of querying header map

sync/src/lib.rs, sync/src/synchronizer/headers_process.rs, sync/src/synchronizer/mod.rs, sync/src/types.rs
To avoid possible performance issues on headers synchronization.
---
- [The first commit introduced the `headers_sync_timeout` treat `headers_sync_timeout` as a **total** timeout for all headers.](https://github.com/nervosnetwork/ckb/commit/b7db483cb519c37d15dfbd868d4621091c61d6a2#diff-af95c26bdbe8ee3013958651bd249995R143-R148)
- [But, the commit add a upper bound to `estimated_headers_count`, try to treat the timeout as a **partial** timeout, but didn't finish it.](https://github.com/nervosnetwork/ckb/commit/f14c8dc0fb5bd77e5935e818d2340f38c3802ab6#diff-67a34c19141a7c62f189385b4c2bacf7R181-R185)
The timeout has upper bound, but the headers need to sync doesn't have a upper bound, it could be a fatal error in someday.
- Current timeout is `base_timeout + estimated_headers_count * …
=> refactor: use a new method to detect headers sync timeout

Cargo.lock, ckb-bin/src/subcommand/run.rs, sync/Cargo.toml, sync/src/relayer/compact_block_process.rs, sync/src/synchronizer/headers_process.rs, sync/src/synchronizer/mod.rs, sync/src/types/header_map/backend.rs, sync/src/types/header_map/backend_rocksdb.rs, sync/src/types/header_map/kernel_lru.rs, sync/src/types/header_map/memory.rs, sync/src/types/header_map/mod.rs, sync/src/types/mod.rs, util/app-config/src/app_config.rs
- Open a temporary rocksdb (default is `${ckb_data_dir}/tmp/ckb-tmp-*`) to store a part data of header map which exceeded the configured quota.
- Why not use the same rocksdb as block data?
- It is just temporary data, all data was destroyed when ckb shutdown, so the format of data can be changed in any commits, we don't have to do migrations on it.
- I don't want to create columns, it requires migrations. Also too many columns will affect performance. 
- If I use current existed columns, then traverse all data will be difficult.
At present, no data in chain database have key-prefix.
For example, if we use key `header-${header_hash}` to save headers, key `uncle-${uncle_hash}` to save uncles,  key `block-${block_hash}` to save blocks, then we can save them in a same column and we can …
=> improvement: don't cache all data of header map in memory during IBD

sync/src/lib.rs, tx-pool/src/lib.rs, tx-pool/src/pool.rs, tx-pool/src/process.rs, verification/src/lib.rs
- Since `tx-pool` is split from `ckb-shared` after #1567, we can remove all user-specified targets for `tx-pool`.
https://github.com/nervosnetwork/ckb/blob/dfc944a1ce7be98285cd34a45772e671f1434a6c/shared/src/lib.rs#L20
- After [CKB PR 2078: chore: use fully qualified module name as the default log target](https://github.com/nervosnetwork/ckb/pull/2078), almost all logs use `$crate::env!("CARGO_PKG_NAME").replace("-", "_")` as first part of log targets.
=> chore: unify logger targets

rpc/src/module/debug.rs, util/app-config/src/app_config.rs, util/jsonrpc-types/src/debug.rs, util/jsonrpc-types/src/lib.rs, util/logger/src/lib.rs
- Support multiple file loggers in `ckb.toml`.
For example, the follow configuration will write all `info` logs into `run.log` and `stdout`, all `trace` logs into `trace.log` and `ckb_chain=info` logs into `chain_info.log`:
```toml
[logger]
filter = "info"
color = true
log_to_file = true
log_to_stdout = true
[logger.extra.trace]
filter = "trace"
[logger.extra.chain_info]
filter = "off,ckb_chain=info"
```
- Support configuring extra file loggers via RPC (in module `Debug`).
```shell
curl -H 'content-type: application/json' -d \
'{ "id": 2, "jsonrpc": "2.0", "method": "set_extra_logger", "params": ["chain_info", {"filter": "off,ckb_chain=info"}] }' \
http://localhost:8114
curl -H 'content-type: application/json' -d \
'{ "id": 2, "jsonrpc": "2.0", "method": "set_extra_logger", "params": …
```
=> feat: support multiple file loggers

rpc/src/module/debug.rs, util/app-config/src/app_config.rs, util/app-config/src/lib.rs, util/jsonrpc-types/src/debug.rs, util/jsonrpc-types/src/lib.rs, util/logger/src/lib.rs
- After #2175 , the name of rpc `set_logger_filter` is not proper (`the main logger` or `a extra logger`), change to `update_main_logger`  (in module `Debug`).
And let `update_main_logger` take full control of main logger filter, not only filter.
- `panic` when failed to open a log file doesn't output any error messages.
Use `eprintln!(..)` and `process::exit(..)` instead of `panic`.
- `panic` in logger service thread doesn't stop ckb process, but only stop logger service.
Just ignore the error logger, keep the logger service running.
```shell
curl -H 'content-type: application/json' -d \
'{ "id": 2, "jsonrpc": "2.0", "method": "update_main_logger", "params": [{"to_file": false}] }' \
http://localhost:8114 
curl -H 'content-type: application/json' -d \
'{ "id": 2, "jsonrpc": "2.0", …
```
=> feat: take full control of main logger filter via RPC

Cargo.lock, Cargo.toml, chain/Cargo.toml, chain/src/chain.rs, chain/src/tests/find_fork.rs, chain/src/tests/mod.rs, chain/src/tests/truncate.rs, chain/src/tests/util.rs, util/rust-unstable-port/Cargo.toml, util/rust-unstable-port/src/lib.rs, util/test-chain-utils/src/mock_store.rs
Previously, proposal-table update not considered in chain rollback, it's almost impossible to happen in hashrate-based chain. But can be triggered by `truncate` RPC.
Proposal fix: 
* check whether need reload proposal_table from block when the fork occurs.
* make sure fork blocks is sorted
=> fix: update proposal table after chain reorg

test/src/assertion/mod.rs, test/src/assertion/reward_assertion.rs, test/src/assertion/tx_assertion.rs, test/src/lib.rs, test/src/main.rs, test/src/node.rs, test/src/specs/mining/basic.rs, test/src/specs/mining/bootstrap.rs, test/src/specs/mining/fee.rs, test/src/specs/mining/proposal.rs, test/src/specs/mining/size_limit.rs, test/src/specs/mining/tx_select.rs, test/src/specs/mining/uncle.rs, test/src/util/mod.rs, test/src/util/tx.rs
Refactor about integration service mining relate cases:
1. Add comment for explain what does the case do;
2. Update some assertions and add relate info if assert failed;
Besides there also add a new folder `test/src/assertion` which contains some assert functions, a new folder `test/src/util` which contains some functions used in cases setup.
=> refactor: integration service - mining part

rpc/src/module/test.rs, test/src/node.rs, test/src/rpc.rs, tx-pool/src/process.rs, tx-pool/src/service.rs
allows user to generate block through rpc, it's a convenient feature for dApp integration test (like `truncate` rpc)
```shell
curl -d '{"id": 1, "jsonrpc": "2.0", "method":"generate_block","params": []}' \
-H 'content-type:application/json' 'http://localhost:8114'
curl -d '{"id": 1, "jsonrpc": "2.0", "method":"generate_block","params": [{"code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8", "args": "0xc8328aabcd9b9e8e64fbc566c4385c3bdeb219d7", "hash_type": "type"}]}' \
-H 'content-type:application/json' 'http://localhost:8114'
```
=> feat: add `generate_block` rpc to IntegrationTest module

rpc/README.md, rpc/json/rpc.json, rpc/src/module/pool.rs, rpc/src/module/test.rs, test/src/node.rs, test/src/specs/indexer/basic.rs, test/src/specs/rpc/truncate.rs, test/src/specs/tx_pool/limit.rs, test/src/specs/tx_pool/pool_resurrect.rs, test/src/specs/tx_pool/txs_relay_order.rs, tx-pool/src/pool.rs, tx-pool/src/process.rs, tx-pool/src/service.rs, util/jsonrpc-types/src/pool.rs
The state of the transaction pool is related to the chain tip. So attaching `tip_hash` and `tip_number` into `TxPoolInfo` which returns by RPC `tx_pool_info` makes it more rigorous.
=> feat: tx_pool_info include tip hash

network/src/network.rs, network/src/protocols/mod.rs, rpc/README.md, rpc/json/rpc.json, rpc/src/module/net.rs, util/jsonrpc-types/src/net.rs
allows user to pause and restart p2p network message processing through rpc
=> feat: add `set_network_active` rpc

ckb-bin/src/lib.rs
Issue: if the config was malformed and an error was thrown in `setup_app`, the process wouldn't exit.
=> fix: should exit with error code when setup failed

Cargo.lock, ckb-bin/Cargo.toml, ckb-bin/src/subcommand/run.rs, tx-pool/src/service.rs, util/logger-service/src/lib.rs, util/runtime/Cargo.toml, util/runtime/src/lib.rs
- Simplify dependencies of `ckb-async-runtime`.
- Use `::std::sync::Barrier` instead of `crossbeam-channel`.
- Let method `ckb-async-runtime::new_runtime` more general.
- Accept name prefix for threads.
- Accept `tokio::runtime::Builder` as an optional parameter, so we can set options for the runtime.
- After we upgrade `tokio` from 0.1 to 0.2, the thread name of `tokio` runtime threads has a redundant suffix "-".
- [`tokio-0.1.x::runtime::Builder::name_prefix(...)`](https://docs.rs/tokio/0.1.22/tokio/runtime/struct.Builder.html#method.name_prefix)
- [`tokio-0.2.x::runtime::Builder::thread_name(...)`](https://docs.rs/tokio/0.2.22/tokio/runtime/struct.Builder.html#method.thread_name)
- Use a default thread name in logs instead of an empty string.
Without color, a log record with empty …
=> chore: several minor changes about thread and runtime

network/src/network.rs, rpc/README.md, rpc/json/rpc.json, rpc/src/module/net.rs, test/src/specs/sync/block_sync.rs, util/jsonrpc-types/src/lib.rs, util/jsonrpc-types/src/net.rs
added `connected_duration`, `last_ping_duration`, `protocols` and `sync_state` to `get_peers` rpc
=> feat: add more fields to rpc `get_peers`

error/src/internal.rs, rpc/src/error.rs, rpc/src/module/pool.rs, test/src/specs/tx_pool/collision.rs, test/src/specs/tx_pool/limit.rs, tx-pool/src/component/container.rs, tx-pool/src/component/pending.rs, tx-pool/src/component/proposed.rs, tx-pool/src/error.rs, tx-pool/src/pool.rs, tx-pool/src/process.rs, tx-pool/src/service.rs, util/snapshot/src/lib.rs, verification/src/contextual_block_verifier.rs, verification/src/lib.rs, verification/src/transaction_verifier.rs
proposal changes:
* rename ContextualTransactionVerifier -> TimeRelativeTransactionVerifier
* split NonContextualTransactionVerifier from TransactionVerifier
* check syntactic correctness first before 
* refactory tx-pool rejection error
* re-broadcast when duplicated tx submit
=> small tx-pool refactoring 

script/src/error.rs, script/src/ill_transaction_checker.rs, script/src/lib.rs, script/src/type_id.rs, script/src/types.rs, script/src/verify.rs
* Add information to help locating which script produces the error, including the first input or output index, whether it is lock or type script.
* Add extra info:
* Add the upper limit in ExceededMaximumCycles
* Add a link to the system script exit codes table for ValidationFailure
=> refactor: Improve script error

rpc/src/module/net.rs
This PR fixes a deadlock bug caused by conflicting lock order in `block_fetcher.rs` and `net.rs`
`block_fetcher.rs`
SyncState#inflight_blocks write lock acquisition
https://github.com/nervosnetwork/ckb/blob/37dac610489e2a15636cb6d192f831b9af2fc8f5/sync/src/synchronizer/block_fetcher.rs#L98
SyncState#peers#state write lock acquisition
https://github.com/nervosnetwork/ckb/blob/37dac610489e2a15636cb6d192f831b9af2fc8f5/sync/src/synchronizer/block_fetcher.rs#L124
v.s
`net.rs`
SyncState#peers#state read lock acquisition
https://github.com/nervosnetwork/ckb/blob/719d937fbdddaeca8d9b70c96344b548e889eb7b/rpc/src/module/net.rs#L124
SyncState#inflight_blocks read lock acquisition
https://github.com/nervosnetwork/ckb/blob/719d937fbdddaeca8d9b70c96344b548e889eb7b/rpc/src/module/net.rs#L150
This …
=> fix: rpc get_peers deadlock caused by conflicting lock order

network/src/network.rs, network/src/protocols/test.rs, rpc/README.md, rpc/json/rpc.json, rpc/src/module/net.rs, util/jsonrpc-types/src/lib.rs, util/jsonrpc-types/src/net.rs
add `active`, `connections` and `protocols` fields to local_node_info (waiting for https://github.com/nervosnetwork/ckb/pull/2144)
=> feat: add more fields to `local_node_info` rpc

sync/src/types/mod.rs
Try to resolve integration test `block_sync_relayer_collaboration` that will occasionally go wrong, add a line of log where I suspect there may be a problem.
=> chore: add log to `try_search_orphan_pool`

Cargo.lock, pow/Cargo.toml, pow/src/eaglesong.rs, pow/src/eaglesong_blake2b.rs, verification/src/convert.rs, verification/src/error.rs, verification/src/header_verifier.rs, verification/src/lib.rs, verification/src/tests/header_verifier.rs
Include more info in the error messages:
* Add expected version and actual value in header version error.
Add logs to ease debugging PoW. It can be enabled by setting the log level:
```
[logger]
filter = "info,ckb-pow=debug"
```
=> refactor: Improve error when submitting block

test/src/net.rs, test/src/node.rs, test/src/utils.rs, test/src/worker.rs
Update integration test log from `ckb-it-xxx` to `ckb-it-case_name-node_index-xxx`.
Because of node_id initialize after the node start, and node start need a working_dir which contains the node log, so I use `node_index` in the test case instead of `node_id`.
=> chore: prefix integration test log with case name and node index

sync/src/synchronizer/block_fetcher.rs, sync/src/types/mod.rs, test/src/main.rs, test/src/specs/sync/last_common_header.rs, test/src/specs/sync/mod.rs
`last_common_header` is like a cursor of block-sync mechanism between the local node and remote peers. The local node only fetches blocks from peers who have a better chain. It means it is not necessary to timely advance the `last_common_header` of peers whose chain is worse than the local. 
However, https://github.com/nervosnetwork/ckb/pull/2196 adds `last_common_header` to RPC `get_peers`. It expects that the returned `last_common_header` to provide a more realistic picture. Hence I create this PR, timely advance the `last_common_header` of peers even their chains are worse than the local.
=> feat: advance last_common_header even the peer is worse than us

Cargo.lock, util/fixed-hash/Cargo.toml, util/fixed-hash/macros/Cargo.toml, util/fixed-hash/macros/src/lib.rs, util/fixed-hash/src/lib.rs, util/occupied-capacity/Cargo.toml, util/occupied-capacity/macros/Cargo.toml, util/occupied-capacity/macros/src/lib.rs, util/occupied-capacity/src/lib.rs
Since rust 1.45.0, [function-like procedural macros in expressions, patterns, and statements are stabilized](https://blog.rust-lang.org/2020/07/16/Rust-1.45.0.html#stabilizing-function-like-procedural-macros-in-expressions-patterns-and-statements), [`proc-macro-hack`](https://crates.io/crates/proc-macro-hack) is superseded by native support for `#[proc_macro]`.
=> chore: remove dependencies "proc-macro-hack" for crates in the workspace

Cargo.lock, Cargo.toml, ckb-bin/Cargo.toml, ckb-bin/src/lib.rs, ckb-bin/src/setup_guard.rs, util/Cargo.toml, util/app-config/Cargo.toml, util/app-config/src/app_config.rs, util/app-config/src/lib.rs, util/logger-config/Cargo.toml, util/logger-config/src/lib.rs, util/logger-service/Cargo.toml, util/logger-service/src/lib.rs, util/src/lib.rs, util/src/strings.rs
_Originally posted by @doitian in https://github.com/nervosnetwork/ckb/pull/2199#discussion_r465498134_
- Split logger config and service.
- Let `ckb-app-config` only be dependent on `ckb-logger-config`.
- Move the function which checks identifier into `ckb-util`.
=> refactor: split logger config and service

Cargo.lock, util/memory-tracker/Cargo.toml, util/memory-tracker/src/process.rs, util/memory-tracker/src/rocksdb.rs, util/memory-tracker/src/utils.rs
Use metrics to output memory statistics, so we can draw charts in Grafana via prometheus.
=> refactor: replace logs by metrics for memory tracker

bors.toml
`"Travis CI - Branch"` is equal to `"continuous-integration/travis-ci/push"`.
`"Travis CI - Pull Request"` is **NOT** equal to `"continuous-integration/travis-ci/pull"`.
I try to find which service changed it (GitHub, Travis or Bors), but no result.
I only can confirm that the name was changed.
=> ci: fix the bors via setting the right pr status

tx-pool/src/component/mod.rs, tx-pool/src/component/pending.rs, tx-pool/src/component/proposed.rs
CKB block has two dimensional limits on transactions, the total cycles and total bytes. Pool uses vbytes by uniforming these two dimension:
* Convert cycles and bytes to percentage of the block respectively.
* Pick the larger one
* Multiplying the larger percent with the block bytes limit gives the vbytes.
Thus the ratio between bytes and cycles is block cycles limit dividing the bytes limit.
I increase the precision to 7 digits so that
```
abs(MAX_BLOCK_BYTES - MAX_BLOCK_CYCLES * DEFAULT_BYTES_PER_CYCLES) < 1
```
=> chore: document DEFAULT_BYTES_PER_CYCLES and increase precision

devtools/doc/rpc.py, resource/ckb.toml, rpc/README.md, rpc/json/rpc.json, rpc/src/error.rs, rpc/src/module/chain.rs, rpc/src/module/indexer.rs, rpc/src/service_builder.rs, rpc/src/test.rs, util/app-config/src/configs/rpc.rs
resolve https://github.com/nervosnetwork/ckb/issues/2247, rpc method can be deprecated by adding `deprecated.` prefix to the rpc name:
```diff
+    #[rpc(name = "deprecated.get_cells_by_lock_hash")]
-    #[rpc(name = "get_cells_by_lock_hash")]
fn get_cells_by_lock_hash
```
=> feat: deprecated rpc method by adding `deprecated.` prefix to the rpc name

network/src/network.rs
For example, the 8~10 lines of the log file for our all integration tests at present are:
> Failed to open AddrManager db, file: "XXX/addr_manager.db", error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
> Failed to open BanList db, file: "XXX/ban_list.db", error: Os { code: 2, kind: NotFound, message: "No such file or directory" } 
> receiving shutdown signal ...
I think it's a bit confusing and scary.
=> chore: amend a log message which could cause users to be panic

network/src/network.rs, network/src/protocols/ping.rs, network/src/protocols/test.rs, rpc/README.md, rpc/json/rpc.json, rpc/src/module/net.rs
This PR added a `ping_peers` rpc, which requests that a ping be sent to all connected peers, to measure ping time. 
for reviewer's reference: the code change of `network/src/network.rs` is using struct deconstruction and scoped clone to replace the original multiple rename clone.
before:
```
let foo = Arc::new(...);
let foo_clone = foo.clone();
thread::spawn(move || {
let foo_clone_1 = foo_clone.clone();
thread::spawn(move || {
foo_clone_1.bar();
});
foo_clone.bar();
});
foo.bar();
```
now:
```
let foo = Arc::new(...);
{
let foo = foo.clone();
thread::spawn(move || {
{
let foo = foo.clone();
thread::spawn(move || {
foo.bar();
});
}
foo.bar();
});
}
foo.bar();
```
makes it easier to read and add new variables.
=> feat: add ping_peers rpc

network/Cargo.toml, network/src/peer_store/peer_store_db.rs
I got a `PermissionDenied` error when running a lightnode on android which is using the `ckb-network` as a lib:
```
08-28 15:35:55.052  9853  9881 I RustStdoutStderr: 2020-08-28 15:35:55.052 +09:00 NetworkRuntime WARN ckb_network::services::dump_peer_store  Dump peer store error, path: "/storage/emulated/0/Android/data/rust.example.android/files/db/peer_store" error: Io(Custom { kind: PermissionDenied, error: PathError { path: "/data/local/tmp/.tmponp0Nt", err: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } } })
```
This PR removes tmp directory dependencies, make it possible to using `ckb-network` as a lib on android and also running ckb full node on a system without tmp directory mouting
=> chore: remove tmp directory dependencies

test/src/net.rs, test/src/node.rs, test/src/utils.rs, test/src/worker.rs
When debug integration case in local, we may run a single case lots time, then there is a big problem how to find the logs under an execution.
Old log structure:
```
├── ckb-it-get_blocks_timeout-net-G65fZ4
├── ckb-it-get_blocks_timeout-node0-LZRUJE
├── ckb-it-get_blocks_timeout-node1-11uL3C
```
New log structure:
```
├── ckb-it-get_blocks_timeout-UccnLI
│   ├── net
│   ├── node0
│   └── node1
```
Another change is updating `node.working_dir` and `net.working_dir` from `String` to `PathBuf`
=> chore: integration test - put case log together

ckb-bin/src/subcommand/run.rs
network background services (peer store dump, etc) can not be dropped automatically when rpc tcp service is on, this PR drop the rpc_server explicitly to resolve this issue. (I don't know the root reason, but it works)
=> fix: resolve network background service cleanup issue when rpc tcp server is on

Cargo.lock, notify/src/lib.rs, rpc/README.md, rpc/json/rpc.json, rpc/src/module/subscription.rs, rpc/src/server.rs, shared/src/shared.rs, tx-pool/Cargo.toml, tx-pool/src/process.rs, tx-pool/src/service.rs, util/jsonrpc-types/src/lib.rs, util/jsonrpc-types/src/pool.rs
This PR added a `new_transaction` topic to subscription rpc, user will get notified when new transaction is submitted to pool.
tcp tx subscription example:
```
telnet localhost 18114
> {"id": 2, "jsonrpc": "2.0", "method": "subscribe", "params": ["new_transaction"]}
< {"jsonrpc":"2.0","result":"0x3","id":2}
< {"jsonrpc":"2.0","method":"subscribe","params":{"result":"... pool transaction entry json string...","subscription":"0x3"}}
```
=> feat: add tx subscription

Makefile
[`ws` allows remote attacker to run the process out of memory.](https://rustsec.org/advisories/RUSTSEC-2020-0043)
Since it is no longer actively maintained, we couldn't fix it in the short term, skip it temporarily to avoid blocking other PRs.
p.s. That issue was reported before one year, but there is still no reply.
=> ci: skip RUSTSEC-2020-0043 temporarily

ckb-bin/src/subcommand/init.rs, resource/build.rs, resource/ckb.toml, resource/default.db-options, resource/src/lib.rs
- Reduce the database directory size.
```
[DBOptions]
max_total_wal_size=134217728 # default: no size limit
keep_log_file_num=32 # default: 1000
```
- [Reduce the maximum memory in IBD: drop immutable memtables faster.](https://github.com/facebook/rocksdb/commit/2f41ecfe75f0ebf33e4969083b031c7a97ebaee7)
```
[CFOptions "default"]
write_buffer_size=8388608
min_write_buffer_number_to_merge=1
max_write_buffer_number=2
max_write_buffer_size_to_maintain=-1
```
- [Tuning according to the official document.](https://github.com/facebook/rocksdb/wiki/Setup-Options-and-Basic-Tuning/d7cb90f771d8b8fd4ea605b6da299255709a77c2#other-general-options)
```
[DBOptions]
bytes_per_sync=1048576
max_background_compactions=4
max_background_flushes=2
[CFOptions "default"]
level_compaction_dynamic_level_bytes=true …
```
=> improvement: add a default options file

Cargo.lock, miner/Cargo.toml, miner/src/miner.rs, store/Cargo.toml, store/src/cache.rs, store/src/store.rs, sync/Cargo.toml, sync/src/relayer/transaction_hashes_process.rs, sync/src/types/mod.rs, tx-pool/Cargo.toml, tx-pool/src/block_assembler/mod.rs, tx-pool/src/pool.rs, tx-pool/src/process.rs, util/network-alert/Cargo.toml, util/network-alert/src/alert_relayer.rs, util/network-alert/src/notifier.rs, verification/Cargo.toml, verification/src/cache.rs, verification/src/contextual_block_verifier.rs, verification/src/transaction_verifier.rs
We forked `lru-cache` cause we need such `peek` function, `lru` seems a good alternative.
=> refactor: replace legacy lru-cache

README.md
I cannot find a new link so I just remove it.
=> chore: remove dead link to mining doc

SECURITY.md
The mailing list is hosted by google group (https://groups.google.com/u/0/a/nervos.org/g/security-mailing-list). Anyone can join the mailing list to receive security notifications.
=> chore: add security mailing list info

sync/src/synchronizer/mod.rs
When the local data is lower than minwork, the log display is incorrect
=> chore: log shows error

.travis.yml, azure-pipelines.yml, devtools/ci/package.sh
Using draft release so that we can publish the releases when all the builds are ready.
=> chore(ci): Use draft release to package CKB

Cargo.lock
futures-rs:
https://rustsec.org/advisories/RUSTSEC-2020-0059
https://rustsec.org/advisories/RUSTSEC-2020-0060
https://rustsec.org/advisories/RUSTSEC-2020-0061
Solution: Upgrade to >= 0.3.7
smallvec:
https://rustsec.org/advisories/RUSTSEC-2018-0018
Solution: Upgrade to >= 0.6.13
=> fix: unsound advisory warnning

network/src/peer.rs, network/src/peer_registry.rs, network/src/protocols/mod.rs, network/src/protocols/ping.rs, network/src/services/protocol_type_checker.rs, network/src/tests/peer_registry.rs, rpc/src/module/net.rs
1. Reduce the performance cost of frequently acquiring global locks by removing other protocols registered on received
2. Reduce ping received calculation
=> chore: reduce lock on protocols received

Cargo.lock, deny.toml, network/Cargo.toml, network/src/network.rs, network/src/protocols/discovery/mod.rs, network/src/protocols/discovery/state.rs, network/src/protocols/identify/mod.rs, util/app-config/Cargo.toml
1. Upgrade tentacle
2. Enable reuse port on unix, Windows system has permission problems, it cannot be turned on by default
3. The discovery protocol version number has been increased to identify whether the observed address can be broadcasted
=> chore: upgrade tentacle, enable reuse port

sync/src/status.rs
This state is a normal state, which means that when the transaction is in the proposal phase, the node is not involved in it, and the transaction needs to be pulled remotely during compact block message processing, and the current state is pulling
=> chore: change inflight request tx reach limit status to 1xx

rpc/src/error.rs, test/src/specs/relay/transaction_relay_low_fee_rate.rs, tx-pool/src/error.rs, tx-pool/src/process.rs
The first parameter is the minimum transaction fee, not the fee rate.
https://github.com/nervosnetwork/ckb/blob/50ddac6ccd951a8e2a2f180c59a291f76e00d6e5/tx-pool/src/process.rs#L411-L414
https://github.com/nervosnetwork/ckb/blob/50ddac6ccd951a8e2a2f180c59a291f76e00d6e5/tx-pool/src/error.rs#L11-L15
=> fix: the description for the low fee rate error

ckb-bin/src/subcommand/init.rs, docs/configure.md
=> docs: fix outdated documents, use `ckb-cli` instead of `ckb cli`

Cargo.lock, error/Cargo.toml, error/src/internal.rs, error/src/lib.rs, util/dao/utils/Cargo.toml, util/dao/utils/src/error.rs, util/dao/utils/src/lib.rs, verification/Cargo.toml, verification/src/error.rs, verification/src/lib.rs
`enum-display-derive` is too old and brings unnecessary compilation tasks. After replacing with `derive_more`, crates such as `syn`/`quote` will only need to compile one version
=> chore: replace enum-derive crate

devtools/doc/rpc.py, rpc/Cargo.toml, rpc/src/module/subscription.rs, util/jsonrpc-types/src/lib.rs, util/jsonrpc-types/src/subscription.rs
At present, write a subscription client have to copy those codes or depend on the server crate.
It doesn't make sense.
=> chore: expose jsonrpc types for subscription

Makefile, ckb-bin/Cargo.toml
1. `with_sentry` feature should be disabled in integration test
2. fix ckb-bin compiler error
=> fix: resolve integration script and build error

Cargo.lock, miner/Cargo.toml, util/fixed-hash/core/src/std_str.rs
`futures` changelog:
```
Switch proc-macros to use native #[proc_macro] at Rust 1.45+ (#2243)
Add WeakShared (#2169)
Add TryStreamExt::try_buffered (#2245)
Add StreamExt::cycle (#2252)
Implemented Clone for stream::{Empty, Pending, Repeat, Iter} (#2248, #2252)
Fix panic in some TryStreamExt combinators (#2250)
```
Unified console to 0.12
Fix warning on `fixed-hash-core`
=> chore: upgrade futures and console

Cargo.lock, db-migration/Cargo.toml, miner/Cargo.toml, miner/src/miner.rs
due to indicatif's console depends on the writing problem, the `console` must be forced to upgrade to the latest version
=> chore: upgrade console

deny.toml
Could be fixed after  [CKB-VM Issue-119: Replace `memmap` crate since it is unmaintained](https://github.com/nervosnetwork/ckb-vm/issues/119) fixed.
=> ci: skip RUSTSEC-2020-0077 temporarily

benches/benches/benchmarks/next_epoch_ext.rs, spec/src/consensus.rs, spec/src/lib.rs
- We can test different `orphan_rate_target` in our internal test networks or mock tests.
Only break those customized chains which have `genesis_epoch_length % 40 != 0`.
=> feat: let the consensus params `orphan_rate_target` to be configurable

Cargo.lock, network/Cargo.toml, util/crypto/Cargo.toml, util/hash/Cargo.toml, util/hash/src/lib.rs
This PR use https://github.com/jjyr/blake2b-ref.rs in wasm32 target and upgrade secp256k1 (https://github.com/rust-bitcoin/rust-secp256k1/pull/208), make it easy to compile to wasm32 on MacOS
=> chore: use blake2b-ref for wasm and upgrade secp256k1

deny.toml
- [`ordered_float:NotNan` may contain `NaN` after panic in assignment operators](https://github.com/RustSec/advisory-db/blob/dec05d79abc4e468cc225e36af6351d19e7b8063/crates/ordered-float/RUSTSEC-2020-0082.md)
- `ordered_float` released two patched versions: `1.1.1` and `2.0.1`.
- CKB doesn't use `ordered_float` directly, CKB introduces the dependency via `heim`.
- `heim < 0.1` uses [`ordered_float = "~1.0"`](https://github.com/heim-rs/heim/blob/v0.0.11/heim-process/src/sys/common.rs#L21); `heim >= 0.1` uses [`ordered_float = "~2.0"`](https://github.com/heim-rs/heim/blob/2a6922ead22ef6e095de0be94779c82b5d1d4ca1/heim-process/Cargo.toml#L24), but it doesn't release.
CKB **are not affected** by this security issue: `heim` only uses the `NotNan` in [a private …
=> ci: skip RUSTSEC-2020-0082 temporarily since not affected

indexer/src/lib.rs, indexer/src/store.rs, rpc/src/service_builder.rs
1. deprecated method name change to "deprecated.xxx", need to remove this prefix
2. indexer module always open DB on default，and it will leave log/DB files on disk, these are not needed
=> fix: don't open db when disable indexer module, fix deprecated method response

Cargo.lock, sync/Cargo.toml, sync/src/relayer/mod.rs
- The crate `ratelimit_meter` is deprecated and the original author re-write a new crate `governor`.
- The crate `ratelimit_meter` had depended on an old version of `parking_lot` (`^0.9.0`) which has security [RUSTSEC-2020-0070: Some `lock_api` lock guard objects can cause data races](https://rustsec.org/advisories/RUSTSEC-2020-0070).
**This security issue isn't fixed in this PR.** To fix it completed, another three group of crates are still required to upgrade:
- `ckb-stop-handler` and `ckb-util`.
- `jsonrpc-*`.
- `metrics-*`
=> chore(deps): replace ratelimit_meter by governor

Cargo.lock
fix https://github.com/RustSec/advisory-db/blob/master/crates/arc-swap/RUSTSEC-2020-0091.md
=> chore(deps): bump arc-swap from 0.4.7 to 0.4.8

Makefile, util/app-config/src/app_config.rs, util/app-config/src/sentry_config.rs
After https://github.com/nervosnetwork/ckb/pull/2351, integration test cannot run for ckb which builds with `--features with_sentry`.
=> chore(integration): add sentry section into ckb.toml in integration test

Cargo.toml, Makefile, ckb-bin/Cargo.toml, network/Cargo.toml, network/src/network.rs, network/src/services/mod.rs
This PR extracts dns seeding related function to a feature flag, make it easy to compile ckb-network crate to wasm target.
=> chore: add with_dns_seeding feature to ckb-network

network/src/protocols/discovery/mod.rs, network/src/protocols/discovery/state.rs
Filter own monitor first, otherwise port reuse will not be enabled
=> chore: filter self listen first

README.md, devtools/doc/rpc.py, devtools/release/publish-crates.sh, rpc/README.md
Add the MSRV plicy in README.md if it exists, otherwise generate one before `cargo publish`. 
Example: https://crates.io/crates/ckb-util/0.39.0-pre
=> chore: add MSRV policy for all crates

test/src/main.rs, test/src/worker.rs
After all integration test cases finished, it would be better have a brief report to check test results.
The test results in this PR show like this:
```
TEST                                               | STATUS     | DURATION
HandlingDescendantsOfProposed                      | Passed     | 5 s
RelayInvalidTransaction                            | Passed     | 5 s
AlertPropagation                                   | Passed     | 17 s
ChainFork4                                         | Passed     | 19 s
...
BlockSyncWithUncle                                 | Failed     | 9 s
Total elapsed time: 425.92992889s
```
=> chore(integration): print test results after integration test finished

Cargo.lock, benches/Cargo.toml, ckb-bin/Cargo.toml, miner/Cargo.toml, miner/src/worker/dummy.rs, miner/src/worker/mod.rs, network/Cargo.toml, script/Cargo.toml, script/src/verify.rs, sync/Cargo.toml, test/Cargo.toml, util/app-config/Cargo.toml, util/crypto/Cargo.toml, util/multisig/Cargo.toml, verification/Cargo.toml
Upgrade tinny-keccak, base64 and rand.
* Bump tiny-keccak from 1.5.0 to 2.0.2, see #2444 
* Bump base64 from 0.10.1 to 0.13.0, see #2437 
* Bump direct dependency of rand from 0.6.5 to 0.7.3, deprecating #2440
=> Upgrade dependencies tiny-keccak base64 and rand

test/src/specs/relay/transaction_relay_low_fee_rate.rs
- In the function `gen_spendable(..)`, 12 blocks are created.
https://github.com/nervosnetwork/ckb/blob/aff994e68f6bb7935e2dd371c92a27be72936c97/test/src/specs/relay/transaction_relay_low_fee_rate.rs#L21
- Then, the cell which is created in the 12th block, will be used as a spendable cell.
https://github.com/nervosnetwork/ckb/blob/aff994e68f6bb7935e2dd371c92a27be72936c97/test/src/specs/relay/transaction_relay_low_fee_rate.rs#L24-L29
- So the spendable cell will be broadcasted from `node-0` to `node-1`.
https://github.com/nervosnetwork/ckb/blob/aff994e68f6bb7935e2dd371c92a27be72936c97/test/src/specs/relay/transaction_relay_low_fee_rate.rs#L34-L37
- Then, we expect to get a low fee rate error.
https://github.com/nervosnetwork/ckb/blob/aff994e68f6bb7935e2dd371c92a27be72936c97/test/src/specs/r …
=> ci: fix potential failure in integration test TransactionRelayLowFeeRate

Cargo.lock, Cargo.toml, deny.toml, util/metrics-service/Cargo.toml, util/metrics/Cargo.toml
- chore(deps): use patched metrics to fix [`RUSTSEC-2020-0041`](https://rustsec.org/advisories/RUSTSEC-2020-0041.html).
So we can remove `sentry` from `[patch.crates-io]` in `Cargo.toml`.
https://github.com/nervosnetwork/ckb/blob/d04f413879a7e62d2f21eebefda9c4f58cec22f2/Cargo.toml#L99
The section `[patch.crates-io]` doesn't work for `cargo install ckb`, it's **a potential risk** since we released all ckb-related crates.
The commits of patch are:
- [fix: RUSTSEC-2020-0041](https://github.com/nervosnetwork/metrics-rs/commit/4fd13f6b93022c5ec0f415515948648eaec34317)
- [chore(deps): bump parking_lot from 0.10 to 0.11](https://github.com/nervosnetwork/metrics-rs/commit/c3fbcd95fbc1a3b0b7d5d3acd4d1e9d9e1aa9bea) to fix [`RUSTSEC-2020-0070`](https://rustsec.org/advisories/RUSTSEC-2020-0070.html) …
=> chore(deps): use patched metrics

build.rs
Each time when I run `make integration` or some other commands, about 15 seconds will be spent for waiting linking `ckb-bin`.
It wastes me a lot of times. (More than 40 times / 10 minutes each day.)
After this PR, when run `cargo build` or `cargo run` but nothing changed, `ckb` won't be linked again.
There are a lots of reason why the file in ".git/HEAD" isn't existed. It's common. For example, calling `git gc`.
=> chore: if the file in ".git/HEAD" isn't existed, ckb-bin will be re-linked every time when "cargo build"

rpc/README.md, util/jsonrpc-types/src/chain_info.rs
Chain info's epoch come from tip_header https://github.com/nervosnetwork/ckb/blob/c3133ad66de38c03685c218b97d9f7845ad83d1d/rpc/src/module/stats.rs#L102-L108
And according to  https://github.com/nervosnetwork/ckb/blob/c3133ad66de38c03685c218b97d9f7845ad83d1d/util/types/src/core/views.rs#L405
`epoch` in `HeaderView` is `EpochNumberWithFraction` instead of `EpochNumber`
=> chore(doc): fix doc about epoch in type `ChainInfo`

chain/src/tests/block_assembler.rs
- `ChainController::process_block(..)` is synchronized, it will wait for the response.
https://github.com/nervosnetwork/ckb/blob/6e34d89a44aaeba3ffbfbf62c173e6a0a6547273/chain/src/chain.rs#L200-L208
- But when `ChainService::process_block(..)`, it will send `NewUncle(..)` to `TxPoolController` without waiting for the response.
https://github.com/nervosnetwork/ckb/blob/6e34d89a44aaeba3ffbfbf62c173e6a0a6547273/chain/src/chain.rs#L491-L497
- So, with a very small probability, the uncle block may not have been processed by `TxPoolService`.
So the follow line will throw the error: `panicked at 'index out of bounds: the len is 0 but the index is 0`.
https://github.com/nervosnetwork/ckb/blob/6e34d89a44aaeba3ffbfbf62c173e6a0a6547273/chain/src/tests/block_assembler.rs#L210
Append …
=> test: fix test "test_prepare_uncles"; it could failed with a very small chance

test/src/node.rs, test/src/util/mining.rs
- `ChainController::process_block(..)` is synchronized, it will wait for the response.
https://github.com/nervosnetwork/ckb/blob/6e34d89a44aaeba3ffbfbf62c173e6a0a6547273/chain/src/chain.rs#L200-L208
- But when `ChainService::process_block(..)`, it will send `ChainReorg(..)` to `TxPoolController` without waiting for the response.
https://github.com/nervosnetwork/ckb/blob/6e34d89a44aaeba3ffbfbf62c173e6a0a6547273/chain/src/chain.rs#L454-L461
https://github.com/nervosnetwork/ckb/blob/6e34d89a44aaeba3ffbfbf62c173e6a0a6547273/tx-pool/src/service.rs#L195-L198
- So, with a very small probability, the `ChainReorg(..)` may not have been processed by `TxPoolService` before we use transactions in the new tip block.
Then the error `TransactionFailedToResolve: Resolve failed Unknown([OutPoint(0x..)])` …
=> test: fix potential failure in integration tests, such as DifferentTxsWithSameInput

error/src/lib.rs
The `AnyError` was `anyhow::Error` at first:
https://github.com/nervosnetwork/ckb/blob/2e067a7c5b02eed6a9b565b5c2c5a73197bb227f/error/src/lib.rs#L7
But `anyhow::Error` is not cloneable, so we use `AnyError` to wrapper around it.
https://github.com/nervosnetwork/ckb/blob/6e34d89a44aaeba3ffbfbf62c173e6a0a6547273/error/src/lib.rs#L16
So, we shouldn't let users to know the `AnyError`. For example:
> {"code":-301,"message":"TransactionFailedToResolve: OutPoint(Unknown([OutPoint(0xb3d1846ad3af896eb11f83826bd13f57a464c012d1e17c8182cf988f4720abf600000000)]))","data":"Error { kind: OutPoint, inner: AnyError(Unknown([OutPoint(0xb3d1846ad3af896eb11f83826bd13f57a464c012d1e17c8182cf988f4720abf60
0000000)])) }"}
But the follow codes use `fmt::Debug` to format the error, and return the `String` to the …
=> chore: hide the AnyError since it's only an internal type

Makefile, test/src/main.rs
- In `Makefile` we set `RUST_LOG` but in `main.rs` we parse `CKB_LOG` for the log filter.
https://github.com/nervosnetwork/ckb/blob/d04f413879a7e62d2f21eebefda9c4f58cec22f2/Makefile#L37-L43
https://github.com/nervosnetwork/ckb/blob/d04f413879a7e62d2f21eebefda9c4f58cec22f2/test/src/main.rs#L39-L42
- Use `RUST_LOG` not `CKB_LOG`, because `CKB_LOG` will override the configurations of nodes which started by `ckb-tests`.
- Add more log outputs.
=> ci: fix the log output of integration tests and output more logs

Cargo.lock, network/Cargo.toml, util/app-config/Cargo.toml
Features
Add protocol spawn feature(#278)
Revert yamux buffer(#281)
Remove secp256k1 wasm compatible(#282)
Add doc(#289)
Bug Fix
Unified substream error output(#287)
Fix some msg left on buffer(#288)
Change blocking session detection(#290)
=> chore: upgrade tentacle

sync/src/synchronizer/mod.rs, test/src/specs/sync/get_blocks.rs
- `GetBlocks` is sent by `BlockFetchCMD` in thread `BlockDownload`.
https://github.com/nervosnetwork/ckb/blob/a1bd7d2f5909d4cd60a8b58fac8aa5d0ca30d078/sync/src/synchronizer/mod.rs#L631
https://github.com/nervosnetwork/ckb/blob/a1bd7d2f5909d4cd60a8b58fac8aa5d0ca30d078/sync/src/synchronizer/mod.rs#L604-L607
- `HeadersProcess` is asynchronously running in global runtime.
- `GetBlocks` and `HeadersProcess` are parallel.
- Choose integration test `GetBlocksTimeout` as the example to explain the issue:
- After sent all headers to node1, the test check the next `SyncMessage` immediately.
https://github.com/nervosnetwork/ckb/blob/a1bd7d2f5909d4cd60a8b58fac8aa5d0ca30d078/test/src/specs/sync/get_blocks.rs#L29-L40
And only check the type of `SyncMessage`. …
=> test: fix potential failure in integration test GetBlocksTimeout

Cargo.lock
Ref:
- [RUSTSEC-2021-0003: smallvec: Buffer overflow in SmallVec::insert_many](https://rustsec.org/advisories/RUSTSEC-2021-0003.html)
- [Rust-SmallVec Issue-252: Buffer overflow in `insert_many()](https://github.com/servo/rust-smallvec/issues/252)
=> chore(deps): bump smallvec from 0.6.13 / 1.3.0 to 0.6.14 / 1.6.1 to fix RUSTSEC-2021-0003

resource/Cargo.toml
Lock the version of tempfile to `= 3.1.0` to fix wasm-build-test.
WASM build test does not commit the `Cargo.lock` so it will choose the latest version according to the semver requirements.
On Jan 12, 2021, tempfile 3.2.0 has released so WASM build test starts to use it. However, this new version requires `rand 0.8`, which by turn depends on `getrandom 0.2.1`. Starting from `getrandom 0.2.0`, it does not support `wasm32-unknown-unknown` (see [getrandom unsupported targets](https://docs.rs/getrandom/0.2.0/getrandom/index.html#unsupported-targets)), so the build fails.
=> fix: fix wasm build by locking tempfile

ckb-bin/src/subcommand/run.rs
Edit section `[rpc]` in `ckb.toml`:
```toml
modules = []
```
p.s. `NetworkController` contains all other `Controllers`, so we can only extend its lifetime to let all controllers work well.
=> fix: network should work without rpc

util/jsonrpc-types/src/lib.rs, util/jsonrpc-types/src/primitive.rs
According to the suggestion of https://github.com/nervosnetwork/ckb/pull/2494#discussion_r551694750, add impl for `EpochNumberWithFraction`, this would be useful for get `epoch_number`, `epoch_index` and `epoch_length` from `EpochNumberWithFraction`
=> chore: add impl for EpochNumberWithFraction which used for getting details of epoch

ckb-bin/src/subcommand/run.rs, util/app-config/src/args.rs, util/app-config/src/cli.rs, util/app-config/src/lib.rs
Ckb stores chain spec into the database and compare the configured chain spec on starting.
A user may want to overwrite the stored chain spec when it changes the configured chain spec and makes sure the change is acceptable. Therefore this PR adds `--overwrite-spec` command option to overwrite the stored chain spec.
---
* If you want to just skip the chain spec checking without overriding the stored one:
```shell
ckb run --skip-spec-check ...
```
* If you want to overwrite the stored chain spec with the configured one:
```shell
ckb run --overwrite-spec ...
```
=> feat: provide `--overwrite-spec` to override the chain spec in storage

db/src/db.rs, resource/ckb.toml, util/app-config/src/configs/db.rs
`cache_index_and_filter_blocks` is enabled in `default.db-options`, quote rocksdb doc:
```
By putting index, filter, and compression dictionary blocks in block cache, these blocks have to compete against data blocks for staying in cache
```
current rocksdb index size is around 32MB, and the default rocksdb block cache size is 8MB, which hurts the db read performance, this PR changed the default cache size to 128MB.
We should consider using [Partitioned Index](https://github.com/facebook/rocksdb/wiki/Partitioned-Index-Filters) later.
=> fix: resolve rocksdb cache size issue when using `default.db-options`

network/src/network_group.rs, network/src/peer.rs, network/src/peer_store/peer_store_impl.rs
`NetworkGroup` is just a trait for type conversion, for which we should use the built-in `From` trait
=> chore: refactor NetworkGroup trait

.travis.yml, azure-pipelines.yml, devtools/azure/windows-dependencies.yml, devtools/windows/make.ps1, test/run.sh, test/src/main.rs, test/src/node.rs, test/src/worker.rs
- Collect entire logs for failed integration tests.
Since a lot of integration tests are too difficult to reproduce, this PR will upload entire logs of integration tests to our server, include the entire data of nodes. So we could download them to diagnose what happened in CI servers.
- Remove temporary data for any integration tests after it passed **in default**, and you can disable it by `--keep-tmp-data`.
Running integration tests will occupy a lot of disk space (almost `600 MiB` raw data in total), and it's a bit complex to remove data for passed tests after all tests done.
- I remove all `--max-time 1200` from `integration tests`, so we can run all tests after merged into develop.
=> ci: collect entire logs for failed integration tests

test/Cargo.toml, test/src/main.rs, test/src/specs/relay/compact_block.rs, util/dao/src/lib.rs
1. Add a test case [`BlockTransactionsRelayParentOfOrphanBlock`](https://github.com/keroro520/ckb/blob/9ce5bb90fd8dda31b3e3e3733c26770f3be3b1c5/test/src/specs/relay/compact_block.rs#L309-L314)
2. Simplify the test case CompactBlockRelayParentOfOrphanBlock.
3. Remove the useless  function`base_block_reward` in ckb-dao.
=> Split test case BlockTransactionsRelayParentOfOrphanBlock

Cargo.lock, network/Cargo.toml
futures:
```
* Fixed `Unpin` impl of `future::{MaybeDone, TryMaybeDone}` where trait bounds were accidentally added in 0.3.9. (#2317)
* Fixed heap buffer overflow in `AsyncReadExt::{read_to_end, read_to_string}` (#2314)
* Fixed type-inference in `sink::unfold` by specifying more of its types (breaking change -- see #2311)
* Significantly improved compile time when `async-await` crate feature is disabled (#2273)
* Added `stream::repeat_with` (#2279)
* Added `StreamExt::unzip` (#2263)
* Added `sink::unfold` (#2268)
* Added `SinkExt::feed` (#2155)
* Implemented `FusedFuture` for `oneshot::Receiver` (#2300)
* Implemented `Clone` for `sink::With` (#2290)
* Re-exported `MapOkOrElse`, `MapInto`, `OkInto`, `TryFlatten`, `WriteAllVectored` (#2275)
```
tentacle:
```
- Port futures-rs fix on …
```
=> chore: upgrade deps

test/run.sh
When integration tests failed in Travis CI, the nodes data directories are not uploaded.
Set the environment variable to put the nodes data directories into the upload directory.
https://github.com/nervosnetwork/ckb/blob/1fc0dc0981f8bbd9a720773972e47ef7f5f08413/test/src/utils.rs#L215
The equivalent code in Azure CI:
https://github.com/nervosnetwork/ckb/blob/1fc0dc0981f8bbd9a720773972e47ef7f5f08413/devtools/windows/make.ps1#L90-L93
=> ci: set env var to put nodes data into upload dir

util/runtime/src/lib.rs
Runtimes may be incompatible in different versions of tokio. As ckb-async-runtime wraps a specified version tokio, it should publicly expose that version tokio so that the ckb-async-runtime users can use components of that specified version tokio, such as `tokio::time::sleep`.
=> chore: expose the depended tokio from ckb-async-runtime

README.md, docs/platform-support.md
Support for different platforms are organized into three tiers, each with a different set of guarantees.
The Rust implementation uses the [Assembly based interpreter mode](https://github.com/nervosnetwork/ckb-vm#notes-on-different-modes) (ASM mode) of the CKB VM. This must be considered as a consensus rule in Lina, the mainnet and Aggron, the testnet.
Miners connecting to Lina (the mainnet) and Aggron (the testnet) must use Tier 1 or Tier 2 platforms, where Tier 1 is recommended.
The other nodes should use Tier 1 or Tier 2 platforms as well.
=> doc: CKB platform support into tiers

Cargo.lock, Cargo.toml, db/src/db.rs, freezer/src/freezer.rs, shared/Cargo.toml, shared/src/shared.rs, store/src/db.rs, sync/Cargo.toml, sync/src/lib.rs, sync/src/net_time_checker.rs, sync/src/relayer/mod.rs, sync/src/status.rs, sync/src/synchronizer/block_fetcher.rs, sync/src/synchronizer/get_blocks_process.rs, sync/src/synchronizer/get_headers_process.rs, sync/src/synchronizer/headers_process.rs, sync/src/synchronizer/mod.rs, sync/src/tests/inflight_blocks.rs, sync/src/types/mod.rs, test/Cargo.toml, test/src/specs/relay/transaction_relay.rs, test/src/specs/sync/get_blocks.rs, test/src/specs/sync/invalid_locator_size.rs, util/constant/Cargo.toml, util/constant/src/lib.rs, util/constant/src/store.rs, util/constant/src/sync.rs, util/snapshot/Cargo.toml, util/snapshot/src/lib.rs
Even we use `DeleteRange` apply to delete the range of keys, seems Rocksdb still hasn't implemented the feature of using seek() to skip until the end of range delete end yet.
Rocksdb iter seek slows down dramatically when there are many deletes.
Manually call `CompactRange()` for the range to delete,  this approach can solve the problem.
=> manually trigger compaction after freeze

Cargo.lock, ckb-bin/Cargo.toml, ckb-bin/src/subcommand/migrate.rs, ckb-bin/src/subcommand/run.rs, db-migration/src/lib.rs, db-schema/src/lib.rs, shared/src/shared.rs, util/app-config/src/args.rs, util/app-config/src/cli.rs, util/app-config/src/lib.rs
- docs: fix a typo
- chore: no migration version means the database is uninitialized
At present, `migration_check` will return `true` if the database is uninitialized.
But an uninitialized database doesn't have data required to migrate.
This is important when do `migration_check` in `ckb run`.
- feat: request the approval for database migrations
=> feat: request the approval for database migrations

Cargo.lock
- [RUSTSEC-2020-0146: generic-array: arr! macro erases lifetimes](https://rustsec.org/advisories/RUSTSEC-2020-0146)
- [`generic-array` Issue-98: `arr!` unsoundness](https://github.com/fizyk20/generic-array/issues/98)
- [ChangeLog for `generic-array` from 0.12.3 to 0.12.4](https://github.com/fizyk20/generic-array/compare/1e96864d3fd22f28f54a92f53d59f4ef3135f2a9...42843cdb6c24ef3684494617e78745a62a64a29c)
=> chore(deps): bump generic-array from 0.12.3 to 0.12.4 to fix RUSTSEC-2020-0146

test/src/node.rs, test/src/util/mining.rs
Same issues as #2483.
As a follow-up of #2483 which only fix few integration tests, this PR could fix more.
This PR could fix potential failures for at least follow integration tests:
- For the 1st commit:
- BlockTransactionsRelayParentOfOrphanBlock
- ConflictInGap
- DAOWithSatoshiCellOccupied
- FeeOfMaxBlockProposalsLimit
- FeeOfMultipleMaxBlockProposalsLimit
- FeeOfTransaction
- ForkedTransaction
- HandlingDescendantsOfCommitted
- HandlingDescendantsOfProposed
- MiningBasic
- ProposalExpireRuleForCommittingAndExpiredAtOneTime
- ProposeOutOfOrder
- ReorgHandleProposals
- RpcTransactionProof
- RpcTruncate
- SendLargeCyclesTxInBlock
- SpendSatoshiCell
- WithdrawDAO
- WithdrawDAOWithOverflowCapacity
- For the 2nd commit:
- PoolReconcile
p.s. Check #2483 for the failure analysis report and …
=> test: waiting for tx pool in integration tests

Cargo.lock, ckb-bin/Cargo.toml, ckb-bin/src/lib.rs, ckb-bin/src/subcommand/db_repair.rs, ckb-bin/src/subcommand/mod.rs, db/Cargo.toml, db/src/db.rs, rpc/src/module/test.rs, shared/Cargo.toml, shared/src/shared.rs, test/src/main.rs, test/src/specs/tx_pool/dead_cell_deps.rs, test/src/specs/tx_pool/mod.rs, test/src/util/cell.rs, util/app-config/src/args.rs, util/app-config/src/cli.rs, util/app-config/src/lib.rs
This PR adds `generate_block_with_template` rpc, so that dApps can get block template from `get_block_template` rpc, and then add or remove tx / proposal / uncle data in block template, and finally submit it via this rpc to control the newly generated block data.
btw, I think that we should add rpc doc to the `IntegrationTest` module, will create a new PR later.
=> feat: add rpc generate_block_with_template to IntegrationTest rpc module

ckb-bin/src/subcommand/migrate.rs, db-migration/src/lib.rs, db/src/lib.rs, db/src/read_only_db.rs, shared/src/shared.rs, util/app-config/src/args.rs, util/app-config/src/lib.rs
* Perform migration check with read-only mode to prevent automatically create columns breaking compatibility
* Fix the error message is displayed incorrectly while performing the migration
Run error: Error { kind: Spec, inner: GenesisMismatch(...
=> readonly for migrate check

ckb-bin/src/subcommand/migrate.rs, db-migration/src/lib.rs, db/src/lib.rs, db/src/read_only_db.rs, shared/src/shared.rs, util/app-config/src/args.rs, util/app-config/src/lib.rs
* Perform migration check with read-only mode to prevent automatically create columns breaking compatibility
* Fix the error message is displayed incorrectly while performing the migration
Run error: Error { kind: Spec, inner: GenesisMismatch(...
=> [backport] readonly for migrate check

network/src/network.rs, network/src/protocols/discovery/mod.rs, network/src/protocols/test.rs, test/src/specs/p2p/discovery.rs, util/app-config/src/configs/network.rs
the timer interval of checking `DiscoveryMessage::Nodes` announce message should be 24 hours, I think it was incorrectly set to 7 seconds in old code, this PR resolved this issue and corrected some code comments
=> chore: modify discovery announce interval

sync/src/synchronizer/mod.rs, sync/src/tests/inflight_blocks.rs, sync/src/types/mod.rs, test/src/specs/sync/get_blocks.rs
1. disable penalty when download nodes are scarce
2. allow the protection node to be disconnected due to sync judgment
=> feat: Fix download scheduler

spec/src/consensus.rs
The code block started at line 104 with 3 space but ended at line 113 with 1 space.
For some editors (with rust official plugins):
- No code highlighting.
- Couldn't fold code block.
- [rust-lang/rust.vim for Vim](https://github.com/rust-lang/rust.vim/)
- [rust-lang/rust-mode for Emacs](https://github.com/rust-lang/rust-mode)
=> chore: fix unaligned documentation which break highlighting for some editors

rpc/src/module/test.rs, test/src/rpc.rs, test/src/specs/sync/block_sync.rs, test/src/utils.rs
fix a bug which is introduced by https://github.com/nervosnetwork/ckb/pull/2569: this rpc will fail after height 11 on a local dev chain. This PR changed an integration test also to utilize this rpc to make issue it's covered by testing.
=> fix: resolve generate_block_with_template rpc error

rpc/README.md, rpc/src/module/chain.rs, test/src/assertion/reward_assertion.rs, test/src/rpc.rs, test/src/specs/dao/dao_verifier.rs, test/src/specs/mining/fee.rs
[`get_cellbase_output_capacity_details`](https://github.com/nervosnetwork/ckb/tree/80da25593086cf99723ae350f20e8ae43d965aa6/rpc#method-get_cellbase_output_capacity_details) will be deprecated soon and [`get_block_economic_state`](https://github.com/nervosnetwork/ckb/tree/80da25593086cf99723ae350f20e8ae43d965aa6/rpc#method-get_block_economic_state) is the alternative.
In this PR, I replace `get_cellbase_output_capacity_details` with `get_block_economic_state` and do some refactory in integration test.
=> Replace `get_cellbase_output_capacity_details` with `get_block_economic_state` in test

util/reward-calculator/src/lib.rs
This PR will reduce the rocksdb query especially `get_block_txs_hashes` in the `committed_idx_proc`, which is a slow query according to profiler result.
=> perf: shortcut return proposal reward when target_proposals is empty

network/src/network.rs, network/src/protocols/identify/mod.rs
ref: #2565 
if no peer id on addr, it will always output an error log when trying to dial the observed addr:
```
error!("Do not dial addr without peer id, addr: {}", addr);
```
=> fix: don't remove peer id on addr

network/src/network.rs, rpc/src/module/pool.rs, shared/src/shared.rs, shared/src/shared_builder.rs, sync/src/relayer/mod.rs, sync/src/relayer/transaction_hashes_process.rs, sync/src/types/mod.rs, tx-pool/src/process.rs, tx-pool/src/service.rs, util/launcher/src/lib.rs
When the relay protocol receives tx hashes, the previous code has already checked if the transaction has been seen recently in the `tx_filter`:
https://github.com/nervosnetwork/ckb/blob/410023d97dcb23521bfe3d38ad542eefe0ec94c3/sync/src/relayer/transaction_hashes_process.rs#L53-L74
And when the proposal tx is received, it will update the `tx_filter` also:
https://github.com/nervosnetwork/ckb/blob/410023d97dcb23521bfe3d38ad542eefe0ec94c3/sync/src/relayer/block_proposal_process.rs#L53
it is redundant to check proposal tx hash again through tx-pool.
This PR removed this unnecessary checking and refactor the local submitted tx hash broadcasting also.
=> perf: skip fresh proposal id checking in TransactionHashes message

.github/actions/terraform/Dockerfile, .github/actions/terraform/README.md, .github/actions/terraform/action.yml, .github/actions/terraform/apply.sh, .github/actions/terraform/cleanup.sh, .github/actions/terraform/main.sh
Action desctiption: [action-terraform](https://github.com/keroro520/ckb/blob/action-terraform/.github/actions/terraform/README.md)
CI tests "benchmark" and "sync-mainnet" apply AWS instances on-demand. I created a docker action using the Github Action `post` keyword to ensure that the applied instances must be destroyed.
=> feat: add github action "terraform"

.github/workflows/sync.yml
This PR adds a Github Actions workflow, "Sync-Mainnet".
In this workflow,
it applies AWS resources based on [Terraform configuration files #2712](https://github.com/nervosnetwork/ckb/pull/2712),
executes tests via [Ansible playbook #2713](https://github.com/nervosnetwork/ckb/pull/2713).
=> feat: add workflow "Sync-Mainnet"

.github/dependabot.yml, Cargo.lock
- Remove outdated versions from `.github/dependabot.yml`.
We already use later versions for those crates. 
- Bump serde from 1.0.105 to 1.0.126.
=> chore(deps): bump serde from 1.0.105 to 1.0.126

.github/workflows/ci.yaml, devtools/windows/make.ps1, test/run.sh
This PR contains 2 tips:
1.Upload integration files in  github actions and remove usless variables from UnitTest job
2. Remove jobs `Cyclic_dev_dependencies` & `Latest_Linters` from CI
=> Upload logfile in github actions when integation failed and remove allow-failure jobs

chain/src/lib.rs, spec/src/lib.rs, util/dao/utils/src/error.rs, util/instrument/src/lib.rs, util/runtime/src/lib.rs
Fix errors when execture `RUSTDOCFLAGS='-D warnings' cargo doc --all --no-deps`.
p.s. Maybe we should add a CI check?
=> docs: fix missing links and deprecated descriptions

sync/src/synchronizer/mod.rs, sync/src/types/mod.rs
`PeerState#disconnect` is only used in `Synchronizer#eviction`, it's unnecessary to use this field since we have added it to the eviction vec already.
=> chore: remove unnecessary field from `PeerState`

sync/src/synchronizer/in_ibd_process.rs, sync/src/synchronizer/mod.rs, sync/src/types/mod.rs
We are using 3 fields `sync_started` / `sync_connected` / `not_sync_until` in the headers sync process, this PR refactored them to a state machine enum `HeadersSyncState`
=> refactor: move state flag to `HeadersSyncState` enum

script/src/error.rs, script/src/type_id.rs, script/src/verify.rs
Before the error message only link to the error codes for the system
scripts. This commit links to a page organized by script hash type and
code hash. The community can contribute the error codes pages for
various scripts in https://github.com/nervosnetwork/ckb-script-error-codes
See the example page for the built-in `TYPE_ID` script:
https://nervosnetwork.github.io/ckb-script-error-codes/by-type-hash/00000000000000000000000000000000000000000000000000545950455f4944.html#-3
=> doc: use community contributed site for script error codes

Cargo.lock, miner/Cargo.toml, miner/src/client.rs
The bug is that miner always panics, because the future created by hyper 0.13 needs tokio 0.2 runtime.
This bug is introduced since #2773 yesterday.
That PR removed the duplicate version of "hyper" and only kept one version of "hyper".
In fact, I had tested the miner for each commit in that PR, and everything was OK when I did tests.
To be honest, I don't know why this 100%-panic bug wasn't appeared yesterday.
I guess if it's because I didn't clear the "target" directory when I did tests.
This time, I cleared the "target" directory and re-compiled the executable file.
And I ran a dev-chain with 1 node and 4 miners in different speeds for 1 hours, no panics anymore.
=> fix: miner panics since the future created by hyper 0.13 need tokio 0.2 runtime

.github/workflows/ci.yaml
When there are multiple ci workflows pendding for the same branch,
cancel old ones and only keep the last one.
See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
=> ci: limit ci concurrency

.github/workflows/basic-checks.yaml, .github/workflows/build-checks.yaml, .github/workflows/execute-command.yaml, .github/workflows/integration-tests-checks.yaml, .github/workflows/nocompile-checks.yaml, .github/workflows/preflight-checks.yaml, .github/workflows/slash-command.yaml, .github/workflows/unit-tests-checks.yaml, devtools/windows/make.ps1
- A Personal Access Token `REPO_ACCESS_TOKEN`:
- For **public** repository, the `public_repo` permission is enough.
- For **private** repository, the whole `repo` permission is required.
- These Actions only work when the scripts are already in default branch.
For example, default branch in `nervosnetwork/ckb` is `develop` branch.
I want to show a coding-pattern of GitHub Actions:
- We can have only one trigger.
For example, we don't have to use a lot of cron jobs.
We only need one, and dispatch to other workflow if the condition was satisfied.
And we can put all conditions in this trigger action.
- We can split a big workflow into several small workflows.
If any workflow is failed, we can just re-run that failed workflow, not all.
- With the Action [Slash Command Dispatch], we can run or …
=> ci: enabled github-hosted ci for forked repositories and support control them with commit messages or pr comments

resource/ckb.toml, store/src/cache.rs, store/src/store.rs, test/template/ckb.toml, util/app-config/src/configs/store.rs
The cellbase's cache hit ratio was found to be zero in testing the cache efficiency of store layer (running an ibd sync on mainnet), it's only used in `RewardVerifier` and `BlockAssembler`.
For `RewardVerifier`, it will only be called once for each block, it can never hit the cache, while for `BlockAssembler`, since there is a block template cache already, there is no need to overlay this cache, and the `get_cellbase` actually hits rocksdb's own cache quite well, so I don't see the need to introduce additional overhead.
please note that `cellbase_cache_size` is removed from configuration file, however, old version configuration file is compatible with this change since we ignore unknown conf fields.
=> chore: remove lru cache from get_cellbase fn

Cargo.lock, sync/Cargo.toml, sync/src/relayer/mod.rs, sync/src/relayer/transaction_hashes_process.rs, sync/src/relayer/transactions_process.rs, sync/src/types/mod.rs
This PR optimized `tx_ask_for` related code, replace `tx_ask_for_map/tx_ask_for_set` with one `KeyedPriorityQueue`, avoids unnecessary hashset operation in `remove_ask_for_tx` and `pop_ask_for_txs` fn. 
And the memory layout is also optimized: 
1. the vec in `tx_ask_for_map` is removed.
2. `inflight_transactions` is removed.
3. `tx_ask_for` is traced in the global state (renamed to `unknown_tx_hashes`)
=> perf: use KeyedPriorityQueue to replace BTreeMap/HashSet

Cargo.toml, test/Cargo.toml
Since "Cargo PR-8500" merged, as "Cargo Issue-8502" said: "if a crate will also be built as a runtime dependency, that would result in Cargo building it twice, once with opt-level 0 and once with opt-level 3."
So, in this PR I customize the `opt-level` to the default values, to make sure each crates only be compiled once.
When `make prod`  for `v0.42.0`:
- This PR can reduce the number of compiled dependencies 9.56%  (`596 -> 544`).
- This PR can reduce the size of target directory 14.2% (`1_813_100 bytes -> 1_587_780 bytes`).
- Save total compile time.
**Notice: the size of final binary won't be chaneged.**
- [Cargo PR-8500: Build host dependencies with opt-level 0 by default](https://github.com/rust-lang/cargo/pull/8500)
- [Cargo Issue-8502: Support opt-level ranges to avoid building …
=> build: customize `opt-level` to avoid building some crates twice

chain/src/tests/block_assembler.rs, rpc/src/module/stats.rs, rpc/src/test.rs, spec/src/consensus.rs, spec/src/lib.rs, test/src/specs/rpc/get_blockchain_info.rs, test/src/specs/rpc/submit_block.rs, util/types/src/conversion/blockchain.rs, util/types/src/core/advanced_builders.rs, util/types/src/core/extras.rs, verification/contextual/src/tests/contextual_block_verifier.rs, verification/src/error.rs, verification/src/header_verifier.rs, verification/src/tests/genesis_verifier.rs, verification/src/tests/header_verifier.rs
The data of epoch in bytes is not same as the `EpochNumberWithFraction`.
https://github.com/nervosnetwork/ckb/blob/85bf46065cc91e75980c9ee82925af77c524964d/util/types/src/conversion/blockchain.rs#L105-L110
https://github.com/nervosnetwork/ckb/blob/85bf46065cc91e75980c9ee82925af77c524964d/util/types/src/core/extras.rs#L452-L459
It cause a few unintended consequences.
For example, the RPC return `"0x"` as the epoch of genesis block, but the integration tests checks if its length is `1`.
And we couldn't convert it back with the same value.
```rust
let original = Uint64::default();
let epoch: EpochNumberWithFraction = original.unpack();
let result: Uint64 = epoch.pack();
assert_eq!(result, original); // failed!
```
- When convert a series of bytes to an `EpochNumberWithFraction`, don't change …
=> refactor: verify the epoch in block headers explicitly
